// Batch 5: learn surge (_x5_): articles+10, listening+10, grammar+10, writing+10.
const fs=require('fs');const path=require('path');const file=path.join(__dirname,'content.json');
const content=JSON.parse(fs.readFileSync(file,'utf8'));

const articles=[
 {id:'art_x5_cats_purr',lv:'B1',field:'saglik',title:'Why Do Cats Purr?',
  body:"Everyone knows that cats purr when they are happy. When you stroke a cat on your lap, the soft, steady sound seems like a clear sign of pleasure. But scientists who study cats say the full story is more interesting than that.\n\nCats do not only purr when they feel good. They also purr when they are hungry, when they are hurt, and even at the vet, where most cats are far from happy. Mother cats purr while feeding their kittens, and the kittens purr back. Because of this, many researchers believe purring is a way of communicating, a signal that can mean different things at different times.\n\nThere is another surprising idea. The purr of a cat vibrates at a low frequency, and some studies suggest that these vibrations may help bones and muscles stay strong and heal faster. This could explain why cats purr when they are injured or resting after a fight. In other words, purring might work a little like a built-in medicine.\n\nSo the next time a cat purrs on your lap, remember that it may be saying more than 'I am happy'. It might be asking for food, calming itself down, or even repairing its own body — all with one gentle sound.",
  items:[
   {q:"What is the common belief about purring mentioned at the start?",opts:["Cats purr only when they are happy","Cats purr only when they are hungry","Cats never purr at home","Purring is a sign of illness"],ans:0,tr:"Yazının başında, kedilerin yalnızca mutluyken mırladığı yaygın inancı verilir.",en:"The opening states the common belief that cats purr only when happy."},
   {q:"Why do researchers think purring is a form of communication?",opts:["Because only old cats purr","Because cats purr in many different situations","Because purring is very loud","Because cats purr only at night"],ans:1,tr:"Kediler açken, yaralıyken, veterinerde de mırladığı için araştırmacılar bunu iletişim olarak görür.",en:"Cats purr in many different situations, so researchers see it as communication."},
   {q:"What do some studies suggest about the vibrations of purring?",opts:["They may help bones and muscles heal","They frighten other animals","They keep the cat awake","They make the cat hungry"],ans:0,tr:"Bazı çalışmalara göre mırlamanın titreşimleri kemik ve kasların iyileşmesine yardım edebilir.",en:"Some studies suggest the vibrations may help bones and muscles heal."},
   {q:"Why might a cat purr after a fight, according to the text?",opts:["To call its kittens","To repair its body while resting","To ask for a toy","To show it won the fight"],ans:1,tr:"Yaralıyken ya da dinlenirken mırlama, vücudu onaran 'yerleşik ilaç' gibi çalışıyor olabilir.",en:"Purring while resting may work like built-in medicine, repairing the body."},
   {q:"What is the main idea of the article?",opts:["Purring has several possible meanings and uses","Cats are the happiest animals","Purring is dangerous for kittens","Vets do not like purring cats"],ans:0,tr:"Ana fikir: mırlamanın birden çok olası anlamı ve işlevi vardır.",en:"The main idea is that purring has several possible meanings and uses."}]},
 {id:'art_x5_tea_history',lv:'B2',field:'sosyal',title:'How Tea Travelled the World',
  body:"According to an old Chinese story, tea was discovered by accident when leaves from a wild tree blew into an emperor's pot of boiling water. Whatever the truth of the legend, people in China were drinking tea thousands of years ago, first as a medicine and later for pleasure.\n\nFor centuries, tea remained an Asian secret. It reached Japan with travelling monks, who turned its preparation into a careful ceremony that still exists today. Europeans only met the drink much later, when traders brought small, expensive boxes of leaves home by ship. At first, only the very rich could afford it, and tea was locked away as carefully as jewellery.\n\nThat changed as trade grew. In Britain, tea became so popular that it shaped daily life: a whole meal, afternoon tea, was invented around it. The demand also had a darker side, driving global trade routes, fierce competition between empires, and even wars. Plantations were established in India and Sri Lanka, which today produce much of the world's tea.\n\nNow tea is the most widely drunk beverage on Earth after water. From Turkish tulip-shaped glasses to Japanese bowls and English china cups, every culture has given the same simple leaf its own shape, taste, and meaning.",
  items:[
   {q:"How was tea first used in China, according to the text?",opts:["As a medicine","As a dessert","As a perfume","As a dye for cloth"],ans:0,tr:"Metne göre çay Çin'de önce ilaç olarak kullanıldı, sonra keyif için içildi.",en:"Tea was first used as a medicine in China, and later for pleasure."},
   {q:"Who carried tea to Japan?",opts:["Soldiers","Travelling monks","Farmers","Sea captains"],ans:1,tr:"Çayı Japonya'ya gezgin keşişler götürdü ve hazırlanışını törene dönüştürdüler.",en:"Travelling monks took tea to Japan and turned its preparation into a ceremony."},
   {q:"Why was tea locked away like jewellery in early Europe?",opts:["It was believed to be poisonous","It was extremely expensive","It smelled too strong","It was illegal to drink"],ans:1,tr:"Avrupa'ya az ve pahalı geldiği için ilk başta yalnızca zenginler alabiliyor, mücevher gibi saklanıyordu.",en:"It was so expensive at first that only the rich could afford it."},
   {q:"What does the phrase 'a darker side' refer to?",opts:["The colour of strong tea","Competition, empires, and wars driven by tea demand","Drinking tea at night","The taste of cheap tea"],ans:1,tr:"'Karanlık yüz', çay talebinin küresel rekabeti, imparatorluk çekişmelerini ve savaşları körüklemesidir.",en:"It refers to the fierce competition, empires, and wars driven by demand for tea."},
   {q:"What point does the final paragraph make?",opts:["Tea is losing popularity everywhere","Each culture has adapted tea in its own way","Only Asia drinks tea today","Tea tastes the same in every country"],ans:1,tr:"Son paragraf, her kültürün aynı yaprağa kendi biçimini ve anlamını verdiğini vurgular.",en:"The final paragraph stresses that every culture has given tea its own shape and meaning."}]},
 {id:'art_x5_bird_navigation',lv:'B2',field:'fen',title:'How Birds Find Their Way',
  body:"Every autumn, billions of birds leave their homes and fly thousands of kilometres to warmer lands. Many travel at night, cross open oceans, and still arrive at the same small lake or forest they visited the year before. How do they manage a journey that would be impossible for a human without a map?\n\nScientists have found that birds use several tools at once. By day, they follow the position of the sun; by night, many steer by the stars, just as ancient sailors once did. Young birds in cages have been observed studying the night sky, apparently learning the pattern of the stars before their first journey.\n\nEven more remarkably, birds seem to sense the Earth's magnetic field, the same invisible force that moves a compass needle. Special cells, possibly in their eyes, appear to let them 'see' the direction of north. Experiments show that when this sense is disturbed, birds become confused, even under clear skies.\n\nLandmarks matter too. Older birds remember coastlines, rivers, and mountain ranges from earlier trips, and they often
