const fs=require('fs');const path=require('path');const file=path.join(__dirname,'content.json');
const content=JSON.parse(fs.readFileSync(file,'utf8'));
const PROMPT="Summarize the points made in the lecture, being sure to explain how they cast doubt on the specific points made in the reading passage.";
const toeflint=[
 {id:'ti_x4_four_day_week',type:'writing',lv:'B2',topic:'The four-day working week',minWords:150,
  reading:{title:'The Case for a Four-Day Week',
   body:"Many companies are now considering a shorter working week, and there are strong reasons to believe it would benefit both employees and employers.\n\nFirst, well-rested workers tend to be more productive. When people have an extra day to recover, they return to their desks with more energy and concentration, so the same amount of work can be completed in fewer hours.\n\nSecond, a four-day week would reduce a company's running costs. Offices that close one extra day each week use less electricity, heating, and water, and these savings can be considerable over a year.\n\nFinally, the change would be good for the environment. With one fewer day of commuting, fewer cars would be on the road, cutting both traffic and pollution across the city."},
  lecture:{body:"Now, the reading makes the four-day week sound wonderful, but I'd be careful before getting too excited. Take the first point, about productivity. The thing is, when you cut a day, the same workload doesn't just disappear. In a lot of cases, employees end up cramming five days of tasks into four, which actually raises stress and can lower the quality of their work, not improve it. Second, those cost savings. They sound nice, but a lot of an office's expenses are fixed — the rent, the software, the insurance — and these don't fall just because the lights are off one extra day. Some firms even have to hire more staff to cover the missing day, which costs more, not less. And finally, this idea about the environment. People often forget that a free day off doesn't mean people stay home. Many use that extra day to drive somewhere, go shopping, or travel for leisure, so the reduction in pollution can be far smaller than the reading suggests."},
  prompt:PROMPT,
  keyPoints:["Workers may cram five days of work into four, raising stress instead of productivity.","Many office costs are fixed and do not fall, and extra staff may even be needed.","People often drive on their day off, so pollution may not drop as expected."]},
 {id:'ti_x4_electric_cars',type:'writing',lv:'B2',topic:'Electric cars and urban pollution',minWords:150,
  reading:{title:'Electric Cars as a Clean Solution',
   body:"Switching from petrol vehicles to electric cars is often presented as the answer to pollution in our cities, and the argument rests on three main points.\n\nTo begin with, electric cars produce no exhaust fumes. As they run, they release none of the gases that make city air unhealthy, so replacing petrol cars would clearly improve the air people breathe.\n\nIn addition, electric cars are cheaper to run. Electricity costs less than petrol for the same distance, and the motors have fewer parts that can break, so drivers save money over time.\n\nMoreover, the technology helps fight climate change. Because electric cars use no petrol, the total amount of carbon dioxide released into the atmosphere would fall sharply."},
  lecture:{body:"So the passage is very positive about electric cars, but the picture is more complicated than it lets on. Let's start with the air pollution claim. Yes, the car itself has no exhaust, but the electricity to charge it has to come from somewhere. If a city's power still comes mainly from burning coal or gas, you've simply moved the pollution from the street to the power station. Now, on the question of cost. Electricity may be cheaper per kilometre, that's true, but these cars are far more expensive to buy in the first place, and the battery often has to be replaced after some years at a very high price. For many families, the total cost is not lower at all. And about climate change — building the batteries is the catch. Mining and processing the metals they need uses huge amounts of energy and damages the land, so the carbon savings are smaller, and slower to appear, than the reading claims."},
  prompt:PROMPT,
  keyPoints:["The electricity may come from coal or gas, moving pollution to the power station.","High purchase price and costly battery replacement can outweigh the cheaper running cost.","Mining and making batteries uses much energy, reducing the climate benefit."]},
 {id:'ti_x4_museum_fee',type:'writing',lv:'B2',topic:'Introducing a museum admission fee',minWords:150,
  reading:{title:'Why the Museum Should Charge for Entry',
   body:"The city museum, which is currently free, is considering charging visitors a small admission fee. Supporters of the plan give several reasons why this would help the museum.\n\nFirst, the fee would provide much-needed income. The money collected could be used to repair the building, buy new exhibits, and pay the staff properly, all of which the museum struggles to afford today.\n\nSecond, a charge would reduce overcrowding. On busy days the galleries are so full that it is hard to see anything, and a fee would mean fewer but more serious visitors.\n\nThird, people tend to value what they pay for. Visitors who have bought a ticket are likely to take the exhibits more seriously and behave more respectfully inside the museum."},
  lecture:{body:"The reading lists some neat-sounding benefits of charging for the museum, but I don't think they hold up. Take the income argument first. It assumes the same number of people will keep coming once there's a charge, but that almost never happens. Attendance usually drops sharply when a free museum starts charging, and with far fewer visitors, the total income can actually fall, not rise. Second, this idea about overcrowding. Sure, fewer people would come — but the museum's whole purpose is to bring art and history to as many citizens as possible. Cutting the crowd by shutting out families who can't easily pay isn't a success; it's the museum failing at its main job. And the third point, that people value what they pay for? There's really no good evidence for that. Plenty of visitors treat free galleries with great respect, and charging a fee mostly just keeps out the people who would have benefited most."},
  prompt:PROMPT,
  keyPoints:["Attendance usually falls when a free museum starts charging, so income may drop, not rise.","Reducing the crowd by excluding those who cannot pay undermines the museum's main purpose.","There is little evidence that paying makes visitors more respectful; free galleries are respected too."]},
 {id:'ti_x4_stone_observatory',type:'writing',lv:'C1',topic:'Was the stone circle an ancient observatory?',minWords:150,
  reading:{title:'An Ancient Astronomical Observatory',
   body:"A famous prehistoric stone circle has long puzzled archaeologists. One popular theory argues that it was built mainly as an astronomical observatory, used to track the movements of the sun and stars.\n\nThe strongest evidence is alignment. On the longest day of the year, the sun rises exactly over one particular stone, a coincidence that seems far too precise to be accidental.\n\nSupporters also point to the enormous effort involved. Moving such massive stones over long distances would only have been worthwhile for a purpose of the highest importance, such as marking the seasons for farming.\n\nFinally, similar circles elsewhere show comparable alignments, suggesting that the builders shared a deliberate astronomical tradition."},
  lecture:{body:"This observatory theory is appealing, but the evidence is weaker than it first appears. Let's begin with that famous sunrise alignment. Here's the problem: a circle has so many stones and so many gaps that, by pure chance, some of them are bound to line up with the sunrise, the sunset, or a bright star on some important day. Point a line in almost any direction and it will match something in the sky. So a single alignment proves very little. Now, the argument from effort. Yes, moving the stones took enormous work — but people throughout history have made huge efforts for religious or social reasons, not scientific ones. A temple or a meeting place for ceremonies would explain the effort just as well, without any astronomy. And as for the similar circles elsewhere, that's not strong support either. Shared building styles usually spread because of shared culture and religion, and they tell us almost nothing about whether the people inside were studying the stars."},
  prompt:PROMPT,
  keyPoints:["With many stones, some alignment with the sky is likely by chance and proves little.","The huge effort could equally reflect religious or social motives rather than science.","Similar circles elsewhere may share culture or religion, not an astronomical purpose."]},
 {id:'ti_x4_remote_work_productivity',type:'writing',lv:'C1',topic:'Does remote work raise productivity?',minWords:150,
  reading:{title:'The Productivity Gains of Remote Work',
   body:"Since many companies began allowing employees to work from home, supporters have argued that the change makes workforces more productive, for several reasons.\n\nFirst, remote workers avoid the daily commute. The hours once lost travelling to and from an office can now be spent working or resting, leaving employees fresher and more efficient.\n\nSecond, home offers fewer interruptions. Without colleagues stopping by to chat or constant meetings, workers can concentrate deeply on difficult tasks for longer periods.\n\nThird, remote work widens the pool of talent. A company can hire the best people from anywhere in the country, rather than only those who live close enough to travel in each day."},
  lecture:{body:"The reading is confident that working from home boosts productivity, but each of its points deserves a second look. Start with the commute. It's true people save travel time, but that time doesn't automatically go into work. At home, there are children, household chores, deliveries — endless small distractions that an office simply doesn't have, and these can eat up far more than the commute ever did. Second, the claim about fewer interruptions. In practice, a lot of the quick, useful exchanges that used to happen in person now turn into long chains of messages and video calls, which are slower and more tiring. Deep concentration isn't guaranteed just because you're alone. And the third point, hiring from anywhere — that may help the company find talent, but it says nothing about whether each worker is more productive. In fact, managing a team spread across many places is harder, communication slips, and projects can move more slowly, not faster."},
  prompt:PROMPT,
  keyPoints:["Saved commute time is often lost to household distractions that offices lack.","Face-to-face exchanges become slow message chains and calls, harming concentration.","Hiring from anywhere does not raise individual output and makes teams harder to manage."]},
 {id:'ti_x4_wolf_reintroduction',type:'writing',lv:'C1',topic:'Reintroducing wolves to a national park',minWords:150,
  reading:{title:'Bringing Back the Wolves',
   body:"Conservationists have proposed returning wolves to a national park where they were hunted to extinction long ago. They argue that this reintroduction would benefit the whole ecosystem.\n\nTo begin with, wolves would control the deer population. With no large predators, deer have multiplied and stripped the land of young trees, and wolves would restore a natural balance.\n\nFurthermore, the return of wolves would help other species recover. As forests regrow, birds, insects, and beavers would all find new habitats, increasing the park's biodiversity.\n\nLastly, the wolves would attract visitors. Tourists eager to see or hear wild wolves would bring valuable income to the towns around the park."},
  lecture:{body:"This plan to bring back the wolves sounds wonderful on paper, but it overlooks some serious difficulties. Take the first claim, about controlling the deer. The trouble is that a small group of released wolves rarely makes a big dent in a deer population spread over a huge area. The deer simply move to places the wolves don't patrol, so the young trees may keep disappearing anyway. Now, the idea that other species will bounce back. That assumes the forest recovers quickly, but in reality these changes can take many decades, and other factors — climate, disease, human activity — often matter far more than the presence of a few predators. And on the tourism point: yes, some visitors are curious, but wolves are shy and are almost never seen. More importantly, farmers living nearby tend to oppose the plan strongly, fearing for their sheep and cattle, and that conflict can drive tourists and goodwill away rather than attract them."},
  prompt:PROMPT,
  keyPoints:["A few wolves may barely affect deer spread across a large area, as the deer relocate.","Forest and species recovery can take decades and depends more on other factors.","Wolves are rarely seen, and nearby farmers' opposition can outweigh any tourism gain."]}
];
content.toeflint=(content.toeflint||[]).concat(toeflint);
fs.writeFileSync(file,JSON.stringify(content,null,2));
const l={};toeflint.forEach(t=>l[t.lv]=(l[t.lv]||0)+1);
console.log('toeflint added:',toeflint.length,'lv',JSON.stringify(l));
