const fs=require('fs');const path=require('path');const file=path.join(__dirname,'content.json');
const content=JSON.parse(fs.readFileSync(file,'utf8'));
const articles=[
 {id:'art_x5_lost_languages',lv:'B2',field:'sosyal',title:'When a Language Falls Silent',
  body:"Of the roughly seven thousand languages spoken today, experts believe that nearly half may disappear before the end of this century. A language is usually considered safe only while children are still learning it at home. Once parents begin to raise their children in a more powerful national language instead, the older tongue can vanish within a single generation.\n\nWhy should this matter? Each language is far more than a list of words. It carries a unique way of describing the world, along with stories, songs, and knowledge built up over centuries. When the last fluent speaker of a language dies, much of that knowledge dies too, and it can almost never be fully recovered.\n\nAround the world, communities are now fighting to keep their languages alive. Some record their elders so that future generations can hear how words were spoken. Others create schools where lessons are taught in the local tongue, or build apps and dictionaries to help young learners. These efforts do not always succeed, but they show a growing awareness of what is at stake.\n\nProtecting a language is difficult and slow work, and it cannot be done by outsiders alone. In the end, a language survives only if its own community chooses to speak it. Yet the wider world can help, by treating small languages not as obstacles to progress but as treasures worth keeping.",
  items:[
   {q:"According to the text, when is a language usually considered safe?",opts:["When it has a written dictionary","While children are still learning it at home","When governments make it official","When it is taught to outsiders"],ans:1,tr:"Bir dil, çocuklar onu evde öğrenmeye devam ettiği sürece güvende sayılır.",en:"A language is considered safe while children are still learning it at home."},
   {q:"Why does the writer say losing a language matters?",opts:["It makes travel more difficult","It carries unique knowledge that can rarely be recovered","It lowers the value of dictionaries","It confuses national governments"],ans:1,tr:"Her dil, neredeyse geri kazanılamayan özgün bilgi taşıdığı için kaybı önemlidir.",en:"A language carries unique knowledge that can almost never be recovered."},
   {q:"What is one method communities use to protect their languages?",opts:["Banning the national language","Recording elders and creating local-language schools","Refusing to teach children","Closing their dictionaries"],ans:1,tr:"Topluluklar, yaşlıları kaydetmek ve yerel dilde okullar kurmak gibi yöntemler kullanır.",en:"Communities record elders and create schools that teach in the local language."},
   {q:"What does the writer say is essential for a language to survive?",opts:["Help from outsiders only","That its own community chooses to speak it","A large number of words","A powerful national government"],ans:1,tr:"Bir dil ancak kendi topluluğu onu konuşmayı seçerse hayatta kalır.",en:"A language survives only if its own community chooses to speak it."},
   {q:"What is the writer's overall attitude towards small languages?",opts:["They are obstacles to progress","They are treasures worth protecting","They should be replaced quickly","They are impossible to record"],ans:1,tr:"Yazar küçük dilleri korunmaya değer hazineler olarak görür.",en:"The writer regards small languages as treasures worth keeping."}]},
 {id:'art_x5_honeybee_dance',lv:'B2',field:'fen',title:'The Dancing Language of Bees',
  body:"When a honeybee finds a rich patch of flowers, it faces a problem: how can it tell the rest of the hive where the food is? Bees cannot speak, and the inside of a hive is completely dark. Yet somehow a single bee can send hundreds of others straight to a meal that may be kilometres away.\n\nThe answer, discovered by a curious scientist almost a century ago, is a kind of dance. Back at the hive, the successful bee moves in a tight figure-of-eight pattern, shaking its body as it goes. The direction of this 'waggle' tells the other bees which way to fly in relation to the sun, while the length of the dance signals how far they must travel.\n\nWhat makes this so remarkable is that the bees are communicating abstract information, not simply reacting to what is in front of them. A dancing bee is, in effect, describing a place that the others cannot see. For a long time, many people assumed that such behaviour was unique to humans.\n\nScientists are still studying exactly how the watching bees read the dance in the dark, perhaps by feeling its movements and listening to tiny sounds. Whatever the full explanation, the discovery changed the way we think about animal minds, reminding us that intelligence in nature can take forms we never expected.",
  items:[
   {q:"What problem does a honeybee face after finding flowers?",opts:["It cannot fly back to the hive","It must tell other bees where the food is without speaking","It cannot eat the food alone","It forgets the way home"],ans:1,tr:"Arı, konuşmadan diğerlerine yiyeceğin yerini anlatmak zorundadır.",en:"The bee must tell others where the food is without being able to speak."},
   {q:"What does the direction of the waggle dance tell other bees?",opts:["How sweet the flowers are","Which way to fly in relation to the sun","How many bees should go","What colour the flowers are"],ans:1,tr:"'Waggle' dansının yönü, güneşe göre hangi yöne uçacaklarını gösterir.",en:"The direction of the waggle shows which way to fly relative to the sun."},
   {q:"Why does the writer find the dance so remarkable?",opts:["It is very beautiful to watch","The bees communicate about a place they cannot see","It happens only at night","It uses no movement at all"],ans:1,tr:"Arılar göremedikleri bir yer hakkında soyut bilgi ilettiği için dans dikkat çekicidir.",en:"The bees communicate abstract information about a place they cannot see."},
   {q:"What was once widely assumed about this kind of behaviour?",opts:["That it was unique to humans","That it was impossible","That only birds could do it","That it had no purpose"],ans:0,tr:"Uzun süre böyle bir davranışın yalnızca insanlara özgü olduğu sanıldı.",en:"It was long assumed that such behaviour was unique to humans."},
   {q:"What does the discovery suggest about intelligence in nature?",opts:["It exists only in large animals","It can take forms we never expected","It is the same in every species","It cannot be studied"],ans:1,tr:"Keşif, doğadaki zekânın beklemediğimiz biçimler alabileceğini gösterir.",en:"It suggests intelligence in nature can take forms we never expected."}]},
 {id:'art_x5_sourdough',lv:'B1',field:'saglik',title:'The Oldest Way to Make Bread',
  body:"Long before anyone sold packets of yeast in shops, people made bread rise using something much simpler: a mixture of flour and water left out in the open air. This mixture, known as a sourdough starter, catches tiny living things called wild yeast and friendly bacteria that float all around us.\n\nLeft for a few days and fed with fresh flour, the starter begins to bubble and grow. When a baker mixes some of it into dough, these tiny organisms produce gas, and that gas makes the bread rise. They also create the slightly sour taste that gives this kind of bread its name.\n\nMaking sourdough takes patience. The starter must be fed regularly, almost like a small pet, and the bread itself needs many hours to rise. For this reason, many people gave it up when faster methods appeared. In recent years, however, sourdough has become popular again, partly because people enjoy making things slowly with their own hands.\n\nThere may be health reasons too. Some studies suggest that the long, slow rise makes the bread easier for the body to digest. Whether or not that is true, sourdough connects us to one of the oldest skills in human history, a skill that needs nothing more than flour, water, time, and a little care.",
  items:[
   {q:"What is a sourdough starter made from?",opts:["Shop-bought yeast and sugar","Flour and water left in the open air","Milk and eggs","Salt and oil"],ans:1,tr:"Ekşi maya başlangıcı, açık havada bırakılan un ve sudan yapılır.",en:"A sourdough starter is made from flour and water left in the open air."},
   {q:"What makes sourdough bread rise?",opts:["Gas produced by tiny living organisms","Heat from the oven alone","Added sugar","Stirring it quickly"],ans:0,tr:"Ekşi maya ekmeğini, minik canlıların ürettiği gaz kabartır.",en:"Gas produced by the tiny living organisms makes the bread rise."},
   {q:"Why did many people stop making sourdough?",opts:["It tasted bad","Faster methods appeared","Flour became expensive","It was banned"],ans:1,tr:"Daha hızlı yöntemler çıkınca birçok kişi ekşi mayayı bıraktı.",en:"Many people gave it up when faster methods appeared."},
   {q:"Why has sourdough become popular again?",opts:["It needs no flour","People enjoy making things slowly by hand","It is the cheapest bread","It rises in minutes"],ans:1,tr:"İnsanlar bir şeyi yavaşça elleriyle yapmaktan keyif aldığı için ekşi maya yeniden popüler oldu.",en:"It is popular again partly because people enjoy making things slowly by hand."},
   {q:"What possible health benefit does the text mention?",opts:["It contains no calories","The slow rise may make it easier to digest","It cures illnesses","It removes the need for vegetables"],ans:1,tr:"Metin, yavaş kabarmanın ekmeği sindirmesi daha kolay hale getirebileceğinden söz eder.",en:"The text mentions the slow rise may make the bread easier to digest."}]},
 {id:'art_x5_clock_time',lv:'C1',field:'sosyal',title:'How the Clock Changed the World',
  body:"For most of human history, people measured time by the sun, the seasons, and the natural rhythms of the body. A task took as long as it took, and few people needed to know the exact hour. The mechanical clock, which spread through Europe from the medieval period onward, slowly and quietly transformed this way of life.\n\nAt first, clocks were enormous machines housed in church and town towers, ringing bells to mark the hours for everyone within hearing. As they became smaller and cheaper, they moved into homes and, eventually, into pockets. With them came a new idea: that time was something fixed and divisible, the same for everyone, to be measured and not merely felt.\n\nThis change had effects that reached far beyond convenience. Factories could now demand that workers arrive at a precise minute and labour for an exact number of hours. Trains could run to shared timetables, and business could be coordinated across great distances. In countless ways, the clock made the modern, tightly organised world possible.\n\nYet some thinkers argue that we paid a price for this precision. By turning time into something to be counted and saved, we may have made ourselves its servants, forever rushing and forever short of it. The clock gave us extraordinary order, but it also taught us, perhaps too well, to feel that time is always running out.",
  items:[
   {q:"How did most people measure time before mechanical clocks?",opts:["By precise hours and minutes","By the sun, seasons, and natural rhythms","By factory timetables","By ringing their own bells"],ans:1,tr:"İnsanlar çoğunlukla zamanı güneş, mevsimler ve doğal ritimlerle ölçerdi.",en:"Most people measured time by the sun, the seasons, and natural rhythms."},
   {q:"What new idea about time did clocks bring?",opts:["That time could be felt but not measured","That time was fixed, divisible, and the same for everyone","That time did not exist","That only churches owned time"],ans:1,tr:"Saatler, zamanın sabit, bölünebilir ve herkes için aynı olduğu fikrini getirdi.",en:"Clocks brought the idea that time was fixed, divisible, and the same for everyone."},
   {q:"What does the writer say clocks made possible?",opts:["The end of all factories","The modern, tightly organised world","A return to natural rhythms","The disappearance of trains"],ans:1,tr:"Yazara göre saatler modern, sıkı örgütlenmiş dünyayı mümkün kıldı.",en:"The writer says clocks made the modern, tightly organised world possible."},
   {q:"What 'price' do some thinkers say we paid?",opts:["Clocks became too expensive","We became servants of time, always rushing","We forgot how to build towers","Trains stopped running on time"],ans:1,tr:"Bazı düşünürlere göre, sürekli koşturarak zamanın hizmetkârı haline geldik.",en:"Some thinkers say we became servants of time, forever rushing."},
   {q:"What is the main idea of the final paragraph?",opts:["Clocks brought order but also a sense of time running out","Clocks have no effect on daily life","Everyone should throw away their clocks","Time cannot be measured at all"],ans:0,tr:"Son paragrafın ana fikri, saatlerin düzen getirirken bir yandan zamanın tükendiği hissini de yarattığıdır.",en:"The final paragraph's main idea is that clocks brought order but also a sense that time is running out."}]},
 {id:'art_x5_tardigrade',lv:'C1',field:'fen',title:'The Toughest Animal on Earth',
  body:"It is smaller than a grain of sand, lives in the moss on garden walls, and may be the most indestructible creature ever studied. The tardigrade, sometimes called the water bear, looks almost comical under a microscope, plodding along on eight stubby legs. Yet this tiny animal can survive conditions that would kill almost anything else.\n\nWhen its watery home dries out, the tardigrade performs an extraordinary trick. It pulls in its legs, expels most of the water from its body, and curls into a dry, lifeless-looking ball. In this state, its inner workings almost completely stop. It can remain this way for years, and then, when water returns, it slowly comes back to life as though nothing had happened.\n\nIn this dried-out form, tardigrades have endured tests that sound like science fiction. They have survived being frozen to nearly the coldness of outer space, heated above the boiling point of water, and even exposed to the vacuum and radiation of space itself. Few, if any, other animals could withstand such extremes.\n\nScientists are fascinated not just by the toughness of these creatures but by how they achieve it. Understanding the special substances that protect a tardigrade's cells could one day help us store medicines without refrigeration, or protect human tissue from damage. The humble water bear, it turns out, may have lessons to teach us all.",
  items:[
   {q:"What does a tardigrade do when its home dries out?",opts:["It lays eggs and dies","It curls into a dry ball and nearly stops functioning","It grows larger legs","It swims to a new pond"],ans:1,tr:"Su kuruyunca tardigrad kuru bir top haline gelir ve işlevleri neredeyse durur.",en:"It curls into a dry ball and its inner workings almost completely stop."},
   {q:"What happens when water returns to a dried tardigrade?",opts:["It stays lifeless forever","It slowly comes back to life","It explodes","It turns into another animal"],ans:1,tr:"Su geri geldiğinde tardigrad yavaşça yeniden canlanır.",en:"When water returns, it slowly comes back to life."},
   {q:"Which extreme condition have tardigrades survived?",opts:["The vacuum and radiation of space","Being eaten by fish","A thousand years of sunlight","Living without any moss"],ans:0,tr:"Tardigradlar uzayın boşluğu ve radyasyonu gibi koşullara dayanmıştır.",en:"Tardigrades have survived the vacuum and radiation of space."},
   {q:"Why are scientists interested in how tardigrades survive?",opts:["To make them larger","It could help store medicines without refrigeration","To teach them to swim","To remove them from gardens"],ans:1,tr:"Bilim insanları, bunun ilaçları soğutmadan saklamaya yardımcı olabileceği için ilgileniyor.",en:"Understanding it could help store medicines without refrigeration."},
   {q:"What is the writer's tone towards the tardigrade?",opts:["Fearful and disgusted","Admiring and curious","Bored and dismissive","Angry and worried"],ans:1,tr:"Yazarın tardigrada karşı tutumu hayranlık ve merak doludur.",en:"The writer's tone is admiring and curious."}]},
 {id:'art_x5_public_library',lv:'B2',field:'sosyal',title:'More Than a Room of Books',
  body:"Ask most people what a library is for, and they will say borrowing books. That answer was never quite complete, and today it is more incomplete than ever. The modern public library has quietly become one of the most useful, and most underrated, spaces in any town.\n\nLibraries have always offered something rare: a warm, quiet place that anyone may enter without being asked to buy a thing. For a student with no quiet room at home, a job-seeker who needs the internet, or an older person living alone, this open door can matter enormously. In a world where most public spaces expect us to spend money, the library asks for nothing.\n\nMany libraries now lend far more than books. Visitors can borrow tools, musical instruments, or even seeds for their gardens. They run classes in everything from computer skills to local history, and they offer a meeting place for clubs and community groups. For new arrivals to a country, the library is often the first place to find help in their own language.\n\nNone of this means that books no longer matter; they remain at the heart of what a library is. But it does mean that those who measure a library only by the number of books it lends are missing the point. A good library lends opportunity, and that is far harder to count.",
  items:[
   {q:"What does the writer say is special about libraries?",opts:["They are the cheapest shops","Anyone may enter without being asked to buy anything","They only allow students","They are always noisy"],ans:1,tr:"Kütüphanelerin özelliği, kimsenin bir şey satın alması beklenmeden girebilmesidir.",en:"Anyone may enter a library without being asked to buy anything."},
   {q:"Who is given as an example of someone the open door helps?",opts:["A wealthy shop owner","A job-seeker who needs the internet","A famous writer","A factory manager"],ans:1,tr:"Açık kapının yardımcı olduğu örneklerden biri, internete ihtiyaç duyan bir iş arayandır.",en:"A job-seeker who needs the internet is given as an example."},
   {q:"What can visitors borrow from many modern libraries besides books?",opts:["Cars and houses","Tools, instruments, or seeds","Food and clothes","Money"],ans:1,tr:"Birçok modern kütüphaneden kitap dışında alet, çalgı ya da tohum ödünç alınabilir.",en:"Visitors can borrow tools, instruments, or seeds besides books."},
   {q:"What does the writer mean by 'a good library lends opportunity'?",opts:["Libraries should charge money","A library's value goes beyond the number of books lent","Books are no longer important","Libraries should stop lending books"],ans:1,tr:"Bu ifade, bir kütüphanenin değerinin ödünç verdiği kitap sayısının ötesine geçtiğini anlatır.",en:"It means a library's value goes beyond the number of books it lends."},
   {q:"What does the writer think of judging libraries only by book numbers?",opts:["It is the correct measure","It misses the point","It is the kindest view","It helps libraries grow"],ans:1,tr:"Yazara göre kütüphaneleri yalnızca kitap sayısıyla değerlendirmek konuyu kaçırmaktır.",en:"The writer thinks judging libraries only by book numbers misses the point."}]},
 {id:'art_x5_circadian',lv:'C1',field:'saglik',title:'The Clock Inside Us',
  body:"Hidden deep within the brain lies a tiny cluster of cells that acts like a master clock, quietly setting the rhythm of nearly everything our bodies do. This internal clock, known as the circadian system, runs on a cycle of roughly twenty-four hours, telling us when to feel awake, when to grow sleepy, and even when to feel hungry.\n\nLeft entirely alone, this clock would drift slightly out of step with the real day. To keep it accurate, the body relies on signals from the outside world, the most powerful of which is light. When morning light reaches the eyes, it tells the brain that the day has begun, helping the inner clock to reset itself and stay in time with the sun.\n\nProblems arise when our behaviour and our inner clock fall out of agreement. Travelling quickly across time zones produces the familiar misery of jet lag. Working through the night, or staring at bright screens long after dark, can confuse the system in similar ways, leaving people tired during the day and wide awake at night.\n\nResearchers increasingly believe that a disturbed clock is not merely unpleasant but harmful, linked to poor concentration and a range of health problems. The good news is that the same clock that is so easily upset can also be gently guided. By seeking out daylight in the morning and dimming our screens at night, we can help our inner clock do the job it has been doing for millions of years.",
  items:[
   {q:"What does the circadian system do?",opts:["It controls only hunger","It sets the rhythm of nearly everything the body does","It replaces sleep","It measures temperature only"],ans:1,tr:"Sirkadiyen sistem, bedenin yaptığı neredeyse her şeyin ritmini ayarlar.",en:"The circadian system sets the rhythm of nearly everything the body does."},
   {q:"What is the most powerful signal that keeps the inner clock accurate?",opts:["Noise","Light","Food","Exercise"],ans:1,tr:"İç saati doğru tutan en güçlü dış sinyal ışıktır.",en:"Light is the most powerful signal keeping the inner clock accurate."},
   {q:"What causes jet lag, according to the text?",opts:["Eating too much on a plane","Behaviour and the inner clock falling out of agreement","Sleeping for too long","Bright morning light"],ans:1,tr:"Jet lag, davranış ile iç saatin uyumsuz hale gelmesinden kaynaklanır.",en:"Jet lag is caused by behaviour and the inner clock falling out of step."},
   {q:"Why do bright screens at night cause problems?",opts:["They use too much electricity","They can confuse the circadian system","They improve concentration","They reset the clock perfectly"],ans:1,tr:"Gece parlak ekranlar sirkadiyen sistemi şaşırtabildiği için sorun yaratır.",en:"Bright screens at night can confuse the circadian system."},
   {q:"What practical advice does the writer give?",opts:["Avoid all daylight","Seek morning light and dim screens at night","Sleep only during the day","Stare at screens before bed"],ans:1,tr:"Yazar, sabah gün ışığı almayı ve geceleri ekranları kısmayı önerir.",en:"The writer advises seeking morning daylight and dimming screens at night."}]},
 {id:'art_x5_concrete',lv:'B2',field:'fen',title:'The Material That Built the Modern World',
  body:"Look around almost any city and you will see it everywhere: in pavements, bridges, tunnels, and towers. Concrete is so common that we barely notice it, yet it is the most widely used building material on Earth after water. Its story stretches back thousands of years and reaches right into the problems of our own age.\n\nThe secret of concrete is surprisingly simple. When a grey powder called cement is mixed with water, sand, and stones, a chemical reaction begins that turns the soft, wet mixture into something as hard as rock. Because it can be poured into almost any shape before it sets, concrete lets builders create forms that would be impossible with cut stone alone.\n\nThe ancient Romans were masters of this material, and some of their concrete structures still stand after two thousand years. Strangely, the knowledge of how to make such durable concrete was largely lost for centuries, and only rediscovered and improved in the modern age. Today, enormous quantities are produced every year to house a growing and increasingly urban population.\n\nThis success comes at a cost. Making cement releases large amounts of carbon dioxide, so concrete is now a significant contributor to climate change. Scientists are racing to develop greener versions, and even concrete that can repair its own cracks. The challenge is to keep the benefits of this remarkable material while reducing the harm it does to the planet.",
  items:[
   {q:"How common is concrete, according to the text?",opts:["It is rarely used today","It is the most used building material after water","It is used only in bridges","It is less common than stone"],ans:1,tr:"Metne göre beton, sudan sonra en çok kullanılan yapı malzemesidir.",en:"Concrete is the most widely used building material after water."},
   {q:"Why is concrete so useful to builders?",opts:["It is completely free","It can be poured into almost any shape before it sets","It never gets hard","It needs no water"],ans:1,tr:"Beton, sertleşmeden önce neredeyse her şekle dökülebildiği için çok kullanışlıdır.",en:"It can be poured into almost any shape before it sets."},
   {q:"What is surprising about ancient Roman concrete?",opts:["It was never used","The knowledge to make such durable concrete was largely lost","It was stronger than diamond","It was made without cement"],ans:1,tr:"Şaşırtıcı olan, böyle dayanıklı beton yapma bilgisinin büyük ölçüde kaybolmasıdır.",en:"The knowledge of making such durable concrete was largely lost for centuries."},
   {q:"What is the environmental problem with concrete?",opts:["It uses too much wood","Making cement releases large amounts of carbon dioxide","It cannot be poured","It is too light"],ans:1,tr:"Sorun, çimento üretiminin büyük miktarda karbondioksit salmasıdır.",en:"Making cement releases large amounts of carbon dioxide."},
   {q:"What are scientists trying to develop?",opts:["Concrete that is heavier","Greener concrete that can even repair its own cracks","A way to stop using concrete entirely","Concrete made only of stone"],ans:1,tr:"Bilim insanları, kendi çatlaklarını bile onarabilen daha çevreci beton geliştirmeye çalışıyor.",en:"Scientists are developing greener concrete that can even repair its own cracks."}]},
 {id:'art_x5_storytelling',lv:'B1',field:'sosyal',title:'Why We Tell Stories',
  body:"Every known human society, from the largest city to the smallest village, tells stories. Long before writing existed, people sat around fires and shared tales of heroes, animals, and faraway places. Storytelling is so old and so universal that many scientists believe it is a basic part of being human.\n\nBut why do we do it? One reason is that stories help us learn. A story about a child who wanders too far and meets danger teaches a lesson far more powerfully than a simple warning ever could. Through stories, each generation passes on what it has learned about the world.\n\nStories also bring people together. When we share a tale, we share feelings, and for a short time we see the world through someone else's eyes. This may help explain why we care so deeply about characters who do not even exist. A good story can make us laugh, cry, or hold our breath, all while we sit perfectly still.\n\nToday we tell stories in new ways, through films, games, and screens of every kind, but the basic activity has not changed. We are still doing what our ancestors did around the fire: making sense of our lives by turning them into stories, and sharing those stories with one another.",
  items:[
   {q:"What does the writer say about storytelling across societies?",opts:["Only modern societies tell stories","Every known human society tells stories","Stories began with writing","Villages do not tell stories"],ans:1,tr:"Yazara göre bilinen her insan toplumu hikâye anlatır.",en:"Every known human society tells stories."},
   {q:"How do stories help us learn?",opts:["They teach lessons more powerfully than simple warnings","They replace all schools","They are always written down","They give exact instructions"],ans:0,tr:"Hikâyeler, dersleri basit bir uyarıdan çok daha güçlü biçimde öğretir.",en:"Stories teach lessons more powerfully than a simple warning could."},
   {q:"Why does the writer say we care about characters who don't exist?",opts:["Because stories let us see the world through someone else's eyes","Because the characters are real","Because we are forced to","Because stories are boring"],ans:0,tr:"Hikâyeler dünyayı başkasının gözünden görmemizi sağladığı için var olmayan karakterleri umursarız.",en:"Stories let us see the world through someone else's eyes."},
   {q:"What does the writer say about modern storytelling?",opts:["It has completely disappeared","The basic activity has not changed","It no longer brings people together","It is only done in writing"],ans:1,tr:"Yazara göre biçim değişse de hikâye anlatmanın özü değişmedi.",en:"The basic activity of storytelling has not changed."}]},
 {id:'art_x5_invasive_species',lv:'C1',field:'fen',title:'When a Newcomer Takes Over',
  body:"Sometimes a plant or animal is carried, by accident or on purpose, to a part of the world where it has never lived before. Most such travellers simply fail to survive. A few, however, find their new home so welcoming that they spread out of control, and these are what scientists call invasive species.\n\nThe danger comes from the absence of limits. In its original home, a species is held in check by the predators, diseases, and competitors it evolved alongside. Carried to a new land without any of these, it may multiply with astonishing speed, crowding out native plants and animals that have no defence against it.\n\nThe results can be severe. A single introduced fish can empty a lake of the species that lived there for thousands of years. An imported insect can destroy forests across an entire continent. Beyond the harm to nature, invasive species cost the world's economies enormous sums each year in lost crops and damaged waterways.\n\nDealing with them is notoriously difficult. Once a species is firmly established, removing it completely is often impossible, and the methods used can themselves cause harm. For this reason, experts stress that prevention is far cheaper and more effective than cure. Stopping a newcomer before it arrives is, almost always, the wisest course of all.",
  items:[
   {q:"What is an invasive species?",opts:["Any animal that migrates","A species that spreads out of control in a new home","A species that quickly dies out","A plant grown in gardens"],ans:1,tr:"İstilacı tür, yeni bir yurtta kontrolsüz biçimde yayılan türdür.",en:"An invasive species spreads out of control in a new home."},
   {q:"Why can an invasive species multiply so fast?",opts:["It has no predators or competitors in the new land","It is fed by humans","It needs no food","It is always larger"],ans:0,tr:"İstilacı tür, yeni topraklarda kendisini sınırlayan avcı veya rakibi olmadığı için hızla çoğalır.",en:"It multiplies fast because it has no predators or competitors in the new land."},
   {q:"What example of severe harm does the text give?",opts:["A garden flower spreading slowly","One introduced fish emptying a lake","A bird singing too loudly","A plant growing taller"],ans:1,tr:"Metin, tek bir yabancı balığın bir gölü boşaltabileceği örneğini verir.",en:"The text gives the example of one introduced fish emptying a lake."},
   {q:"Why is dealing with invasive species difficult?",opts:["They are too small to see","Once established, removing them completely is often impossible","They are protected by law everywhere","They never cause any harm"],ans:1,tr:"Bir tür iyice yerleştiğinde tamamen kaldırmak çoğu zaman imkânsız olduğu için baş etmek zordur.",en:"Once established, removing them completely is often impossible."},
   {q:"What do experts say is the wisest approach?",opts:["Ignoring the problem","Prevention rather than cure","Introducing more species","Waiting many years"],ans:1,tr:"Uzmanlar, tedaviden çok önlemenin en akıllıca yol olduğunu vurgular.",en:"Experts say prevention is wiser and more effective than cure."}]}
];
content.articles=content.articles.concat(articles);
fs.writeFileSync(file,JSON.stringify(content,null,2));
const lv={},fl={};articles.forEach(a=>{lv[a.lv]=(lv[a.lv]||0)+1;fl[a.field]=(fl[a.field]||0)+1;});
console.log('articles x5 added:',articles.length,'lv',JSON.stringify(lv),'field',JSON.stringify(fl));
