const fs=require('fs');const path=require('path');const file=path.join(__dirname,'content.json');
const content=JSON.parse(fs.readFileSync(file,'utf8'));
function place(arr,c,t){const x=arr[c];const r=arr.filter((_,i)=>i!==c);t=Math.max(0,Math.min(t,r.length));r.splice(t,0,x);return{arr:r,ans:t};}
const topics=[
 {id:'gr_x6_verb_to_be',lv:'A1',title:"Verb 'to be' (am / is / are)",
  exp:"İngilizcede 'to be' fiili (am / is / are) 'olmak' anlamına gelir; kimlik, durum ve yer bildirir. Özneye göre çekimlenir: I am; you / we / they are; he / she / it is. Konuşmada kısaltmalar yaygındır: I'm, you're, he's. Olumsuzda 'not' eklenir (is not = isn't). Soruda fiil öne alınır: Are you ready?\n\nÖrnekler:\n• I am a teacher. (Ben bir öğretmenim.)\n• She is at home. (O evde.)\n• They are very happy. (Onlar çok mutlu.)\n• Are you tired? (Yorgun musun?)\n\nSık tuzaklar: Türkçede 'olmak' çoğu zaman söylenmez ('Ben mutluyum'), ama İngilizcede 'to be' asla düşmez: 'I happy' YANLIŞ, 'I am happy' doğru. Ayrıca özneye doğru biçimi seç: 'He are' değil 'He is'.",
  items:[
   {q:"I ___ a student at this school.",opts:["am","is","are"],ans:0,tr:"'I' öznesiyle -> am."},
   {q:"She ___ my best friend.",opts:["am","is","are"],ans:1,tr:"'She' (tekil 3.) -> is."},
   {q:"They ___ from Spain.",opts:["is","am","are"],ans:2,tr:"'They' (çoğul) -> are."},
   {q:"___ you a doctor?",opts:["Am","Is","Are"],ans:2,tr:"'you' ile soru -> Are you ...?"},
   {q:"The cat ___ under the table.",opts:["is","are","am"],ans:0,tr:"'The cat' (tekil) -> is."},
   {q:"We ___ ready to start.",opts:["am","is","are"],ans:2,tr:"'We' (çoğul) -> are."},
   {q:"He ___ not at work today.",opts:["are","is","am"],ans:1,tr:"'He' + not -> is not (isn't)."},
   {q:"My parents ___ very kind.",opts:["is","are","am"],ans:1,tr:"'My parents' (çoğul) -> are."}]},
 {id:'gr_x6_present_simple',lv:'A1',title:'Present Simple',
  exp:"Geniş zaman (Present Simple), alışkanlıkları, tekrarlanan eylemleri ve genel gerçekleri anlatır. Fiil yalın hâlde kullanılır; ama özne 'he / she / it' ise fiile -s (veya -es) eklenir: I work / she works. Olumsuz ve soru için yardımcı fiil 'do / does' gelir ve ana fiil yalın kalır: I don't work; Does he work?\n\nÖrnekler:\n• I drink tea every morning. (Her sabah çay içerim.)\n• She lives in Ankara. (O Ankara'da yaşar.)\n• Water boils at 100 degrees. (Su 100 derecede kaynar.)\n• Do you like music? (Müzik sever misin?)\n\nSık tuzaklar: 3. tekil şahısta -s'i unutma: 'She work' YANLIŞ, 'She works' doğru. Soru/olumsuzda -s yardımcı fiile geçer, ana fiile değil: 'Does she works?' YANLIŞ, 'Does she work?' doğru.",
  items:[
   {q:"She ___ to school by bus.",opts:["go","goes","going"],ans:1,tr:"3. tekil şahıs -> goes."},
   {q:"I ___ coffee in the morning.",opts:["drinks","drink","am drink"],ans:1,tr:"'I' ile yalın fiil -> drink."},
   {q:"___ he speak English?",opts:["Do","Does","Is"],ans:1,tr:"3. tekil soru -> Does."},
   {q:"They ___ television every evening.",opts:["watches","watch","watching"],ans:1,tr:"'They' (çoğul) -> watch."},
   {q:"The sun ___ in the east.",opts:["rise","rises","rising"],ans:1,tr:"Genel gerçek, 3. tekil -> rises."},
   {q:"We ___ like spicy food.",opts:["doesn't","don't","isn't"],ans:1,tr:"'We' olumsuz -> don't."},
   {q:"My brother ___ football on Sundays.",opts:["play","plays","playing"],ans:1,tr:"3. tekil -> plays."},
   {q:"I ___ understand this question.",opts:["don't","doesn't","am not"],ans:0,tr:"'I' olumsuz -> don't."}]},
 {id:'gr_x6_present_continuous',lv:'A1',title:'Present Continuous',
  exp:"Şimdiki zaman (Present Continuous), tam şu anda ya da bu günlerde süren eylemleri anlatır. Yapısı: özneye uygun 'to be' (am / is / are) + fiil + -ing. Olumsuzda 'to be' + not; soruda 'to be' öne alınır.\n\nÖrnekler:\n• I am reading a book now. (Şu an bir kitap okuyorum.)\n• She is cooking dinner. (O yemek yapıyor.)\n• They are playing outside. (Onlar dışarıda oynuyor.)\n• What are you doing? (Ne yapıyorsun?)\n\nSık tuzaklar: 'to be' fiilini unutma: 'I reading' YANLIŞ, 'I am reading' doğru. Ayrıca 'like, want, know, love' gibi durum fiilleri genellikle -ing almaz: 'I am knowing' YANLIŞ, 'I know' doğru.",
  items:[
   {q:"Look! The baby ___ .",opts:["sleeps","is sleeping","sleep"],ans:1,tr:"Şu an süren eylem -> is sleeping."},
   {q:"I ___ my homework right now.",opts:["do","am doing","does"],ans:1,tr:"Şu an -> am doing."},
   {q:"What ___ you ___ ?",opts:["do / do","are / doing","is / doing"],ans:1,tr:"Şimdiki zaman sorusu -> are you doing."},
   {q:"They ___ football at the moment.",opts:["play","are playing","plays"],ans:1,tr:"'at the moment' -> are playing."},
   {q:"She ___ TV; she is studying.",opts:["isn't watching","doesn't watch","not watching"],ans:0,tr:"Şu an olumsuz -> isn't watching."},
   {q:"We ___ for the bus now.",opts:["wait","are waiting","waits"],ans:1,tr:"'now' -> are waiting."},
   {q:"He ___ a letter to his friend.",opts:["is writing","writes","write"],ans:0,tr:"Şu an süren -> is writing."},
   {q:"Why ___ you crying?",opts:["do","are","is"],ans:1,tr:"Şimdiki zaman sorusu -> are you crying."}]},
 {id:'gr_x6_there_is_are',lv:'A1',title:'There is / There are',
  exp:"Bir şeyin var olduğunu ya da bir yerde bulunduğunu söylemek için 'There is' (tekil) ve 'There are' (çoğul) kullanılır. Sayılamayan isimlerle 'There is' gelir. Olumsuz: There isn't / There aren't. Soru: Is there ...? / Are there ...?\n\nÖrnekler:\n• There is a book on the table. (Masada bir kitap var.)\n• There are three chairs in the room. (Odada üç sandalye var.)\n• There isn't any milk. (Hiç süt yok.)\n• Are there any questions? (Herhangi bir soru var mı?)\n\nSık tuzaklar: Fiili isme göre seç: 'There is two cats' YANLIŞ, 'There are two cats' doğru. Soru ve olumsuzda çoğunlukla 'any' kullanılır: 'Is there any bread?' Türkçedeki 'var' düşmez, İngilizcede 'there is/are' gereklidir.",
  items:[
   {q:"___ a big park near my house.",opts:["There is","There are","It is"],ans:0,tr:"Tekil isim -> There is."},
   {q:"___ many people at the party.",opts:["There is","There are","There be"],ans:1,tr:"Çoğul isim -> There are."},
   {q:"___ any sugar in the coffee?",opts:["Are there","Is there","There is"],ans:1,tr:"Sayılamayan/tekil soru -> Is there."},
   {q:"There ___ four seasons in a year.",opts:["is","are","be"],ans:1,tr:"'four seasons' çoğul -> are."},
   {q:"There ___ any bread left.",opts:["isn't","aren't","not"],ans:0,tr:"Sayılamayan olumsuz -> isn't."},
   {q:"___ there any apples in the fridge?",opts:["Is","Are","Do"],ans:1,tr:"'apples' çoğul soru -> Are there."},
   {q:"There ___ a problem with the car.",opts:["is","are","have"],ans:0,tr:"Tekil -> There is."},
   {q:"There ___ two banks on this street.",opts:["is","are","be"],ans:1,tr:"'two banks' çoğul -> are."}]},
 {id:'gr_x6_prepositions_place',lv:'A1',title:'Prepositions of Place (in / on / at / under)',
  exp:"Yer edatları bir şeyin nerede olduğunu gösterir. 'in' kapalı/çevrili alan (in the box, in London), 'on' yüzey (on the table, on the wall), 'at' nokta/belirli yer (at the door, at the bus stop), 'under' altında, 'next to / between / behind / in front of' konum bildirir.\n\nÖrnekler:\n• The keys are in my bag. (Anahtarlar çantamda.)\n• The picture is on the wall. (Resim duvarda.)\n• I'm waiting at the bus stop. (Otobüs durağında bekliyorum.)\n• The cat is under the bed. (Kedi yatağın altında.)\n\nSık tuzaklar: Şehir/ülke için 'in' (in Turkey), belirli nokta için 'at' (at the airport). 'on' yüzeyle ilgilidir: 'on the table' (masanın üstünde), 'in the table' değil. Türkçedeki '-de/-da' üç ayrı edata karşılık gelebilir; bağlama bak.",
  items:[
   {q:"The milk is ___ the fridge.",opts:["on","in","at"],ans:1,tr:"Kapalı alan içi -> in."},
   {q:"Your phone is ___ the desk.",opts:["on","in","at"],ans:0,tr:"Yüzey -> on."},
   {q:"I'll meet you ___ the station.",opts:["in","on","at"],ans:2,tr:"Belirli nokta/buluşma -> at."},
   {q:"The ball rolled ___ the sofa.",opts:["under","on","at"],ans:0,tr:"Altında -> under."},
   {q:"She lives ___ Istanbul.",opts:["at","in","on"],ans:1,tr:"Şehir -> in."},
   {q:"The bank is ___ the post office and the café.",opts:["under","on","between"],ans:2,tr:"İki şey arası -> between."},
   {q:"There is a lamp ___ the table.",opts:["on","in","at"],ans:0,tr:"Yüzey üstü -> on."},
   {q:"Wait for me ___ the door.",opts:["in","at","on"],ans:1,tr:"Belirli nokta -> at."}]},
 {id:'gr_x6_can_ability',lv:'A1',title:"Can / Can't (Ability & Permission)",
  exp:"'can' yeteneği ('yapabilmek'), olasılığı ve izni anlatan bir kip fiilidir. Ardından fiilin yalın hâli gelir (can + V1); özneye göre değişmez. Olumsuzu 'cannot / can't'. Soruda 'can' öne alınır: Can you swim?\n\nÖrnekler:\n• I can swim very well. (Çok iyi yüzebilirim.)\n• She can't drive a car. (O araba kullanamaz.)\n• Can you help me, please? (Bana yardım edebilir misin?)\n• We can meet tomorrow. (Yarın buluşabiliriz.)\n\nSık tuzaklar: 'can'den sonra 'to' kullanma: 'I can to swim' YANLIŞ, 'I can swim' doğru. Fiile -s ekleme: 'She cans' YANLIŞ, 'She can' doğru. Ana fiil daima yalın: 'can swims' değil 'can swim'.",
  items:[
   {q:"I ___ play the guitar.",opts:["can","cans","can to"],ans:0,tr:"Kip fiili yalın -> can play."},
   {q:"___ you speak French?",opts:["Do","Can","Are"],ans:1,tr:"Yetenek sorusu -> Can you ...?"},
   {q:"She ___ swim; she's afraid of water.",opts:["can't","doesn't can","not can"],ans:0,tr:"Olumsuz yetenek -> can't."},
   {q:"We can ___ tomorrow if you're free.",opts:["to meet","meet","meets"],ans:1,tr:"can + yalın fiil -> meet."},
   {q:"___ I open the window, please?",opts:["Can","Do","Am"],ans:0,tr:"İzin isteme -> Can I ...?"},
   {q:"He ___ ride a bike now.",opts:["can","cans","is can"],ans:0,tr:"Kip fiili değişmez -> can."},
   {q:"Birds ___ fly, but they can't talk.",opts:["can","cans","can to"],ans:0,tr:"Yalın kip -> can fly."},
   {q:"I'm sorry, I ___ come to your party.",opts:["can't","don't can","not can"],ans:0,tr:"Olumsuz -> can't come."}]},
 {id:'gr_x6_past_simple',lv:'A2',title:'Past Simple',
  exp:"Geçmiş zaman (Past Simple), geçmişte başlayıp biten eylemleri anlatır. Düzenli fiillere -ed eklenir (work → worked); düzensiz fiillerin özel biçimi vardır (go → went, see → saw). Olumsuz ve soruda yardımcı fiil 'did' kullanılır ve ana fiil YALIN hâle döner: I didn't go; Did you see?\n\nÖrnekler:\n• I visited my grandmother yesterday. (Dün büyükannemi ziyaret ettim.)\n• She went to Paris last year. (Geçen yıl Paris'e gitti.)\n• We didn't watch the film. (Filmi izlemedik.)\n• Did they arrive on time? (Zamanında geldiler mi?)\n\nSık tuzaklar: 'did' varken ana fiil geçmiş hâlde olmaz: 'Did you went?' YANLIŞ, 'Did you go?' doğru. Düzensiz fiilleri ezberle: 'goed' değil 'went'.",
  items:[
   {q:"We ___ a great film last night.",opts:["watch","watched","watching"],ans:1,tr:"Düzenli fiil geçmiş -> watched."},
   {q:"She ___ to London in 2019.",opts:["go","went","goes"],ans:1,tr:"Düzensiz fiil geçmiş -> went."},
   {q:"___ you enjoy the party?",opts:["Did","Do","Was"],ans:0,tr:"Geçmiş soru -> Did."},
   {q:"They ___ come to the meeting.",opts:["didn't","don't","weren't"],ans:0,tr:"Geçmiş olumsuz -> didn't."},
   {q:"I ___ a strange noise last night.",opts:["hear","heard","hearing"],ans:1,tr:"Düzensiz fiil -> heard."},
   {q:"Did she ___ the email?",opts:["send","sent","sends"],ans:0,tr:"'did' + yalın fiil -> send."},
   {q:"He ___ his keys at home yesterday.",opts:["leave","left","leaves"],ans:1,tr:"Düzensiz fiil -> left."},
   {q:"We ___ dinner at eight o'clock.",opts:["have","had","has"],ans:1,tr:"Düzensiz fiil -> had."}]},
 {id:'gr_x6_past_continuous',lv:'A2',title:'Past Continuous',
  exp:"Sürekli geçmiş zaman (Past Continuous), geçmişte belirli bir anda süregelen eylemi anlatır. Yapısı: was / were + fiil + -ing. Çoğu zaman Past Simple ile birlikte kullanılır: uzun eylem -ing'li, onu kesen kısa eylem geçmiş yalın hâlde ('when' ile) gelir.\n\nÖrnekler:\n• I was reading when the phone rang. (Telefon çaldığında okuyordum.)\n• They were playing in the garden. (Bahçede oynuyorlardı.)\n• What were you doing at ten? (Saat onda ne yapıyordun?)\n• While she was cooking, he arrived. (O yemek yaparken adam geldi.)\n\nSık tuzaklar: was/were seçimini özneye göre yap: I/he/she/it → was, you/we/they → were. Kesen kısa eylem Past Simple olur: 'when the phone was ringing I answered' yerine 'when the phone rang, I answered'.",
  items:[
   {q:"I ___ TV when you called.",opts:["watched","was watching","am watching"],ans:1,tr:"Kesilen uzun eylem -> was watching."},
   {q:"They ___ football at six o'clock.",opts:["were playing","was playing","played"],ans:0,tr:"'They' -> were playing."},
   {q:"While she ___ , the lights went out.",opts:["cooked","was cooking","cooks"],ans:1,tr:"'while' + süren eylem -> was cooking."},
   {q:"What ___ you doing at midnight?",opts:["was","were","did"],ans:1,tr:"'you' -> were doing."},
   {q:"He ___ when the accident happened.",opts:["drove","was driving","drives"],ans:1,tr:"Süregelen eylem -> was driving."},
   {q:"We ___ dinner when they arrived.",opts:["were having","had","have"],ans:0,tr:"'We' süren eylem -> were having."},
   {q:"The sun ___ , so we went out.",opts:["shone","was shining","shines"],ans:1,tr:"Arka plan durum -> was shining."},
   {q:"I ___ not sleeping at that time.",opts:["was","were","did"],ans:0,tr:"'I' -> was not sleeping."}]},
 {id:'gr_x6_future_will_going',lv:'A2',title:'Future: will & be going to',
  exp:"Gelecekten söz etmenin iki yaygın yolu vardır. 'will + V1' anlık kararları, tahminleri ve söz vermeleri anlatır. 'be going to + V1' önceden yapılmış planları ve kanıta dayalı tahminleri anlatır.\n\nÖrnekler:\n• I'll help you with your bags. (Çantalarına yardım ederim. — anlık karar)\n• I'm going to visit Rome next month. (Gelecek ay Roma'yı ziyaret edeceğim. — plan)\n• It will rain tomorrow. (Yarın yağmur yağacak. — tahmin)\n• Look at those clouds! It's going to rain. (Şu bulutlara bak! Yağmur yağacak. — kanıt var)\n\nSık tuzaklar: Konuşurken kurulan karar için 'going to' yerine 'will' kullan. Planlanmış şeyler için 'will' yerine 'be going to' daha doğaldır. 'be going to'da 'be' fiilini unutma: 'I going to' YANLIŞ, 'I am going to' doğru.",
  items:[
   {q:"The phone is ringing. I ___ answer it.",opts:["will","am going to","going to"],ans:0,tr:"Anlık karar -> will."},
   {q:"We ___ move to a new house next year.",opts:["will","are going to","go"],ans:1,tr:"Önceden yapılmış plan -> are going to."},
   {q:"Look at the sky! It ___ snow.",opts:["will","is going to","goes"],ans:1,tr:"Kanıta dayalı tahmin -> is going to."},
   {q:"Don't worry, I ___ tell anyone.",opts:["won't","am not going","not will"],ans:0,tr:"Söz verme (olumsuz) -> won't."},
   {q:"She ___ study medicine; she has decided.",opts:["will","is going to","goes to"],ans:1,tr:"Kesin plan -> is going to."},
   {q:"I think our team ___ win the match.",opts:["will","going to","is go to"],ans:0,tr:"Tahmin/görüş -> will."},
   {q:"They ___ get married in June.",opts:["will","are going to","go to"],ans:1,tr:"Planlanmış olay -> are going to."},
   {q:"Maybe I ___ call you later.",opts:["will","am going to","go to"],ans:0,tr:"Belirsiz tahmin (maybe) -> will."}]},
 {id:'gr_x6_countable_uncountable',lv:'A2',title:'Countable & Uncountable Nouns',
  exp:"Sayılabilen isimler (countable) tek tek sayılabilir ve çoğul alır: a book / two books. Sayılamayan isimler (uncountable) sayılmaz ve çoğul almaz: water, money, information, advice, bread. Sayılamayanlarla 'a/an' kullanılmaz; miktar için 'some, any, a lot of, a little/much' gelir; sayılabilenlerle 'many, a few' kullanılır.\n\nÖrnekler:\n• I need some information. (Biraz bilgiye ihtiyacım var.)\n• She gave me good advice. (Bana iyi öğüt verdi.)\n• There are many books here. (Burada çok kitap var.)\n• How much money do you have? (Ne kadar paran var?)\n\nSık tuzaklar: 'informations, advices, moneys' YANLIŞTIR — bu isimler çoğul almaz. Saymak için 'a piece of' kullan: 'a piece of advice'. 'many' sayılabilenlerle, 'much' sayılamayanlarla gelir.",
  items:[
   {q:"I'd like some ___ , please.",opts:["informations","information","a information"],ans:1,tr:"Sayılamayan, çoğulsuz -> information."},
   {q:"How ___ water do you drink daily?",opts:["many","much","few"],ans:1,tr:"Sayılamayan -> much."},
   {q:"She bought three ___ at the market.",opts:["breads","loaves of bread","bread"],ans:1,tr:"Saymak için 'loaves of bread'."},
   {q:"There are too ___ cars in the city.",opts:["much","many","little"],ans:1,tr:"Sayılabilen çoğul -> many."},
   {q:"Can you give me some ___ ?",opts:["advice","advices","an advice"],ans:0,tr:"Sayılamayan -> advice."},
   {q:"We only have a ___ eggs left.",opts:["little","few","much"],ans:1,tr:"Sayılabilen az -> a few."},
   {q:"He doesn't have ___ money.",opts:["many","much","a few"],ans:1,tr:"Sayılamayan olumsuz -> much."},
   {q:"I need to buy some ___ .",opts:["furnitures","furniture","a furniture"],ans:1,tr:"'furniture' sayılamaz -> furniture."}]},
 {id:'gr_x6_adverbs_frequency',lv:'A2',title:'Adverbs of Frequency',
  exp:"Sıklık zarfları bir eylemin ne sıklıkla yapıldığını gösterir: always (%100), usually, often, sometimes, rarely, never (%0). Cümlede yeri önemlidir: ana fiilden ÖNCE, ama 'to be' fiilinden SONRA gelir.\n\nÖrnekler:\n• I always brush my teeth at night. (Geceleri hep dişlerimi fırçalarım.)\n• She is usually late. (O genellikle geç kalır.) — 'be'den sonra\n• We sometimes eat out. (Bazen dışarıda yeriz.)\n• He never drinks coffee. (O hiç kahve içmez.)\n\nSık tuzaklar: Zarfı 'be' fiilinden sonra koy: 'She always is late' YANLIŞ, 'She is always late' doğru. 'never' zaten olumsuzdur, ikinci olumsuz ekleme: 'I don't never' YANLIŞ, 'I never' doğru. 'sometimes' cümle başında da olabilir.",
  items:[
   {q:"I ___ eat breakfast before work.",opts:["always","am always","always am"],ans:0,tr:"Ana fiilden önce -> always eat."},
   {q:"She is ___ friendly to everyone.",opts:["always","never is","don't"],ans:0,tr:"'be'den sonra -> is always."},
   {q:"We ___ go to the cinema.",opts:["sometimes","are sometimes","sometimes are"],ans:0,tr:"Ana fiilden önce -> sometimes go."},
   {q:"He ___ drinks alcohol.",opts:["never","don't never","is never"],ans:0,tr:"Tek olumsuz -> never drinks."},
   {q:"They are ___ at home in the evening.",opts:["usually","usually are","don't usually"],ans:0,tr:"'be'den sonra -> are usually."},
   {q:"I ___ watch horror films.",opts:["rarely","am rarely","rarely am"],ans:0,tr:"Ana fiilden önce -> rarely watch."},
   {q:"My teacher is ___ angry.",opts:["never","never is","doesn't"],ans:0,tr:"'be'den sonra -> is never."},
   {q:"___ , we visit our grandparents.",opts:["Sometimes","Never we","Always are"],ans:0,tr:"Cümle başı zarf -> Sometimes."}]},
 {id:'gr_x6_prepositions_time',lv:'A2',title:'Prepositions of Time (at / on / in)',
  exp:"Zaman edatları ne zamanı belirtir. 'at' saat ve belirli anlar için (at 7 o'clock, at night, at the weekend), 'on' gün ve tarihler için (on Monday, on 5th May), 'in' ay, mevsim, yıl ve uzun dönemler için (in July, in summer, in 2020, in the morning).\n\nÖrnekler:\n• The meeting is at three o'clock. (Toplantı saat üçte.)\n• I was born on 12th March. (12 Mart'ta doğdum.)\n• We travel in the summer. (Yazın seyahat ederiz.)\n• She wakes up early in the morning. (Sabahları erken kalkar.)\n\nSık tuzaklar: 'in the morning/afternoon/evening' ama 'AT night'. Günlerle 'on', saatlerle 'at' kullan: 'in Monday' YANLIŞ, 'on Monday' doğru. 'next / last / every' ile edat kullanılmaz: 'in next week' değil 'next week'.",
  items:[
   {q:"The train leaves ___ 9 o'clock.",opts:["in","on","at"],ans:2,tr:"Saat -> at."},
   {q:"My birthday is ___ October.",opts:["in","on","at"],ans:0,tr:"Ay -> in."},
   {q:"We have a test ___ Friday.",opts:["in","on","at"],ans:1,tr:"Gün -> on."},
   {q:"It gets cold ___ winter.",opts:["at","on","in"],ans:2,tr:"Mevsim -> in."},
   {q:"I don't work ___ night.",opts:["at","on","in"],ans:0,tr:"'night' özel durumu -> at night."},
   {q:"She was born ___ 2005.",opts:["on","in","at"],ans:1,tr:"Yıl -> in."},
   {q:"Let's meet ___ Saturday morning.",opts:["at","on","in"],ans:1,tr:"Belirli gün -> on Saturday morning."},
   {q:"The shop opens early ___ the morning.",opts:["at","on","in"],ans:2,tr:"'the morning' -> in."}]},
 {id:'gr_x6_possessives',lv:'A2',title:"Possessives ('s and possessive pronouns)",
  exp:"Sahiplik göstermenin birkaç yolu vardır. İnsanlar/canlılar için ismin sonuna 's eklenir (Ana's book). Çoğul isimlerde yalnızca kesme işareti gelir (the students' room). İyelik sıfatları isimden önce gelir: my, your, his, her, its, our, their. İyelik zamirleri tek başına kullanılır: mine, yours, his, hers, ours, theirs.\n\nÖrnekler:\n• This is Tom's car. (Bu Tom'un arabası.)\n• The girls' school is new. (Kızların okulu yeni.)\n• Is this your bag? — No, it's hers. (Bu senin çantan mı? — Hayır, onunki.)\n• Their house is bigger than ours. (Onların evi bizimkinden büyük.)\n\nSık tuzaklar: İyelik zamirinden sonra isim gelmez: 'This is mine book' YANLIŞ, 'This is my book' ya da 'This is mine' doğru. 'its' (iyelik) ile 'it's' (it is) karıştırılır.",
  items:[
   {q:"This is ___ pencil, not yours.",opts:["my","mine","me"],ans:0,tr:"İsimden önce iyelik sıfatı -> my."},
   {q:"That bag isn't mine; it's ___ .",opts:["her","hers","she"],ans:1,tr:"Tek başına iyelik zamiri -> hers."},
   {q:"I met ___ sister yesterday.",opts:["Tom's","Toms","Tom"],ans:0,tr:"Sahiplik -> Tom's."},
   {q:"The ___ toys are everywhere.",opts:["childrens","children's","childrens'"],ans:1,tr:"Düzensiz çoğul iyelik -> children's."},
   {q:"Is this book ___ ?",opts:["your","yours","you"],ans:1,tr:"Soru sonunda tek başına -> yours."},
   {q:"The dog wagged ___ tail.",opts:["it's","its","his"],ans:1,tr:"İyelik 'its' (it's değil)."},
   {q:"This house is ___ ; we bought it last year.",opts:["our","ours","us"],ans:1,tr:"Tek başına iyelik zamiri -> ours."},
   {q:"The ___ room is on the left.",opts:["boys'","boys","boy's"],ans:0,tr:"Çoğul iyelik -> boys'."}]},
 {id:'gr_x6_should_advice',lv:'A2',title:"'should' for Advice",
  exp:"'should' bir öneri ya da tavsiye vermek için kullanılan kip fiilidir ('-meli/-malı'). Ardından fiilin yalın hâli gelir (should + V1), özneye göre değişmez. Olumsuzu 'shouldn't' (yapmaman iyi olur). Soruda öne alınır: Should I ...?\n\nÖrnekler:\n• You should see a doctor. (Bir doktora görünmelisin.)\n• He shouldn't eat so much sugar. (O kadar çok şeker yememeli.)\n• Should I call her now? (Onu şimdi aramalı mıyım?)\n• We should leave early to avoid traffic. (Trafiğe yakalanmamak için erken çıkmalıyız.)\n\nSık tuzaklar: 'should'dan sonra 'to' kullanma: 'You should to rest' YANLIŞ, 'You should rest' doğru. Fiile -s ekleme: 'She should goes' değil 'She should go'. 'should' zorunluluk değil öneridir; kesin zorunluluk için 'must / have to' kullanılır.",
  items:[
   {q:"You look tired. You ___ rest.",opts:["should","should to","shoulds"],ans:0,tr:"Öneri, yalın fiil -> should rest."},
   {q:"He ___ smoke; it's bad for him.",opts:["shouldn't","don't should","not should"],ans:0,tr:"Olumsuz öneri -> shouldn't."},
   {q:"___ I bring an umbrella?",opts:["Should","Do","Am"],ans:0,tr:"Öneri sorusu -> Should I ...?"},
   {q:"We should ___ early tomorrow.",opts:["to leave","leave","leaves"],ans:1,tr:"should + yalın fiil -> leave."},
   {q:"She ___ study more for the exam.",opts:["should","shoulds","should to"],ans:0,tr:"Kip değişmez -> should study."},
   {q:"You ___ tell lies to your friends.",opts:["shouldn't","doesn't should","not should"],ans:0,tr:"Olumsuz -> shouldn't tell."},
   {q:"They ___ be more careful with money.",opts:["should","should to","shoulding"],ans:0,tr:"Yalın kip -> should be."},
   {q:"What ___ I do about this problem?",opts:["should","do","am"],ans:0,tr:"Tavsiye sorusu -> should."}]}
];
// balance ans across 0-2 within this group
let ctr=0;for(const t of topics)for(const q of t.items){const r=place(q.opts,q.ans,ctr%3);q.opts=r.arr;q.ans=r.ans;ctr++;}
content.grammar=content.grammar.concat(topics);
fs.writeFileSync(file,JSON.stringify(content,null,2));
const lv={};topics.forEach(t=>lv[t.lv]=(lv[t.lv]||0)+1);
const ans={};topics.forEach(t=>t.items.forEach(q=>ans[q.ans]=(ans[q.ans]||0)+1));
console.log('A1-A2 grammar added:',topics.length,'lv',JSON.stringify(lv),'ans',JSON.stringify(ans));
