const fs=require('fs');const path=require('path');const file=path.join(__dirname,'content.json');
const content=JSON.parse(fs.readFileSync(file,'utf8'));
const oddout=[
 {id:'oo_x4_mars_exploration',lv:'C1',field:'fen',sentences:[
  "Robotic rovers have been exploring the surface of Mars for more than two decades.","They drill into rocks, analyse the soil, and send detailed images back to Earth.","From this data, scientists have built a picture of a planet that was once far wetter than it is today.","Each new mission adds to our understanding of whether life could ever have existed there.","The first commercial flight across the Atlantic was a major event in aviation history."],ans:4,
  tr:"Paragraf Mars rover'larını ve gezegenin geçmişini anlatır; Atlantik üzerindeki ilk ticari uçuştan söz eden cümle konu dışıdır.",en:"The paragraph is about Mars rovers and the planet's past; the sentence about the first transatlantic flight is off-topic."},
 {id:'oo_x4_caffeine_effect',lv:'B2',field:'saglik',sentences:[
  "Caffeine is one of the most widely used stimulants in the world.","It works by blocking the chemical in the brain that makes us feel sleepy.","For this reason, a cup of coffee can help people feel alert in the morning.","Too much caffeine late in the day, however, can make it hard to fall asleep.","Most kitchens contain at least one wooden cutting board."],ans:4,
  tr:"Paragraf kafeinin uyarıcı etkisini anlatır; mutfaklarda tahta kesme tahtası bulunduğunu söyleyen cümle alakasızdır.",en:"The paragraph explains caffeine's stimulant effect; the sentence about wooden cutting boards is unrelated."},
 {id:'oo_x4_french_revolution',lv:'C1',field:'sosyal',sentences:[
  "The French Revolution began in 1789 amid deep anger over taxes and inequality.","Crowds in Paris seized power from a monarchy that seemed unable to reform itself.","The years that followed brought both new ideas of citizenship and terrible violence.","Many of the political terms we use today were shaped during this turbulent period.","Olive trees can live for several hundred years if the climate is mild."],ans:4,
  tr:"Paragraf Fransız Devrimi'ni ele alır; zeytin ağaçlarının ömrünü anlatan cümle konuyla bağlantısızdır.",en:"The paragraph is about the French Revolution; the sentence on the lifespan of olive trees is unrelated."},
 {id:'oo_x4_recycling_metal',lv:'B2',field:'fen',sentences:[
  "Recycling metal uses far less energy than producing it from raw ore.","Old cans and machines are melted down and shaped into new products.","Because metal can be reused many times, it is one of the most valuable materials to recycle.","This saves energy and reduces the need for mining.","The novel was translated into more than thirty languages."],ans:4,
  tr:"Paragraf metal geri dönüşümünün enerji tasarrufunu anlatır; romanın otuz dile çevrildiğini söyleyen cümle konu dışıdır.",en:"The paragraph is about energy savings from recycling metal; the sentence about the novel's translations is off-topic."},
 {id:'oo_x4_sleep_stages',lv:'C1',field:'saglik',sentences:[
  "During the night the brain passes through several distinct stages of sleep.","In the deepest stage, the body repairs tissue and strengthens the immune system.","In another stage, known as REM sleep, vivid dreams usually occur.","Disturbing these cycles, even without reducing total sleep, can leave a person feeling tired.","The harbour was famous for the quality of its fresh fish."],ans:4,
  tr:"Paragraf uyku evrelerini anlatır; limanın taze balığıyla ünlü olduğunu söyleyen cümle alakasızdır.",en:"The paragraph describes sleep stages; the sentence about the harbour's fresh fish is unrelated."},
 {id:'oo_x4_ancient_trade_routes',lv:'C1',field:'sosyal',sentences:[
  "Long before modern shipping, goods moved across continents along established trade routes.","Merchants carried silk, spices, and precious metals over deserts and mountains.","Along with these goods travelled languages, religions, and new technologies.","In this way, distant civilisations influenced one another far more than is often assumed.","A healthy adult heart beats about seventy times a minute."],ans:4,
  tr:"Paragraf eski ticaret yollarını ve kültürel etkileşimi anlatır; kalbin dakikadaki atış sayısını veren cümle konu dışıdır.",en:"The paragraph is about ancient trade routes and exchange; the sentence on heart rate is off-topic."},
 {id:'oo_x4_electric_grid',lv:'C1',field:'fen',sentences:[
  "Keeping an electricity grid stable means matching supply to demand at every moment.","If too little power is produced, lights dim and machines fail.","If too much is produced, the system can be damaged just as easily.","Operators therefore watch the network constantly and adjust output second by second.","Many ancient cities were built around a central marketplace."],ans:4,
  tr:"Paragraf elektrik şebekesinin arz-talep dengesini anlatır; eski şehirlerin pazar yeri etrafında kurulduğunu söyleyen cümle alakasızdır.",en:"The paragraph is about balancing the electricity grid; the sentence on ancient marketplaces is unrelated."},
 {id:'oo_x4_vitamin_d',lv:'B2',field:'saglik',sentences:[
  "Our bodies make vitamin D when sunlight falls on the skin.","This vitamin helps to keep bones strong and healthy.","People who spend little time outdoors may not produce enough of it.","Doctors sometimes recommend supplements for those at risk.","The museum's new wing was designed by a famous architect."],ans:4,
  tr:"Paragraf D vitamini ve kemik sağlığını anlatır; müzenin yeni kanadının ünlü bir mimarca tasarlandığını söyleyen cümle konu dışıdır.",en:"The paragraph is about vitamin D and bone health; the sentence about the museum's architect is off-topic."},
 {id:'oo_x4_printing_money',lv:'C1',field:'sosyal',sentences:[
  "When a government prints far more money than its economy can support, prices tend to rise.","Each unit of currency then buys a little less than it did before.","If this continues unchecked, people may lose confidence in the money itself.","History offers several examples of currencies that collapsed in exactly this way.","Penguins spend much of their lives swimming in cold southern waters."],ans:4,
  tr:"Paragraf aşırı para basımı ve enflasyonu anlatır; penguenlerin soğuk sularda yüzdüğünü söyleyen cümle alakasızdır.",en:"The paragraph is about printing money and inflation; the sentence about penguins is unrelated."},
 {id:'oo_x4_plant_communication',lv:'C1',field:'fen',sentences:[
  "Scientists have discovered that plants can communicate with one another.","When attacked by insects, some plants release chemicals into the air.","Nearby plants detect these signals and begin to prepare their own defences.","This hidden conversation helps a whole group of plants survive.","The stadium can hold over sixty thousand spectators."],ans:4,
  tr:"Paragraf bitkilerin kimyasal iletişimini anlatır; stadyumun seyirci kapasitesini veren cümle konu dışıdır.",en:"The paragraph is about plant chemical communication; the sentence on stadium capacity is off-topic."},
 {id:'oo_x4_minimum_sleep_teens',lv:'B2',field:'saglik',sentences:[
  "Teenagers generally need more sleep than adults do.","Their bodies and brains are still growing and changing rapidly.","Yet many of them stay up late and struggle to wake for early classes.","As a result, a large number of students are tired throughout the school day.","The recipe calls for two cups of flour and a little salt."],ans:4,
  tr:"Paragraf ergenlerin uyku ihtiyacını anlatır; un ve tuz isteyen tarif cümlesi alakasızdır.",en:"The paragraph is about teenagers' need for sleep; the recipe sentence is unrelated."},
 {id:'oo_x4_roman_law',lv:'C1',field:'sosyal',sentences:[
  "The legal system of ancient Rome shaped much of the law used in Europe today.","Roman jurists developed clear rules about property, contracts, and citizenship.","These principles were written down and studied for centuries after the empire fell.","Many modern legal terms can be traced directly back to Latin originals.","Bamboo is one of the fastest-growing plants on Earth."],ans:4,
  tr:"Paragraf Roma hukukunun etkisini anlatır; bambunun en hızlı büyüyen bitkilerden olduğunu söyleyen cümle konu dışıdır.",en:"The paragraph is about Roman law's influence; the sentence about bamboo is off-topic."},
 {id:'oo_x4_volcano_monitoring',lv:'C1',field:'fen',sentences:[
  "Scientists watch active volcanoes for signs that an eruption may be near.","Small earthquakes often increase in the weeks before the ground breaks open.","Gases escaping from the rock can also reveal what is happening below.","By combining these clues, experts can sometimes warn people in time.","The orchestra rehearsed the symphony for several weeks."],ans:4,
  tr:"Paragraf volkan izlemeyi anlatır; orkestranın senfoniyi prova ettiğini söyleyen cümle alakasızdır.",en:"The paragraph is about volcano monitoring; the sentence about the orchestra is unrelated."},
 {id:'oo_x4_handwriting_decline',lv:'B2',field:'sosyal',sentences:[
  "As more writing moves to screens, many people use handwriting less and less.","Some schools now spend far less time teaching children to write by hand.","Researchers wonder whether this change will affect how well children learn to spell.","Others point out that typing is simply the skill most jobs now require.","The blue whale is the largest animal that has ever lived."],ans:4,
  tr:"Paragraf el yazısının azalmasını tartışır; mavi balinanın en büyük hayvan olduğunu söyleyen cümle konu dışıdır.",en:"The paragraph discusses the decline of handwriting; the sentence about the blue whale is off-topic."},
 {id:'oo_x4_desalination',lv:'C1',field:'fen',sentences:[
  "In dry coastal regions, some countries now turn seawater into drinking water.","The process removes the salt, leaving water that is safe to use.","Although it can supply cities that have no rivers, it uses a great deal of energy.","Engineers are searching for cheaper ways to carry out this difficult task.","The festival attracts thousands of music lovers every summer."],ans:4,
  tr:"Paragraf deniz suyunun arıtılmasını anlatır; festivalin müzikseverleri çektiğini söyleyen cümle alakasızdır.",en:"The paragraph is about desalination; the sentence about the music festival is unrelated."},
 {id:'oo_x4_memory_palace',lv:'C1',field:'saglik',sentences:[
  "For thousands of years, people have used clever tricks to remember long lists.","One ancient method asks you to imagine placing each item in a familiar room.","To recall the list, you simply walk through the room in your mind.","Competitors in memory contests still rely on this surprisingly powerful technique.","The bakery on the corner opens at six every morning."],ans:4,
  tr:"Paragraf hafıza tekniklerini anlatır; köşedeki fırının altıda açıldığını söyleyen cümle konu dışıdır.",en:"The paragraph is about memory techniques; the sentence about the bakery's opening time is off-topic."},
 {id:'oo_x4_renewable_jobs',lv:'B2',field:'sosyal',sentences:[
  "As countries build more wind and solar farms, new kinds of jobs are appearing.","Workers are needed to install panels, maintain turbines, and manage the power they produce.","Many of these roles are in regions that once depended on coal.","For some communities, the shift to clean energy has brought welcome employment.","Spiders have eight legs and most of them spin webs."],ans:4,
  tr:"Paragraf yenilenebilir enerjinin yeni iş alanlarını anlatır; örümceklerin sekiz bacağını anlatan cümle alakasızdır.",en:"The paragraph is about new jobs in renewable energy; the sentence about spiders is unrelated."},
 {id:'oo_x4_coral_nurseries',lv:'C1',field:'fen',sentences:[
  "To help damaged reefs, scientists have begun growing coral in underwater nurseries.","Small fragments are attached to frames where they can grow in safety.","Once they are large enough, divers move them onto the damaged reef.","Although slow, this patient work is giving some reefs a second chance.","The ancient library held thousands of handwritten scrolls."],ans:4,
  tr:"Paragraf mercan fidanlıklarını anlatır; eski kütüphanenin el yazması tomarları olduğunu söyleyen cümle konu dışıdır.",en:"The paragraph is about coral nurseries; the sentence about the ancient library's scrolls is off-topic."},
 {id:'oo_x4_food_waste',lv:'B2',field:'sosyal',sentences:[
  "A surprising amount of the food produced in the world is never eaten.","Some is lost on farms, while much is thrown away in shops and homes.","Wasting food also wastes the water and energy used to grow it.","Reducing this waste could feed many people and protect the environment.","Lightning is hotter than the surface of the sun."],ans:4,
  tr:"Paragraf gıda israfını anlatır; yıldırımın güneş yüzeyinden sıcak olduğunu söyleyen cümle alakasızdır.",en:"The paragraph is about food waste; the sentence about lightning's temperature is off-topic."},
 {id:'oo_x4_dolphin_intelligence',lv:'C1',field:'fen',sentences:[
  "Dolphins are among the most intelligent animals in the ocean.","They use a system of clicks and whistles to communicate with one another.","Some appear to call each other by signals that work rather like names.","Scientists are still trying to understand how complex this communication really is.","The bridge took almost ten years to complete."],ans:4,
  tr:"Paragraf yunusların zekâsını ve iletişimini anlatır; köprünün on yılda tamamlandığını söyleyen cümle konu dışıdır.",en:"The paragraph is about dolphin intelligence and communication; the sentence about the bridge is off-topic."}
];
content.oddout=content.oddout.concat(oddout);
fs.writeFileSync(file,JSON.stringify(content,null,2));
console.log('oddout x4 added:',oddout.length,'total',content.oddout.length);
