// Batch 4a: surge for the six YDS banks (_x4_ ids). Additive only.
const fs = require('fs'); const path = require('path');
const file = path.join(__dirname, 'content.json');
const content = JSON.parse(fs.readFileSync(file, 'utf8'));
function place(arr, correctIdx, target) {
  const correct = arr[correctIdx];
  const rest = arr.filter((_, i) => i !== correctIdx);
  const t = Math.max(0, Math.min(target, rest.length));
  rest.splice(t, 0, correct);
  return { arr: rest, ans: t };
}

const cloze = [
  { id:'cz_x4_dna_structure', lv:'C1', field:'fen', title:'The Shape of Life',
    text:"The discovery of the structure of DNA is often described as one of the most important moments in the history of biology. For years, scientists knew that this molecule somehow (1) ____ the instructions that living things pass to their offspring, but its exact form remained a mystery. When researchers finally showed that DNA takes the shape of a twisted ladder, the elegance of the design immediately (2) ____ how copying might occur. Each side of the ladder could serve as a template from which a new, identical partner was (3) ____. This insight transformed the field, for it explained how information could be (4) ____ faithfully from one generation to the next. Later work revealed that small changes, or mutations, in the sequence can (5) ____ the way an organism develops, providing the raw material on which evolution acts.",
    blanks:[
      {n:1,opts:['carried','hid','ignored','wasted'],ans:0,tr:"'carried the instructions' = talimatları taşıyordu; DNA kalıtsal bilgiyi taşır. 'hid/ignored' bağlama aykırı.",en:"'carried the instructions' fits: DNA holds hereditary information. 'hid/ignored' contradict."},
      {n:2,opts:['concealed','suggested','prevented','delayed'],ans:1,tr:"'suggested how copying might occur' = kopyalamanın nasıl olabileceğini düşündürdü; tasarımın zarafeti mekanizmayı ima eder.",en:"'suggested how copying might occur' fits: the design hinted at the mechanism."},
      {n:3,opts:['destroyed','built','forgotten','sold'],ans:1,tr:"'a new partner was built' = yeni bir eş inşa edildi; şablondan yeni zincir oluşturulur.",en:"'a new partner was built' fits: a new strand is formed from the template."},
      {n:4,opts:['copied','lost','reduced','hidden'],ans:0,tr:"'information could be copied faithfully' = bilgi sadakatle kopyalanabilir; kalıtımın özü.",en:"'information could be copied faithfully' captures inheritance."},
      {n:5,opts:['stabilise','alter','ignore','measure'],ans:1,tr:"'mutations can alter the way an organism develops' = mutasyonlar gelişimi değiştirebilir; evrimin ham maddesi.",en:"'mutations can alter development' provides the raw material for evolution."}]},
  { id:'cz_x4_renaissance_patronage', lv:'C1', field:'sosyal', title:'Art and Its Patrons',
    text:"The extraordinary flowering of painting and sculpture during the Renaissance cannot be understood without considering the people who paid for it. Wealthy merchants and powerful families competed to (1) ____ the finest artists, treating great works as a sign of their own taste and status. Far from being free to follow their own vision, painters often had to (2) ____ the detailed wishes of those who commissioned them, from the subject of a picture to the precise colours used. Yet this system did not (3) ____ creativity; on the contrary, the steady supply of money allowed artists to experiment with new techniques and materials. Over time, the most successful masters gained enough reputation to (4) ____ greater independence, choosing their own subjects and charging high fees. The relationship between art and wealth, then, was far more (5) ____ than the popular image of the lonely genius suggests.",
    blanks:[
      {n:1,opts:['employ','dismiss','ignore','punish'],ans:0,tr:"'employ the finest artists' = en iyi sanatçıları çalıştırmak; hamiler usta peşindeydi.",en:"'employ the finest artists' fits patrons competing for talent."},
      {n:2,opts:['reject','follow','forget','mock'],ans:1,tr:"'follow the detailed wishes' = ayrıntılı istekleri izlemek; sipariş veren belirlerdi.",en:"'follow the detailed wishes' fits: commissioners dictated terms."},
      {n:3,opts:['encourage','crush','reward','reflect'],ans:1,tr:"'did not crush creativity' = yaratıcılığı ezmedi; sonraki 'on the contrary' karşıtlık kurar.",en:"'did not crush creativity' fits the 'on the contrary' that follows."},
      {n:4,opts:['lose','win','hide','copy'],ans:1,tr:"'win greater independence' = daha fazla bağımsızlık kazanmak; ün bağımsızlık getirdi.",en:"'win greater independence' fits: reputation brought freedom."},
      {n:5,opts:['simple','complex','recent','illegal'],ans:1,tr:"'far more complex' = çok daha karmaşık; yalnız dâhi imgesiyle çelişir.",en:"'far more complex' contrasts with the lonely-genius image."}]},
  { id:'cz_x4_gut_microbes', lv:'B2', field:'saglik', title:'The Bacteria Within',
    text:"For most of medical history, the bacteria living inside the human body were seen mainly as a source of disease. Recently, however, scientists have begun to (1) ____ that many of these tiny organisms are in fact helpful. The community of microbes in our intestines, sometimes called the gut flora, helps us to (2) ____ food that we could not break down on our own. These bacteria also produce certain vitamins and appear to (3) ____ the immune system, teaching it to tell friend from enemy. When the balance of this community is (4) ____, perhaps by a poor diet or a course of antibiotics, the effects can reach far beyond the stomach. Some studies even suggest a link to mood, which is why researchers are now so (5) ____ to understand how these invisible partners shape our health.",
    blanks:[
      {n:1,opts:['deny','realise','forget','hide'],ans:1,tr:"'realise that many are helpful' = çoğunun yararlı olduğunu fark etmek; eski görüşün revizyonu.",en:"'realise that many are helpful' fits the revised view."},
      {n:2,opts:['waste','digest','refuse','count'],ans:1,tr:"'digest food' = yiyeceği sindirmek; bağırsak florasının işlevi.",en:"'digest food' is the gut flora's function."},
      {n:3,opts:['weaken','support','ignore','sell'],ans:1,tr:"'support the immune system' = bağışıklığı desteklemek; sonrasında 'teaching it' bunu açıklar.",en:"'support the immune system' fits 'teaching it to tell friend from enemy'."},
      {n:4,opts:['disturbed','perfect','praised','hidden'],ans:0,tr:"'the balance is disturbed' = denge bozulduğunda; kötü diyet/antibiyotik örneği.",en:"'the balance is disturbed' fits the diet/antibiotic example."},
      {n:5,opts:['unwilling','keen','afraid','slow'],ans:1,tr:"'so keen to understand' = anlamaya öyle istekli; araştırma ilgisinin nedeni.",en:"'so keen to understand' fits researchers' interest."}]},
  { id:'cz_x4_deforestation', lv:'C1', field:'fen', title:'When the Forests Fall',
    text:"Tropical forests are sometimes called the lungs of the planet, yet vast areas of them are cleared every year. The most obvious reason is economic: land that (1) ____ trees can be sold or used to grow crops and raise cattle. The consequences, however, reach far beyond the cleared ground itself. Forests store enormous amounts of carbon, and when they are burned this carbon is (2) ____ into the atmosphere, adding to global warming. The loss of trees also (3) ____ countless species of their only habitat, driving some towards extinction. Perhaps less obviously, large forests help to (4) ____ rainfall across whole regions, so their removal can make distant farmland drier. For all these reasons, many governments and organisations are now searching for ways to make standing forests more (5) ____ than the land beneath them.",
    blanks:[
      {n:1,opts:['once held','never had','always lacked','quietly sold'],ans:0,tr:"'land that once held trees' = bir zamanlar ağaç olan toprak; temizlenen arazi.",en:"'land that once held trees' describes cleared ground."},
      {n:2,opts:['absorbed','released','hidden','frozen'],ans:1,tr:"'carbon is released into the atmosphere' = karbon atmosfere salınır; yanma ile.",en:"'carbon is released' fits burning forests."},
      {n:3,opts:['provides','deprives','reminds','rewards'],ans:1,tr:"'deprives countless species of their habitat' = türleri yaşam alanından yoksun bırakır.",en:"'deprives species of their habitat' fits extinction risk."},
      {n:4,opts:['regulate','ignore','sell','waste'],ans:0,tr:"'help to regulate rainfall' = yağışı düzenlemeye yardımcı olmak; ormanın bölgesel rolü.",en:"'help to regulate rainfall' fits forests' regional role."},
      {n:5,opts:['cheaper','valuable','dangerous','distant'],ans:1,tr:"'more valuable than the land beneath' = altındaki topraktan daha değerli; koruma teşviki.",en:"'more valuable than the land beneath' fits the conservation incentive."}]},
  { id:'cz_x4_behavioural_econ', lv:'C1', field:'sosyal', title:'The Limits of Rational Choice',
    text:"Traditional economics long assumed that people make decisions in a coldly rational way, carefully weighing costs against benefits. In recent decades, however, a new field has (1) ____ this comfortable picture. By running careful experiments, researchers have shown that human choices are frequently (2) ____ by factors that have nothing to do with logic. The way a question is worded, the order in which options appear, or simply what other people are doing can all (3) ____ our decisions. We tend, for example, to fear a loss far more than we value an equal gain, a tendency that classical theory cannot easily (4) ____. Rather than dismissing such behaviour as mere error, the new approach treats it as a regular and predictable feature of the human mind, one that policymakers can take into account when they design (5) ____ that gently guide people towards better choices.",
    blanks:[
      {n:1,opts:['confirmed','challenged','praised','copied'],ans:1,tr:"'challenged this comfortable picture' = bu rahat tabloyu sarstı; yeni alanın katkısı.",en:"'challenged this comfortable picture' fits the new field."},
      {n:2,opts:['shaped','ignored','perfected','measured'],ans:0,tr:"'choices are shaped by factors' = seçimler mantık dışı etkenlerce biçimlenir.",en:"'choices are shaped by factors' fits the finding."},
      {n:3,opts:['sharpen','sway','reward','count'],ans:1,tr:"'sway our decisions' = kararlarımızı etkilemek; bağlam etkisi.",en:"'sway our decisions' fits contextual influence."},
      {n:4,opts:['explain','cause','enjoy','sell'],ans:0,tr:"'cannot easily explain' = kolayca açıklayamaz; klasik teorinin sınırı.",en:"'cannot easily explain' fits the limit of classical theory."},
      {n:5,opts:['weapons','policies','prisons','holidays'],ans:1,tr:"'design policies that gently guide' = nazikçe yönlendiren politikalar tasarlamak; dürtme teorisi.",en:"'policies that gently guide people' fits nudge-style design."}]},
  { id:'cz_x4_organ_transplant', lv:'C1', field:'saglik', title:'A Question of Supply',
    text:"Organ transplantation is one of the great achievements of modern surgery, allowing a failing heart or kidney to be (1) ____ with a healthy one from a donor. The main obstacle is no longer the operation itself, which has become remarkably safe, but the chronic (2) ____ of suitable organs. Far more patients are waiting than there are donors available, and many die before a match can be (3) ____. To address this, some countries have changed their laws so that citizens are assumed to be donors unless they (4) ____ choose otherwise, a system that has raised donation rates. Scientists are also exploring bolder solutions, such as growing organs in the laboratory or adapting those of animals. Whatever the method, the goal is the same: to (5) ____ the painful gap between the number of organs needed and the number that can be found.",
    blanks:[
      {n:1,opts:['replaced','painted','hidden','sold'],ans:0,tr:"'replaced with a healthy one' = sağlıklısıyla değiştirilmek; nakil tanımı.",en:"'replaced with a healthy one' defines a transplant."},
      {n:2,opts:['surplus','shortage','beauty','noise'],ans:1,tr:"'chronic shortage of organs' = organ kıtlığı; ana sorun.",en:"'chronic shortage of organs' is the main obstacle."},
      {n:3,opts:['found','wasted','denied','sold'],ans:0,tr:"'a match can be found' = uyumlu organ bulunabilir; bekleme listesi.",en:"'a match can be found' fits the waiting list."},
      {n:4,opts:['actively','rarely','never','loudly'],ans:0,tr:"'unless they actively choose otherwise' = aksini etkin biçimde seçmedikçe; varsayılan bağış.",en:"'actively choose otherwise' fits opt-out donation."},
      {n:5,opts:['widen','close','ignore','enjoy'],ans:1,tr:"'close the painful gap' = acı veren açığı kapatmak; amaç.",en:"'close the gap' states the goal."}]},
  { id:'cz_x4_industrial_revolution', lv:'B2', field:'sosyal', title:'The Age of Machines',
    text:"The Industrial Revolution changed human life more deeply than almost any event before it. Within a few generations, goods that had always been made slowly by hand began to be produced in vast (1) ____ by machines. People who had farmed the land for centuries moved into rapidly growing cities to (2) ____ work in the new factories. Life there was often hard: hours were long, wages were low, and the air was thick with smoke. Yet the changes also (3) ____ enormous wealth and, in time, cheaper goods for ordinary families. Perhaps most importantly, the period created a sense that the future need not (4) ____ the past, that human societies could be transformed by invention. The world we live in today, with its constant search for new technology, is in many ways the (5) ____ of those noisy early factories.",
    blanks:[
      {n:1,opts:['quantities','silence','colours','holidays'],ans:0,tr:"'produced in vast quantities' = büyük miktarlarda üretmek; makineyle seri üretim.",en:"'in vast quantities' fits machine production."},
      {n:2,opts:['avoid','seek','forget','sell'],ans:1,tr:"'to seek work in the factories' = fabrikada iş aramak; kente göç.",en:"'to seek work' fits migration to cities."},
      {n:3,opts:['destroyed','created','hid','reduced'],ans:1,tr:"'created enormous wealth' = büyük servet yarattı; olumlu yön.",en:"'created enormous wealth' fits the positive side."},
      {n:4,opts:['resemble','help','reward','follow'],ans:0,tr:"'need not resemble the past' = geçmişe benzemek zorunda değil; ilerleme fikri.",en:"'need not resemble the past' fits the idea of progress."},
      {n:5,opts:['enemy','child','rival','victim'],ans:1,tr:"'the child of those early factories' = o erken fabrikaların çocuğu; süreklilik metaforu.",en:"'the child of those early factories' fits the continuity metaphor."}]},
  { id:'cz_x4_quantum_world', lv:'C1', field:'fen', title:'The Strange Rules of the Very Small',
    text:"At the scale of atoms and the particles inside them, nature behaves in ways that seem to (1) ____ common sense. A particle that we might picture as a tiny ball can also act like a spreading wave, and until it is measured it appears to exist in several states at (2) ____. These ideas were so unfamiliar that even the scientists who developed them found the results difficult to (3) ____. Yet the theory has been tested countless times and has never failed, making it one of the most successful descriptions of nature ever produced. Far from being mere abstraction, its predictions (4) ____ much of modern technology, from the lasers in supermarket scanners to the chips inside our phones. The lesson, perhaps, is that the universe is under no (5) ____ to match the expectations of creatures who evolved to deal with rocks and rivers.",
    blanks:[
      {n:1,opts:['confirm','defy','reward','copy'],ans:1,tr:"'defy common sense' = sağduyuya meydan okumak; kuantumun tuhaflığı.",en:"'defy common sense' fits quantum strangeness."},
      {n:2,opts:['once','random','noon','the same time'],ans:3,tr:"'in several states at the same time' = aynı anda birkaç durumda; süperpozisyon.",en:"'at the same time' fits superposition."},
      {n:3,opts:['accept','sell','hide','count'],ans:0,tr:"'difficult to accept' = kabul etmesi güç; tanıdık olmayan sonuçlar.",en:"'difficult to accept' fits the unfamiliar results."},
      {n:4,opts:['underpin','ignore','delay','waste'],ans:0,tr:"'predictions underpin modern technology' = öngörüler teknolojinin temelini oluşturur.",en:"'underpin modern technology' fits lasers and chips."},
      {n:5,opts:['obligation','holiday','danger','price'],ans:0,tr:"'under no obligation to match our expectations' = beklentilerimize uymak zorunda değil.",en:"'under no obligation' fits the closing point."}]},
  { id:'cz_x4_procrastination', lv:'B2', field:'saglik', title:'Why We Put Things Off',
    text:"Almost everyone has, at some point, delayed an important task in favour of something easier or more pleasant. Psychologists who study this habit, known as procrastination, argue that it is rarely a simple matter of (1) ____. More often, people put things off because the task makes them feel anxious or bored, and avoiding it brings a short moment of (2) ____. Unfortunately, the task does not disappear, and the stress usually (3) ____ as the deadline approaches. Researchers suggest that the most effective response is not to wait for motivation to appear but to make the first step as (4) ____ as possible, perhaps by promising to work for only five minutes. Once a person has begun, continuing often feels surprisingly easy. Understanding procrastination as an emotional habit rather than a (5) ____ failing can make it far less frightening to overcome.",
    blanks:[
      {n:1,opts:['laziness','genius','wealth','luck'],ans:0,tr:"'rarely a simple matter of laziness' = nadiren sadece tembellik meselesi; yaygın yanılgıyı çürütür.",en:"'a simple matter of laziness' is the myth being corrected."},
      {n:2,opts:['relief','pain','anger','noise'],ans:0,tr:"'a short moment of relief' = kısa bir rahatlama anı; kaçınmanın ödülü.",en:"'a short moment of relief' fits avoidance."},
      {n:3,opts:['disappears','grows','freezes','helps'],ans:1,tr:"'the stress usually grows' = stres genelde artar; erteleme sonucu.",en:"'the stress usually grows' fits procrastination's cost."},
      {n:4,opts:['hard','small','expensive','boring'],ans:1,tr:"'make the first step as small as possible' = ilk adımı olabildiğince küçük yapmak; strateji.",en:"'as small as possible' fits the recommended strategy."},
      {n:5,opts:['moral','musical','foreign','royal'],ans:0,tr:"'rather than a moral failing' = ahlaki bir kusur olarak değil; duygusal alışkanlık vurgusu.",en:"'a moral failing' contrasts with the emotional-habit view."}]},
  { id:'cz_x4_age_exploration', lv:'B2', field:'sosyal', title:'Across Unknown Seas',
    text:"In the fifteenth and sixteenth centuries, sailors from Europe set out on voyages that would (1) ____ the map of the world. Driven by the hope of profit and the search for new routes to the spices of Asia, they crossed oceans that had never before been (2) ____ by their people. These journeys required real courage, for the ships were small and the dangers were great. The results, however, were enormous and not always happy. Contact between distant continents allowed plants, animals, and ideas to (3) ____ in every direction, changing diets and landscapes forever. At the same time, the arrival of the newcomers often brought disease and conquest to the peoples they (4) ____. The age of exploration, then, must be remembered as a period that was at once (5) ____ and deeply destructive, depending very much on where one stood.",
    blanks:[
      {n:1,opts:['redraw','hide','forget','copy'],ans:0,tr:"'redraw the map of the world' = dünya haritasını yeniden çizmek; keşiflerin etkisi.",en:"'redraw the map' fits the impact of exploration."},
      {n:2,opts:['crossed','painted','sold','counted'],ans:0,tr:"'never before been crossed' = daha önce hiç geçilmemiş; bilinmeyen okyanuslar.",en:"'never before been crossed' fits unknown seas."},
      {n:3,opts:['spread','vanish','rest','hide'],ans:0,tr:"'allowed plants and ideas to spread' = bitki ve fikirlerin yayılmasını sağladı; değiş tokuş.",en:"'to spread in every direction' fits the exchange."},
      {n:4,opts:['encountered','invented','rewarded','praised'],ans:0,tr:"'the peoples they encountered' = karşılaştıkları halklar; fetih ve hastalık.",en:"'the peoples they encountered' fits conquest and disease."},
      {n:5,opts:['remarkable','silent','cheap','recent'],ans:0,tr:"'at once remarkable and deeply destructive' = hem dikkat çekici hem yıkıcı; çift yönlü değerlendirme.",en:"'remarkable and deeply destructive' fits the balanced verdict."}]},
  { id:'cz_x4_wildfire_ecology', lv:'C1', field:'fen', title:'Fire and the Forest',
    text:"To most people, a forest fire is simply a disaster, and in many cases it certainly is. Yet ecologists have come to understand that fire is also a natural part of how some landscapes (1) ____. Certain trees, for instance, produce cones that only open and release their seeds when (2) ____ to intense heat, so that a new generation springs up after the flames have passed. For thousands of years, small, frequent fires cleared away dead wood and kept these systems healthy. Problems arise when humans (3) ____ all fires for long periods, allowing fuel to build up until an eventual blaze becomes far more (4) ____ than any natural one. Managing such landscapes, therefore, is not a matter of removing fire altogether but of restoring something closer to the balance that existed before people tried to (5) ____ it completely.",
    blanks:[
      {n:1,opts:['function','vanish','rest','hide'],ans:0,tr:"'how some landscapes function' = bazı ekosistemlerin işleyişi; ateşin doğal rolü.",en:"'how landscapes function' fits fire's natural role."},
      {n:2,opts:['exposed','hidden','sold','married'],ans:0,tr:"'exposed to intense heat' = yoğun ısıya maruz kalınca; kozalakların açılması.",en:"'exposed to intense heat' fits seed release."},
      {n:3,opts:['suppress','enjoy','count','paint'],ans:0,tr:"'humans suppress all fires' = insanlar tüm yangınları bastırınca; yakıt birikimi.",en:"'suppress all fires' fits fuel build-up."},
      {n:4,opts:['gentle','destructive','distant','cheap'],ans:1,tr:"'far more destructive' = çok daha yıkıcı; biriken yakıtın sonucu.",en:"'far more destructive' fits accumulated fuel."},
      {n:5,opts:['control','reward','copy','sell'],ans:0,tr:"'tried to control it completely' = onu tümüyle kontrol etmeye çalışmak; dengeyi bozan tutum.",en:"'control it completely' fits the disruptive approach."}]},
  { id:'cz_x4_telemedicine', lv:'B2', field:'saglik', title:'The Doctor on the Screen',
    text:"In recent years, more and more patients have begun to see their doctors not in person but through a screen. This practice, known as telemedicine, allows a patient at home to (1) ____ a video call with a nurse or physician many miles away. For people who live far from a hospital or who find travel difficult, the benefits are (2) ____: advice that once required a long journey can now arrive in minutes. Telemedicine is also useful for simple matters, such as checking on a patient's recovery or (3) ____ a repeat prescription. It is not, of course, a complete (4) ____ for the traditional visit, since many conditions still need a physical examination. Used wisely, however, it can free doctors to spend more time with the patients who truly need to be (5) ____ in person.",
    blanks:[
      {n:1,opts:['have','avoid','sell','forget'],ans:0,tr:"'have a video call' = görüntülü görüşme yapmak; telesağlığın tanımı.",en:"'have a video call' defines telemedicine."},
      {n:2,opts:['clear','hidden','cheap','dangerous'],ans:0,tr:"'the benefits are clear' = yararlar açık; uzaktakiler için.",en:"'the benefits are clear' fits remote patients."},
      {n:3,opts:['hiding','renewing','wasting','selling'],ans:1,tr:"'renewing a repeat prescription' = tekrar reçeteyi yenilemek; basit işler.",en:"'renewing a prescription' fits simple tasks."},
      {n:4,opts:['copy','replacement','danger','holiday'],ans:1,tr:"'not a complete replacement' = tam bir ikame değil; muayene gerektiren durumlar.",en:"'not a complete replacement' fits cases needing examination."},
      {n:5,opts:['seen','sold','hidden','counted'],ans:0,tr:"'seen in person' = yüz yüze görülmek; gerçekten gerekli hastalar.",en:"'seen in person' fits patients who truly need it."}]},
  { id:'cz_x4_byzantine_trade', lv:'C1', field:'sosyal', title:'The Crossroads City',
    text:"For more than a thousand years, the city of Constantinople stood at the meeting point of Europe and Asia, and its wealth (1) ____ heavily on this position. Goods from distant lands passed through its harbours, and the taxes collected on them filled the treasury of the empire. The city's craftsmen were famous for luxury items, especially silk, the secret of whose production the state guarded (2) ____. So great was the flow of trade that the city's coinage became a trusted currency across much of the medieval world, (3) ____ in markets far beyond the empire's borders. Yet such riches also made the city a (4) ____ for ambitious rivals, and its walls were tested again and again. When those defences finally failed, the loss was felt not only locally but across a network of commerce that had (5) ____ on the great crossroads city for centuries.",
    blanks:[
      {n:1,opts:['rested','vanished','wasted','hid'],ans:0,tr:"'wealth rested on this position' = zenginlik bu konuma dayanıyordu; coğrafi avantaj.",en:"'rested on this position' fits geographic advantage."},
      {n:2,opts:['carelessly','jealously','rarely','loudly'],ans:1,tr:"'guarded jealously' = kıskançlıkla korunan ipek sırrı.",en:"'guarded jealously' fits the silk secret."},
      {n:3,opts:['hidden','accepted','burned','lost'],ans:1,tr:"'accepted in markets far beyond' = uzak pazarlarda kabul edilen; güvenilir para.",en:"'accepted in distant markets' fits the trusted coinage."},
      {n:4,opts:['target','reward','holiday','copy'],ans:0,tr:"'a target for ambitious rivals' = hırslı rakipler için hedef; zenginliğin bedeli.",en:"'a target for rivals' fits the cost of riches."},
      {n:5,opts:['depended','rested','agreed','insisted'],ans:0,tr:"'a network that had depended on the city' = şehre bağımlı ağ; düşüşün etkisi. 'depend on' kalıbı.",en:"'depended on the city' fits the trade network's reliance."}]},
  { id:'cz_x4_biodiversity', lv:'B2', field:'fen', title:'The Web of Living Things',
    text:"A healthy natural area is rarely home to just one or two kinds of plant and animal. Instead, it usually contains a great (1) ____ of species, each connected to the others in countless ways. Scientists use the word biodiversity to describe this richness, and they warn that it is now (2) ____ at an alarming rate. When one species disappears, the effect is rarely limited to that single creature. A predator may lose its prey, a plant may lose the insect that (3) ____ it, and the whole system can become less stable as a result. Protecting biodiversity is not, therefore, simply a matter of saving a few attractive animals; it is about keeping the entire web of life strong enough to (4) ____ the shocks that nature, and human activity, will inevitably bring. For this reason, many scientists regard it as one of the most (5) ____ tasks of our age.",
    blanks:[
      {n:1,opts:['variety','silence','danger','colour'],ans:0,tr:"'a great variety of species' = büyük bir tür çeşitliliği; biyoçeşitlilik tanımı.",en:"'a great variety of species' defines biodiversity."},
      {n:2,opts:['rising','falling','resting','hiding'],ans:1,tr:"'falling at an alarming rate' = endişe verici hızla azalan; uyarı.",en:"'falling at an alarming rate' fits the warning."},
      {n:3,opts:['pollinates','destroys','ignores','sells'],ans:0,tr:"'the insect that pollinates it' = onu tozlaştıran böcek; bağlantı örneği.",en:"'the insect that pollinates it' fits the example of connection."},
      {n:4,opts:['cause','withstand','enjoy','sell'],ans:1,tr:"'withstand the shocks' = şoklara dayanmak; istikrar amacı.",en:"'withstand the shocks' fits the goal of stability."},
      {n:5,opts:['trivial','important','foreign','recent'],ans:1,tr:"'one of the most important tasks' = en önemli görevlerden biri; sonuç.",en:"'one of the most important tasks' concludes the passage."}]},
  { id:'cz_x4_cognitive_bias', lv:'C1', field:'saglik', title:'The Tricks of the Mind',
    text:"We like to believe that our judgements are based on careful thought, but psychologists have shown that the mind takes many (1) ____ that can lead us astray. These mental shortcuts, known as cognitive biases, usually work quickly and without our (2) ____. One of the best known is the tendency to notice and remember only the evidence that supports what we already believe, while quietly (3) ____ anything that does not. Such biases are not a sign of stupidity; even the most intelligent people fall victim to them, often without realising it. The first step towards thinking more clearly is simply to (4) ____ that these tendencies exist, since a danger that is recognised is far easier to guard against. Trained to pause and question their first reaction, people can learn to (5) ____ at least some of the errors that the mind makes so naturally.",
    blanks:[
      {n:1,opts:['shortcuts','holidays','prisoners','colours'],ans:0,tr:"'the mind takes many shortcuts' = zihin birçok kestirme kullanır; bilişsel önyargı.",en:"'shortcuts' names cognitive biases."},
      {n:2,opts:['awareness','money','permission','noise'],ans:0,tr:"'without our awareness' = farkındalığımız olmadan; otomatik işleyiş.",en:"'without our awareness' fits automatic operation."},
      {n:3,opts:['ignoring','rewarding','selling','counting'],ans:0,tr:"'quietly ignoring anything that does not' = desteklemeyeni göz ardı etmek; teyit yanlılığı.",en:"'ignoring anything that does not' fits confirmation bias."},
      {n:4,opts:['deny','recognise','enjoy','sell'],ans:1,tr:"'recognise that these tendencies exist' = bu eğilimleri kabul etmek; ilk adım.",en:"'recognise that these tendencies exist' is the first step."},
      {n:5,opts:['cause','avoid','enjoy','copy'],ans:1,tr:"'avoid at least some of the errors' = hataların bir kısmından kaçınmak; sonuç.",en:"'avoid at least some of the errors' concludes the point."}]}
];
content.cloze = content.cloze.concat(cloze);
fs.writeFileSync(file, JSON.stringify(content, null, 2));
console.log('cloze x4 added:', cloze.length, 'total cloze', content.cloze.length);
