// Oxford 3000 A1 vocab. Format: [w, lv, pos, tr, ex]
module.exports = [
["a","A1","art.","bir (belirsiz tanımlık)","I have a red car."],
["about","A1","adv., prep.","hakkında; yaklaşık","This book is about animals."],
["above","A1","adv., prep.","yukarıda, üstünde","The picture is above the bed."],
["across","A1","adv., prep.","karşıya, karşısında; boyunca","The shop is across the street."],
["action","A1","n.","eylem, hareket; aksiyon","I like action films."],
["activity","A1","n.","etkinlik, faaliyet","Swimming is my favourite activity."],
["actor","A1","n.","aktör, oyuncu","He is a famous actor."],
["actress","A1","n.","kadın oyuncu","The actress is in a new film."],
["add","A1","v.","eklemek; toplamak","Add some sugar to the tea."],
["address","A1","n., v.","adres; hitap etmek","What is your address?"],
["adult","A1","adj., n.","yetişkin","Two adults and one child, please."],
["advice","A1","n.","tavsiye, öğüt","Can you give me some advice?"],
["afraid","A1","adj.","korkmuş; korkan","I am afraid of dogs."],
["after","A1","adv., conj., prep.","sonra","We play football after school."],
["afternoon","A1","n.","öğleden sonra","See you tomorrow afternoon."],
["again","A1","adv.","tekrar, yine","Please say that again."],
["age","A1","n., v.","yaş; çağ","What is your age?"],
["ago","A1","adv.","önce (geçmişte)","I saw him two days ago."],
["agree","A1","v.","aynı fikirde olmak, katılmak","I agree with you."],
["air","A1","n.","hava","The air is clean in the mountains."],
["airport","A1","n.","havalimanı","The airport is far from the city."],
["all","A1","adv., det., pron.","hepsi, tüm","All my friends are here."],
["also","A1","adv.","ayrıca, de/da","She speaks English and also French."],
["always","A1","adv.","her zaman, daima","I always get up at seven."],
["amazing","A1","adj.","şaşırtıcı, harika","The view from here is amazing."],
["and","A1","conj.","ve","I like tea and coffee."],
["angry","A1","adj.","kızgın, öfkeli","Dad was angry about the broken window."],
["animal","A1","n.","hayvan","A cat is a small animal."],
["another","A1","det., pron.","başka, bir tane daha","Can I have another apple?"],
["answer","A1","n., v.","cevap; cevaplamak","I don't know the answer."],
["any","A1","adv., det., pron.","hiç, herhangi","Do you have any questions?"],
["anyone","A1","pron.","herhangi biri, kimse","Is anyone at home?"],
["anything","A1","pron.","herhangi bir şey, hiçbir şey","I can't see anything."],
["apartment","A1","n.","daire, apartman dairesi","Our apartment is on the third floor."],
["apple","A1","n.","elma","She eats an apple every day."],
["april","A1","n.","nisan","My birthday is in April."],
["area","A1","n.","alan, bölge","This is a quiet area of the city."],
["around","A1","adv., prep.","etrafında, çevresinde; yaklaşık","We walked around the park."],
["arrive","A1","v.","varmak, ulaşmak","The train arrives at six."],
["art","A1","n.","sanat","She loves modern art."],
["article","A1","n.","makale; eşya","I read an article about cats."],
["artist","A1","n.","sanatçı, ressam","The artist paints pictures of the sea."],
["as","A1","adv., conj., prep.","gibi; olarak; iken","She works as a teacher."],
["ask","A1","v.","sormak; rica etmek","Can I ask you a question?"],
["at","A1","prep.","-de/-da (yer/zaman)","We meet at school at nine."],
["august","A1","n.","ağustos","We go on holiday in August."],
["aunt","A1","n.","teyze, hala","My aunt lives in Izmir."],
["away","A1","adv.","uzakta, uzağa","The school is two kilometres away."],
["baby","A1","n.","bebek","The baby is sleeping now."],
["back","A1","adj., adv., n., v.","geri; arka; sırt","Come back soon!"],
["bad","A1","adj.","kötü","The weather is bad today."],
["bag","A1","n.","çanta, torba","My bag is very heavy."],
["ball","A1","n.","top","The children play with a ball."],
["banana","A1","n.","muz","Monkeys love bananas."],
["band","A1","n.","müzik grubu; bant","My favourite band has a new song."],
["bank","A1","n.","banka; kıyı","The bank opens at nine."],
["bath","A1","n.","banyo (küvette yıkanma)","I have a bath every evening."],
["bathroom","A1","n.","banyo (oda)","The bathroom is upstairs."],
["be","A1","v., aux. v.","olmak","I want to be a doctor."],
["beach","A1","n.","plaj, kumsal","We played on the beach all day."],
["beautiful","A1","adj.","güzel","What a beautiful garden!"],
["because","A1","conj.","çünkü","I'm happy because it's Friday."],
["become","A1","v.","olmak, haline gelmek","He wants to become a pilot."],
["bed","A1","n.","yatak","I go to bed at ten."],
["bedroom","A1","n.","yatak odası","My bedroom is small but nice."],
["beer","A1","n.","bira","He ordered a glass of beer."],
["before","A1","adv., conj., prep.","önce","Wash your hands before dinner."],
["begin","A1","v.","başlamak","The film begins at eight."],
["beginning","A1","n.","başlangıç","The beginning of the book is funny."],
["behind","A1","adv., prep.","arkasında","The cat is behind the door."],
["believe","A1","v.","inanmak","I believe you."],
["below","A1","adv., prep.","altında, aşağıda","Write your name below the line."],
["best","A1","adj., adv., n.","en iyi","She is my best friend."],
["better","A1","adj., adv., n.","daha iyi","I feel better today."],
["between","A1","adv., prep.","arasında","The bank is between the shop and the cafe."],
["bicycle","A1","n.","bisiklet","I ride my bicycle to school."],
["big","A1","adj.","büyük","They live in a big house."],
["bike","A1","n.","bisiklet, motosiklet","My bike is blue."],
["bill","A1","n., v.","hesap, fatura","Can we have the bill, please?"],
["bird","A1","n.","kuş","A small bird sat on the window."],
["birthday","A1","n.","doğum günü","Happy birthday!"],
["black","A1","adj., n.","siyah","She has black hair."],
["blog","A1","n.","blog","She writes a blog about food."],
["blonde","A1","adj.","sarışın","The girl has blonde hair."],
["blue","A1","adj., n.","mavi","The sky is blue today."],
["boat","A1","n.","tekne, kayık","We went to the island by boat."],
["body","A1","n.","vücut, beden","Exercise is good for your body."],
["book","A1","n., v.","kitap; ayırtmak","I read a book every week."],
["boot","A1","n.","bot, çizme","I need new boots for winter."],
["bored","A1","adj.","sıkılmış, canı sıkkın","I'm bored; let's go out."],
["boring","A1","adj.","sıkıcı","The film was long and boring."],
["born","A1","v.","doğmak (be born)","I was born in 2005."],
["both","A1","det., pron.","her ikisi (de)","Both answers are correct."],
["bottle","A1","n.","şişe","A bottle of water, please."],
["box","A1","n.","kutu","The toys are in the box."],
["boy","A1","n.","erkek çocuk, oğlan","The boy is playing football."],
["boyfriend","A1","n.","erkek arkadaş, sevgili","Her boyfriend is very kind."],
["bread","A1","n.","ekmek","We buy fresh bread every morning."],
["break","A1","n., v.","mola; kırmak","Let's have a break for tea."],
["breakfast","A1","n.","kahvaltı","I have breakfast at seven."],
["bring","A1","v.","getirmek","Please bring your books tomorrow."],
["brother","A1","n.","erkek kardeş, ağabey","My brother is older than me."],
["brown","A1","adj., n.","kahverengi","She has brown eyes."],
["build","A1","v.","inşa etmek, yapmak","They want to build a new school here."],
["building","A1","n.","bina, yapı","That tall building is a hotel."],
["bus","A1","n.","otobüs","I go to work by bus."],
["business","A1","n.","iş, ticaret","My uncle has a small business."],
["busy","A1","adj.","meşgul; yoğun","I'm busy this week."],
["but","A1","conj., prep.","ama, fakat","I like tea but not coffee."],
["butter","A1","n.","tereyağı","She put butter on the bread."],
["buy","A1","v.","satın almak","I want to buy a new phone."],
["by","A1","adv., prep.","tarafından; ile; yanında","We travelled by train."],
["bye","A1","excl.","hoşça kal, güle güle","Bye! See you tomorrow."],
["cafe","A1","n.","kafe","Let's meet at the cafe at ten."],
["cake","A1","n.","kek, pasta","Mum made a chocolate cake."],
["call","A1","n., v.","aramak; çağırmak; arama","Call me this evening."],
["camera","A1","n.","fotoğraf makinesi, kamera","I took the photo with my camera."],
["can","A1","n., modal v.","-ebilmek; teneke kutu","I can swim very well."],
["cannot","A1","modal v.","-ememek","I cannot come today."],
["capital","A1","adj., n.","başkent; büyük harf","Ankara is the capital of Turkey."],
["car","A1","n.","araba, otomobil","Dad washes the car on Sundays."],
["card","A1","n.","kart","I sent her a birthday card."],
["career","A1","n.","kariyer, meslek yaşamı","She wants a career in music."],
["carrot","A1","n.","havuç","Rabbits eat carrots."],
["carry","A1","v.","taşımak","Can you carry this bag for me?"],
["cat","A1","n.","kedi","Our cat sleeps all day."],
["cd","A1","n.","CD","He has a lot of old CDs."],
["cent","A1","n.","sent","The pen costs ninety cents."],
["centre","A1","n., v.","merkez","The shop is in the city centre."],
["century","A1","n.","yüzyıl","The castle is from the twelfth century."],
["chair","A1","n., v.","sandalye","Please sit on this chair."],
["change","A1","n., v.","değişiklik; değiştirmek; bozuk para","I want to change my plan."],
["chart","A1","n., v.","çizelge, grafik","The chart shows the test results."],
["cheap","A1","adj., adv.","ucuz","The market is cheaper than the shop."],
["check","A1","n., v.","kontrol etmek; kontrol","Check your answers again."],
["cheese","A1","n.","peynir","I like cheese on my bread."],
["chicken","A1","n.","tavuk","We had chicken and rice for dinner."],
["child","A1","n.","çocuk","Every child needs love."],
["chocolate","A1","n.","çikolata","She gave me a box of chocolates."],
["choose","A1","v.","seçmek","Choose a colour you like."],
["cinema","A1","n.","sinema","We went to the cinema last night."],
["city","A1","n.","şehir, kent","Istanbul is a very big city."],
["class","A1","n.","sınıf; ders","My class starts at nine."],
["classroom","A1","n.","derslik, sınıf","The classroom has big windows."],
["clean","A1","adj., v.","temiz; temizlemek","I clean my room on Saturdays."],
["climb","A1","n., v.","tırmanmak","The children climb trees in the garden."],
["clock","A1","n.","saat (duvar/masa)","The clock on the wall is slow."],
["close","A1","adj., adv., n., v.","kapatmak; yakın","Please close the door."],
["clothes","A1","n.","giysiler, kıyafetler","I bought new clothes for the party."],
["club","A1","n.","kulüp","She is in the chess club."],
["coat","A1","n.","palto, mont","Take your coat; it's cold."],
["coffee","A1","n.","kahve","Two coffees, please."],
["cold","A1","adj., n.","soğuk; soğuk algınlığı","The water is very cold."],
["college","A1","n.","yüksekokul, kolej","My sister studies at a college."],
["colour","A1","n.","renk","What colour is your bag?"],
["come","A1","v.","gelmek","Come here, please."],
["common","A1","adj.","yaygın, ortak","Smith is a common name in England."],
["company","A1","n.","şirket; eşlik","My father works for a big company."],
["compare","A1","v.","karşılaştırmak","Compare the two pictures."],
["complete","A1","adj., v.","tamamlamak; eksiksiz","Complete the sentences with these words."],
["computer","A1","n.","bilgisayar","I use my computer for homework."],
["concert","A1","n.","konser","The concert starts at eight."],
["conversation","A1","n.","sohbet, konuşma","We had a long conversation about films."],
["cook","A1","n., v.","pişirmek; aşçı","My mother cooks very well."],
["cooking","A1","n.","yemek pişirme","Cooking is fun at the weekend."],
["cool","A1","adj., v.","serin; havalı","It's cool in the evening."],
["correct","A1","adj., v.","doğru; düzeltmek","All your answers are correct."],
["cost","A1","n., v.","fiyat, maliyet; mal olmak","How much does it cost?"],
["could","A1","modal v.","-ebilirdi; (kibar rica)","Could you help me, please?"],
["country","A1","n.","ülke; kırsal","Turkey is a beautiful country."],
["course","A1","n.","kurs; tabii (of course)","I'm taking an English course."],
["cousin","A1","n.","kuzen","My cousin lives in Ankara."],
["cow","A1","n.","inek","The cows are in the field."],
["cream","A1","adj., n.","krema, krem (rengi)","I like cream in my coffee."],
["create","A1","v.","yaratmak, oluşturmak","Children create pictures with paper and colour."],
["culture","A1","n.","kültür","I want to learn about Japanese culture."],
["cup","A1","n.","fincan, bardak; kupa","Would you like a cup of tea?"],
["customer","A1","n.","müşteri","The shop was full of customers."],
["cut","A1","n., v.","kesmek; kesik","Cut the bread with this knife."],
["dad","A1","n.","baba","My dad drives a bus."],
["dance","A1","n., v.","dans; dans etmek","Let's dance to this song."],
["dancer","A1","n.","dansçı","She is a very good dancer."],
["dancing","A1","n.","dans etme","Dancing makes me happy."],
["dangerous","A1","adj.","tehlikeli","Don't swim here; it's dangerous."],
["dark","A1","adj., n.","karanlık; koyu","It gets dark early in winter."],
["date","A1","n., v.","tarih; randevu","What's the date today?"],
["daughter","A1","n.","kız evlat","Their daughter is five years old."],
["day","A1","n.","gün","Monday is the first day of the week."],
["dear","A1","adj., excl.","sevgili; değerli","Dear Anna, how are you?"],
["december","A1","n.","aralık (ay)","It often snows in December."],
["decide","A1","v.","karar vermek","We decided to stay at home."],
["delicious","A1","adj.","lezzetli, nefis","This soup is delicious!"],
["describe","A1","v.","tarif etmek, betimlemek","Describe your best friend."],
["description","A1","n.","tanım, tarif","Write a short description of your town."],
["design","A1","n., v.","tasarım; tasarlamak","I like the design of this chair."],
["desk","A1","n.","çalışma masası, sıra","My books are on the desk."],
["detail","A1","n., v.","ayrıntı, detay","Tell me all the details."],
["dialogue","A1","n.","diyalog, karşılıklı konuşma","Read the dialogue with a partner."],
["dictionary","A1","n.","sözlük","Look up the word in a dictionary."],
["die","A1","v.","ölmek","Plants die without water."],
["diet","A1","n.","beslenme düzeni; diyet","Fruit is an important part of a healthy diet."],
["difference","A1","n.","fark","What's the difference between these two words?"],
["different","A1","adj.","farklı, değişik","My brother and I are very different."],
["difficult","A1","adj.","zor","This question is too difficult."],
["dinner","A1","n.","akşam yemeği","We have dinner at seven."],
["dirty","A1","adj.","kirli","My shoes are dirty."],
["discuss","A1","v.","tartışmak, görüşmek","We discussed the plan in class."],
["dish","A1","n.","yemek; tabak","This dish is made with rice."],
["do","A1","v., aux. v.","yapmak","I do my homework after school."],
["doctor","A1","n.","doktor","You should see a doctor."],
["dog","A1","n.","köpek","The dog runs in the park."],
["dollar","A1","n.","dolar","The book costs ten dollars."],
["door","A1","n.","kapı","Someone is at the door."],
["down","A1","adv., prep.","aşağı, aşağıya","Sit down, please."],
["downstairs","A1","adj., adv.","alt kat(ta)","The kitchen is downstairs."],
["draw","A1","v.","çizmek","Children love to draw pictures."],
["dress","A1","n., v.","elbise; giyinmek","She wore a red dress to the party."],
["drink","A1","n., v.","içecek; içmek","Drink some water after sport."],
["drive","A1","n., v.","araba kullanmak, sürmek","My mum drives me to school."],
["driver","A1","n.","sürücü, şoför","The bus driver was very friendly."],
["during","A1","prep.","sırasında, boyunca","We swim a lot during the summer."],
["dvd","A1","n.","DVD","We watched a DVD at home."],
["each","A1","adv., det., pron.","her (biri)","Each student has a book."],
["ear","A1","n.","kulak","Rabbits have long ears."],
["early","A1","adj., adv.","erken","I get up early on Mondays."],
["east","A1","adj., adv., n.","doğu","The sun rises in the east."],
["easy","A1","adj.","kolay","The test was very easy."],
["eat","A1","v.","yemek (yemek)","We eat lunch at noon."],
["egg","A1","n.","yumurta","I had an egg for breakfast."],
["eight","A1","num.","sekiz","The shop opens at eight."],
["eighteen","A1","num.","on sekiz","She is eighteen years old."],
["eighty","A1","num.","seksen","My grandmother is eighty."],
["elephant","A1","n.","fil","The elephant is the biggest land animal."],
["eleven","A1","num.","on bir","The match starts at eleven."],
["else","A1","adv.","başka","What else do you need?"],
["email","A1","n., v.","e-posta; e-posta göndermek","Send me an email tonight."],
["end","A1","n., v.","son; bitmek","The film ends at ten."],
["enjoy","A1","v.","keyif almak, hoşlanmak","I enjoy playing tennis."],
["enough","A1","adv., det., pron.","yeterli, yeterince","We have enough food for everyone."],
["euro","A1","n.","avro","The ticket costs ten euros."],
["even","A1","adj., adv.","bile, hatta; düz","Even a child can do this."],
["evening","A1","n.","akşam","We watch TV in the evening."],
["event","A1","n.","etkinlik, olay","The school has a sports event today."],
["ever","A1","adv.","hiç (soru); her zaman","Have you ever been to London?"],
["every","A1","det.","her","I walk to school every day."],
["everybody","A1","pron.","herkes","Everybody likes the new teacher."],
["everyone","A1","pron.","herkes","Everyone is here now."],
["everything","A1","pron.","her şey","Everything is ready for the party."],
["exam","A1","n.","sınav","I have an English exam tomorrow."],
["example","A1","n.","örnek","Give me an example, please."],
["excited","A1","adj.","heyecanlı","I'm excited about the trip."],
["exciting","A1","adj.","heyecan verici","The match was very exciting."],
["exercise","A1","n., v.","egzersiz, alıştırma; spor yapmak","Do exercise three on page ten."],
["expensive","A1","adj.","pahalı","This watch is too expensive."],
["explain","A1","v.","açıklamak","Can you explain this word?"],
["extra","A1","adj., adv., n.","ekstra, fazladan","Can we have an extra chair?"],
["eye","A1","n.","göz","She has green eyes."],
["face","A1","n., v.","yüz","Wash your face and hands."],
["fact","A1","n.","gerçek, olgu","It's a fact that fish live in water."],
["fall","A1","n., v.","düşmek; sonbahar","Be careful, don't fall!"],
["false","A1","adj.","yanlış; sahte","Is the sentence true or false?"],
["family","A1","adj., n.","aile","My family lives in a small town."],
["famous","A1","adj.","ünlü","Paris is famous for its tower."],
["fantastic","A1","adj.","harika, müthiş","We had a fantastic holiday."],
["far","A1","adj., adv.","uzak","The station is not far from here."],
["farm","A1","n., v.","çiftlik","There are many animals on the farm."],
["farmer","A1","n.","çiftçi","The farmer gets up very early."],
["fast","A1","adj., adv.","hızlı","He runs very fast."],
["fat","A1","adj., n.","şişman; yağ","The cat is getting fat."],
["father","A1","n.","baba","My father works in a bank."],
["favourite","A1","adj., n.","en sevilen, favori","Blue is my favourite colour."],
["february","A1","n.","şubat","February is the shortest month."],
["feel","A1","n., v.","hissetmek","I feel happy today."],
["feeling","A1","n.","duygu, his","I have a good feeling about this."],
["festival","A1","n.","festival","There is a music festival in June."],
["few","A1","adj., det., pron.","az; birkaç (a few)","I have a few questions."],
["fifteen","A1","num.","on beş","The break is fifteen minutes."],
["fifth","A1","num.","beşinci","My office is on the fifth floor."],
["fifty","A1","num.","elli","Fifty people came to the party."],
["fill","A1","v.","doldurmak","Fill the glass with water."],
["film","A1","n., v.","film; filme çekmek","We watched a film about space."],
["final","A1","adj., n.","son, final","This is your final answer?"],
["find","A1","v.","bulmak","I can't find my keys."],
["finish","A1","n., v.","bitirmek; bitiş","School finishes at three."],
["fire","A1","n., v.","ateş, yangın","The fire is warm and nice."],
["first","A1","adv., det., n., num.","ilk, birinci","January is the first month."],
["fish","A1","n., v.","balık; balık tutmak","There are many fish in this lake."],
["five","A1","num.","beş","I have five lessons today."],
["flat","A1","adj., n.","daire; düz","They live in a small flat."],
["flight","A1","n.","uçuş","Our flight leaves at nine."],
["floor","A1","n.","zemin, yer; kat","The toys are on the floor."],
["flower","A1","n.","çiçek","She picked a flower from the garden."],
["fly","A1","n., v.","uçmak; sinek","Birds fly south in winter."],
["follow","A1","v.","takip etmek, izlemek","Follow me, please."],
["food","A1","n.","yiyecek, yemek","Italian food is delicious."],
["foot","A1","n.","ayak","My left foot hurts."],
["football","A1","n.","futbol","We play football after school."],
["for","A1","prep.","için","This present is for you."],
["forget","A1","v.","unutmak","Don't forget your keys."],
["form","A1","n., v.","form; biçim; oluşturmak","Please fill in this form."],
["forty","A1","num.","kırk","The lesson is forty minutes."],
["four","A1","num.","dört","A car has four wheels."],
["fourteen","A1","num.","on dört","She is fourteen years old."],
["fourth","A1","num.","dördüncü","April is the fourth month."],
["free","A1","adj., adv., v.","ücretsiz; özgür; boş","The museum is free on Mondays."],
["friday","A1","n.","cuma","We have a test on Friday."],
["friend","A1","n.","arkadaş, dost","My best friend lives next door."],
["friendly","A1","adj.","cana yakın, arkadaş canlısı","The people here are very friendly."],
["from","A1","prep.","-den/-dan; -li (yer)","I am from Turkey."],
["front","A1","adj., n.","ön","Wait in front of the school."],
["fruit","A1","n.","meyve","Eat fruit every day."],
["full","A1","adj.","dolu; tok","The bus is full this morning."],
["fun","A1","adj., n.","eğlence; eğlenceli","We had a lot of fun at the picnic."],
["funny","A1","adj.","komik","He told a funny story."],
["future","A1","adj., n.","gelecek","What do you want to do in the future?"],
["game","A1","n.","oyun; maç","Let's play a game."],
["garden","A1","n.","bahçe","There are roses in our garden."],
["geography","A1","n.","coğrafya","Geography is my favourite subject."],
["get","A1","v.","almak; ulaşmak; olmak","Where can I get a ticket?"],
["girl","A1","n.","kız (çocuk)","The girl is reading a book."],
["girlfriend","A1","n.","kız arkadaş, sevgili","He bought flowers for his girlfriend."],
["give","A1","v.","vermek","Give me your hand."],
["glass","A1","n.","bardak; cam","A glass of milk, please."],
["go","A1","n., v.","gitmek","We go to school by bus."],
["good","A1","adj., n.","iyi","That's a good idea."],
["goodbye","A1","excl., n.","hoşça kal","We said goodbye at the station."],
["grandfather","A1","n.","büyükbaba, dede","My grandfather tells great stories."],
["grandmother","A1","n.","büyükanne, nine","My grandmother makes the best cake."],
["grandparent","A1","n.","büyükanne/büyükbaba","I visit my grandparents every Sunday."],
["great","A1","adj.","harika; büyük","We had a great time at the beach."],
["green","A1","adj., n.","yeşil","The grass is green."],
["grey","A1","adj., n.","gri","The sky is grey today."],
["group","A1","n.","grup","Work in groups of four."],
["grow","A1","v.","büyümek; yetiştirmek","Children grow very fast."],
["guess","A1","n., v.","tahmin etmek; tahmin","Guess how old I am!"],
["guitar","A1","n.","gitar","He plays the guitar very well."],
["gym","A1","n.","spor salonu","I go to the gym twice a week."],
["hair","A1","n.","saç","She has long brown hair."],
["half","A1","adv., det., n., pron.","yarım, yarı","Half of the class is absent."],
["hand","A1","n., v.","el; uzatmak","Wash your hands before lunch."],
["happen","A1","v.","olmak, meydana gelmek","What happened to your arm?"],
["happy","A1","adj.","mutlu","I'm happy to see you."],
["hard","A1","adj., adv.","zor; sert; sıkı (çalışmak)","This exercise is hard."],
["hat","A1","n.","şapka","Wear a hat in the sun."],
["hate","A1","n., v.","nefret etmek; nefret","I hate cold weather."],
["have","A1","v., aux. v.","sahip olmak; yemek/içmek","I have two sisters."],
["have to","A1","modal v.","-mek zorunda olmak","I have to leave now."],
["he","A1","pron.","o (erkek)","He is my brother."],
["head","A1","n., v.","baş, kafa","My head hurts."],
["health","A1","n.","sağlık","Fruit is good for your health."],
["healthy","A1","adj.","sağlıklı","She eats healthy food every day."],
["hear","A1","v.","duymak, işitmek","Can you hear the music?"],
["hello","A1","excl., n.","merhaba","Hello! How are you?"],
["help","A1","n., v.","yardım; yardım etmek","Can you help me with this bag?"],
["her","A1","det., pron.","onun (kadın); ona/onu","This is her book."],
["here","A1","adv.","burada, buraya","Come here, please."],
["hey","A1","excl.","hey (seslenme)","Hey! Wait for me!"],
["hi","A1","excl.","selam","Hi, my name is Ali."],
["him","A1","pron.","onu/ona (erkek)","I saw him at school."],
["his","A1","det., pron.","onun (erkek)","His car is red."],
["history","A1","n.","tarih (ders/bilim)","We learn about old cities in history."],
["hobby","A1","n.","hobi, uğraş","Reading is my favourite hobby."],
["holiday","A1","n.","tatil","We go on holiday in July."],
["home","A1","adj., adv., n.","ev; eve","I stayed at home yesterday."],
["homework","A1","n.","ev ödevi","I do my homework in the evening."],
["hope","A1","n., v.","ummak, umut etmek; umut","I hope you feel better soon."],
["horse","A1","n.","at","She rides a horse at the farm."],
["hospital","A1","n.","hastane","The hospital is near the park."],
["hot","A1","adj.","sıcak","Be careful, the soup is hot."],
["hotel","A1","n.","otel","We stayed at a hotel by the sea."],
["hour","A1","n.","saat (süre)","The film is two hours long."],
["how","A1","adv.","nasıl; ne kadar","How are you today?"],
["however","A1","adv.","ancak, yine de","I was tired; however, I finished the work."],
["hundred","A1","num.","yüz (sayı)","There are a hundred students in the hall."],
["hungry","A1","adj.","aç","I'm hungry; let's eat."],
["husband","A1","n.","koca, eş","Her husband is a teacher."],
["i","A1","pron.","ben","I am a student."],
["ice","A1","n.","buz","There is ice on the road."],
["ice cream","A1","n.","dondurma","The children want ice cream."],
["idea","A1","n.","fikir","What a good idea!"],
["if","A1","conj.","eğer, -se/-sa","If it rains, we will stay in."],
["imagine","A1","v.","hayal etmek","Imagine you are on a beach."],
["important","A1","adj.","önemli","Sleep is important for health."],
["improve","A1","v.","geliştirmek, iyileştirmek","I want to improve my English."],
["in","A1","adv., prep.","içinde, -de/-da","The keys are in my bag."],
["include","A1","v.","içermek, dahil etmek","The price includes breakfast."],
["information","A1","n.","bilgi","Where can I get information about buses?"],
["interest","A1","n., v.","ilgi; ilgilendirmek","She has an interest in art."],
["interested","A1","adj.","ilgili, ilgi duyan","I'm interested in old films."],
["interesting","A1","adj.","ilginç","That's an interesting question."],
["internet","A1","n.","internet","I found the answer on the internet."],
["interview","A1","n., v.","mülakat, röportaj","He has a job interview tomorrow."],
["into","A1","prep.","içine, -e/-a","Put the milk into the fridge."],
["introduce","A1","v.","tanıştırmak, tanıtmak","Let me introduce my friend Ayşe."],
["island","A1","n.","ada","We took a boat to the island."],
["it","A1","n., pron.","o (cansız/hayvan)","It is a beautiful day."],
["its","A1","det.","onun (cansız/hayvan)","The dog wagged its tail."],
["jacket","A1","n.","ceket, mont","Take your jacket; it's windy."],
["january","A1","n.","ocak (ay)","The new year starts in January."],
["jeans","A1","n.","kot pantolon","He wears jeans at the weekend."],
["job","A1","n.","iş, meslek","She has a new job at a bank."],
["join","A1","v.","katılmak","Why don't you join our club?"],
["journey","A1","n.","yolculuk","The journey takes three hours."],
["juice","A1","n.","meyve suyu","A glass of orange juice, please."],
["july","A1","n.","temmuz","It's very hot in July."],
["june","A1","n.","haziran","School ends in June."],
["keep","A1","v.","tutmak, saklamak; sürdürmek","Keep your money in a safe place."],
["key","A1","adj., n., v.","anahtar; temel","I lost my house key."],
["kilometre","A1","n.","kilometre","The lake is five kilometres away."],
["kind","A1","adj., n.","tür, çeşit; nazik","What kind of music do you like?"],
["kitchen","A1","n.","mutfak","Mum is cooking in the kitchen."],
["know","A1","v.","bilmek; tanımak","I know the answer."],
["land","A1","n., v.","kara, toprak; inmek","The plane lands at noon."],
["language","A1","n.","dil, lisan","English is an easy language to start."],
["large","A1","adj.","büyük, geniş","A large pizza, please."],
["last","A1","adv., det., n., v.","son; geçen; sürmek","I saw her last week."],
["late","A1","adj., adv.","geç","Don't be late for school."],
["later","A1","adj., adv.","daha sonra","See you later!"],
["laugh","A1","n., v.","gülmek; kahkaha","The joke made everyone laugh."],
["learn","A1","v.","öğrenmek","I'm learning English."],
["left","A1","adj., adv., n.","sol","Turn left at the bank."],
["leg","A1","n.","bacak","The table has four legs."],
["lesson","A1","n.","ders","The first lesson is maths."],
["let","A1","v.","izin vermek; haydi (let's)","Let's go to the park."],
["letter","A1","n.","mektup; harf","I wrote a letter to my friend."],
["library","A1","n.","kütüphane","I borrow books from the library."],
["lie","A1","n., v.","uzanmak; yalan (söylemek)","I lie on the sofa after lunch."],
["life","A1","n.","yaşam, hayat","Life in a village is quiet."],
["light","A1","adj., n., v.","ışık; hafif; açık (renk)","Turn on the light, please."],
["like","A1","n., prep., v.","sevmek, hoşlanmak; gibi","I like apples."],
["lion","A1","n.","aslan","The lion is called the king of animals."],
["list","A1","n., v.","liste","Write a shopping list."],
["listen","A1","v.","dinlemek","Listen to the teacher."],
["little","A1","adj., adv., det., pron.","küçük; az","She has a little dog."],
["live","A1","adj., adv., v.","yaşamak, oturmak; canlı","I live in a small town."],
["local","A1","adj., n.","yerel","We shop at the local market."],
["long","A1","adj., adv.","uzun","The river is very long."],
["look","A1","n., v.","bakmak; görünmek","Look at the board, please."],
["lose","A1","v.","kaybetmek","Don't lose your ticket."],
["lot","A1","adv., det., pron.","çok (a lot of)","She has a lot of books."],
["love","A1","n., v.","sevmek; aşk, sevgi","I love my family."],
["lunch","A1","n.","öğle yemeği","We have lunch at school."],
["machine","A1","n.","makine","This machine makes coffee."],
["magazine","A1","n.","dergi","She reads a fashion magazine."],
["main","A1","adj.","ana, başlıca","The main door is closed."],
["man","A1","n.","adam, erkek","The man in the hat is my uncle."],
["many","A1","det., pron.","çok, birçok","How many brothers do you have?"],
["market","A1","n., v.","pazar, çarşı","We buy vegetables at the market."],
["married","A1","adj.","evli","My sister is married."],
["match","A1","n., v.","maç; eşleştirmek; kibrit","The match starts at three."],
["may","A1","n., modal v.","-ebilir (olasılık/izin); mayıs","It may rain today."],
["maybe","A1","adv.","belki","Maybe we can go tomorrow."],
["me","A1","pron.","beni, bana","Can you help me?"],
["meal","A1","n.","öğün, yemek","Breakfast is my favourite meal."],
["mean","A1","v.","anlamına gelmek; demek istemek","What does this word mean?"],
["meaning","A1","n.","anlam","Find the meaning in the dictionary."],
["meat","A1","n.","et","I don't eat meat."],
["meet","A1","v.","buluşmak; tanışmak","Nice to meet you!"],
["meeting","A1","n.","toplantı","Dad has a meeting at ten."],
["member","A1","n.","üye","I'm a member of the music club."],
["menu","A1","n.","menü","Can we see the menu, please?"],
["message","A1","n.","mesaj","Send me a message tonight."],
["metre","A1","n.","metre","The pool is twenty-five metres long."],
["midnight","A1","n.","gece yarısı","The party ended at midnight."],
["mile","A1","n.","mil","The town is ten miles away."],
["milk","A1","n.","süt","I drink milk every morning."],
["million","A1","num.","milyon","The city has two million people."],
["miss","A1","v.","kaçırmak; özlemek","Hurry, or we'll miss the bus."],
["modern","A1","adj.","modern, çağdaş","They live in a modern flat."],
["moment","A1","n.","an","Wait a moment, please."],
["monday","A1","n.","pazartesi","The shop is closed on Mondays."],
["money","A1","n.","para","How much money do you have?"],
["month","A1","n.","ay (takvim)","June is my favourite month."],
["more","A1","adv., det., pron.","daha (çok)","Can I have some more tea?"],
["morning","A1","n.","sabah","I run every morning."],
["most","A1","adv., det., pron.","en (çok); çoğu","Most children like games."],
["mother","A1","n.","anne","My mother is a nurse."],
["mountain","A1","n.","dağ","The mountain is covered with snow."],
["mouse","A1","n.","fare","The cat caught a mouse."],
["mouth","A1","n.","ağız","Open your mouth, please."],
["move","A1","n., v.","hareket etmek; taşınmak","We moved to a new house."],
["movie","A1","n.","film","Let's watch a movie tonight."],
["much","A1","adv., det., pron.","çok","How much is this bag?"],
["mum","A1","n.","anne","Mum, where are my shoes?"],
["museum","A1","n.","müze","The museum is free for children."],
["music","A1","n.","müzik","She listens to music every day."],
["must","A1","modal v.","-meli/-malı","You must wear a seat belt."],
["my","A1","det.","benim","This is my school."],
["name","A1","n., v.","isim, ad","My name is Deniz."],
["natural","A1","adj.","doğal","The park has natural beauty."],
["near","A1","adj., adv., prep.","yakın(ında)","The school is near my house."],
["need","A1","n., v., modal v.","ihtiyaç duymak; gerekmek","I need a pen."],
["neighbour","A1","n.","komşu","Our neighbours are very kind."],
["never","A1","adv.","asla, hiç","I never drink coffee at night."],
["new","A1","adj.","yeni","I bought a new phone."],
["news","A1","n.","haber(ler)","I watch the news every evening."],
["newspaper","A1","n.","gazete","Dad reads the newspaper at breakfast."],
["next","A1","adj., adv., n.","sonraki, gelecek","The next bus comes at five."],
["next to","A1","prep.","yanında, bitişiğinde","The bank is next to the cafe."],
["nice","A1","adj.","hoş, güzel, iyi","Have a nice day!"],
["night","A1","n.","gece","The baby sleeps all night."],
["nine","A1","num.","dokuz","School starts at nine."],
["nineteen","A1","num.","on dokuz","She is nineteen years old."],
["ninety","A1","num.","doksan","My grandfather is ninety."],
["no","A1","det., excl.","hayır; hiç","No, thank you."],
["no one","A1","pron.","hiç kimse","No one was at home."],
["nobody","A1","pron.","hiç kimse","Nobody knows the answer."],
["north","A1","adj., adv., n.","kuzey","It is colder in the north."],
["nose","A1","n.","burun","The clown has a red nose."],
["not","A1","adv.","değil; -me/-ma","I'm not tired."],
["note","A1","n., v.","not; not etmek","She left a note on the table."],
["nothing","A1","pron.","hiçbir şey","There is nothing in the box."],
["november","A1","n.","kasım","It rains a lot in November."],
["now","A1","adv., conj.","şimdi","I'm busy now."],
["number","A1","n., v.","sayı, numara","What's your phone number?"],
["nurse","A1","n.","hemşire","The nurse helped the old man."],
["o'clock","A1","adv.","saat ... (tam saat)","It's three o'clock."],
["october","A1","n.","ekim (ay)","Leaves fall in October."],
["of","A1","prep.","-in/-ın; -den","A cup of tea, please."],
["off","A1","adv., prep.","kapalı; uzakta; -den (ayrılma)","Turn off the TV."],
["office","A1","n.","ofis, büro","Mum works in an office."],
["often","A1","adv.","sık sık","We often play in the park."],
["oh","A1","excl.","ah, oh","Oh! What a surprise!"],
["ok","A1","adj., adv., excl.","tamam; iyi","OK, let's start."],
["old","A1","adj.","yaşlı; eski","My grandfather is old."],
["on","A1","adv., prep.","üzerinde, üstünde; açık","The book is on the table."],
["once","A1","adv., conj.","bir kez; bir zamanlar","I swim once a week."],
["one","A1","det., num., pron.","bir","I have one brother."],
["onion","A1","n.","soğan","Cut the onion into small pieces."],
["online","A1","adj., adv.","çevrimiçi","I buy books online."],
["only","A1","adj., adv.","sadece, yalnızca","We have only ten minutes."],
["open","A1","adj., v.","açık; açmak","Open your books, please."],
["opinion","A1","n.","görüş, fikir","In my opinion, this film is great."],
["opposite","A1","adj., adv., n., prep.","karşı(sında); zıt","The hotel is opposite the station."],
["or","A1","conj.","veya, ya da","Tea or coffee?"],
["orange","A1","adj., n.","portakal; turuncu","I drink orange juice at breakfast."],
["order","A1","n., v.","sipariş (etmek); sıra; emir","Are you ready to order?"],
["other","A1","adj., pron.","diğer, başka","Where are the other students?"],
["our","A1","det.","bizim","Our house has a garden."],
["out","A1","adv., prep.","dışarı, dışında","Let's go out for a walk."],
["outside","A1","adj., adv., n., prep.","dışarıda, dışarısı","The children are playing outside."],
["over","A1","adv., prep.","üzerinde; bitmiş; fazla","The plane flew over the city."],
["own","A1","adj., pron., v.","kendi; sahip olmak","I have my own room."],
["page","A1","n.","sayfa","Open your books to page ten."],
["paint","A1","n., v.","boyamak; boya","We painted the wall blue."],
["painting","A1","n.","tablo, resim","There is a painting on the wall."],
["pair","A1","n.","çift","I need a new pair of shoes."],
["paper","A1","n.","kâğıt","Write your name on the paper."],
["paragraph","A1","n.","paragraf","Read the first paragraph."],
["parent","A1","n.","ebeveyn, anne/baba","My parents work in the city."],
["park","A1","n., v.","park; park etmek","The children play in the park."],
["part","A1","n.","bölüm, parça","This is my favourite part of the song."],
["partner","A1","n.","eş, partner; ortak","Work with a partner."],
["party","A1","n.","parti","Are you coming to my birthday party?"],
["passport","A1","n.","pasaport","Show your passport at the airport."],
["past","A1","adj., adv., n., prep.","geçmiş; geçe (saat)","It's ten past nine."],
["pay","A1","n., v.","ödemek","Can I pay by card?"],
["pen","A1","n.","tükenmez kalem","Can I borrow your pen?"],
["pencil","A1","n.","kurşun kalem","Draw with a pencil first."],
["people","A1","n.","insanlar","Many people use the metro."],
["pepper","A1","n.","biber; karabiber","Add salt and pepper to the soup."],
["perfect","A1","adj.","mükemmel, kusursuz","The weather is perfect for a picnic."],
["period","A1","n.","dönem, süre","We lived there for a short period."],
["person","A1","n.","kişi, insan","She is a very kind person."],
["personal","A1","adj.","kişisel","This is a personal question."],
["phone","A1","n., v.","telefon; telefon etmek","My phone is in my bag."],
["photo","A1","n.","fotoğraf","I took a photo of the sunset."],
["photograph","A1","n., v.","fotoğraf (çekmek)","This is an old photograph of my family."],
["phrase","A1","n.","ifade, söz öbeği","Learn these useful phrases."],
["piano","A1","n.","piyano","She plays the piano beautifully."],
["piece","A1","n.","parça, dilim","Would you like a piece of cake?"],
["pig","A1","n.","domuz","The pig lives on the farm."],
["pink","A1","adj., n.","pembe","The baby's room is pink."],
["place","A1","n., v.","yer; koymak","This is a nice place for lunch."],
["plan","A1","n., v.","plan; planlamak","What are your plans for the weekend?"],
["plane","A1","n.","uçak","The plane leaves at seven."],
["plant","A1","n., v.","bitki; dikmek","Water the plants every day."],
["play","A1","n., v.","oynamak; çalmak; oyun","The kids play in the garden."],
["player","A1","n.","oyuncu","He is the best player on the team."],
["please","A1","excl., v.","lütfen","A glass of water, please."],
["point","A1","n., v.","nokta; puan; işaret etmek","You get one point for each answer."],
["police","A1","n.","polis","Call the police!"],
["policeman","A1","n.","polis memuru (erkek)","The policeman stopped the car."],
["pool","A1","n.","havuz","The hotel has a swimming pool."],
["poor","A1","adj.","yoksul, fakir; zavallı","The poor cat is hungry."],
["popular","A1","adj.","popüler, sevilen","Football is popular everywhere."],
["possible","A1","adj.","mümkün, olası","Is it possible to change my ticket?"],
["post","A1","n., v.","posta; göndermek; paylaşmak","I posted the letter yesterday."],
["potato","A1","n.","patates","We had potatoes with the chicken."],
["pound","A1","n.","sterlin; libre","The book costs five pounds."],
["practice","A1","n.","pratik, alıştırma","You need more practice."],
["practise","A1","v.","pratik yapmak, alıştırma yapmak","Practise English every day."],
["prefer","A1","v.","tercih etmek","I prefer tea to coffee."],
["prepare","A1","v.","hazırlamak, hazırlanmak","Mum is preparing dinner."],
["present","A1","adj., n., v.","hediye; şimdiki; sunmak","I got a nice present for my birthday."],
["pretty","A1","adj., adv.","güzel, hoş; oldukça","What a pretty dress!"],
["probably","A1","adv.","muhtemelen, büyük olasılıkla","It will probably rain tomorrow."],
["problem","A1","n.","sorun, problem","No problem, I can help."],
["product","A1","n.","ürün","This shop sells local products."],
["programme","A1","n.","program","My favourite programme starts at eight."],
["purple","A1","adj., n.","mor","She wore a purple scarf."],
["put","A1","v.","koymak","Put the milk in the fridge."],
["quarter","A1","n.","çeyrek","It's a quarter past two."],
["question","A1","n., v.","soru","Can I ask a question?"],
["quick","A1","adj.","hızlı, çabuk","Let's have a quick lunch."],
["quickly","A1","adv.","hızla, çabucak","He finished his homework quickly."],
["quiet","A1","adj.","sessiz, sakin","Please be quiet in the library."],
["quite","A1","adv.","oldukça","The test was quite easy."],
["radio","A1","n.","radyo","I listen to the radio in the car."],
["rain","A1","n., v.","yağmur; yağmak","It rains a lot in spring."],
["read","A1","v.","okumak","I read before bed every night."],
["reader","A1","n.","okur, okuyucu","She is a fast reader."],
["reading","A1","n.","okuma","Reading is good for you."],
["ready","A1","adj.","hazır","Are you ready to go?"],
["real","A1","adj.","gerçek","Is that a real flower?"],
["really","A1","adv.","gerçekten","I really like this song."],
["reason","A1","n.","sebep, neden","What's the reason for the delay?"],
["red","A1","adj., n.","kırmızı","She has a red bike."],
["relax","A1","v.","rahatlamak, dinlenmek","I relax with music after work."],
["remember","A1","v.","hatırlamak","Do you remember my name?"],
["repeat","A1","n., v.","tekrarlamak","Can you repeat that, please?"],
["report","A1","n., v.","rapor (etmek)","Write a short report about your trip."],
["restaurant","A1","n.","restoran, lokanta","We had dinner at a nice restaurant."],
["result","A1","n., v.","sonuç","The exam results come on Friday."],
["return","A1","n., v.","dönmek; iade etmek","We return home at six."],
["rice","A1","n.","pirinç, pilav","We eat rice with the meat."],
["rich","A1","adj.","zengin","The rich man gave money to the school."],
["ride","A1","n., v.","binmek (bisiklet/at); sürüş","I ride my bike to school."],
["right","A1","adj., adv., n.","sağ; doğru; hak","Turn right at the corner."],
["river","A1","n.","nehir, ırmak","The river is deep here."],
["road","A1","n.","yol, cadde","The road to the village is narrow."],
["room","A1","n.","oda; yer","My room is upstairs."],
["rule","A1","n., v.","kural","Follow the rules of the game."],
["run","A1","n., v.","koşmak","I run in the park every morning."],
["sad","A1","adj.","üzgün","She is sad because her cat is ill."],
["salad","A1","n.","salata","I had a salad for lunch."],
["salt","A1","n.","tuz","Pass the salt, please."],
["same","A1","adj., adv., pron.","aynı","We go to the same school."],
["sandwich","A1","n.","sandviç","I made a cheese sandwich."],
["saturday","A1","n.","cumartesi","We play football on Saturdays."],
["school","A1","n.","okul","School starts at half past eight."],
["science","A1","n.","fen, bilim","We do experiments in science class."],
["scientist","A1","n.","bilim insanı","The scientist works in a laboratory."],
["sea","A1","n.","deniz","We swim in the sea in summer."],
["second","A1","adv., det., n., num.","ikinci; saniye","February is the second month."],
["section","A1","n.","bölüm, kısım","Read the first section of the text."],
["see","A1","v.","görmek","I can see the sea from my window."],
["sell","A1","v.","satmak","They sell fruit at the market."],
["send","A1","v.","göndermek","Send me a photo of your dog."],
["september","A1","n.","eylül","School starts in September."],
["seven","A1","num.","yedi","A week has seven days."],
["seventeen","A1","num.","on yedi","My brother is seventeen."],
["seventy","A1","num.","yetmiş","My grandmother is seventy years old."],
["share","A1","n., v.","paylaşmak; pay","We share a room, my brother and I."],
["she","A1","pron.","o (kadın)","She is my teacher."],
["sheep","A1","n.","koyun","The sheep are on the hill."],
["shirt","A1","n.","gömlek","He wears a white shirt to work."],
["shoe","A1","n.","ayakkabı","These shoes are too small."],
["shop","A1","n., v.","dükkân, mağaza; alışveriş yapmak","The shop closes at eight."],
["shopping","A1","n.","alışveriş","We go shopping on Saturdays."],
["short","A1","adj.","kısa","It's a short walk to the station."],
["should","A1","modal v.","-meli (öneri)","You should drink more water."],
["show","A1","n., v.","göstermek; gösteri","Show me your photos."],
["shower","A1","n.","duş","I take a shower every morning."],
["sick","A1","adj.","hasta","He is sick and stayed at home."],
["similar","A1","adj.","benzer","Our bags are similar."],
["sing","A1","v.","şarkı söylemek","She sings in the school choir."],
["singer","A1","n.","şarkıcı","The singer has a beautiful voice."],
["sister","A1","n.","kız kardeş, abla","My sister is ten years old."],
["sit","A1","v.","oturmak","Sit next to me."],
["situation","A1","n.","durum","The situation is getting better."],
["six","A1","num.","altı","We have six lessons today."],
["sixteen","A1","num.","on altı","She is sixteen years old."],
["sixty","A1","num.","altmış","An hour has sixty minutes."],
["skill","A1","n.","beceri, yetenek","Reading is an important skill."],
["skirt","A1","n.","etek","She wore a long skirt."],
["sleep","A1","n., v.","uyumak; uyku","I sleep eight hours every night."],
["slow","A1","adj., v.","yavaş","The bus is slow in the morning."],
["small","A1","adj.","küçük","They live in a small house."],
["snake","A1","n.","yılan","There is a snake in the grass!"],
["snow","A1","n., v.","kar; kar yağmak","The children played in the snow."],
["so","A1","adv., conj.","bu yüzden; çok","I was tired, so I went to bed."],
["some","A1","det., pron.","biraz, bazı","Would you like some tea?"],
["somebody","A1","pron.","birisi","Somebody left the door open."],
["someone","A1","pron.","birisi","Someone is knocking at the door."],
["something","A1","pron.","bir şey","I want to tell you something."],
["sometimes","A1","adv.","bazen","Sometimes we eat out."],
["son","A1","n.","oğul","Their son is a doctor."],
["song","A1","n.","şarkı","This is my favourite song."],
["soon","A1","adv.","yakında, birazdan","The bus will come soon."],
["sorry","A1","adj., excl.","üzgün; özür dilerim","Sorry, I'm late."],
["soup","A1","n.","çorba","Hot soup is good in winter."],
["south","A1","adj., adv., n.","güney","The beach is in the south."],
["space","A1","n.","uzay; boşluk, yer","The rocket went into space."],
["speak","A1","v.","konuşmak","Do you speak English?"],
["special","A1","adj.","özel","Today is a special day."],
["spelling","A1","n.","yazım, imla","Check the spelling of this word."],
["spend","A1","v.","harcamak; (zaman) geçirmek","We spent two weeks at the sea."],
["sport","A1","n.","spor","Tennis is my favourite sport."],
["star","A1","n., v.","yıldız","The stars are bright tonight."],
["start","A1","n., v.","başlamak; başlangıç","The film starts at nine."],
["statement","A1","n.","ifade, açıklama","Read the statements and say true or false."],
["station","A1","n.","istasyon, gar","The train station is near the hotel."],
["stay","A1","n., v.","kalmak","We stayed at home all day."],
["still","A1","adj., adv.","hâlâ; yine de; durgun","Are you still at work?"],
["stop","A1","n., v.","durmak; durak","The bus stops here."],
["story","A1","n.","hikâye, öykü","Grandma tells us stories at night."],
["street","A1","n.","sokak, cadde","Our street is very quiet."],
["strong","A1","adj.","güçlü, kuvvetli","He is strong; he can carry the box."],
["student","A1","n.","öğrenci","The students are in the classroom."],
["study","A1","n., v.","ders çalışmak; okumak (bölüm)","I study English every evening."],
["style","A1","n.","tarz, stil","I like your style!"],
["success","A1","n.","başarı","The party was a big success."],
["sugar","A1","n.","şeker","Do you take sugar in your tea?"],
["summer","A1","n.","yaz","We go to the beach in summer."],
["sun","A1","n.","güneş","The sun is shining today."],
["sunday","A1","n.","pazar (gün)","We visit grandma on Sundays."],
["supermarket","A1","n.","süpermarket","I bought milk from the supermarket."],
["sure","A1","adj., adv.","emin; elbette","Are you sure about that?"],
["sweater","A1","n.","kazak","Wear a sweater; it's cold."],
["swim","A1","n., v.","yüzmek","Can you swim?"],
["swimming","A1","n.","yüzme","Swimming is great exercise."],
["t-shirt","A1","n.","tişört","He wore jeans and a T-shirt."],
["table","A1","n.","masa; tablo","The dinner is on the table."],
["take","A1","v.","almak; götürmek; (süre) sürmek","Take an umbrella with you."],
["talk","A1","n., v.","konuşmak; konuşma","We talked about the holiday."],
["tall","A1","adj.","uzun boylu; yüksek","My father is very tall."],
["taxi","A1","n.","taksi","We took a taxi to the airport."],
["tea","A1","n.","çay","Would you like some tea?"],
["teach","A1","v.","öğretmek","She teaches maths at our school."],
["teacher","A1","n.","öğretmen","Our teacher is very kind."],
["team","A1","n.","takım, ekip","Our team won the match."],
["teenager","A1","n.","genç (13-19 yaş)","Teenagers love music and games."],
["telephone","A1","n., v.","telefon (etmek)","The telephone is ringing."],
["television","A1","n.","televizyon","We watch television after dinner."],
["tell","A1","v.","söylemek, anlatmak","Tell me about your day."],
["ten","A1","num.","on","The shop opens at ten."],
["tennis","A1","n.","tenis","We play tennis on Sundays."],
["terrible","A1","adj.","berbat, korkunç","The weather was terrible yesterday."],
["test","A1","n., v.","test, sınav; denemek","We have a maths test today."],
["text","A1","n., v.","metin; mesaj atmak","Read the text and answer the questions."],
["than","A1","conj., prep.","-den (karşılaştırma)","My brother is taller than me."],
["thank","A1","v.","teşekkür etmek","Thank you for your help."],
["thanks","A1","excl., n.","teşekkürler","Thanks for the present!"],
["that","A1","adv., conj., det., pron.","şu, o; ki","That book is mine."],
["the","A1","art.","(belirli tanımlık)","The sun is hot today."],
["theatre","A1","n.","tiyatro","We saw a play at the theatre."],
["their","A1","det.","onların","Their house is big."],
["them","A1","pron.","onları, onlara","I saw them at the park."],
["then","A1","adv.","sonra; o zaman","We had dinner, then watched TV."],
["there","A1","adv.","orada; (there is/are) var","There is a cat in the garden."],
["they","A1","pron.","onlar","They are my friends."],
["thing","A1","n.","şey","What is that thing on the table?"],
["think","A1","v.","düşünmek; sanmak","I think it will rain."],
["third","A1","n., num.","üçüncü","March is the third month."],
["thirsty","A1","adj.","susamış","I'm thirsty; I need water."],
["thirteen","A1","num.","on üç","She is thirteen years old."],
["thirty","A1","num.","otuz","The class has thirty students."],
["this","A1","adv., det., pron.","bu","This is my brother."],
["thousand","A1","num.","bin","The car costs ten thousand dollars."],
["three","A1","num.","üç","I have three sisters."],
["through","A1","adv., prep.","içinden, boyunca","The train goes through a tunnel."],
["thursday","A1","n.","perşembe","We have art class on Thursday."],
["ticket","A1","n.","bilet","Two tickets for the film, please."],
["tired","A1","adj.","yorgun","I'm tired after the long walk."],
["to","A1","prep.","-e/-a; için","We go to school by bus."],
["today","A1","adv., n.","bugün","Today is my birthday."],
["together","A1","adv.","birlikte, beraber","We study together after school."],
["toilet","A1","n.","tuvalet","Where is the toilet, please?"],
["tomato","A1","n.","domates","The salad has tomatoes and onions."],
["tomorrow","A1","adv., n.","yarın","See you tomorrow!"],
["tonight","A1","adv., n.","bu gece, bu akşam","We're watching a film tonight."],
["too","A1","adv.","de/da; çok fazla","I like ice cream too."],
["tooth","A1","n.","diş","Brush your teeth twice a day."],
["topic","A1","n.","konu","Today's topic is animals."],
["tourist","A1","n.","turist","Many tourists visit Istanbul."],
["town","A1","n.","kasaba, şehir","We live in a small town."],
["traffic","A1","n.","trafik","The traffic is bad in the morning."],
["train","A1","n., v.","tren; antrenman yapmak","The train to Ankara leaves at nine."],
["travel","A1","n., v.","seyahat (etmek)","I love to travel."],
["tree","A1","n.","ağaç","The birds sing in the trees."],
["trousers","A1","n.","pantolon","These trousers are too long."],
["true","A1","adj.","doğru, gerçek","Is the story true?"],
["tuesday","A1","n.","salı","I have music class on Tuesday."],
["turn","A1","n., v.","dönmek; sıra","Turn left at the school."],
["tv","A1","n.","televizyon","What's on TV tonight?"],
["twelve","A1","num.","on iki","A year has twelve months."],
["twenty","A1","num.","yirmi","The book has twenty pages."],
["twice","A1","adv.","iki kez","I clean my room twice a week."],
["two","A1","num.","iki","I have two cats."],
["type","A1","n., v.","tür, tip; yazmak (klavyede)","What type of music do you like?"],
["umbrella","A1","n.","şemsiye","Take an umbrella; it's raining."],
["uncle","A1","n.","amca, dayı","My uncle lives on a farm."],
["under","A1","adv., prep.","altında","The cat is under the table."],
["understand","A1","v.","anlamak","I don't understand this question."],
["university","A1","n.","üniversite","She studies at a university in Izmir."],
["until","A1","conj., prep.","-e kadar","Wait here until I come back."],
["up","A1","adv., prep.","yukarı; kalkmış","Stand up, please."],
["upstairs","A1","adj., adv.","üst kat(ta)","My bedroom is upstairs."],
["us","A1","pron.","bizi, bize","Come with us!"],
["use","A1","n., v.","kullanmak; kullanım","Can I use your phone?"],
["useful","A1","adj.","yararlı, kullanışlı","This app is very useful."],
["usually","A1","adv.","genellikle","I usually walk to school."],
["vacation","A1","n.","tatil","We are on vacation in August."],
["vegetable","A1","n.","sebze","Eat your vegetables!"],
["video","A1","n.","video","We watched a funny video."],
["village","A1","n.","köy","My grandparents live in a village."],
["visit","A1","n., v.","ziyaret (etmek)","We visited the museum on Sunday."],
["visitor","A1","n.","ziyaretçi","The museum has many visitors."],
["wait","A1","n., v.","beklemek","Wait for me at the bus stop."],
["waiter","A1","n.","garson","The waiter brought the menu."],
["wake","A1","v.","uyanmak; uyandırmak","I wake up at seven."],
["walk","A1","n., v.","yürümek; yürüyüş","We walk to school every day."],
["wall","A1","n.","duvar","There is a clock on the wall."],
["want","A1","v.","istemek","I want a glass of water."],
["warm","A1","adj., v.","ılık, sıcak","The water is warm."],
["wash","A1","n., v.","yıkamak","Wash your hands before dinner."],
["watch","A1","n., v.","izlemek; kol saati","We watch TV in the evening."],
["water","A1","n., v.","su; sulamak","Drink a lot of water."],
["we","A1","pron.","biz","We are students."],
["wear","A1","v.","giymek","I wear a uniform at school."],
["weather","A1","n.","hava (durumu)","The weather is nice today."],
["website","A1","n.","internet sitesi","The school has a new website."],
["wednesday","A1","n.","çarşamba","We have sport on Wednesday."],
["week","A1","n.","hafta","See you next week."],
["weekend","A1","n.","hafta sonu","What do you do at the weekend?"],
["welcome","A1","adj., excl., n., v.","hoş geldiniz; karşılamak","Welcome to our home!"],
["west","A1","adj., adv., n.","batı","The sun sets in the west."],
["what","A1","det., pron.","ne","What is your name?"],
["when","A1","adv., conj., pron.","ne zaman; -dığında","When is your birthday?"],
["where","A1","adv., conj.","nerede, nereye","Where do you live?"],
["which","A1","det., pron.","hangi","Which colour do you like?"],
["white","A1","adj., n.","beyaz","The walls are white."],
["who","A1","pron.","kim","Who is that man?"],
["why","A1","adv.","neden, niçin","Why are you late?"],
["wife","A1","n.","karı, eş","His wife is a doctor."],
["will","A1","n., modal v.","-ecek/-acak","I will call you tomorrow."],
["win","A1","n., v.","kazanmak","Our team will win the match."],
["window","A1","n.","pencere","Open the window, please."],
["wine","A1","n.","şarap","A glass of red wine, please."],
["winter","A1","n.","kış","It snows in winter."],
["with","A1","prep.","ile, birlikte","I live with my family."],
["without","A1","prep.","-sız/-siz, olmadan","I can't read without my glasses."],
["woman","A1","n.","kadın","The woman in the red coat is my aunt."],
["wonderful","A1","adj.","harika, şahane","We had a wonderful day!"],
["word","A1","n.","kelime, sözcük","Learn five new words every day."],
["work","A1","n., v.","çalışmak; iş","My mother works in a hospital."],
["worker","A1","n.","işçi, çalışan","The workers start at eight."],
["world","A1","n.","dünya","The world is full of beautiful places."],
["would","A1","modal v.","-erdi; (kibar istek)","Would you like some tea?"],
["write","A1","v.","yazmak","Write your name here."],
["writer","A1","n.","yazar","The writer has a new book."],
["writing","A1","n.","yazma, yazı","Her writing is very neat."],
["yeah","A1","excl.","evet (gündelik)","Yeah, that's right."],
["year","A1","n.","yıl, sene","A year has twelve months."],
["yellow","A1","adj., n.","sarı","The sunflower is yellow."],
["yes","A1","excl.","evet","Yes, please."],
["yesterday","A1","adv., n.","dün","I was at home yesterday."],
["you","A1","pron.","sen, siz","You are my friend."],
["young","A1","adj., n.","genç","The young man helped me."],
["your","A1","det.","senin, sizin","What is your name?"],
["yourself","A1","pron.","kendin","Tell me about yourself."]
];
