// Oxford 5000 B2-C1 vocab: Q-R-S. Format: [w, lv, pos, tr, ex]
module.exports = [
["query","C1","n.","sorgu, soru","Send any queries to the support team."],
["quest","C1","n.","arayış, macera","The book follows a knight's quest for a lost crown."],
["questionnaire","B2","n.","anket (formu)","Guests fill in a short questionnaire at checkout."],
["quota","C1","n.","kota","The boat had already caught its weekly quota of fish."],
["racial","B2","adj.","ırksal, ırkla ilgili","The city has a long history of racial diversity."],
["racism","B2","n.","ırkçılık","The club banned fans found guilty of racism."],
["racist","B2","adj., n.","ırkçı","Racist comments were removed from the forum."],
["radar","C1","n.","radar","The storm appeared suddenly on the radar."],
["radiation","B2","n.","radyasyon, ışınım","The suit protects workers from radiation."],
["radical","C1","adj.","köklü, radikal","The plan needs radical changes before approval."],
["rage","C1","n.","öfke, hiddet","He slammed the door in a fit of rage."],
["raid","C1","n., v.","baskın; baskın yapmak","Police raided the warehouse at dawn."],
["rail","B2","n.","ray; demiryolu; korkuluk","The goods travel by rail to the coast."],
["rally","C1","n., v.","miting; ralli; toparlanmak","Thousands attended a rally for peace."],
["random","B2","adj.","rastgele","The winners are chosen at random."],
["range","B2","v.","(arasında) değişmek; uzanmak","Prices range from ten to fifty pounds."],
["rank","B2","n., v.","rütbe, sıra; sıralamak","She rose to the rank of captain."],
["ranking","C1","n.","sıralama","The university improved its world ranking."],
["rape","C1","n., v.","tecavüz; tecavüz etmek","He was convicted of rape and imprisoned."],
["rapid","B2","adj.","hızlı, süratli","The patient made a rapid recovery."],
["rapidly","B2","adv.","hızla","The fire spread rapidly through the dry forest."],
["rat","B2","n.","sıçan","Rats had gnawed through the cables."],
["rate","B2","v.","değerlendirmek, derecelendirmek","Viewers rated the show nine out of ten."],
["rating","B2","n.","derecelendirme, puan","The hotel has a five-star rating."],
["ratio","C1","n.","oran","The school has a low student-teacher ratio."],
["rational","C1","adj.","akılcı, mantıklı","There must be a rational explanation for the noise."],
["raw","B2","adj.","çiğ; işlenmemiş, ham","The dish is made with raw fish."],
["ray","C1","n.","ışın","A ray of sunlight broke through the clouds."],
["reach","B2","n.","erişim, ulaşma mesafesi","Keep medicines out of the reach of children."],
["readily","C1","adv.","kolayca; gönüllüce","The information is readily available online."],
["realistic","B2","adj.","gerçekçi","Set yourself realistic goals for the year."],
["realization","C1","n.","farkına varma; gerçekleştirme","The realization that he was lost came slowly."],
["realm","C1","n.","alan, diyar","Such speeds remain in the realm of fantasy."],
["rear","C1","adj., n.","arka","The engine sits at the rear of the car."],
["reasonable","B2","adj.","makul, mantıklı","The shop sells good shoes at reasonable prices."],
["reasonably","B2","adv.","makul ölçüde; oldukça","The team played reasonably well in the first half."],
["reasoning","C1","n.","akıl yürütme, muhakeme","Explain the reasoning behind your decision."],
["reassure","C1","v.","içini rahatlatmak, güven vermek","The pilot reassured passengers about the noise."],
["rebel","C1","n.","asi, isyancı","The rebels controlled the mountain passes."],
["rebellion","C1","n.","isyan, ayaklanma","The rebellion was crushed within a month."],
["rebuild","B2","v.","yeniden inşa etmek","The town was rebuilt after the earthquake."],
["recall","B2","v.","hatırlamak; geri çağırmak","I don't recall meeting her before."],
["receiver","B2","n.","alıcı; ahize","He picked up the receiver and dialled."],
["recession","B2","n.","durgunluk, resesyon","Many shops closed during the recession."],
["recipient","C1","n.","alıcı (kişi)","She was the youngest recipient of the prize."],
["reckon","B2","v.","sanmak, tahmin etmek; hesaplamak","I reckon it'll rain before evening."],
["recognition","B2","n.","tanıma; takdir","Her work finally received international recognition."],
["reconstruction","C1","n.","yeniden inşa; canlandırma","The programme showed a reconstruction of the crime."],
["recount","C1","v.","anlatmak, nakletmek","He recounted his adventures in the desert."],
["recover","B2","v.","iyileşmek; geri kazanmak","She is recovering well after the operation."],
["recovery","B2","n.","iyileşme; geri kazanım","Doctors expect a full recovery."],
["recruit","B2","n., v.","acemi (asker), yeni eleman; işe almak","The army recruits thousands of young people yearly."],
["recruitment","B2","n.","işe alım","The hospital launched a nurse recruitment drive."],
["reduction","B2","n.","azaltma, indirim","Members get a reduction on all tickets."],
["referee","B2","n.","hakem","The referee showed him a yellow card."],
["referendum","C1","n.","referandum, halk oylaması","The change was approved in a national referendum."],
["reflection","C1","n.","yansıma; derin düşünme","She studied her reflection in the shop window."],
["reform","C1","n., v.","reform; ıslah etmek","The new law reforms the tax system."],
["refuge","C1","n.","sığınak, barınak","The walkers took refuge from the storm in a barn."],
["refugee","B2","n.","mülteci, sığınmacı","The camp shelters thousands of refugees."],
["refusal","C1","n.","ret, kabul etmeme","His refusal to apologise made things worse."],
["regain","C1","v.","yeniden kazanmak","She slowly regained her strength."],
["regard","B2","n., v.","saygı; bakımdan; olarak görmek","I regard her as my closest friend."],
["regardless","C1","adv.","ne olursa olsun, aldırmadan","They continued the match regardless of the rain."],
["regime","C1","n.","rejim; düzen","The old regime collapsed almost overnight."],
["regional","B2","adj.","bölgesel","The regional dialect is hard for outsiders."],
["register","B2","n., v.","kayıt; kaydolmak, kaydetmek","Students must register for exams by Friday."],
["registration","B2","n.","kayıt (işlemi)","Registration opens at nine o'clock."],
["regret","B2","n., v.","pişmanlık; pişman olmak","He regrets selling his grandfather's watch."],
["regulate","B2","v.","düzenlemek, denetlemek","The valve regulates the flow of water."],
["regulation","B2","n.","yönetmelik, düzenleme","New regulations limit noise after midnight."],
["regulator","C1","n.","düzenleyici (kurum)","The energy regulator capped household prices."],
["regulatory","C1","adj.","düzenleyici (mevzuata ilişkin)","The drug awaits regulatory approval."],
["rehabilitation","C1","n.","rehabilitasyon, iyileştirme","The centre offers rehabilitation after injury."],
["reign","C1","n., v.","saltanat, hükümdarlık (dönemi); hüküm sürmek","The castle was built during her reign."],
["reinforce","B2","v.","güçlendirmek, pekiştirmek","Steel bars reinforce the concrete walls."],
["rejection","C1","n.","ret, reddedilme","She kept every rejection letter from publishers."],
["relatively","B2","adv.","nispeten, görece","The test is relatively easy to pass."],
["relevance","C1","n.","ilgililik, geçerlilik","The old map has little relevance today."],
["relevant","B2","adj.","ilgili, konuyla alakalı","Include only the relevant details in your report."],
["reliability","C1","n.","güvenilirlik","The engine is famous for its reliability."],
["relief","B2","n.","rahatlama; yardım (afet)","It was a relief to hear they were safe."],
["relieve","B2","v.","hafifletmek, rahatlatmak","A warm bath relieves tired muscles."],
["relieved","B2","adj.","rahatlamış","She felt relieved when the results came back clear."],
["reluctant","C1","adj.","isteksiz, gönülsüz","He was reluctant to lend his new bike."],
["rely","B2","v.","güvenmek, bel bağlamak","The village relies on tourism for income."],
["remainder","C1","n.","geri kalan, bakiye","She spent the remainder of the day reading."],
["remains","C1","n.","kalıntılar","The remains of a Roman villa were found here."],
["remark","B2","n., v.","söz, yorum; belirtmek","He made a kind remark about her cooking."],
["remarkable","B2","adj.","dikkate değer, olağanüstü","The child shows remarkable musical talent."],
["remarkably","B2","adv.","şaşılacak derecede","The weather stayed remarkably mild all winter."],
["remedy","C1","n.","çare, deva","Honey and lemon is an old remedy for coughs."],
["reminder","C1","n.","hatırlatma, hatırlatıcı","The app sends a reminder before each meeting."],
["removal","C1","n.","kaldırma, çıkarma; taşınma","The removal of the old bridge took a week."],
["render","C1","v.","hâline getirmek; sunmak","The flood rendered the road impassable."],
["renew","C1","v.","yenilemek, uzatmak","Remember to renew your passport in time."],
["renowned","C1","adj.","ünlü, tanınmış","The region is renowned for its olive oil."],
["rental","C1","n.","kiralama (ücreti)","Car rental is cheaper if booked early."],
["replacement","C1","n.","yedek; yerine geçen kişi/şey","The shop sent a replacement for the broken cup."],
["reportedly","C1","adv.","iddiaya göre, bildirildiğine göre","The singer is reportedly working on a new album."],
["reporting","B2","n.","habercilik, raporlama","The paper won awards for its war reporting."],
["representation","C1","n.","temsil; gösterim","Workers demanded representation on the board."],
["representative","B2","adj., n.","temsilci; temsili","A sales representative will call you back."],
["reproduce","C1","v.","çoğalmak; kopyalamak","The virus reproduces inside living cells."],
["reproduction","C1","n.","üreme; reprodüksiyon","The painting is a reproduction, not an original."],
["republic","C1","n.","cumhuriyet","The country became a republic in 1923."],
["reputation","B2","n.","itibar, ün","The restaurant has a reputation for slow service."],
["requirement","B2","n.","gereklilik, şart","A degree is a requirement for this post."],
["rescue","B2","n., v.","kurtarma; kurtarmak","Helicopters rescued the sailors from the rocks."],
["resemble","C1","v.","benzemek","The fruit resembles a small orange."],
["reserve","B2","n., v.","rezerv; yedek; ayırtmak","We reserved a table for eight o'clock."],
["reside","C1","v.","ikamet etmek","The family resides in the capital."],
["residence","C1","n.","konut, ikametgâh","The palace is the president's official residence."],
["resident","B2","adj., n.","sakin, oturan","Residents complained about the construction noise."],
["residential","C1","adj.","konutlara ait, yerleşim-","The factory is too close to a residential area."],
["residue","C1","n.","kalıntı, tortu","Rinse the cloth to remove any soap residue."],
["resign","B2","v.","istifa etmek","The coach resigned after the defeat."],
["resignation","C1","n.","istifa; boyun eğme","The minister announced her resignation."],
["resist","B2","v.","direnmek, karşı koymak","I couldn't resist a second slice of cake."],
["resistance","C1","n.","direniş, direnç","The plan met fierce resistance from staff."],
["resolution","B2","n.","karar; çözüm; çözünürlük","She made a resolution to exercise daily."],
["resolve","B2","v.","çözmek; karar vermek","The dispute was resolved without a strike."],
["resort","B2","n.","tatil beldesi; (son) çare","They spent a week at a seaside resort."],
["respective","C1","adj.","kendi, sırasıyla ait","After dinner we returned to our respective rooms."],
["respectively","C1","adv.","sırasıyla","The brothers are six and nine, respectively."],
["restoration","C1","n.","restorasyon; geri getirme","The church reopened after years of restoration."],
["restore","B2","v.","onarmak; geri getirmek","Power was restored within a few hours."],
["restraint","C1","n.","kısıtlama; özdenetim","He showed great restraint despite the insults."],
["restrict","B2","v.","kısıtlamak, sınırlamak","The new rules restrict parking in the centre."],
["restriction","B2","n.","kısıtlama","Speed restrictions apply near schools."],
["resume","C1","v.","yeniden başlamak, kaldığı yerden sürdürmek","Talks will resume after the holidays."],
["retail","B2","n.","perakende (satış)","She has worked in retail for ten years."],
["retain","B2","v.","korumak, elde tutmak","The town retains much of its old charm."],
["retirement","B2","n.","emeklilik","He took up painting after retirement."],
["retreat","C1","n., v.","geri çekilme; inziva; geri çekilmek","The army retreated across the river."],
["retrieve","C1","v.","geri almak, kurtarmak; (bilgi) çekmek","The dog retrieved the ball from the lake."],
["reveal","B2","v.","açığa çıkarmak, ifşa etmek","The survey revealed a surprising trend."],
["revelation","C1","n.","ifşa; beklenmedik gerçek","The diary's revelations shocked the family."],
["revenge","C1","n.","intikam, öç","He swore revenge on those who betrayed him."],
["revenue","B2","n.","gelir, hasılat","Advertising provides most of the site's revenue."],
["reverse","C1","adj., n., v.","ters; tersine çevirmek; geri gitmek","The court reversed its earlier decision."],
["revision","B2","n.","gözden geçirme; (sınav) tekrar","The plan needs one final revision."],
["revival","C1","n.","canlanma, yeniden doğuş","The craft is enjoying an unexpected revival."],
["revive","C1","v.","canlandırmak; ayıltmak","A cup of coffee revived me after the long drive."],
["revolution","B2","n.","devrim","The revolution toppled the monarchy."],
["revolutionary","C1","adj.","devrimci; çığır açan","The printing press was a revolutionary invention."],
["reward","B2","n., v.","ödül; ödüllendirmek","A reward was offered for the missing dog."],
["rhetoric","C1","n.","retorik, söz sanatı; boş laf","His speech was all rhetoric and no substance."],
["rhythm","B2","n.","ritim","The drummer kept a steady rhythm."],
["rid","B2","v.","kurtarmak, arındırmak (get rid of)","We finally got rid of the old sofa."],
["ridiculous","B2","adj.","gülünç, saçma","It's ridiculous to pay so much for water."],
["rifle","C1","n.","tüfek","The soldiers cleaned their rifles in silence."],
["riot","C1","n.","ayaklanma, kargaşa","Prices sparked riots in several cities."],
["rip","C1","v.","yırtmak","He ripped the letter in half."],
["risky","B2","adj.","riskli","Lending money to friends can be risky."],
["ritual","C1","n.","ritüel, ayin","Morning coffee is a daily ritual for many."],
["rival","B2","adj., n.","rakip","The two rival teams share a stadium."],
["rob","B2","v.","soymak, gasp etmek","Two men robbed the bank in broad daylight."],
["robbery","B2","n.","soygun","The robbery took less than three minutes."],
["robust","C1","adj.","sağlam, gürbüz, dayanıklı","The bridge has a robust steel frame."],
["rock","C1","v.","sallamak, sarsmak","The scandal rocked the entire industry."],
["rocket","B2","n.","roket","The rocket carried two satellites into orbit."],
["rod","C1","n.","çubuk; olta kamışı","He spent the morning fishing with his new rod."],
["romance","B2","n.","romantizm, aşk ilişkisi; aşk romanı","Their romance began on a train to Vienna."],
["root","B2","n.","kök; köken","The problem has its roots in poor planning."],
["rose","B2","n.","gül","He brought her a single red rose."],
["rotate","C1","v.","dönmek; dönüşümlü çalışmak","The blades rotate at high speed."],
["rotation","C1","n.","dönme; rotasyon","The earth completes one rotation every day."],
["roughly","B2","adv.","kabaca, yaklaşık","The journey takes roughly two hours."],
["round","B2","n.","tur, raunt; devriye","She was knocked out in the second round."],
["routine","B2","adj.","rutin, olağan","The fault was found during a routine check."],
["rub","B2","v.","ovmak, sürtmek","He rubbed his hands to warm them."],
["rubber","B2","adj., n.","kauçuk, lastik; silgi","Wear rubber gloves when using bleach."],
["ruin","B2","n., v.","yıkıntı; mahvetmek","Rain ruined our plans for the picnic."],
["ruling","C1","n.","hüküm, karar (mahkeme)","The court's ruling surprised legal experts."],
["rumour","C1","n.","söylenti, dedikodu","Rumours of a merger pushed the shares up."],
["rural","B2","adj.","kırsal","Rural schools often struggle to find teachers."],
["rush","B2","n., v.","acele; koşuşturma; acele etmek","There's no rush; take your time."],
["sack","C1","v.","işten atmak, kovmak","He was sacked for repeatedly arriving late."],
["sacred","C1","adj.","kutsal","The spring is sacred to the local people."],
["sacrifice","C1","n., v.","fedakârlık, kurban; feda etmek","She sacrificed her weekends to finish the project."],
["saint","C1","n.","aziz, ermiş","The church is named after a local saint."],
["sake","C1","n.","hatır, uğur (for the sake of)","They stayed together for the sake of the children."],
["sample","B2","v.","tatmak, denemek; örneklem almak","Visitors can sample the local cheeses for free."],
["sanction","C1","n.","yaptırım; onay","The council imposed sanctions on the company."],
["satellite","B2","n.","uydu","The satellite sends back images of the storm."],
["satisfaction","B2","n.","memnuniyet, tatmin","She looked at the finished wall with satisfaction."],
["satisfied","B2","adj.","memnun, tatmin olmuş","The inspector was satisfied with the repairs."],
["satisfy","B2","v.","tatmin etmek; (şartı) karşılamak","The answer did not satisfy the examiner."],
["saving","B2","n.","tasarruf, birikim","Buying in bulk means a real saving."],
["say","C1","n.","söz hakkı","Workers want more say in how the firm is run."],
["scale","B2","n.","ölçek; terazi; pul (balık)","The scale of the damage became clear at dawn."],
["scandal","B2","n.","skandal","The scandal forced two ministers to resign."],
["scare","B2","n., v.","korku, panik; korkutmak","The sudden noise scared the horses."],
["scattered","C1","adj.","dağınık, saçılmış","Scattered showers are expected in the west."],
["scenario","B2","n.","senaryo, olasılık","In the worst scenario, the river floods the town."],
["sceptical","C1","adj.","şüpheci, kuşkulu","Experts remain sceptical about the claims."],
["schedule","B2","v.","planlamak, programa koymak","The meeting is scheduled for Monday morning."],
["scheme","B2","n.","plan, program; düzen (entrika)","The city runs a bicycle-sharing scheme."],
["scholar","B2","n.","bilim insanı, âlim","Scholars disagree about the poem's author."],
["scholarship","B2","n.","burs; ilim","She won a scholarship to study music."],
["scope","C1","n.","kapsam; fırsat alanı","The question is beyond the scope of this lesson."],
["scratch","B2","n., v.","çizik; kaşımak, çizmek","The cat scratched the new sofa."],
["scream","B2","n., v.","çığlık; çığlık atmak","She screamed when the lights went out."],
["screen","B2","v.","taramak (sağlık); gösterime sokmak; perdelemek","All passengers are screened before boarding."],
["screening","B2","n.","tarama (sağlık); gösterim","Regular screening can catch the disease early."],
["screw","C1","n., v.","vida; vidalamak","Tighten the screws on the door hinge."],
["scrutiny","C1","n.","inceleme, didik didik etme","The accounts came under close scrutiny."],
["seal","C1","n., v.","mühür; fok; mühürlemek, sızdırmaz yapmak","Seal the envelope before posting it."],
["seat","B2","v.","oturtmak; (kapasite) almak","The hall seats four hundred people."],
["sector","B2","n.","sektör, kesim","She moved from banking to the public sector."],
["secular","C1","adj.","laik, dünyevi","The school provides a secular education."],
["secure","B2","adj., v.","güvenli; sağlamak, güvence altına almak","The team secured a place in the final."],
["seek","B2","v.","aramak, çabalamak","Thousands seek work in the city every year."],
["seeker","B2","n.","arayan kişi","The library helps job seekers write applications."],
["seemingly","C1","adv.","görünüşe göre","The seemingly simple task took all day."],
["segment","C1","n.","bölüm, dilim, kesim","The airline targets the budget segment of the market."],
["seize","C1","v.","ele geçirmek; yakalamak (fırsat)","Customs officers seized the smuggled goods."],
["seldom","C1","adv.","nadiren","He seldom speaks about his childhood."],
["select","B2","v.","seçmek","Select the strongest seedlings for planting."],
["selection","B2","n.","seçim; seçki","The shop offers a wide selection of teas."],
["selective","C1","adj.","seçici","The school is highly selective about admissions."],
["self","B2","n.","benlik, öz","She was her usual cheerful self again."],
["seminar","B2","n.","seminer","The seminar covered new teaching methods."],
["senator","C1","n.","senatör","The senator promised to oppose the bill."],
["senior","B2","adj.","kıdemli; yaşça büyük","She is a senior engineer at the plant."],
["sensation","C1","n.","his, duyum; olay yaratan şey","A tingling sensation spread through his fingers."],
["sense","B2","v.","sezmek, hissetmek","The dog sensed the storm before we did."],
["sensitive","B2","adj.","hassas, duyarlı","The topic is too sensitive for a public debate."],
["sensitivity","C1","n.","duyarlılık, hassasiyet","Handle the matter with great sensitivity."],
["sentence","B2","v.","mahkûm etmek, ceza vermek","The judge sentenced him to five years."],
["sentiment","C1","n.","duygu, kanı","Public sentiment turned against the war."],
["separation","C1","n.","ayrılık, ayrılma","The separation of powers protects democracy."],
["sequence","B2","n.","dizi, sıralama","Enter the numbers in the correct sequence."],
["serial","C1","adj.","seri (halinde olan)","Police linked the cases to a serial offender."],
["session","B2","n.","oturum, seans","The morning session ends at noon."],
["set-up","C1","n.","düzen, yapı; kuruluş","The studio's set-up takes an hour to arrange."],
["settle","B2","v.","yerleşmek; halletmek; durulmak","The family settled in a quiet coastal town."],
["settlement","C1","n.","yerleşim; uzlaşma","The two firms reached an out-of-court settlement."],
["settler","B2","n.","yerleşimci","The first settlers built homes near the river."],
["severe","B2","adj.","şiddetli, ağır; sert","The region suffered a severe drought."],
["severely","B2","adv.","ciddi biçimde, ağır şekilde","The storm severely damaged the pier."],
["sexuality","C1","n.","cinsellik, cinsel yönelim","The novel explores identity and sexuality."],
["sexy","B2","adj.","seksi, çekici","The car has a sexy, streamlined design."],
["shade","B2","n.","gölge (serinlik); ton","We ate lunch in the shade of an oak."],
["shadow","B2","n.","gölge (siluet)","The tower cast a long shadow across the square."],
["shallow","B2","adj.","sığ; yüzeysel","Children played in the shallow end of the pool."],
["shame","B2","n.","utanç; yazık","It's a shame the museum was closed."],
["shape","B2","v.","biçimlendirmek, şekillendirmek","Childhood experiences shape our adult habits."],
["shaped","B2","adj.","biçimli, şeklinde","The pool is shaped like a guitar."],
["shareholder","C1","n.","hissedar","Shareholders approved the merger at the meeting."],
["shatter","C1","v.","paramparça etmek/olmak","The blast shattered windows across the street."],
["shed","C1","v.","dökmek (yaprak/gözyaşı); kurtulmak; ışık tutmak","The report sheds light on the bank's losses."],
["sheer","C1","adj.","katıksız, salt; sarp","They won through sheer determination."],
["shelter","B2","n., v.","barınak, sığınak; barındırmak","We sheltered from the rain under a bridge."],
["shift","B2","v.","kaydırmak, değişmek","Public opinion has shifted towards reform."],
["ship","B2","v.","sevk etmek, göndermek","The order ships within two working days."],
["shipping","C1","n.","denizcilik, nakliye","The canal is open to international shipping."],
["shock","B2","n., v.","şok; sarsmak","The news of the closure shocked the staff."],
["shocked","B2","adj.","şok olmuş, sarsılmış","Shocked residents surveyed the flood damage."],
["shocking","B2","adj.","şok edici, sarsıcı","The documentary contains some shocking scenes."],
["shoot","C1","n.","filiz, sürgün; çekim","Green shoots appeared a week after sowing."],
["shooting","B2","n.","silahlı saldırı; çekim (film)","Police are investigating a shooting in the suburb."],
["shore","B2","n.","kıyı, sahil","Waves crashed against the rocky shore."],
["short-term","B2","adj.","kısa vadeli","The job is short-term, just for the summer."],
["shortage","B2","n.","kıtlık, eksiklik","The hospital faces a shortage of nurses."],
["shortly","B2","adv.","kısa süre içinde, birazdan","The doctor will see you shortly."],
["shot","B2","n.","atış; deneme; (fotoğraf) kare; aşı","His second shot hit the target."],
["shrink","C1","v.","küçülmek, çekmek; daralmak","The sweater shrank in the wash."],
["shrug","C1","v.","omuz silkmek","She shrugged and turned back to her book."],
["sibling","B2","n.","kardeş","He has three younger siblings."],
["sigh","C1","n., v.","iç çekiş; iç çekmek","He sighed and started the report again."],
["signature","B2","n.","imza","The form needs your signature at the bottom."],
["significance","B2","n.","önem, anlam","The discovery's significance was clear at once."],
["significant","B2","adj.","önemli, kayda değer","There has been a significant drop in crime."],
["significantly","B2","adv.","önemli ölçüde","Prices vary significantly between regions."],
["silence","B2","n.","sessizlik","A minute's silence was held for the victims."],
["silk","B2","n.","ipek","The scarf is made of pure silk."],
["simulate","C1","v.","benzetimini yapmak, taklit etmek","The software simulates the flow of traffic."],
["simulation","C1","n.","simülasyon, benzetim","Pilots train for emergencies in a simulation."],
["simultaneously","C1","adv.","aynı anda, eşzamanlı olarak","The film opened simultaneously in forty countries."],
["sin","C1","n.","günah","He confessed his sins to the priest."],
["sincere","B2","adj.","içten, samimi","Please accept my sincere apologies."],
["situated","C1","adj.","konumlanmış, yer alan","The hotel is situated beside the lake."],
["sketch","C1","n.","eskiz, taslak; skeç","She drew a quick sketch of the harbour."],
["skilled","B2","adj.","becerikli, vasıflı","The repair needs a skilled electrician."],
["skip","C1","v.","atlamak, es geçmek; sekmek","Don't skip breakfast before the exam."],
["skull","B2","n.","kafatası","The helmet protects the skull from impact."],
["slam","C1","v.","çarpmak, hızla kapatmak","He slammed the door behind him."],
["slap","C1","v.","tokat atmak; şaplak vurmak","She slapped the table to get attention."],
["slash","C1","v.","kesmek (derin); büyük ölçüde indirmek","The store slashed prices for the sale."],
["slave","B2","n.","köle","Slaves built many of the ancient monuments."],
["slavery","C1","n.","kölelik","The museum traces the history of slavery."],
["slide","B2","n., v.","kaydırak; slayt; kaymak","The children took turns on the slide."],
["slight","B2","adj.","hafif, az; narin","There's a slight chance of snow tonight."],
["slip","B2","v.","kaymak; sıvışmak; düşmek (hafifçe)","She slipped on the wet floor."],
["slogan","B2","n.","slogan","The campaign needs a catchy slogan."],
["slope","B2","n., v.","yokuş, eğim; eğimli olmak","The garden slopes gently down to the river."],
["slot","C1","n.","yuva, delik; zaman dilimi","The dentist has a free slot at three."],
["smash","C1","v.","parçalamak; çarpmak","The ball smashed the kitchen window."],
["snap","C1","v.","kırılmak (çıt diye); parlamak (öfke); fotoğraf çekmek","The branch snapped under his weight."],
["so-called","B2","adj.","sözde, sözüm ona","The so-called expert had never seen a real case."],
["soak","C1","v.","ıslatmak; suda bekletmek","Soak the beans overnight before cooking."],
["soar","C1","v.","fırlamak (fiyat); süzülmek","Ticket prices soared after the announcement."],
["socialist","C1","adj.","sosyalist","The party follows a broadly socialist programme."],
["solar","B2","adj.","güneşle ilgili, güneş-","Solar panels cover the school's roof."],
["sole","C1","adj.","tek, yegâne","She is the sole owner of the company."],
["solely","C1","adv.","yalnızca, sadece","The decision rests solely with the board."],
["solicitor","C1","n.","avukat (danışman, İng.)","A solicitor handled the house purchase."],
["solidarity","C1","n.","dayanışma","Workers struck in solidarity with the miners."],
["solo","C1","adj., n.","solo, tek başına","She flew her first solo flight at nineteen."],
["somehow","B2","adv.","bir şekilde, her nasılsa","Somehow the cat opened the cupboard."],
["sometime","B2","adv.","(gelecekte/geçmişte) bir ara","Let's meet for lunch sometime next week."],
["somewhat","B2","adv.","biraz, bir ölçüde","The results were somewhat better than feared."],
["sophisticated","B2","adj.","sofistike, gelişmiş; incelikli","The lab uses highly sophisticated equipment."],
["soul","B2","n.","ruh, can","The old town is the soul of the city."],
["sound","C1","adj.","sağlam, sağlıklı; makul","The bridge is structurally sound."],
["sovereignty","C1","n.","egemenlik","The treaty respects each nation's sovereignty."],
["spam","C1","n.","istenmeyen e-posta","My inbox is full of spam this morning."],
["span","C1","n., v.","süre, açıklık; yayılmak, kapsamak","Her career spanned five decades."],
["spare","B2","adj., v.","yedek; ayırmak; esirgemek","Can you spare ten minutes for a quick call?"],
["spark","C1","v.","ateşlemek, tetiklemek","The decision sparked a wave of protests."],
["specialist","B2","adj., n.","uzman","A heart specialist examined the patient."],
["specialize","B2","v.","uzmanlaşmak","The firm specializes in maritime law."],
["specialized","C1","adj.","özelleşmiş, uzmanlaşmış","The task requires specialized equipment."],
["species","B2","n.","tür (canlı)","The island hosts several rare bird species."],
["specification","C1","n.","teknik özellik, şartname","The parts must meet strict specifications."],
["specify","B2","v.","belirtmek, açıkça tanımlamak","The recipe doesn't specify the oven temperature."],
["specimen","C1","n.","örnek, numune","The museum displays a perfect specimen of quartz."],
["spectacle","C1","n.","görkemli gösteri/manzara","The fireworks were a spectacular spectacle."],
["spectacular","B2","adj.","muhteşem, görkemli","The road offers spectacular views of the coast."],
["spectator","B2","n.","seyirci","Thousands of spectators lined the route."],
["spectrum","C1","n.","spektrum, yelpaze","The plan drew support from across the political spectrum."],
["speculate","B2","v.","tahmin yürütmek; spekülasyon yapmak","Reporters speculated about the singer's next move."],
["speculation","B2","n.","spekülasyon, tahmin","Speculation about a merger drove up the shares."],
["speed","B2","v.","hızla gitmek; hızlandırmak","The ambulance sped through the empty streets."],
["spell","C1","n.","dönem, süre; büyü","We enjoyed a spell of warm weather."],
["sphere","C1","n.","küre; alan, çevre","She is well known in academic spheres."],
["spice","B2","n.","baharat","The market sells spices from all over the world."],
["spill","B2","v.","dökmek, dökülmek","He spilled coffee all over the keyboard."],
["spin","C1","n., v.","dönüş; döndürmek; (haberi) çarpıtma","The dancer spun gracefully on one foot."],
["spine","C1","n.","omurga; (kitap) sırt","Lifting badly can injure your spine."],
["spiritual","B2","adj.","manevi, ruhsal","The retreat offers rest and spiritual renewal."],
["spite","B2","n.","inat, garez (in spite of: rağmen)","They went sailing in spite of the wind."],
["split","B2","n., v.","bölünme; bölmek, ayrılmak","The profits are split equally between partners."],
["spoil","B2","v.","bozmak, mahvetmek; şımartmak","Don't let one mistake spoil your day."],
["spokesman","B2","n.","sözcü (erkek)","A company spokesman confirmed the closure."],
["spokesperson","B2","n.","sözcü","The spokesperson declined to comment further."],
["spokeswoman","B2","n.","sözcü (kadın)","A police spokeswoman gave a short statement."],
["sponsor","B2","n., v.","sponsor; desteklemek","A local bank sponsors the youth team."],
["sponsorship","B2","n.","sponsorluk","The festival depends on corporate sponsorship."],
["sporting","B2","adj.","sporla ilgili; centilmence","It was the city's biggest sporting event."],
["spot","B2","v.","fark etmek, gözüne çarpmak","She spotted an error in the contract."],
["spotlight","C1","n.","spot ışığı; ilgi odağı","The scandal put the ministry in the spotlight."],
["spouse","C1","n.","eş","Employees may bring their spouses to the dinner."],
["spread","B2","n.","yayılma; sürme (yiyecek)","The spread of the disease slowed in spring."],
["spring","B2","v.","sıçramak, fırlamak","The cat sprang onto the windowsill."],
["spy","C1","n., v.","casus; casusluk etmek","The spy passed secrets to a foreign power."],
["squad","C1","n.","ekip, tim; kadro","The bomb squad cleared the building."],
["squeeze","C1","v.","sıkmak; sıkıştırmak","Squeeze a little lemon over the fish."],
["stab","C1","v.","bıçaklamak","The victim was stabbed twice in the arm."],
["stability","C1","n.","istikrar, denge","Children need stability at home to thrive."],
["stabilize","C1","v.","istikrara kavuş(tur)mak","Doctors worked to stabilize the patient."],
["stable","B2","adj.","istikrarlı, dengeli; sabit","The patient is now in a stable condition."],
["stage","B2","v.","sahnelemek; düzenlemek","Workers staged a one-day strike."],
["stake","C1","n.","pay, hisse; risk altındaki şey","She owns a forty per cent stake in the firm."],
["stall","B2","n.","tezgâh, stant","The market stall sells homemade jam."],
["stance","B2","n.","tutum, duruş","The party softened its stance on taxes."],
["stand","B2","n.","stant; duruş; tribün","Our company has a stand at the trade fair."],
["standing","C1","adj.","sürekli, daimi; ayakta","The committee has a standing invitation to visit."],
["stare","B2","v.","dik dik bakmak","It's rude to stare at strangers."],
["stark","C1","adj.","çıplak, sert (gerçek); keskin (karşıtlık)","The report paints a stark picture of poverty."],
["starve","B2","v.","açlıktan ölmek/kıvranmak","Without rain, the cattle would starve."],
["statistical","C1","adj.","istatistiksel","The difference is not statistically significant."],
["status","B2","n.","statü, durum","Check the status of your order online."],
["steadily","B2","adv.","istikrarlı biçimde, düzenli olarak","Sales have grown steadily since spring."],
["steady","B2","adj.","sabit, düzenli; sarsılmaz","Keep the camera steady while filming."],
["steam","B2","n.","buhar","Steam rose from the hot springs."],
["steel","B2","n.","çelik","The frame is made of stainless steel."],
["steep","B2","adj.","dik (yokuş); keskin (artış)","The path up the cliff is very steep."],
["steer","C1","v.","yönlendirmek; direksiyon kullanmak","He steered the boat into the harbour."],
["stem","C1","n., v.","sap, gövde; kaynaklanmak; durdurmak","Most complaints stem from late deliveries."],
["step","B2","v.","adım atmak, basmak","Please step away from the closing doors."],
["stereotype","C1","n.","basmakalıp yargı, klişe","The film avoids the usual stereotypes about teenagers."],
["sticky","B2","adj.","yapışkan; çetrefilli","The jam left a sticky mess on the table."],
["stiff","B2","adj.","sert, katı; tutulmuş (kas)","My neck is stiff from sleeping badly."],
["stimulate","B2","v.","teşvik etmek, uyarmak, canlandırmak","Lower taxes may stimulate the economy."],
["stimulus","C1","n.","uyarıcı, teşvik","The plants respond to light as a stimulus."],
["stir","C1","v.","karıştırmak; kıpırdamak; (duygu) uyandırmak","Stir the soup until it thickens."],
["stock","B2","n.","stok; hisse senedi","The shop has a large stock of spare parts."],
["storage","C1","n.","depolama, saklama","The flat has plenty of storage space."],
["straightforward","C1","adj.","basit, dolambaçsız; dobra","The instructions are short and straightforward."],
["strain","C1","n.","zorlanma, gerginlik; tür (mikrop)","The extra work put a strain on the whole team."],
["strand","C1","n.","tel, iplik; öğe (hikâye)","A strand of hair fell across her face."],
["strategic","C1","adj.","stratejik","The port has great strategic importance."],
["stream","B2","n.","dere; akış, akım","A small stream runs behind the house."],
["strengthen","B2","v.","güçlendirmek","Exercise strengthens the heart."],
["stretch","B2","n., v.","esneme; uzanmak; germek","Stretch your legs before the long drive."],
["strict","B2","adj.","katı, sıkı","The school has strict rules about phones."],
["strictly","B2","adv.","kesinlikle; tam anlamıyla","Smoking is strictly forbidden indoors."],
["strike","B2","n., v.","grev; vuruş; çarpmak; grev yapmak","Train drivers will strike on Friday."],
["striking","C1","adj.","çarpıcı, dikkat çekici","There is a striking similarity between the twins."],
["strip","C1","n., v.","şerit; soymak, sökmek","Workers stripped the old paint from the door."],
["strive","C1","v.","çabalamak, gayret etmek","The school strives to include every child."],
["stroke","B2","n.","felç, inme; vuruş; okşama","He never fully recovered from the stroke."],
["structural","C1","adj.","yapısal","The survey found no structural damage."],
["structure","B2","v.","yapılandırmak","Structure your essay around three main points."],
["struggle","B2","n., v.","mücadele; çabalamak","Many families struggle to pay the rent."],
["stuff","B2","v.","tıkıştırmak, doldurmak","He stuffed the papers into his bag and ran."],
["stumble","C1","v.","tökezlemek; (upon) rastlamak","She stumbled on the uneven pavement."],
["stun","C1","v.","afallatmak; sersemletmek","The verdict stunned the courtroom."],
["stunning","B2","adj.","çarpıcı, nefes kesici","The terrace offers a stunning view of the bay."],
["subject","B2","adj.","tabi, maruz (subject to)","Flights are subject to delay in bad weather."],
["submission","C1","n.","teslim (etme); boyun eğme","The deadline for submissions is Friday noon."],
["submit","B2","v.","sunmak, teslim etmek; boyun eğmek","Submit your application before the deadline."],
["subscriber","C1","n.","abone","The channel has two million subscribers."],
["subscription","C1","n.","abonelik","I cancelled my magazine subscription."],
["subsequent","B2","adj.","sonraki, müteakip","Subsequent events proved her right."],
["subsequently","B2","adv.","daha sonra, akabinde","He was arrested and subsequently released."],
["subsidy","C1","n.","sübvansiyon, devlet desteği","Farmers receive subsidies for green projects."],
["substantial","C1","adj.","önemli ölçüde, hatırı sayılır","She inherited a substantial sum of money."],
["substantially","C1","adv.","önemli ölçüde","Costs have risen substantially this year."],
["substitute","C1","n., v.","yedek; ikame; yerine koymak","You can substitute honey for sugar in this recipe."],
["substitution","C1","n.","yerine koyma; oyuncu değişikliği","The coach made two substitutions at half-time."],
["subtle","C1","adj.","ince, belli belirsiz; kurnazca","There's a subtle difference between the two shades."],
["suburb","B2","n.","banliyö, dış mahalle","They moved to a quiet suburb with good schools."],
["suburban","C1","adj.","banliyöye özgü","The train passes through endless suburban streets."],
["succession","C1","n.","art arda geliş; veraset","A succession of storms battered the coast."],
["successive","C1","adj.","ardışık, art arda gelen","The team won three successive titles."],
["successor","C1","n.","halef, ardıl","The director named her successor before retiring."],
["suck","C1","v.","emmek","The baby sucked its thumb quietly."],
["sue","C1","v.","dava etmek","The actor sued the paper for libel."],
["suffering","B2","n.","acı, ıstırap","The new drug reduces suffering in late illness."],
["sufficient","B2","adj.","yeterli","Make sure you allow sufficient time for the journey."],
["sufficiently","B2","adv.","yeterince","The water is not sufficiently clean to drink."],
["suicide","C1","n.","intihar","The charity runs a suicide prevention line."],
["suite","C1","n.","suit (oda takımı); takım","They booked the hotel's largest suite."],
["sum","B2","n., v.","toplam, meblağ; özetlemek (sum up)","A large sum of money went missing."],
["summit","C1","n.","zirve (dağ/diplomasi)","World leaders met at a climate summit."],
["super","B2","adj.","süper, harika","The kids had a super time at the fair."],
["superb","C1","adj.","mükemmel, enfes","The restaurant serves superb seafood."],
["superior","C1","adj.","üstün; üst (rütbece)","The new model is clearly superior to the old."],
["supervise","C1","v.","denetlemek, gözetmek","A lifeguard supervises the pool at all times."],
["supervision","C1","n.","denetim, gözetim","Children may swim only under adult supervision."],
["supervisor","C1","n.","süpervizör, amir; danışman","Report any faults to your supervisor."],
["supplement","C1","n., v.","takviye, ek; takviye etmek","She supplements her income by giving lessons."],
["supportive","C1","adj.","destekleyici","Her colleagues were supportive during her illness."],
["supposedly","C1","adv.","güya, sözde","The castle is supposedly haunted."],
["suppress","C1","v.","bastırmak","He struggled to suppress a laugh."],
["supreme","C1","adj.","en yüksek, yüce","The case went to the supreme court."],
["surge","C1","n., v.","dalgalanma, ani artış; kabarmak","A surge in demand emptied the shelves."],
["surgeon","B2","n.","cerrah","The surgeon explained the operation step by step."],
["surgery","B2","n.","ameliyat; muayenehane","He needs surgery on his knee."],
["surgical","C1","adj.","cerrahi","The kit contains sterile surgical gloves."],
["surplus","C1","n.","fazla(lık), artık","The farm sells its surplus vegetables at market."],
["surrender","C1","v.","teslim olmak; teslim etmek","The garrison surrendered after a long siege."],
["surround","B2","v.","çevrelemek, kuşatmak","High walls surround the old city."],
["surrounding","B2","adj.","çevredeki, etraftaki","The fire spread to surrounding fields."],
["surveillance","C1","n.","gözetim, izleme","The suspect was kept under constant surveillance."],
["survey","B2","v.","incelemek; anket yapmak; ölçmek","Engineers surveyed the damaged bridge."],
["survival","B2","n.","hayatta kalma","The seal pup's survival depends on thick fur."],
["survivor","B2","n.","hayatta kalan, kazazede","Rescuers searched the rubble for survivors."],
["suspect","B2","n., v.","şüpheli; şüphelenmek","Police arrested a suspect within hours."],
["suspend","B2","v.","askıya almak; asmak; uzaklaştırmak","The match was suspended because of lightning."],
["suspension","C1","n.","askıya alma; süspansiyon; uzaklaştırma","He received a two-game suspension."],
["suspicion","C1","n.","şüphe, kuşku","She was arrested on suspicion of fraud."],
["suspicious","C1","adj.","şüpheli; şüpheci","A suspicious package closed the station."],
["sustain","C1","v.","sürdürmek; (yara) almak; beslemek","The soil cannot sustain crops without rain."],
["sustainable","B2","adj.","sürdürülebilir","The hotel runs on sustainable energy."],
["swallow","B2","v.","yutmak","Chew your food well before you swallow."],
["swear","B2","v.","küfretmek; yemin etmek","He swore to tell the truth in court."],
["sweep","B2","v.","süpürmek; hızla yayılmak","A wave of panic swept through the crowd."],
["swing","C1","n., v.","salıncak; sallanmak; ani değişim","The gate swung open in the wind."],
["switch","B2","n.","anahtar, düğme; geçiş","Press the switch by the door for the light."],
["sword","C1","n.","kılıç","The knight drew his sword."],
["symbolic","C1","adj.","sembolik, simgesel","Lighting the lamp has a symbolic meaning."],
["sympathetic","B2","adj.","anlayışlı, sevecen","The nurse gave him a sympathetic smile."],
["sympathy","B2","n.","sempati; başsağlığı; anlayış","We sent flowers as a token of our sympathy."],
["syndrome","C1","n.","sendrom","The syndrome affects roughly one child in a thousand."],
["synthesis","C1","n.","sentez, bireşim","The paper offers a synthesis of recent research."],
["systematic","C1","adj.","sistematik, dizgeli","The library began a systematic review of its books."]
];
