// Oxford 3000 B1 vocab. Format: [w, lv, pos, tr, ex]
module.exports = [
["absolutely","B1","adv.","kesinlikle, tamamen","You're absolutely right about that."],
["academic","B1","adj., n.","akademik","She got good academic results this year."],
["access","B1","n., v.","erişim; erişmek","Students have free access to the library."],
["account","B1","n., v.","hesap; anlatım","I opened a bank account last week."],
["achievement","B1","n.","başarı","Finishing the marathon was a great achievement."],
["ad","B1","n.","reklam, ilan","I saw an ad for the concert online."],
["addition","B1","n.","ekleme; ayrıca (in addition)","In addition to English, she speaks Italian."],
["admire","B1","v.","hayran olmak, beğenmek","I admire her courage and patience."],
["admit","B1","v.","itiraf etmek, kabul etmek","He admitted that he had made a mistake."],
["advanced","B1","adj.","ileri (düzey)","She is in the advanced English class."],
["advise","B1","v.","tavsiye etmek, öğütlemek","The doctor advised him to rest."],
["afford","B1","v.","parası yetmek, gücü olmak","We can't afford a new car this year."],
["agent","B1","n.","temsilci, acente; ajan","The travel agent booked our flights."],
["agreement","B1","n.","anlaşma; uzlaşma","The two sides reached an agreement."],
["ahead","B1","adv.","ileride, önde","The road ahead was blocked by snow."],
["aim","B1","n., v.","amaç(lamak), hedef(lemek)","Our aim is to help new students."],
["alarm","B1","n., v.","alarm; telaşlandırmak","Set the alarm for six o'clock."],
["album","B1","n.","albüm","The band released a new album."],
["alcohol","B1","n.","alkol","The restaurant doesn't serve alcohol."],
["alcoholic","B1","adj.","alkollü","They don't sell alcoholic drinks here."],
["amazed","B1","adj.","hayrete düşmüş","I was amazed by the magician's tricks."],
["ambition","B1","n.","hırs; büyük hedef","Her ambition is to become a pilot."],
["ambitious","B1","adj.","hırslı; iddialı","He is young and very ambitious."],
["analyse","B1","v.","analiz etmek, çözümlemek","Scientists analysed the water samples."],
["analysis","B1","n.","analiz, çözümleme","The analysis showed high levels of salt."],
["announce","B1","v.","duyurmak, ilan etmek","They announced the winners after lunch."],
["announcement","B1","n.","duyuru, anons","Listen carefully to the announcement."],
["annoy","B1","v.","sinirlendirmek, rahatsız etmek","The loud music annoyed the neighbours."],
["annoyed","B1","adj.","sinirlenmiş, kızgın","She was annoyed about the long wait."],
["annoying","B1","adj.","can sıkıcı, sinir bozucu","It's annoying when the bus is late."],
["apart","B1","adv.","ayrı; aralıklı","The two villages are ten kilometres apart."],
["apologize","B1","v.","özür dilemek","He apologized for arriving late."],
["application","B1","n.","başvuru; uygulama","Send your application before Friday."],
["appointment","B1","n.","randevu","I have a dentist appointment at three."],
["appreciate","B1","v.","takdir etmek; minnettar olmak","I really appreciate your help."],
["approximately","B1","adv.","yaklaşık olarak","The journey takes approximately two hours."],
["arrest","B1","n., v.","tutuklamak; tutuklama","Police arrested two men after the robbery."],
["arrival","B1","n.","varış, geliş","We waited for the arrival of the train."],
["assignment","B1","n.","ödev, görev","The teacher gave us a writing assignment."],
["assist","B1","v.","yardım etmek","A nurse assisted the doctor during the operation."],
["atmosphere","B1","n.","atmosfer; hava, ortam","The café has a friendly atmosphere."],
["attach","B1","v.","iliştirmek, eklemek","I attached the photos to the email."],
["attitude","B1","n.","tutum, tavır","A positive attitude helps you learn."],
["attract","B1","v.","çekmek (ilgi/insan)","The festival attracts thousands of visitors."],
["attraction","B1","n.","cazibe; gezilecek yer","The castle is the town's main attraction."],
["authority","B1","n.","otorite, yetki; yetkililer","The local authority repaired the road."],
["aware","B1","adj.","farkında","Are you aware of the new rules?"],
["backwards","B1","adv.","geriye doğru","Count backwards from ten to one."],
["bake","B1","v.","fırında pişirmek","We baked bread on Sunday morning."],
["balance","B1","n., v.","denge(lemek)","Keep a balance between work and rest."],
["ban","B1","n., v.","yasak(lamak)","Smoking is banned in the building."],
["base","B1","n., v.","temel; üs; dayandırmak","The film is based on a true story."],
["basic","B1","adj.","temel, basit","The course teaches basic computer skills."],
["basis","B1","n.","temel, esas","We meet on a weekly basis."],
["battery","B1","n.","pil, batarya","My phone battery is nearly dead."],
["battle","B1","n., v.","savaş, muharebe; mücadele etmek","The battle lasted three days."],
["beauty","B1","n.","güzellik","The beauty of the lake amazed us."],
["bee","B1","n.","arı","A bee landed on the flower."],
["belief","B1","n.","inanç, kanı","Her belief in hard work never changed."],
["bell","B1","n.","zil, çan","The school bell rings at nine."],
["bend","B1","n., v.","bükmek, eğilmek; viraj","Bend your knees when you lift."],
["bite","B1","n., v.","ısırmak; ısırık","The dog doesn't bite, don't worry."],
["block","B1","n., v.","blok; engellemek","A fallen tree blocked the road."],
["bomb","B1","n., v.","bomba(lamak)","The bomb destroyed the bridge."],
["border","B1","n., v.","sınır","We crossed the border at night."],
["bother","B1","v.","rahatsız etmek; zahmet etmek","Don't bother to wash the dishes."],
["branch","B1","n.","dal; şube","The bird sat on a high branch."],
["brand","B1","n., v.","marka","Which brand of phone do you use?"],
["brave","B1","adj.","cesur","The brave girl saved the cat from the fire."],
["breath","B1","n.","nefes, soluk","Take a deep breath and relax."],
["breathe","B1","v.","nefes almak","It's hard to breathe at high altitude."],
["breathing","B1","n.","nefes alma, solunum","Her breathing was slow and calm."],
["bride","B1","n.","gelin","The bride wore a white dress."],
["bubble","B1","n.","kabarcık, baloncuk","The children blew soap bubbles."],
["bury","B1","v.","gömmek","The dog buried its bone in the garden."],
["calm","B1","adj., n., v.","sakin(leşmek); sakinlik","Stay calm during the exam."],
["campaign","B1","n., v.","kampanya (yürütmek)","They started a campaign to clean the beach."],
["campus","B1","n.","kampüs, yerleşke","The university campus has a big library."],
["candidate","B1","n.","aday","Three candidates applied for the job."],
["cap","B1","n.","kep, şapka; kapak","He wears a baseball cap in summer."],
["captain","B1","n.","kaptan","The captain led the team onto the field."],
["careless","B1","adj.","dikkatsiz","A careless mistake cost him the match."],
["category","B1","n.","kategori, ulam","The books are sorted into categories."],
["ceiling","B1","n.","tavan","The lamp hangs from the ceiling."],
["celebration","B1","n.","kutlama","The celebration lasted until midnight."],
["central","B1","adj.","merkezi","The hotel is in a central location."],
["ceremony","B1","n.","tören","The wedding ceremony was short and lovely."],
["chain","B1","n., v.","zincir","The gate was locked with a chain."],
["challenge","B1","n., v.","zorlu görev; meydan okumak","Learning Chinese is a real challenge."],
["champion","B1","n.","şampiyon","She is the national swimming champion."],
["channel","B1","n.","kanal","Which channel is the match on?"],
["chapter","B1","n.","bölüm (kitap)","Read the first chapter for homework."],
["charge","B1","n., v.","ücret (almak); şarj etmek; suçlamak","They charge ten pounds for delivery."],
["cheat","B1","n., v.","kopya çekmek; aldatmak; hileci","It's wrong to cheat in exams."],
["cheerful","B1","adj.","neşeli, güler yüzlü","The waiter greeted us with a cheerful smile."],
["chemical","B1","adj., n.","kimyasal","Don't mix these two chemicals."],
["chest","B1","n.","göğüs; sandık","He felt a pain in his chest."],
["childhood","B1","n.","çocukluk","She spent her childhood by the sea."],
["claim","B1","n., v.","iddia (etmek); talep etmek","He claims he saw a wolf in the forest."],
["clause","B1","n.","cümlecik; madde","This sentence has two clauses."],
["click","B1","n., v.","tıklamak; tık sesi","Click the button to start the video."],
["client","B1","n.","müşteri, müvekkil","The lawyer met her client at noon."],
["cloth","B1","n.","bez, kumaş","Clean the table with a wet cloth."],
["clue","B1","n.","ipucu","The detective found an important clue."],
["coal","B1","n.","kömür","The old train burned coal."],
["coin","B1","n.","madeni para","He found an old coin in the garden."],
["collection","B1","n.","koleksiyon; toplama","His stamp collection is worth a lot."],
["coloured","B1","adj.","renkli","She drew with coloured pencils."],
["combine","B1","v.","birleştirmek","Combine the eggs with the flour."],
["commercial","B1","adj., n.","ticari; reklam (TV)","The film was a commercial success."],
["commit","B1","v.","(suç) işlemek; söz vermek, adamak","He committed a serious crime."],
["communication","B1","n.","iletişim","Good communication is important in a team."],
["comparison","B1","n.","karşılaştırma","Write a comparison of the two cities."],
["competitive","B1","adj.","rekabetçi","He is very competitive in sports."],
["competitor","B1","n.","rakip; yarışmacı","Twenty competitors entered the race."],
["complaint","B1","n.","şikâyet","The hotel received complaints about the noise."],
["complex","B1","adj., n.","karmaşık; kompleks","The instructions are too complex for me."],
["concentrate","B1","v.","konsantre olmak, odaklanmak","I can't concentrate with this noise."],
["conclude","B1","v.","sonuca varmak; bitirmek","The report concludes that prices will rise."],
["conclusion","B1","n.","sonuç, vargı","What conclusion did you reach?"],
["confident","B1","adj.","kendinden emin, özgüvenli","She felt confident before the interview."],
["confirm","B1","v.","onaylamak, doğrulamak","Please confirm your booking by email."],
["confuse","B1","v.","kafasını karıştırmak; karıştırmak","The signs confused the tourists."],
["confused","B1","adj.","kafası karışmış","I'm confused; can you explain again?"],
["connection","B1","n.","bağlantı","The internet connection is slow today."],
["consequence","B1","n.","sonuç (genelde olumsuz)","Think about the consequences of your actions."],
["consist","B1","v.","oluşmak (consist of)","The team consists of eleven players."],
["consume","B1","v.","tüketmek","The car consumes a lot of fuel."],
["consumer","B1","n.","tüketici","Consumers want cheaper energy."],
["contact","B1","n., v.","iletişim (kurmak), temas","Contact me if you have questions."],
["container","B1","n.","kap, konteyner","Store the rice in a closed container."],
["continuous","B1","adj.","sürekli, kesintisiz","There was continuous rain all weekend."],
["contrast","B1","n., v.","karşıtlık, zıtlık","The contrast between the two brothers is striking."],
["convenient","B1","adj.","kullanışlı, uygun, elverişli","The station is convenient for my office."],
["convince","B1","v.","ikna etmek","She convinced me to join the club."],
["costume","B1","n.","kostüm","He wore a pirate costume to the party."],
["cottage","B1","n.","kır evi, kulübe","They rented a cottage by the lake."],
["cotton","B1","n.","pamuk(lu)","This shirt is made of cotton."],
["countryside","B1","n.","kırsal (bölge)","We cycled through the beautiful countryside."],
["court","B1","n.","mahkeme; kort","The case goes to court next month."],
["covered","B1","adj.","kaplı, örtülü","The hills were covered in snow."],
["cruel","B1","adj.","zalim, acımasız","It's cruel to keep birds in small cages."],
["cultural","B1","adj.","kültürel","The city offers many cultural activities."],
["currency","B1","n.","para birimi","What currency do they use in Japan?"],
["current","B1","adj., n.","mevcut, güncel; akıntı","The current situation is improving."],
["currently","B1","adv.","şu anda, hâlen","She is currently working in Berlin."],
["curtain","B1","n.","perde","Open the curtains and let the sun in."],
["custom","B1","n.","gelenek, âdet","It's a local custom to welcome guests with tea."],
["damage","B1","n., v.","hasar (vermek), zarar","The storm damaged the roof."],
["decade","B1","n.","on yıl","The bridge was built a decade ago."],
["decorate","B1","v.","süslemek; boyamak (ev)","We decorated the room for the party."],
["define","B1","v.","tanımlamak","Can you define this word?"],
["definite","B1","adj.","kesin, belirli","We need a definite answer by Friday."],
["definition","B1","n.","tanım","The dictionary gives two definitions."],
["deliver","B1","v.","teslim etmek, dağıtmak","They deliver pizza until midnight."],
["departure","B1","n.","kalkış, ayrılış","Check the departure time of your flight."],
["despite","B1","prep.","rağmen","Despite the rain, we enjoyed the trip."],
["destination","B1","n.","varış noktası, hedef","After ten hours, we reached our destination."],
["determine","B1","v.","belirlemek; saptamak","Tests will determine the cause of the illness."],
["determined","B1","adj.","kararlı","She is determined to pass the exam."],
["development","B1","n.","gelişme, kalkınma","The town has seen rapid development."],
["diagram","B1","n.","şema, diyagram","The diagram shows how the engine works."],
["diamond","B1","n.","elmas; karo","The ring has a small diamond."],
["difficulty","B1","n.","zorluk, güçlük","He has difficulty reading small print."],
["directly","B1","adv.","doğrudan, direkt","Speak directly to the manager."],
["dirt","B1","n.","kir, pislik; toprak","Wash the dirt off your boots."],
["disadvantage","B1","n.","dezavantaj","Living far from work is a disadvantage."],
["disappointed","B1","adj.","hayal kırıklığına uğramış","I was disappointed with my result."],
["disappointing","B1","adj.","hayal kırıklığı yaratan","The end of the film was disappointing."],
["discount","B1","n., v.","indirim","Students get a ten per cent discount."],
["dislike","B1","n., v.","hoşlanmamak; hoşlanmama","She dislikes loud music."],
["divide","B1","n., v.","bölmek, ayırmak","Divide the class into four groups."],
["documentary","B1","n.","belgesel","We watched a documentary about whales."],
["donate","B1","v.","bağışlamak","He donated his old books to the library."],
["doubt","B1","n., v.","şüphe (etmek)","I doubt that the shop is still open."],
["dressed","B1","adj.","giyinmiş","She was dressed in black."],
["drum","B1","n.","davul, bateri","He plays the drums in a band."],
["drunk","B1","adj.","sarhoş","The drunk man couldn't walk straight."],
["due","B1","adj.","beklenen; vadesi gelmiş; nedeniyle (due to)","The train is due at six."],
["dust","B1","n.","toz","The old books were covered in dust."],
["duty","B1","n.","görev; vergi","It's my duty to help my parents."],
["earthquake","B1","n.","deprem","The earthquake shook the whole city."],
["eastern","B1","adj.","doğu(ya ait)","They visited the eastern coast of the island."],
["economic","B1","adj.","ekonomik (ekonomiyle ilgili)","The country faces economic problems."],
["economy","B1","n.","ekonomi","Tourism is important for the economy."],
["edge","B1","n.","kenar, uç","Don't stand near the edge of the cliff."],
["editor","B1","n.","editör","The editor checked the article carefully."],
["educate","B1","v.","eğitmek","The programme educates children about safety."],
["educated","B1","adj.","eğitimli","Her parents are well educated."],
["educational","B1","adj.","eğitici, eğitimsel","The museum has educational programmes for kids."],
["effective","B1","adj.","etkili","Walking is an effective way to keep fit."],
["effectively","B1","adv.","etkili biçimde","She manages her time effectively."],
["effort","B1","n.","çaba, gayret","With a little effort, you can improve fast."],
["election","B1","n.","seçim","The election takes place in May."],
["element","B1","n.","unsur, öğe; element","Trust is a key element of friendship."],
["embarrassed","B1","adj.","utanmış, mahcup","I was embarrassed when I forgot her name."],
["embarrassing","B1","adj.","utandırıcı","It was an embarrassing moment for everyone."],
["emergency","B1","n.","acil durum","In an emergency, call this number."],
["emotion","B1","n.","duygu","The song is full of emotion."],
["employment","B1","n.","istihdam, iş","The factory provides employment for the town."],
["encourage","B1","v.","cesaretlendirmek, teşvik etmek","My teacher encouraged me to write."],
["enemy","B1","n.","düşman","The two countries were enemies for years."],
["engaged","B1","adj.","nişanlı; meşgul","They got engaged last summer."],
["engineering","B1","n.","mühendislik","She studies engineering at university."],
["entertain","B1","v.","eğlendirmek; ağırlamak","The clown entertained the children."],
["entertainment","B1","n.","eğlence","The hotel offers evening entertainment."],
["entrance","B1","n.","giriş","Wait for me at the main entrance."],
["entry","B1","n.","giriş; katılım","Entry to the museum is free."],
["environmental","B1","adj.","çevresel","Plastic waste is an environmental problem."],
["episode","B1","n.","bölüm (dizi)","Did you watch the last episode?"],
["equal","B1","adj., n., v.","eşit (olmak)","Everyone deserves equal treatment."],
["equally","B1","adv.","eşit olarak; aynı derecede","Divide the cake equally."],
["escape","B1","n., v.","kaç(ış)mak; kurtulmak","The bird escaped from its cage."],
["essential","B1","adj.","temel, zorunlu, şart","Water is essential for life."],
["eventually","B1","adv.","sonunda, nihayetinde","Eventually, we found the right house."],
["examine","B1","v.","incelemek; muayene etmek","The doctor examined her carefully."],
["exchange","B1","n., v.","değiş tokuş (etmek); döviz","We exchanged phone numbers."],
["excitement","B1","n.","heyecan","The children couldn't hide their excitement."],
["exhibition","B1","n.","sergi","The exhibition shows old photographs."],
["expand","B1","v.","genişle(t)mek, büyümek","The company plans to expand next year."],
["expected","B1","adj.","beklenen","The expected arrival time is noon."],
["experienced","B1","adj.","deneyimli","She is an experienced driver."],
["explode","B1","v.","patlamak","The fireworks exploded over the river."],
["explore","B1","v.","keşfetmek, dolaşmak","We explored the old town on foot."],
["explosion","B1","n.","patlama","The explosion broke several windows."],
["export","B1","n., v.","ihracat; ihraç etmek","The country exports tea and cotton."],
["fairly","B1","adv.","oldukça; adil biçimde","The test was fairly easy."],
["familiar","B1","adj.","tanıdık, aşina","Her face looks familiar to me."],
["fancy","B1","adj., v.","süslü, şık; canı istemek","Do you fancy a cup of tea?"],
["fascinating","B1","adj.","büyüleyici, çok ilginç","The museum has a fascinating history section."],
["fashionable","B1","adj.","modaya uygun, şık","She always wears fashionable clothes."],
["fasten","B1","v.","bağlamak, takmak (kemer)","Please fasten your seat belts."],
["favour","B1","n., v.","iyilik; kayırmak","Can you do me a favour?"],
["fence","B1","n.","çit","The dog jumped over the fence."],
["fighting","B1","n.","çatışma, kavga","The fighting stopped at sunset."],
["file","B1","n., v.","dosya(lamak)","Save the file before you close it."],
["financial","B1","adj.","finansal, mali","They have some financial problems."],
["fitness","B1","n.","form, kondisyon","Swimming improves your fitness."],
["fixed","B1","adj.","sabit","The menu has a fixed price."],
["flag","B1","n.","bayrak","The flag waves in the wind."],
["flood","B1","n., v.","sel; su basmak","The flood damaged many homes."],
["flour","B1","n.","un","Mix the flour with two eggs."],
["flow","B1","n., v.","akış; akmak","The river flows to the sea."],
["fold","B1","n., v.","katlamak","Fold the paper in half."],
["folk","B1","adj., n.","halk; halk müziği","We listened to Turkish folk songs."],
["force","B1","n., v.","güç, kuvvet; zorlamak","The wind forced us to stop."],
["forever","B1","adv.","sonsuza dek","I will remember this day forever."],
["frame","B1","n., v.","çerçeve(lemek)","The photo is in a silver frame."],
["freeze","B1","v.","donmak; dondurmak","Water freezes at zero degrees."],
["frequently","B1","adv.","sıkça, sık sık","Trains run frequently during the day."],
["friendship","B1","n.","arkadaşlık, dostluk","Their friendship began at school."],
["frighten","B1","v.","korkutmak","The thunder frightened the children."],
["frightened","B1","adj.","korkmuş","The frightened cat hid under the bed."],
["frightening","B1","adj.","korkutucu","It was a frightening experience."],
["frozen","B1","adj.","donmuş; dondurulmuş","We skated on the frozen lake."],
["fry","B1","v.","kızartmak","Fry the onions until they are golden."],
["fuel","B1","n., v.","yakıt","The plane needs more fuel."],
["function","B1","n., v.","işlev (görmek), fonksiyon","The heart's function is to pump blood."],
["fur","B1","n.","kürk, post","The cat has soft white fur."],
["garage","B1","n.","garaj; tamirhane","The car is in the garage."],
["gather","B1","v.","toplanmak; toplamak","The family gathered for dinner."],
["generally","B1","adv.","genellikle","I generally walk to work."],
["generation","B1","n.","kuşak, nesil","Three generations live in that house."],
["generous","B1","adj.","cömert","It was generous of you to share."],
["gentle","B1","adj.","nazik, yumuşak","Be gentle with the kitten."],
["gentleman","B1","n.","beyefendi","An old gentleman opened the door for us."],
["ghost","B1","n.","hayalet","Do you believe in ghosts?"],
["giant","B1","adj., n.","dev (gibi)","A giant wave hit the boat."],
["glad","B1","adj.","memnun, sevinçli","I'm glad you came to the party."],
["global","B1","adj.","küresel","Climate change is a global problem."],
["glove","B1","n.","eldiven","Wear gloves; it's freezing outside."],
["goods","B1","n.","mal(lar), eşya","The shop sells leather goods."],
["graduate","B1","n., v.","mezun (olmak)","She graduated from university last year."],
["grain","B1","n.","tahıl; tane","The farmers store grain for winter."],
["grateful","B1","adj.","minnettar","I'm grateful for your support."],
["growth","B1","n.","büyüme, artış","The town's growth has been fast."],
["guard","B1","n., v.","bekçi, koruma; korumak","A guard stands at the gate."],
["guilty","B1","adj.","suçlu","I feel guilty about forgetting her birthday."],
["hang","B1","v.","asmak; sarkmak","Hang your coat by the door."],
["happiness","B1","n.","mutluluk","Money alone doesn't bring happiness."],
["hardly","B1","adv.","neredeyse hiç, güçbela","I could hardly hear the speaker."],
["headline","B1","n.","manşet, başlık","The story made the front-page headlines."],
["heating","B1","n.","ısıtma (sistemi)","The heating doesn't work in my room."],
["heavily","B1","adv.","yoğun biçimde, ağır şekilde","It rained heavily all night."],
["helicopter","B1","n.","helikopter","A helicopter flew over the stadium."],
["highlight","B1","n., v.","öne çıkan an; vurgulamak","Highlight the new words in the text."],
["highly","B1","adv.","son derece; yüksek düzeyde","The film is highly recommended."],
["historic","B1","adj.","tarihî (önemli)","It was a historic day for the country."],
["historical","B1","adj.","tarihsel","She loves historical novels."],
["honest","B1","adj.","dürüst","Give me an honest answer."],
["horrible","B1","adj.","korkunç, berbat","The medicine has a horrible taste."],
["horror","B1","n.","korku, dehşet","He loves horror films."],
["hurricane","B1","n.","kasırga","The hurricane destroyed the coast."],
["hurry","B1","n., v.","acele (etmek)","Hurry up, or we'll be late!"],
["identity","B1","n.","kimlik","The police checked his identity."],
["ignore","B1","v.","görmezden gelmek","Just ignore the rude comments."],
["illegal","B1","adj.","yasa dışı","Parking here is illegal."],
["imaginary","B1","adj.","hayalî","The child has an imaginary friend."],
["immediate","B1","adj.","acil, ani; en yakın","We need an immediate answer."],
["immigrant","B1","n.","göçmen","Many immigrants work in this city."],
["impact","B1","n., v.","etki; çarpma","The internet has a huge impact on our lives."],
["import","B1","n., v.","ithalat; ithal etmek","The country imports most of its oil."],
["importance","B1","n.","önem","Never forget the importance of sleep."],
["impression","B1","n.","izlenim","She made a good impression at the interview."],
["impressive","B1","adj.","etkileyici","The bridge is an impressive sight."],
["improvement","B1","n.","iyileşme, gelişme","There's a big improvement in your English."],
["incredibly","B1","adv.","inanılmaz derecede","The film was incredibly boring."],
["indeed","B1","adv.","gerçekten, hakikaten","Thank you very much indeed."],
["indicate","B1","v.","göstermek, işaret etmek","The signs indicate the way to the beach."],
["indirect","B1","adj.","dolaylı","He gave an indirect answer to my question."],
["indoor","B1","adj.","kapalı mekân (içi)","The hotel has an indoor pool."],
["indoors","B1","adv.","içeride, kapalı mekânda","Stay indoors during the storm."],
["influence","B1","n., v.","etki(lemek)","Friends influence our choices."],
["ingredient","B1","n.","malzeme (yemek)","Mix all the ingredients in a bowl."],
["injure","B1","v.","yaralamak, sakatlamak","He injured his leg playing football."],
["injured","B1","adj.","yaralı, sakat","The injured player left the field."],
["innocent","B1","adj.","masum, suçsuz","The court found him innocent."],
["intelligence","B1","n.","zekâ; istihbarat","The test measures different kinds of intelligence."],
["intend","B1","v.","niyet etmek","I intend to start my own business."],
["intention","B1","n.","niyet","I have no intention of moving."],
["invest","B1","v.","yatırım yapmak","They invested their savings in a shop."],
["investigate","B1","v.","soruşturmak, araştırmak","Police are investigating the robbery."],
["involved","B1","adj.","dahil, karışmış","He was involved in a car accident."],
["iron","B1","n., v.","demir; ütü(lemek)","I need to iron my shirt."],
["journal","B1","n.","dergi (bilimsel); günlük","Her article appeared in a science journal."],
["judge","B1","n., v.","hâkim, yargıç; yargılamak","Don't judge people by their clothes."],
["keen","B1","adj.","hevesli, istekli","She's keen on photography."],
["keyboard","B1","n.","klavye","My keyboard has some broken keys."],
["kick","B1","n., v.","tekme(lemek)","He kicked the ball into the goal."],
["killing","B1","n.","öldürme, cinayet","The killing shocked the small town."],
["kiss","B1","n., v.","öpücük; öpmek","She kissed her son goodnight."],
["label","B1","n., v.","etiket(lemek)","Read the label before washing."],
["laboratory","B1","n.","laboratuvar","The samples were sent to the laboratory."],
["lack","B1","n., v.","eksiklik; yoksun olmak","Lack of sleep makes you tired."],
["lay","B1","v.","koymak, sermek; yumurtlamak","Lay the map on the table."],
["layer","B1","n.","katman, tabaka","A thick layer of snow covered the cars."],
["leading","B1","adj.","önde gelen; baş(rol)","She is a leading expert on bees."],
["leaf","B1","n.","yaprak","A leaf fell from the tree."],
["leather","B1","n.","deri (malzeme)","He bought a leather jacket."],
["legal","B1","adj.","yasal, hukuki","Is it legal to park here?"],
["leisure","B1","n.","boş vakit","What do you do in your leisure time?"],
["length","B1","n.","uzunluk","The length of the pool is fifty metres."],
["limit","B1","n., v.","sınır(lamak)","There is a speed limit on this road."],
["lip","B1","n.","dudak","Her lips were blue from the cold."],
["liquid","B1","adj., n.","sıvı","Water is a liquid."],
["literature","B1","n.","edebiyat","She studies English literature."],
["living","B1","adj., n.","yaşayan; geçim","He earns his living as a cook."],
["locate","B1","v.","yerini bulmak; konumlanmak","Rescuers located the lost climbers."],
["located","B1","adj.","konumlanmış, bulunan","The school is located near the park."],
["location","B1","n.","konum, yer","The map shows the exact location."],
["lonely","B1","adj.","yalnız (hisseden)","He felt lonely in the new city."],
["loss","B1","n.","kayıp","The loss of the match upset the fans."],
["luxury","B1","adj., n.","lüks","They stayed at a luxury hotel."],
["mad","B1","adj.","deli, çılgın; çok kızgın","The dog went mad with joy."],
["magic","B1","adj., n.","sihir(li), büyü","The show was full of magic tricks."],
["mainly","B1","adv.","başlıca, çoğunlukla","The guests were mainly family."],
["mall","B1","n.","alışveriş merkezi","We met at the shopping mall."],
["management","B1","n.","yönetim","The hotel is under new management."],
["marketing","B1","n.","pazarlama","She works in marketing."],
["marriage","B1","n.","evlilik","Their marriage lasted fifty years."],
["meanwhile","B1","adv.","bu arada, bu esnada","Boil the pasta; meanwhile, make the sauce."],
["measure","B1","n., v.","ölçmek; önlem","Measure the wall before buying paint."],
["mental","B1","adj.","zihinsel, ruhsal","Exercise is good for mental health."],
["mess","B1","n.","dağınıklık, karışıklık","Your room is a complete mess!"],
["mild","B1","adj.","ılıman; hafif","The winter was mild this year."],
["mix","B1","n., v.","karıştırmak; karışım","Mix the sugar and butter together."],
["mixture","B1","n.","karışım","Pour the mixture into a baking dish."],
["mood","B1","n.","ruh hâli, mod","She is in a good mood today."],
["mud","B1","n.","çamur","His boots were covered in mud."],
["murder","B1","n., v.","cinayet; öldürmek","The murder was solved after ten years."],
["muscle","B1","n.","kas","Swimming works every muscle in the body."],
["mystery","B1","n.","gizem, sır","The old house is full of mystery."],
["nail","B1","n.","tırnak; çivi","She painted her nails red."],
["narrative","B1","adj., n.","anlatı, öykü(leme)","The film has a simple narrative."],
["nation","B1","n.","ulus, millet","The whole nation watched the final."],
["native","B1","adj., n.","ana (dil); yerli","Her native language is Turkish."],
["naturally","B1","adv.","doğal olarak","Naturally, the children were excited."],
["necessarily","B1","adv.","ille de, mutlaka (not necessarily)","Expensive doesn't necessarily mean good."],
["needle","B1","n.","iğne","I need a needle and thread."],
["neighbourhood","B1","n.","mahalle, semt, civar","We live in a quiet neighbourhood."],
["nor","B1","adv., conj.","ne de","She doesn't smoke, nor does she drink."],
["northern","B1","adj.","kuzey(e ait)","The northern part of the country is cold."],
["nuclear","B1","adj.","nükleer","The country closed its nuclear plants."],
["obvious","B1","adj.","açık, bariz, besbelli","The answer is obvious."],
["obviously","B1","adv.","açıkça, besbelli ki","He was obviously very tired."],
["occasion","B1","n.","özel gün; durum, fırsat","The dress is for special occasions."],
["occur","B1","v.","meydana gelmek; akla gelmek","The accident occurred at midnight."],
["odd","B1","adj.","tuhaf; tek (sayı)","There's an odd smell in the kitchen."],
["old-fashioned","B1","adj.","modası geçmiş, eski usul","He wears old-fashioned glasses."],
["operation","B1","n.","ameliyat; operasyon","Grandpa needs a heart operation."],
["organized","B1","adj.","düzenli; örgütlü","She is very organized at work."],
["organizer","B1","n.","düzenleyici, organizatör","The organizers expect a big crowd."],
["originally","B1","adv.","aslında, başlangıçta","The family originally came from Spain."],
["ought","B1","modal v.","-meli (ought to)","You ought to see a doctor."],
["ours","B1","pron.","bizimki","Their garden is bigger than ours."],
["outdoor","B1","adj.","açık hava (etkinliği)","The town has an outdoor swimming pool."],
["outdoors","B1","adv.","açık havada, dışarıda","We had lunch outdoors in the garden."],
["painful","B1","adj.","ağrılı, acı veren","His knee is swollen and painful."],
["pale","B1","adj.","solgun; açık (renk)","You look pale; are you ill?"],
["pan","B1","n.","tava, tencere","Heat some oil in a pan."],
["participate","B1","v.","katılmak","All students participated in the project."],
["particularly","B1","adv.","özellikle","I particularly liked the last song."],
["passion","B1","n.","tutku","She has a passion for painting."],
["path","B1","n.","patika, yol","Follow the path through the woods."],
["payment","B1","n.","ödeme","Payment can be made by card."],
["peaceful","B1","adj.","huzurlu; barışçıl","The village is quiet and peaceful."],
["percentage","B1","n.","yüzde, oran","A high percentage of students passed."],
["perfectly","B1","adv.","kusursuzca; tamamen","The jacket fits perfectly."],
["performance","B1","n.","performans; gösteri","The band gave a great performance."],
["personally","B1","adv.","şahsen, kişisel olarak","Personally, I prefer the blue one."],
["persuade","B1","v.","ikna etmek","She persuaded her dad to buy a dog."],
["photographer","B1","n.","fotoğrafçı","The photographer took pictures of the bride."],
["photography","B1","n.","fotoğrafçılık","Photography is my favourite hobby."],
["pin","B1","n., v.","toplu iğne; iliştirmek","Pin the note to the board."],
["pipe","B1","n.","boru; pipo","A water pipe burst in the street."],
["planning","B1","n.","planlama","Good planning saves time."],
["pleasant","B1","adj.","hoş, tatlı","We spent a pleasant evening together."],
["pleasure","B1","n.","zevk, keyif","It's a pleasure to meet you."],
["plenty","B1","pron.","bol bol, çok","We have plenty of time."],
["poem","B1","n.","şiir","She wrote a poem about the sea."],
["poet","B1","n.","şair","The poet read his new work aloud."],
["poetry","B1","n.","şiir (sanatı)","I enjoy reading poetry before bed."],
["poison","B1","n., v.","zehir(lemek)","Some mushrooms contain poison."],
["poisonous","B1","adj.","zehirli","Some snakes are poisonous."],
["policy","B1","n.","politika, ilke","The school has a strict phone policy."],
["political","B1","adj.","politik, siyasi","They discussed political issues."],
["politician","B1","n.","politikacı, siyasetçi","The politician visited our school."],
["politics","B1","n.","siyaset, politika","We don't talk politics at dinner."],
["port","B1","n.","liman","The ship arrived at the port."],
["portrait","B1","n.","portre","The artist painted her portrait."],
["possibly","B1","adv.","belki, muhtemelen","We may possibly move next year."],
["pot","B1","n.","tencere; saksı; kavanoz","The soup is in the pot."],
["pour","B1","v.","dökmek; (yağmur) boşanmak","Pour the milk into the glass."],
["poverty","B1","n.","yoksulluk","Many families live in poverty."],
["powder","B1","n.","toz, pudra","Add a spoon of chilli powder."],
["powerful","B1","adj.","güçlü","The car has a powerful engine."],
["practical","B1","adj.","pratik, kullanışlı; uygulamalı","A small car is practical in the city."],
["pray","B1","v.","dua etmek","They prayed for rain."],
["prayer","B1","n.","dua","She said a short prayer."],
["prediction","B1","n.","tahmin, öngörü","His prediction about the match was right."],
["prepared","B1","adj.","hazır(lıklı)","Be prepared for cold weather."],
["presentation","B1","n.","sunum","I'm giving a presentation tomorrow."],
["press","B1","n., v.","basın; bas(tır)mak","Press the green button."],
["pressure","B1","n.","basınç; baskı","He works well under pressure."],
["pretend","B1","v.","-miş gibi yapmak","The kids pretended to be pirates."],
["previous","B1","adj.","önceki","I liked his previous book more."],
["previously","B1","adv.","daha önce(den)","She previously worked as a nurse."],
["priest","B1","n.","rahip, papaz","The priest spoke softly to the family."],
["primary","B1","adj.","birincil; ilkokul (düzeyi)","Safety is our primary concern."],
["prince","B1","n.","prens","The prince became king at thirty."],
["princess","B1","n.","prenses","The story is about a brave princess."],
["printing","B1","n.","baskı, matbaacılık","The invention of printing changed the world."],
["prisoner","B1","n.","mahkûm, tutsak","The prisoner was released after five years."],
["private","B1","adj.","özel, kişisel","This is a private conversation."],
["producer","B1","n.","yapımcı; üretici","The film producer hired a new director."],
["production","B1","n.","üretim; yapım","Car production increased this year."],
["profession","B1","n.","meslek","Teaching is a rewarding profession."],
["profit","B1","n.","kâr","The shop made a small profit."],
["promote","B1","v.","terfi ettirmek; tanıtmak","She was promoted to manager."],
["proper","B1","adj.","düzgün, uygun","Use the proper tool for the job."],
["properly","B1","adv.","düzgünce, gerektiği gibi","Close the lid properly."],
["property","B1","n.","mülk; özellik","This building is private property."],
["protest","B1","n., v.","protesto (etmek)","Workers protested against low pay."],
["proud","B1","adj.","gururlu","Her parents are proud of her."],
["prove","B1","v.","kanıtlamak","Can you prove that you were there?"],
["punish","B1","v.","cezalandırmak","The teacher punished the noisy students."],
["punishment","B1","n.","ceza","The punishment was too harsh."],
["qualification","B1","n.","nitelik, yeterlilik (belgesi)","What qualifications do you need for this job?"],
["qualified","B1","adj.","nitelikli, ehliyetli","She is a qualified nurse."],
["qualify","B1","v.","hak kazanmak; nitelik kazanmak","Our team qualified for the final."],
["queue","B1","n., v.","kuyruk; sıraya girmek","We queued for an hour for tickets."],
["quit","B1","v.","bırakmak, ayrılmak","He quit his job last month."],
["quotation","B1","n.","alıntı","The essay begins with a quotation."],
["quote","B1","n., v.","alıntı (yapmak)","She quoted a line from the poem."],
["racing","B1","n.","yarış(çılık)","Horse racing is popular here."],
["rare","B1","adj.","nadir, ender","This bird is very rare in Europe."],
["rarely","B1","adv.","nadiren","We rarely eat out on weekdays."],
["reaction","B1","n.","tepki","Her reaction to the gift was lovely."],
["reality","B1","n.","gerçeklik","His dream became a reality."],
["receipt","B1","n.","fiş, makbuz","Keep the receipt in case you return it."],
["recommendation","B1","n.","tavsiye, öneri","I bought the book on her recommendation."],
["reference","B1","n.","referans; atıf","The article includes a list of references."],
["reflect","B1","v.","yansıtmak; düşünmek","The lake reflected the mountains."],
["regularly","B1","adv.","düzenli olarak","Brush your teeth regularly."],
["reject","B1","v.","reddetmek","She rejected the job offer."],
["relate","B1","v.","ilişkilendirmek; bağ kurmak","The two events are closely related."],
["related","B1","adj.","ilgili, bağlantılı; akraba","Stress and illness are often related."],
["relation","B1","n.","ilişki; akraba","Relations between the two countries improved."],
["relative","B1","adj., n.","akraba; göreceli","We visited our relatives in the village."],
["relaxed","B1","adj.","rahatlamış, sakin","I feel relaxed after a holiday."],
["relaxing","B1","adj.","rahatlatıcı, dinlendirici","We had a relaxing day at the beach."],
["release","B1","n., v.","serbest bırakmak; piyasaya çıkarmak","The band releases a new song on Friday."],
["reliable","B1","adj.","güvenilir","My old car is slow but reliable."],
["religion","B1","n.","din","People of many religions live here."],
["religious","B1","adj.","dinî; dindar","It is an important religious festival."],
["remain","B1","v.","kalmak; sürmek","Please remain in your seats."],
["remind","B1","v.","hatırlatmak","Remind me to call my mother."],
["remote","B1","adj.","uzak, ücra; uzaktan","They live in a remote mountain village."],
["rent","B1","n., v.","kira(lamak)","We rented a flat near the centre."],
["repeated","B1","adj.","tekrarlanan","Repeated mistakes are hard to forgive."],
["represent","B1","v.","temsil etmek","She represented her school at the contest."],
["require","B1","v.","gerektirmek; istemek","The game requires two players."],
["reservation","B1","n.","rezervasyon; çekince","I made a reservation for two."],
["resource","B1","n.","kaynak","The library has great online resources."],
["respect","B1","n., v.","saygı (duymak)","Children should respect their elders."],
["responsibility","B1","n.","sorumluluk","Feeding the dog is my responsibility."],
["responsible","B1","adj.","sorumlu","Who is responsible for this mess?"],
["retire","B1","v.","emekli olmak","My father retires next year."],
["retired","B1","adj.","emekli","The retired teacher gives free lessons."],
["revise","B1","v.","tekrar etmek (ders); gözden geçirmek","I'm revising for my history exam."],
["risk","B1","n., v.","risk(e atmak)","There's a risk of rain this evening."],
["robot","B1","n.","robot","A robot cleans the floor at night."],
["roll","B1","n., v.","yuvarlanmak; rulo","The ball rolled under the car."],
["romantic","B1","adj.","romantik","They had a romantic dinner by the sea."],
["rope","B1","n.","halat, ip","Tie the boat with this rope."],
["rough","B1","adj.","pürüzlü; kaba; zorlu","The road is rough and stony."],
["row","B1","n.","sıra, dizi","We sat in the front row."],
["royal","B1","adj.","kraliyetle ilgili","The royal family lives in the palace."],
["rugby","B1","n.","ragbi","Rugby is a tough game."],
["safety","B1","n.","güvenlik, emniyet","Always wear a helmet for safety."],
["sailor","B1","n.","denizci","The old sailor told us sea stories."],
["sand","B1","n.","kum","The children played in the sand."],
["scan","B1","v.","taramak; göz gezdirmek","Scan the text for the key words."],
["scientific","B1","adj.","bilimsel","The claim has no scientific basis."],
["script","B1","n.","senaryo; el yazısı","The actor read the script twice."],
["sculpture","B1","n.","heykel (sanatı)","The garden has a modern sculpture."],
["secondary","B1","adj.","orta (okul); ikincil","She teaches at a secondary school."],
["security","B1","n.","güvenlik","Airport security checked our bags."],
["seed","B1","n.","tohum","Plant the seeds in spring."],
["sensible","B1","adj.","mantıklı, sağduyulu","Wearing boots was a sensible choice."],
["seriously","B1","adv.","ciddi biçimde; cidden","He was seriously hurt in the fall."],
["servant","B1","n.","hizmetçi","The palace had many servants."],
["set","B1","n., v.","ayarlamak; koymak; set, takım","Set the table for dinner, please."],
["setting","B1","n.","ortam; ayar","The hotel has a beautiful mountain setting."],
["sex","B1","n.","cinsiyet; cinsellik","Write your name, age and sex on the form."],
["sexual","B1","adj.","cinsel","The film contains sexual content."],
["sharp","B1","adj.","keskin; sivri; ani","Careful, that knife is sharp."],
["shelf","B1","n.","raf","The cups are on the top shelf."],
["shell","B1","n.","kabuk (deniz/yumurta)","We collected shells on the beach."],
["shine","B1","v.","parlamak","The sun shone all day."],
["shiny","B1","adj.","parlak","He polished the car until it was shiny."],
["shy","B1","adj.","utangaç, çekingen","The shy boy hid behind his mother."],
["sight","B1","n.","görme; manzara, görüntü","The sunset was a beautiful sight."],
["signal","B1","n., v.","sinyal, işaret (vermek)","Wait for the green signal."],
["silent","B1","adj.","sessiz","The room fell silent."],
["silly","B1","adj.","aptalca, saçma","Don't ask silly questions."],
["similarity","B1","n.","benzerlik","There are many similarities between the twins."],
["similarly","B1","adv.","benzer şekilde","Similarly, prices rose in other cities."],
["simply","B1","adv.","sadece; basitçe","Simply press the button to start."],
["sink","B1","v.","batmak; lavabo","The boat sank in the storm."],
["slice","B1","n., v.","dilim(lemek)","Would you like a slice of cake?"],
["slightly","B1","adv.","hafifçe, biraz","I feel slightly better today."],
["smart","B1","adj.","akıllı; şık","That's a smart idea."],
["smooth","B1","adj.","pürüzsüz, düzgün","The baby's skin is so smooth."],
["software","B1","n.","yazılım","The computer needs new software."],
["soil","B1","n.","toprak","Plants grow well in rich soil."],
["solid","B1","adj., n.","katı; sağlam","The table is made of solid wood."],
["southern","B1","adj.","güney(e ait)","They live on the southern coast."],
["specifically","B1","adv.","özellikle, özel olarak","The book is written specifically for beginners."],
["spending","B1","n.","harcama","Family spending rises before holidays."],
["spicy","B1","adj.","baharatlı, acı","I love spicy food."],
["spirit","B1","n.","ruh; moral","The team played with great spirit."],
["spoken","B1","adj.","sözlü, konuşulan","Her spoken English is excellent."],
["stadium","B1","n.","stadyum","The stadium holds fifty thousand fans."],
["staff","B1","n.","personel, kadro","The hotel staff were very helpful."],
["standard","B1","adj., n.","standart","The food here is of a high standard."],
["statistic","B1","n.","istatistik","This statistic surprised everyone."],
["statue","B1","n.","heykel","A statue of the poet stands in the square."],
["stick","B1","n., v.","sopa, çubuk; yapış(tır)mak","Stick the photo on the page."],
["stranger","B1","n.","yabancı, tanımadık kişi","Don't open the door to strangers."],
["strength","B1","n.","güç, kuvvet","Lifting weights builds strength."],
["string","B1","n.","ip, sicim; tel","Tie the box with string."],
["strongly","B1","adv.","şiddetle, kuvvetle","I strongly recommend this book."],
["studio","B1","n.","stüdyo","The band recorded the song in a studio."],
["substance","B1","n.","madde","The bottle contains a dangerous substance."],
["successfully","B1","adv.","başarıyla","She successfully completed the course."],
["sudden","B1","adj.","ani","A sudden noise woke the baby."],
["suffer","B1","v.","acı çekmek; (hastalıktan) mustarip olmak","He suffers from headaches."],
["suitable","B1","adj.","uygun, elverişli","This film is suitable for children."],
["summarize","B1","v.","özetlemek","Summarize the story in five sentences."],
["summary","B1","n.","özet","Write a short summary of the article."],
["supply","B1","n., v.","arz; tedarik (etmek)","The farm supplies milk to the town."],
["supporter","B1","n.","taraftar, destekçi","The supporters sang for their team."],
["surely","B1","adv.","elbette, kuşkusuz","Surely you don't believe that story!"],
["surface","B1","n.","yüzey","Leaves floated on the surface of the water."],
["survive","B1","v.","hayatta kalmak","Camels can survive without water for days."],
["symptom","B1","n.","belirti, semptom","Fever is a symptom of flu."],
["tail","B1","n.","kuyruk","The dog wagged its tail happily."],
["talent","B1","n.","yetenek","She has a talent for music."],
["talented","B1","adj.","yetenekli","He is a talented young actor."],
["tape","B1","n.","bant; kaset","Stick the poster up with tape."],
["tax","B1","n., v.","vergi(lendirmek)","The tax on fuel went up."],
["technical","B1","adj.","teknik","The flight was delayed by a technical problem."],
["technique","B1","n.","teknik, yöntem","The swimmer improved her technique."],
["tend","B1","v.","eğiliminde olmak","I tend to wake up early."],
["tent","B1","n.","çadır","We put up the tent by the river."],
["theirs","B1","pron.","onlarınki","Our garden is small; theirs is huge."],
["theme","B1","n.","tema, konu","Friendship is the main theme of the book."],
["theory","B1","n.","teori, kuram","In theory, the plan should work."],
["therefore","B1","adv.","bu yüzden, dolayısıyla","He was ill and therefore stayed home."],
["though","B1","adv., conj.","gerçi, -e rağmen; yine de","Though it was late, we kept walking."],
["throat","B1","n.","boğaz","I have a sore throat today."],
["throughout","B1","adv., prep.","boyunca, baştan başa","It rained throughout the night."],
["tight","B1","adj.","dar, sıkı","These shoes are too tight."],
["till","B1","conj., prep.","-e kadar","Wait till the rain stops."],
["tin","B1","n.","teneke (kutu); kalay","Open a tin of tomatoes."],
["tiny","B1","adj.","minicik","The baby has tiny fingers."],
["toe","B1","n.","ayak parmağı","I hurt my big toe."],
["tongue","B1","n.","dil (organ)","The doctor looked at my tongue."],
["totally","B1","adv.","tamamen","You're totally right."],
["trade","B1","n., v.","ticaret (yapmak)","The two countries trade with each other."],
["translate","B1","v.","çevirmek, tercüme etmek","Translate this sentence into English."],
["translation","B1","n.","çeviri, tercüme","The translation of the poem is beautiful."],
["treat","B1","v.","davranmak; tedavi etmek; ısmarlamak","Treat others as you want to be treated."],
["treatment","B1","n.","tedavi; muamele","The new treatment works well."],
["trend","B1","n.","eğilim, akım","Short hair is the latest trend."],
["trick","B1","n., v.","numara, hile; kandırmak","The magician showed us a card trick."],
["truth","B1","n.","gerçek, hakikat","Tell me the truth."],
["tube","B1","n.","tüp; boru; metro (Londra)","A tube of toothpaste, please."],
["typically","B1","adv.","tipik olarak, genellikle","Summers here are typically dry."],
["tyre","B1","n.","lastik (araba)","The car has a flat tyre."],
["ugly","B1","adj.","çirkin","The new building is really ugly."],
["unable","B1","adj.","yapamaz, elinden gelmez","I was unable to sleep last night."],
["uncomfortable","B1","adj.","rahatsız (edici)","This chair is very uncomfortable."],
["underwear","B1","n.","iç çamaşırı","Pack enough underwear for the trip."],
["unemployed","B1","adj.","işsiz","He has been unemployed for six months."],
["unemployment","B1","n.","işsizlik","Unemployment fell this year."],
["unfair","B1","adj.","haksız, adaletsiz","The referee's decision was unfair."],
["union","B1","n.","sendika; birlik","The workers joined a union."],
["unless","B1","conj.","-medikçe, olmazsa","We'll be late unless we hurry."],
["unlike","B1","prep.","-in aksine; benzemeyen","Unlike his brother, he is very quiet."],
["unlikely","B1","adj.","olası olmayan, düşük ihtimal","It's unlikely to snow in May."],
["unnecessary","B1","adj.","gereksiz","Cut the unnecessary words from your essay."],
["unpleasant","B1","adj.","nahoş, tatsız","There was an unpleasant smell in the room."],
["update","B1","n., v.","güncelleme(k)","Update the app to the new version."],
["upon","B1","prep.","üzerine, üzerinde","The castle stands upon a hill."],
["upset","B1","adj., v.","üzgün; üzmek","She was upset about the bad news."],
["used","B1","adj.","kullanılmış; alışkın (used to)","He bought a used car."],
["valuable","B1","adj.","değerli","The ring is very valuable."],
["various","B1","adj.","çeşitli","The shop sells various kinds of cheese."],
["version","B1","n.","sürüm, versiyon","This is the new version of the game."],
["victim","B1","n.","kurban, mağdur","The victims of the flood need help."],
["viewer","B1","n.","izleyici","The show has millions of viewers."],
["violent","B1","adj.","şiddetli; şiddet içeren","The film is too violent for children."],
["volunteer","B1","n., v.","gönüllü (olmak)","Volunteers cleaned the beach."],
["vote","B1","n., v.","oy (vermek)","Citizens vote every four years."],
["warn","B1","v.","uyarmak","They warned us about the icy road."],
["warning","B1","n.","uyarı","The sign gives a clear warning."],
["waste","B1","adj., n., v.","israf (etmek); atık","Don't waste water."],
["weapon","B1","n.","silah","The police found the weapon."],
["weigh","B1","v.","tartmak; ağırlığında olmak","The baby weighs four kilos."],
["western","B1","adj.","batı(ya ait)","The western side of the island is wild."],
["whenever","B1","conj.","her ne zaman","Call me whenever you need help."],
["whether","B1","conj.","-ip -mediği; ister ... ister","I don't know whether she is coming."],
["wing","B1","n.","kanat","The bird hurt its wing."],
["within","B1","prep.","içinde (süre/alan)","The doctor will see you within an hour."],
["wonder","B1","n., v.","merak etmek; şaşkınlık; harika","I wonder where she lives."],
["wool","B1","n.","yün","The sweater is made of wool."],
["worldwide","B1","adj., adv.","dünya çapında","The company has offices worldwide."],
["written","B1","adj.","yazılı","We have a written exam on Friday."],
["yard","B1","n.","avlu, bahçe; yarda","The kids play in the yard."],
["youth","B1","n.","gençlik; genç","He spent his youth in a small town."]
];
