// Oxford 5000 B2-C1 vocab: V-Z. Format: [w, lv, pos, tr, ex]
module.exports = [
["vacuum","C1","n.","vakum, boşluk; elektrikli süpürge","His retirement left a vacuum at the top of the firm."],
["vague","C1","adj.","belirsiz, muğlak","She gave only a vague description of the man."],
["valid","B2","adj.","geçerli","Your ticket is valid for three months."],
["validity","C1","n.","geçerlilik","Lawyers questioned the validity of the contract."],
["value","B2","v.","değer vermek; değer biçmek","I value your honest opinion."],
["vanish","C1","v.","gözden kaybolmak, yok olmak","The ship vanished into the fog."],
["variable","C1","adj., n.","değişken","The weather in the hills is highly variable."],
["variation","B2","n.","çeşitlenme, varyasyon; fark","There is wide variation in prices between shops."],
["varied","C1","adj.","çeşitli, farklı farklı","The menu is varied enough for everyone."],
["vary","B2","v.","değişmek, farklılık göstermek","Opening hours vary from branch to branch."],
["vast","B2","adj.","engin, çok geniş","A vast desert stretches beyond the mountains."],
["vein","C1","n.","damar, toplardamar","The nurse found a vein for the injection."],
["venture","C1","n., v.","girişim; cesaret edip gitmek/denemek","Their new venture sells solar lamps."],
["venue","B2","n.","mekân (etkinlik)","The hall is a popular venue for weddings."],
["verbal","C1","adj.","sözlü, sözel","They had a verbal agreement, nothing in writing."],
["verdict","C1","n.","hüküm, jüri kararı","The jury returned a verdict of not guilty."],
["verify","C1","v.","doğrulamak","The bank called to verify the payment."],
["verse","C1","n.","dize, kıta; nazım","She recited a verse from her favourite poem."],
["versus","C1","prep.","karşı (vs.)","Tonight's match is the champions versus the newcomers."],
["vertical","B2","adj.","dikey","The cliff face is almost vertical."],
["very","B2","adj.","ta kendisi, tam da (the very)","This is the very book I was looking for."],
["vessel","C1","n.","gemi; kap; damar","Fishing vessels crowded the small port."],
["veteran","C1","n.","emektar; gazi","The veteran journalist covered five wars."],
["via","B2","prep.","üzerinden, yoluyla","We flew to Tokyo via Istanbul."],
["viable","C1","adj.","uygulanabilir, yaşayabilir","Is the project financially viable?"],
["vibrant","C1","adj.","canlı, hareket dolu","The market is the most vibrant part of town."],
["vice","C1","n.","kötü alışkanlık; ahlaksızlık","Chocolate is my only vice, she joked."],
["vicious","C1","adj.","acımasız, vahşi; kısır (döngü)","Low pay and poor health form a vicious circle."],
["victory","B2","n.","zafer, galibiyet","The team celebrated a famous victory."],
["viewpoint","B2","n.","bakış açısı","Try to see the issue from her viewpoint."],
["villager","C1","n.","köylü, köy sakini","The villagers rebuilt the school themselves."],
["violate","C1","v.","ihlal etmek, çiğnemek","The factory violated safety regulations."],
["violation","C1","n.","ihlal","The court found a violation of basic rights."],
["violence","B2","n.","şiddet","The film contains scenes of violence."],
["virtual","B2","adj.","sanal; fiilen ... sayılan","The museum offers a virtual tour online."],
["virtue","C1","n.","erdem, fazilet; meziyet","Patience is a virtue, as they say."],
["visa","B2","n.","vize","She applied for a student visa."],
["visible","B2","adj.","görünür, görülebilir","The lighthouse is visible from miles away."],
["vision","B2","n.","görme; vizyon, öngörü","The founder had a clear vision for the company."],
["visual","B2","adj.","görsel","The slides add visual interest to the talk."],
["vital","B2","adj.","hayati, yaşamsal","Clean water is vital for the camp."],
["vitamin","B2","n.","vitamin","Oranges are rich in vitamin C."],
["vocal","C1","adj.","sesini yükselten, açık sözlü; vokal","She is a vocal critic of the new road."],
["volume","B2","n.","ses düzeyi; hacim; cilt","Please turn the volume down after midnight."],
["voluntary","B2","adj.","gönüllü; isteğe bağlı","She does voluntary work at the shelter."],
["voting","B2","n.","oy verme, oylama","Voting closes at ten tonight."],
["vow","C1","v.","yemin etmek, ant içmek","He vowed never to borrow money again."],
["vulnerability","C1","n.","savunmasızlık, kırılganlık","The test exposed a vulnerability in the software."],
["vulnerable","C1","adj.","savunmasız, kolay incinir","Newborn animals are vulnerable to the cold."],
["wage","B2","n.","ücret (haftalık/saatlik)","The factory pays a decent weekly wage."],
["wander","B2","v.","başıboş dolaşmak","We wandered through the old town for hours."],
["ward","C1","n.","koğuş, servis (hastane)","The children's ward is on the third floor."],
["warehouse","C1","n.","depo, ambar","The goods are stored in a vast warehouse."],
["warfare","C1","n.","savaş (yöntemi), harp","The book describes medieval siege warfare."],
["warming","B2","n.","ısınma","Global warming is melting the glaciers."],
["warrant","C1","n., v.","arama/tutuklama emri; gerektirmek","Police obtained a warrant to search the flat."],
["warrior","C1","n.","savaşçı","Statues of ancient warriors guard the gate."],
["way","B2","adv.","çok, fazlasıyla (way too)","The soup is way too salty for me."],
["weaken","C1","v.","zayıflatmak, zayıflamak","The illness weakened her for months."],
["weakness","B2","n.","zayıflık; zaaf","Impatience is his greatest weakness."],
["wealth","B2","n.","servet, zenginlik; bolluk","The region's wealth comes from oil."],
["wealthy","B2","adj.","varlıklı, zengin","A wealthy collector bought the painting."],
["weave","C1","v.","dokumak; örmek (hikâye)","The villagers weave carpets by hand."],
["weed","C1","n.","yabani ot","The garden path is full of weeds."],
["weekly","B2","adj.","haftalık","The team holds a weekly planning meeting."],
["weird","B2","adj.","tuhaf, garip","A weird noise came from the attic."],
["welfare","B2","n.","refah; sosyal yardım","The charity protects the welfare of farm animals."],
["well","C1","n.","kuyu","The village draws its water from a deep well."],
["well-being","C1","n.","esenlik, iyilik hâli","Daily exercise improves mental well-being."],
["whatever","C1","adv.","her ne; hiç (olumsuz vurgu)","Order whatever you like; it's my treat."],
["whatsoever","C1","adv.","hiçbir şekilde, asla","There is no evidence whatsoever against her."],
["wheat","B2","n.","buğday","Fields of wheat stretched to the horizon."],
["whereas","B2","conj.","oysa, halbuki","He loves the sea, whereas she prefers mountains."],
["whereby","C1","adv.","ki onunla, aracılığıyla","They signed a deal whereby profits are shared."],
["wherever","B2","conj.","her nerede/nereye","Sit wherever you feel comfortable."],
["whilst","C1","conj.","iken; her ne kadar","Whilst I agree in principle, I have doubts."],
["whip","C1","v.","kamçılamak; çırpmak (krema)","Whip the cream until it forms soft peaks."],
["whisper","B2","n., v.","fısıltı; fısıldamak","She whispered the answer in his ear."],
["whoever","B2","pron.","her kim","Whoever finds the wallet should hand it in."],
["wholly","C1","adv.","tamamen, bütünüyle","The rumour is wholly without foundation."],
["whom","B2","pron.","kim(i/e) (nesne)","To whom should I address the letter?"],
["widely","B2","adv.","yaygın olarak; büyük farkla","The book is widely read in schools."],
["widen","C1","v.","genişletmek, genişlemek","The council plans to widen the narrow bridge."],
["widespread","B2","adj.","yaygın","The storm caused widespread damage."],
["widow","C1","n.","dul (kadın)","The widow kept the farm running alone."],
["width","C1","n.","genişlik, en","Measure the width of the window first."],
["wildlife","B2","n.","yaban hayatı","The reserve protects rare wildlife."],
["willing","B2","adj.","istekli, gönüllü","Are you willing to work at weekends?"],
["willingness","C1","n.","isteklilik, gönüllülük","Her willingness to learn impressed the chef."],
["wind","B2","v.","kıvrılmak, dolanmak; sarmak","The path winds along the cliff edge."],
["wipe","C1","v.","silmek","He wiped the table with a damp cloth."],
["wire","B2","n.","tel, kablo","A loose wire caused the fault."],
["wisdom","B2","n.","bilgelik, hikmet","The old farmer shared his quiet wisdom."],
["wise","B2","adj.","bilge, akıllıca","Saving early was a wise decision."],
["wit","C1","n.","nükte, zekâ","Her speech sparkled with wit."],
["withdraw","B2","v.","çekmek (para); geri çekilmek","He withdrew cash from the machine."],
["withdrawal","C1","n.","çekilme; para çekme; yoksunluk","The army announced its withdrawal from the region."],
["witness","B2","n., v.","tanık; tanık olmak","Two witnesses saw the car jump the lights."],
["workforce","B2","n.","iş gücü","Half the workforce travels in by train."],
["workout","C1","n.","antrenman, egzersiz","She does a short workout before breakfast."],
["workplace","B2","n.","iş yeri","The law improves safety in the workplace."],
["workshop","B2","n.","atölye (çalışması)","The museum runs pottery workshops for children."],
["worm","B2","n.","solucan, kurt","Blackbirds hunt worms on the wet lawn."],
["worse","B2","n.","daha kötüsü","The weather took a turn for the worse."],
["worship","C1","n., v.","ibadet; tapmak","The temple is still a place of worship."],
["worst","B2","n.","en kötüsü","Prepare for the worst and hope for the best."],
["worth","B2","n.","değer","The storm caused millions of pounds' worth of damage."],
["worthwhile","C1","adj.","zahmete değer","Volunteering is a worthwhile use of a gap year."],
["worthy","C1","adj.","layık, değer","The cause is worthy of your support."],
["wound","B2","n., v.","yara; yaralamak","The wound healed without a scar."],
["wrap","B2","v.","sarmak, paketlemek","She wrapped the gift in gold paper."],
["wrist","B2","n.","bilek","He wears his watch on his left wrist."],
["wrong","B2","n.","haksızlık, yanlış","He admitted the wrongs of his past."],
["yell","C1","v.","bağırmak, haykırmak","The coach yelled instructions from the bench."],
["yet","B2","conj.","yine de, ama","The plan was simple, yet it worked perfectly."],
["yield","C1","n., v.","verim; getirmek; boyun eğmek","The orchard yields tons of apples each year."],
["youngster","C1","n.","genç, çocuk","The club trains youngsters from the local estate."],
["zone","B2","n.","bölge, kuşak","Cars are banned from the pedestrian zone."]
];
