// Oxford 5000 B2-C1 vocab: I-J-K. Format: [w, lv, pos, tr, ex]
module.exports = [
["icon","B2","n.","simge, ikon","She became a fashion icon of her generation."],
["id","B2","n.","kimlik (belgesi)","You'll need to show some ID at the entrance."],
["ideal","B2","n.","ideal, ülkü","Equality before the law is a fundamental ideal."],
["identical","B2","adj.","tıpatıp aynı, özdeş","The twins wore identical blue jackets."],
["identification","C1","n.","kimlik tespiti; özdeşleşme","The police asked for identification before letting us in."],
["ideological","C1","adj.","ideolojik","The split in the party was ideological, not personal."],
["ideology","C1","n.","ideoloji","The movement was driven by a strict political ideology."],
["idiot","C1","n.","aptal, salak","I felt like an idiot when I forgot my own number."],
["ignorance","C1","n.","cehalet, bilgisizlik","Fear often grows out of ignorance."],
["illusion","B2","n.","yanılsama, illüzyon","The mirror creates an illusion of space."],
["illustrate","B2","v.","örneklerle açıklamak; resimlemek","A simple chart illustrates the trend clearly."],
["illustration","B2","n.","resimleme, illüstrasyon; örnek","The book contains beautiful hand-drawn illustrations."],
["imagery","C1","n.","imgeler, betimleme","The poem is rich in imagery of the sea."],
["imagination","B2","n.","hayal gücü","Children's games are powered by pure imagination."],
["immense","C1","adj.","çok büyük, muazzam","The project required an immense amount of work."],
["immigration","B2","n.","göç (içe); göçmenlik işlemleri","Immigration has shaped the culture of the city."],
["imminent","C1","adj.","an meselesi, eli kulağında","Dark clouds warned of an imminent storm."],
["immune","B2","adj.","bağışık; etkilenmez","Vaccinated people are largely immune to the disease."],
["impatient","B2","adj.","sabırsız","The passengers grew impatient as the delay continued."],
["implement","B2","v.","uygulamak, yürürlüğe koymak","The school implemented a new attendance policy."],
["implementation","C1","n.","uygulama, yürürlüğe koyma","The implementation of the plan took two years."],
["implication","B2","n.","ima; (olası) sonuç, etki","The new law has serious implications for small firms."],
["imply","B2","v.","ima etmek; anlamına gelmek","Her silence seemed to imply agreement."],
["impose","B2","v.","dayatmak, (vergi/ceza) koymak","The court imposed a heavy fine on the company."],
["impress","B2","v.","etkilemek, hayran bırakmak","The candidate impressed everyone with her answers."],
["impressed","B2","adj.","etkilenmiş","I was impressed by how calm he stayed."],
["imprison","C1","v.","hapsetmek","The journalist was imprisoned for two years."],
["imprisonment","C1","n.","hapis (cezası)","He faces ten years of imprisonment if convicted."],
["inability","C1","n.","yapamama, yetersizlik","His inability to delegate slowed the whole team."],
["inadequate","C1","adj.","yetersiz","The flood defences proved completely inadequate."],
["inappropriate","C1","adj.","uygunsuz, yakışıksız","His joke was inappropriate for a funeral."],
["incentive","B2","n.","teşvik, özendirici","Tax cuts give firms an incentive to invest."],
["inch","B2","n.","inç (2,54 cm)","The water rose several inches overnight."],
["incidence","C1","n.","görülme sıklığı, yaygınlık","The incidence of the disease falls in summer."],
["incident","B2","n.","olay, hadise","Police are investigating an incident at the station."],
["inclined","C1","adj.","eğilimli; meyilli","I'm inclined to agree with your analysis."],
["inclusion","C1","n.","dahil etme/edilme; kapsayıcılık","The inclusion of her name on the list surprised everyone."],
["income","B2","n.","gelir","Families on a low income receive extra support."],
["incorporate","B2","v.","bünyesine katmak, dahil etmek","The design incorporates several safety features."],
["incorrect","B2","adj.","yanlış, hatalı","The address on the parcel was incorrect."],
["increasingly","B2","adv.","giderek daha fazla","Shoppers are increasingly turning to second-hand goods."],
["incur","C1","v.","(masraf/zarar) maruz kalmak, üstlenmek","Late payments incur an extra charge."],
["independence","B2","n.","bağımsızlık","The colony gained its independence in 1960."],
["index","B2","n.","dizin, indeks; gösterge","Look the term up in the index at the back."],
["indication","B2","n.","belirti, işaret","There was no indication that anything was wrong."],
["indicator","C1","n.","gösterge","Unemployment is a key indicator of economic health."],
["indictment","C1","n.","iddianame; (bir şeyin kötülüğünün) kanıtı","The empty playgrounds are a sad indictment of our times."],
["indigenous","C1","adj.","yerli, o topraklara özgü","The park protects plants indigenous to the region."],
["induce","C1","v.","yol açmak; ikna etmek; (doğum) başlatmak","Stress can induce headaches in some people."],
["indulge","C1","v.","kendini şımartmak; (isteğe) boyun eğmek","At weekends she indulges in long, lazy breakfasts."],
["industrial","B2","adj.","endüstriyel, sanayi ile ilgili","The industrial zone lies east of the river."],
["inequality","C1","n.","eşitsizlik","Income inequality has widened over the decade."],
["inevitable","B2","adj.","kaçınılmaz","After such losses, change was inevitable."],
["inevitably","B2","adv.","kaçınılmaz olarak","Inevitably, the cheaper model sold out first."],
["infamous","C1","adj.","adı çıkmış, kötü şöhretli","The area was once infamous for its crime."],
["infant","C1","n.","bebek, küçük çocuk","The clinic monitors the growth of infants."],
["infect","C1","v.","bulaştırmak, enfekte etmek","One sick passenger can infect many others."],
["infection","B2","n.","enfeksiyon","Wash the cut carefully to prevent infection."],
["infer","B2","v.","sonuç çıkarmak, anlam çıkarmak","From her tone, I inferred that she was annoyed."],
["inflation","B2","n.","enflasyon","Inflation rose sharply after the oil shock."],
["inflict","C1","v.","(acı/zarar) vermek, yaşatmak","The storm inflicted severe damage on the coast."],
["influential","C1","adj.","etkili, sözü geçen","She is one of the most influential voices in science."],
["info","B2","n.","bilgi (kısa kullanım)","Check the website for more info about tickets."],
["inform","B2","v.","bilgilendirmek, haber vermek","Please inform us of any change of address."],
["infrastructure","B2","n.","altyapı","The country is investing heavily in transport infrastructure."],
["inhabitant","B2","n.","sakin, oturan","The island has fewer than a hundred inhabitants."],
["inherent","C1","adj.","doğasında olan, içkin","Risk is inherent in every investment."],
["inherit","B2","v.","miras almak","She inherited the farm from her grandfather."],
["inhibit","C1","v.","engellemek, ketlemek","Fear of failure can inhibit creativity."],
["initial","B2","adj.","ilk, başlangıçtaki","My initial reaction was disbelief."],
["initially","B2","adv.","başlangıçta, ilk olarak","Initially the plan seemed too expensive."],
["initiate","C1","v.","başlatmak","The ministry initiated an inquiry into the accident."],
["initiative","B2","n.","girişim; inisiyatif","She showed great initiative in solving the problem."],
["inject","C1","v.","enjekte etmek; (para/canlılık) katmak","The nurse injected the vaccine into his arm."],
["injection","C1","n.","iğne, enjeksiyon","The injection protects against three diseases."],
["injustice","C1","n.","adaletsizlik, haksızlık","They campaigned against injustice in the courts."],
["ink","B2","n.","mürekkep","The printer has run out of ink again."],
["inmate","C1","n.","mahkûm, (kurum) sakini","The prison offers education classes for inmates."],
["inner","B2","adj.","iç, içteki","The inner rooms of the palace were cool and dark."],
["innovation","B2","n.","yenilik, inovasyon","The prize rewards innovation in green technology."],
["innovative","B2","adj.","yenilikçi","The firm is known for its innovative designs."],
["input","B2","n.","girdi; katkı","We'd value your input on the new plan."],
["inquiry","B2","n.","soruşturma; bilgi talebi","The crash led to a public inquiry."],
["insert","B2","v.","sokmak, yerleştirmek, eklemek","Insert the card and enter your code."],
["insertion","C1","n.","ekleme, yerleştirme","The insertion of a new clause delayed the contract."],
["insider","C1","n.","içeriden biri, kurum içi kişi","According to one insider, the deal is nearly done."],
["insight","B2","n.","içgörü, kavrayış","The book offers fresh insight into ancient trade."],
["insist","B2","v.","ısrar etmek","He insisted on paying for everyone's dinner."],
["inspect","C1","v.","denetlemek, incelemek","Officials inspected the factory after the complaints."],
["inspection","C1","n.","denetim, muayene","The bridge passed its annual safety inspection."],
["inspector","B2","n.","müfettiş, denetmen","A ticket inspector boarded the train at noon."],
["inspiration","C1","n.","ilham, esin","The mountains were the inspiration for her paintings."],
["inspire","B2","v.","ilham vermek; cesaretlendirmek","Her courage inspired the whole team."],
["install","B2","v.","kurmak, monte etmek","We installed solar panels on the roof."],
["installation","B2","n.","kurulum; tesis","The installation of the new system took a day."],
["instance","B2","n.","örnek, durum","In most instances, the symptoms disappear quickly."],
["instant","B2","adj.","anında olan, ani","The film was an instant success."],
["instantly","B2","adv.","anında, derhal","She recognised his voice instantly."],
["instinct","C1","n.","içgüdü","Birds build nests by instinct, not by learning."],
["institute","B2","n.","enstitü","She works at a research institute in Geneva."],
["institution","B2","n.","kurum, kuruluş","Universities are among our oldest institutions."],
["institutional","C1","adj.","kurumsal","The report criticised institutional resistance to change."],
["instruct","C1","v.","talimat vermek; öğretmek","The guards were instructed to check every bag."],
["instrumental","C1","adj.","etkili, önemli rol oynayan; enstrümantal","She was instrumental in setting up the charity."],
["insufficient","C1","adj.","yetersiz","The project failed because of insufficient funding."],
["insult","C1","n., v.","hakaret; hakaret etmek","He took the remark as a personal insult."],
["insurance","B2","n.","sigorta","Travel insurance covered the cost of the lost bag."],
["intact","C1","adj.","sağlam, bozulmamış, el değmemiş","Amazingly, the vase survived the move intact."],
["intake","C1","n.","alım (gıda/öğrenci/hava)","Doctors advised him to reduce his salt intake."],
["integral","C1","adj.","ayrılmaz, asli","Music is an integral part of the ceremony."],
["integrate","B2","v.","bütünleştirmek; uyum sağlamak","The app integrates maps with public transport times."],
["integrated","C1","adj.","entegre, bütünleşik","The city has an integrated network of buses and trams."],
["integration","C1","n.","bütünleşme, entegrasyon","The course supports the integration of new arrivals."],
["integrity","C1","n.","dürüstlük; bütünlük","No one ever questioned her integrity."],
["intellectual","B2","adj., n.","entelektüel, zihinsel; aydın","Chess is a demanding intellectual game."],
["intended","B2","adj.","amaçlanan, kasıtlı","The message reached a far wider audience than intended."],
["intense","B2","adj.","yoğun, şiddetli","The heat at midday was intense."],
["intensify","C1","v.","yoğunlaştırmak, şiddetlenmek","The search intensified as night fell."],
["intensity","C1","n.","yoğunluk, şiddet","The intensity of the storm surprised forecasters."],
["intensive","C1","adj.","yoğun(laştırılmış)","She took an intensive course in Spanish."],
["intent","C1","n.","niyet, kasıt","He denied any intent to deceive the buyers."],
["interact","B2","v.","etkileşimde bulunmak","The nursery lets children interact with animals safely."],
["interaction","B2","n.","etkileşim","Face-to-face interaction is hard to replace."],
["interactive","C1","adj.","etkileşimli, interaktif","The museum is full of interactive exhibits."],
["interface","C1","n.","arayüz","The app's interface is clean and easy to learn."],
["interfere","C1","v.","karışmak, müdahale etmek","Don't let work interfere with your sleep."],
["interference","C1","n.","müdahale; parazit","The referee complained about interference from the crowd."],
["interim","C1","adj.","geçici, ara (dönem)","An interim manager will run the office until June."],
["interior","C1","adj., n.","iç; iç mekân","The car's interior smelled of new leather."],
["intermediate","C1","adj.","orta düzey(de)","The class is aimed at intermediate learners."],
["internal","B2","adj.","iç, dahili","The report was for internal use only."],
["interpret","B2","v.","yorumlamak; çevirmenlik yapmak","Each reader interprets the poem differently."],
["interpretation","B2","n.","yorum(lama)","The law is open to more than one interpretation."],
["interrupt","B2","v.","sözünü kesmek, yarıda kesmek","Please don't interrupt while she's explaining."],
["interval","B2","n.","aralık; ara","Trains leave at twenty-minute intervals."],
["intervene","C1","v.","araya girmek, müdahale etmek","A teacher intervened to stop the argument."],
["intervention","C1","n.","müdahale","Early intervention can prevent serious illness."],
["intimate","C1","adj.","samimi, yakın; mahrem","The restaurant has a quiet, intimate atmosphere."],
["intriguing","C1","adj.","merak uyandıran, ilginç","The letter contained an intriguing suggestion."],
["invade","B2","v.","istila etmek; (mahremiyete) izinsiz girmek","The army invaded the neighbouring country at dawn."],
["invasion","B2","n.","istila, işgal","The invasion was condemned around the world."],
["investigation","B2","n.","soruşturma, araştırma","The investigation lasted nearly three years."],
["investigator","C1","n.","soruşturmacı, müfettiş","Investigators examined the wreckage for clues."],
["investment","B2","n.","yatırım","Education is the best investment a country can make."],
["investor","B2","n.","yatırımcı","Small investors lost money when the bank failed."],
["invisible","C1","adj.","görünmez","The gas is invisible but highly dangerous."],
["invoke","C1","v.","(yasa/hak) dayanak göstermek; çağırmak","The lawyer invoked an old law to defend her client."],
["involvement","C1","n.","katılım, dahil olma","He denied any involvement in the robbery."],
["ironic","C1","adj.","ironik, alaycı","It's ironic that the fire station burned down."],
["ironically","C1","adv.","ironik biçimde","Ironically, the diet book made her hungrier."],
["irony","C1","n.","ironi","The irony of his remark was lost on no one."],
["irrelevant","C1","adj.","konu dışı, alakasız","Personal taste is irrelevant to the legal question."],
["isolate","B2","v.","yalıtmak, izole etmek; ayırmak","Scientists isolated the virus within weeks."],
["isolated","B2","adj.","ücra, yalıtılmış; münferit","They live in an isolated farmhouse in the hills."],
["isolation","C1","n.","yalıtılmışlık, yalnızlık; izolasyon","Working from home can lead to social isolation."],
["issue","B2","v.","yayımlamak, vermek, çıkarmak","The ministry issued a warning about the heatwave."],
["jail","B2","n., v.","hapishane; hapse atmak","He spent three months in jail for fraud."],
["jet","B2","n.","jet (uçağı); fıskiye","The team travelled by private jet."],
["joint","B2","adj., n.","ortak; eklem","The project is a joint effort between two universities."],
["journalism","B2","n.","gazetecilik","She studied journalism before joining the paper."],
["joy","B2","n.","sevinç, neşe","The birth of the baby brought great joy."],
["judgement","B2","n.","yargı, karar; muhakeme","Use your own judgement when choosing a route."],
["judicial","C1","adj.","yargısal, adli","The case is now under judicial review."],
["junction","C1","n.","kavşak","Turn left at the next junction."],
["junior","B2","adj.","kıdemsiz; genç","She started as a junior reporter on a local paper."],
["jurisdiction","C1","n.","yargı yetkisi","The court has no jurisdiction over foreign companies."],
["jury","B2","n.","jüri","The jury reached a verdict in two hours."],
["just","C1","adj.","adil, haklı","It was a just punishment for such a crime."],
["justice","B2","n.","adalet","The families are still waiting for justice."],
["justification","C1","n.","gerekçe, haklı neden","There is no justification for such cruelty."],
["justify","B2","v.","haklı çıkarmak, gerekçelendirmek","How can you justify spending so much on shoes?"],
["kidnap","C1","v.","(adam) kaçırmak","The gang planned to kidnap a wealthy businessman."],
["kidney","C1","n.","böbrek","He donated a kidney to his brother."],
["kingdom","C1","n.","krallık; âlem","The kingdom was ruled by a young queen."],
["kit","B2","n.","takım, set; donanım","Keep a first-aid kit in the car."]
];
