// Oxford 5000 B2-C1 vocab: T-U. Format: [w, lv, pos, tr, ex]
module.exports = [
["tackle","B2","n., v.","müdahale (futbol); ele almak, üstüne gitmek","The city is finally tackling its traffic problem."],
["tactic","C1","n.","taktik","Delaying the talks was a deliberate tactic."],
["tactical","C1","adj.","taktiksel","The coach made a tactical change at half-time."],
["tag","B2","n., v.","etiket; etiketlemek","Each plant in the garden has a name tag."],
["tale","B2","n.","öykü, masal","Grandfather told tales of his sailing days."],
["tank","B2","n.","tank; depo","The fish tank needs cleaning."],
["tap","B2","n., v.","musluk; hafifçe vurmak","Someone tapped me on the shoulder."],
["target","B2","v.","hedeflemek, hedef almak","The campaign targets first-time voters."],
["taxpayer","C1","n.","vergi mükellefi","The stadium was built at taxpayers' expense."],
["tear","B2","n., v.","gözyaşı; yırtmak","Be careful not to tear the wrapping paper."],
["technological","B2","adj.","teknolojik","Technological change has transformed farming."],
["teens","B2","n.","gençlik yılları (13-19)","She wrote her first novel in her teens."],
["temple","B2","n.","tapınak; şakak","The ancient temple stands on a hilltop."],
["temporarily","B2","adv.","geçici olarak","The bridge is temporarily closed for repairs."],
["temporary","B2","adj.","geçici","They found temporary accommodation near the station."],
["tempt","C1","v.","ayartmak, cezbetmek","The discount tempted me to buy two."],
["tenant","C1","n.","kiracı","The new tenants moved in last weekend."],
["tendency","B2","n.","eğilim","He has a tendency to interrupt people."],
["tender","C1","adj.","şefkatli; hassas; yumuşak (et)","Cook the meat slowly until it is tender."],
["tension","B2","n.","gerginlik, gerilim","You could feel the tension in the courtroom."],
["tenure","C1","n.","görev süresi; kadro","Crime fell during her tenure as mayor."],
["term","B2","v.","adlandırmak, nitelemek","The plan was termed a failure by critics."],
["terminal","B2","adj., n.","terminal; ölümcül (hastalık)","The flight leaves from the new terminal."],
["terminate","C1","v.","sona erdirmek, feshetmek","Either side may terminate the contract with notice."],
["terms","B2","n.","şartlar, koşullar; ifadeler","Read the terms of the agreement carefully."],
["terrain","C1","n.","arazi","The jeep handles rough terrain easily."],
["terribly","B2","adv.","son derece; berbat biçimde","I'm terribly sorry for the confusion."],
["terrific","C1","adj.","müthiş, harika","The band gave a terrific performance."],
["terrify","B2","v.","dehşete düşürmek","Thunder terrifies our old dog."],
["territory","B2","n.","toprak, bölge; alan","The birds defend their territory fiercely."],
["terror","B2","n.","dehşet, terör","The children fled in terror from the dog."],
["terrorism","B2","n.","terörizm","The summit discussed the fight against terrorism."],
["terrorist","B2","n.","terörist","The terrorists were caught before the attack."],
["testify","C1","v.","tanıklık etmek","Three witnesses testified against the driver."],
["testimony","C1","n.","tanıklık, ifade; kanıt","Her testimony convinced the jury."],
["testing","B2","n.","test etme, deneme","The drug is still undergoing clinical testing."],
["textbook","B2","n.","ders kitabı","The textbook explains each rule with examples."],
["texture","C1","n.","doku","The cake has a light, airy texture."],
["thankfully","C1","adv.","neyse ki, çok şükür","Thankfully, no one was hurt in the fire."],
["theatrical","C1","adj.","tiyatroyla ilgili; yapmacık, gösterişli","He made a theatrical bow as we applauded."],
["theft","B2","n.","hırsızlık","Car theft has fallen in the area."],
["theology","C1","n.","ilahiyat, teoloji","He studied theology before becoming a teacher."],
["theoretical","C1","adj.","kuramsal, teorik","The course mixes theoretical study with practice."],
["therapist","B2","n.","terapist","A speech therapist works with the children weekly."],
["therapy","B2","n.","terapi, tedavi","Physical therapy helped her walk again."],
["thereafter","C1","adv.","ondan sonra, akabinde","He retired in May and moved abroad shortly thereafter."],
["thereby","C1","adv.","böylece, bu suretle","The dam burst, thereby flooding the valley."],
["thesis","B2","n.","tez","She is writing her thesis on coastal erosion."],
["thorough","B2","adj.","kapsamlı, titiz","The mechanic gave the car a thorough check."],
["thoroughly","B2","adv.","iyice, tamamen","Wash the vegetables thoroughly before cooking."],
["thought-provoking","C1","adj.","düşündürücü","The film asks thought-provoking questions about fame."],
["thoughtful","C1","adj.","düşünceli; dalgın","It was thoughtful of you to bring flowers."],
["thread","C1","n.","iplik; (tartışma) konu zinciri","I lost the thread of his long argument."],
["threat","B2","n.","tehdit","Rising seas are a threat to the island."],
["threaten","B2","v.","tehdit etmek","The storm threatened to delay the harvest."],
["threshold","C1","n.","eşik","Her income is just below the tax threshold."],
["thrilled","C1","adj.","çok heyecanlı, sevinçten uçan","We were thrilled to hear about the baby."],
["thrive","C1","v.","gelişmek, serpilmek","Olive trees thrive in this dry climate."],
["thumb","B2","n.","başparmak","He gave a thumbs-up through the window."],
["thus","B2","adv.","böylece; bu nedenle","The factory closed, thus ending an era."],
["tide","C1","n.","gelgit; akış (değişim)","Check the tide before walking to the island."],
["tighten","C1","v.","sıkmak, sıkılaştırmak","The bank tightened its rules on lending."],
["timber","C1","n.","kereste","The cabin is built of local timber."],
["time","B2","v.","zamanlamak","She timed her arrival to miss the traffic."],
["timely","C1","adj.","zamanında, yerinde","A timely warning prevented the crash."],
["timing","B2","n.","zamanlama","The timing of the announcement was unfortunate."],
["tissue","B2","n.","doku; kâğıt mendil","The test examines a small sample of tissue."],
["title","B2","v.","adlandırmak, başlık koymak","The exhibition is titled 'Hidden Cities'."],
["tobacco","C1","n.","tütün","The tax on tobacco rose again this year."],
["tolerance","C1","n.","hoşgörü; tolerans, dayanma sınırı","The school teaches tolerance of different views."],
["tolerate","C1","v.","hoş görmek; katlanmak; dayanmak","The plant tolerates both heat and drought."],
["toll","C1","n.","geçiş ücreti; (death toll) can kaybı","The earthquake's toll rose through the night."],
["ton","B2","n.","ton (ölçü)","The ship carries thousands of tons of grain."],
["tone","B2","n.","ton (ses/renk); üslup","I could tell from her tone that she was upset."],
["tonne","B2","n.","ton (1000 kg)","The recycling plant handles fifty tonnes a day."],
["top","C1","v.","aşmak, üstüne çıkmak; başında olmak","Donations topped a million pounds."],
["torture","C1","n., v.","işkence; işkence etmek","The report documented the torture of prisoners."],
["toss","C1","v.","fırlatmak, atmak; yazı tura atmak","He tossed the keys onto the table."],
["total","C1","v.","toplamı ... olmak","Losses totalled nearly two million."],
["tough","B2","adj.","zor, çetin; dayanıklı; sert","It was a tough decision to sell the farm."],
["tournament","B2","n.","turnuva","Sixteen teams entered the chess tournament."],
["toxic","C1","adj.","zehirli, toksik","The factory released toxic fumes into the air."],
["trace","B2","n., v.","iz; izini sürmek","Police traced the call to a phone box."],
["track","B2","v.","izlemek, takip etmek","The app tracks your daily steps."],
["trademark","C1","n.","ticari marka; alamet-i farika","The logo is a registered trademark."],
["trading","B2","n.","ticaret, alım satım","Trading on the exchange was suspended briefly."],
["tragedy","B2","n.","trajedi, facia","The fire was a tragedy for the whole village."],
["tragic","B2","adj.","trajik, acıklı","He died in a tragic climbing accident."],
["trail","C1","n., v.","patika; iz; peşinden sürüklenmek; geride olmak","The trail winds through the pine forest."],
["trailer","C1","n.","römork; fragman","The trailer made the film look better than it was."],
["trait","B2","n.","özellik, karakter çizgisi","Patience is a useful trait in a teacher."],
["transaction","C1","n.","işlem (ticari)","Each transaction appears on your statement."],
["transcript","C1","n.","tutanak, çözümleme (kayıt); not dökümü","A transcript of the interview was published."],
["transfer","B2","n., v.","aktarma, transfer; aktarmak","She transferred the money to her son's account."],
["transform","B2","v.","dönüştürmek","The railway transformed the small town."],
["transformation","C1","n.","dönüşüm","The district has undergone a complete transformation."],
["transit","C1","n.","transit, geçiş; toplu taşıma","The goods were damaged in transit."],
["transition","B2","n.","geçiş (süreci)","The transition to clean energy will take decades."],
["transmission","C1","n.","iletim, bulaşma; şanzıman","Masks reduce the transmission of the virus."],
["transmit","B2","v.","iletmek; bulaştırmak; yayınlamak","The signal is transmitted via satellite."],
["transparency","C1","n.","şeffaflık","Voters demanded transparency about party funding."],
["transparent","C1","adj.","şeffaf, saydam; apaçık","The jellyfish is almost completely transparent."],
["transportation","B2","n.","ulaşım, taşımacılık","Public transportation is free for children."],
["trap","B2","n., v.","tuzak; kapana kıstırmak","Miners were trapped underground for two days."],
["trauma","C1","n.","travma","Therapy helped her recover from the trauma."],
["treasure","B2","n.","hazine","Divers found treasure in the sunken ship."],
["treaty","C1","n.","antlaşma","The two nations signed a peace treaty."],
["tremendous","C1","adj.","muazzam, müthiş","The play was a tremendous success."],
["trial","B2","n.","duruşma, yargılama; deneme","The trial lasted six weeks."],
["tribal","C1","adj.","kabileye özgü","Tribal elders settled the dispute."],
["tribe","B2","n.","kabile, aşiret","The tribe has lived by the river for centuries."],
["tribunal","C1","n.","mahkeme (özel), yargı kurulu","An employment tribunal heard her case."],
["tribute","C1","n.","övgü, anma; haraç","The concert was a tribute to the late singer."],
["trigger","B2","n., v.","tetik; tetiklemek","Dust can trigger an asthma attack."],
["trillion","B2","num.","trilyon","Global debt now measures in the trillions."],
["trio","C1","n.","üçlü","A jazz trio played in the corner of the café."],
["trip","B2","v.","tökezlemek; çelme takmak","She tripped over the loose carpet."],
["triumph","C1","n.","zafer, büyük başarı","The bridge is a triumph of engineering."],
["troop","B2","n.","birlik (asker), grup","Troops were sent to guard the border."],
["trophy","C1","n.","kupa, ödül","The captain lifted the trophy to wild cheers."],
["tropical","B2","adj.","tropikal","Tropical storms are common in late summer."],
["trouble","B2","v.","rahatsız etmek; zahmet vermek","Sorry to trouble you, but is this seat free?"],
["troubled","C1","adj.","sorunlu, sıkıntılı","He had a troubled childhood but a calm old age."],
["truly","B2","adv.","gerçekten, hakikaten","It was a truly unforgettable evening."],
["trust","B2","n., v.","güven; güvenmek","It takes years to build trust and seconds to lose it."],
["trustee","C1","n.","mütevelli, kayyum","The trustees manage the charity's funds."],
["try","B2","n.","deneme","It's worth a try, even if we fail."],
["tsunami","B2","n.","tsunami","The tsunami destroyed villages along the coast."],
["tuition","C1","n.","öğrenim ücreti; özel ders","Tuition fees rise again next year."],
["tune","B2","n.","ezgi, melodi","He whistled a cheerful tune."],
["tunnel","B2","n.","tünel","The train entered a long mountain tunnel."],
["turnout","C1","n.","katılım (seçim/etkinlik)","Voter turnout reached a record high."],
["turnover","C1","n.","ciro; personel devri","The shop's annual turnover doubled."],
["twist","C1","n., v.","bükme; beklenmedik gelişme; burkmak","The story ends with a clever twist."],
["ultimate","B2","adj.","nihai; en üst düzey","Their ultimate goal is a cure for the disease."],
["ultimately","B2","adv.","sonuçta, en nihayetinde","Ultimately, the choice is yours."],
["unacceptable","B2","adj.","kabul edilemez","Such rudeness is simply unacceptable."],
["uncertainty","B2","n.","belirsizlik","Uncertainty about prices delayed many purchases."],
["unconscious","B2","adj.","baygın; bilinçsiz, farkında olmayan","The fall knocked him unconscious."],
["undergo","B2","v.","geçirmek (süreç), maruz kalmak","The airport is undergoing major renovation."],
["undergraduate","C1","n.","lisans öğrencisi","The library reserves a floor for undergraduates."],
["underlying","C1","adj.","altta yatan","Stress was the underlying cause of his illness."],
["undermine","C1","v.","baltalamak, zayıflatmak","Constant criticism undermines confidence."],
["undertake","B2","v.","üstlenmek; taahhüt etmek","The firm undertook a study of local traffic."],
["undoubtedly","C1","adv.","şüphesiz, hiç kuşkusuz","She is undoubtedly the best player on the team."],
["unexpected","B2","adj.","beklenmedik","An unexpected guest arrived at dinner time."],
["unfold","B2","v.","açılmak; gözler önüne serilmek","The drama unfolded live on television."],
["unfortunate","B2","adj.","talihsiz, şanssız","An unfortunate error delayed the payment."],
["unify","C1","v.","birleştirmek","The new currency helped unify the region's markets."],
["unique","B2","adj.","eşsiz, benzersiz; özgü","Each fingerprint is unique."],
["unite","B2","v.","birleşmek, birleştirmek","The crisis united the rival parties."],
["unity","B2","n.","birlik, bütünlük","The speech called for national unity."],
["universal","B2","adj.","evrensel; herkese ait","The desire for respect is universal."],
["universe","B2","n.","evren","The universe is expanding faster than expected."],
["unknown","B2","adj.","bilinmeyen, meçhul","The poem's author remains unknown."],
["unprecedented","C1","adj.","eşi görülmemiş, emsalsiz","The heatwave was unprecedented in recorded history."],
["unveil","C1","v.","tanıtmak (örtüsünü kaldırmak), açıklamak","The mayor unveiled plans for a new park."],
["upcoming","C1","adj.","yaklaşan, gelecek olan","Tickets for the upcoming tour sold out fast."],
["upgrade","C1","n., v.","yükseltme; yükseltmek","We upgraded the office computers last month."],
["uphold","C1","v.","(kararı) onamak; (ilkeyi) savunmak","The appeal court upheld the original ruling."],
["upper","B2","adj.","üst, yukarıdaki","The upper floors have the best views."],
["upwards","B2","adv.","yukarı doğru","House prices continue to move upwards."],
["urban","B2","adj.","kentsel, şehirle ilgili","Urban life can be noisy and crowded."],
["urge","B2","v.","ısrarla teşvik etmek; çağrıda bulunmak","Doctors urge patients to book check-ups early."],
["urgent","B2","adj.","acil","She received an urgent message from home."],
["usage","B2","n.","kullanım","Water usage rises sharply in summer."],
["useless","B2","adj.","işe yaramaz, faydasız","The map was useless without street names."],
["utility","C1","n.","kamu hizmeti (elektrik/su); fayda","The bill covers all utilities except internet."],
["utilize","C1","v.","yararlanmak, kullanmak","The barn was utilized as a temporary clinic."],
["utterly","C1","adv.","tamamen, son derece","The plan was utterly impractical."]
];
