// Oxford 3000 B2 vocab + a-f C1 gap-fill. Format: [w, lv, pos, tr, ex]
module.exports = [
["abandon","B2","v.","terk etmek, vazgeçmek","The crew abandoned the sinking ship."],
["absolute","B2","adj.","mutlak, kesin","The room was in absolute silence."],
["abundance","C1","n.","bolluk","The island has an abundance of fresh fruit."],
["accelerate","C1","v.","hızlan(dır)mak","The car accelerated onto the motorway."],
["accent","B2","n.","aksan, şive","She speaks English with a French accent."],
["acceptable","B2","adj.","kabul edilebilir","Such behaviour is not acceptable here."],
["accompany","B2","v.","eşlik etmek","Children must be accompanied by an adult."],
["accordance","C1","n.","uyum (in accordance with)","Act in accordance with the safety rules."],
["accurate","B2","adj.","doğru, isabetli, kesin","The report gives an accurate picture of events."],
["accuse","B2","v.","suçlamak","They accused him of stealing the money."],
["acknowledge","B2","v.","kabul etmek, teslim etmek; alındığını bildirmek","She acknowledged that she had been wrong."],
["acquire","B2","v.","edinmek, kazanmak","He acquired a taste for olives abroad."],
["actual","B2","adj.","gerçek, asıl","The actual cost was higher than the estimate."],
["adapt","B2","v.","uyum sağlamak; uyarlamak","Animals adapt to their environment."],
["additional","B2","adj.","ek, ilave","There is an additional charge for luggage."],
["administration","B2","n.","yönetim, idare","The new administration promised reforms."],
["adopt","B2","v.","benimsemek; evlat edinmek","The school adopted a new teaching method."],
["advance","B2","adj., n., v.","ilerleme(k); önceden (in advance)","Book your tickets in advance."],
["affair","B2","n.","mesele, iş; ilişki","The wedding was a quiet family affair."],
["afterwards","B2","adv.","sonrasında, daha sonra","We watched the film and went for pizza afterwards."],
["agency","B2","n.","ajans, acente; kurum","She works for a travel agency."],
["agenda","B2","n.","gündem","The first item on the agenda is the budget."],
["aggressive","B2","adj.","saldırgan; agresif","The dog became aggressive towards strangers."],
["aid","B2","n., v.","yardım (etmek)","The charity sends aid to flood victims."],
["aircraft","B2","n.","hava taşıtı, uçak","The aircraft landed safely despite the fog."],
["albeit","C1","conj.","gerçi, her ne kadar","He accepted the offer, albeit with some doubts."],
["alter","B2","v.","değiştirmek","We had to alter our travel plans."],
["aluminium","C1","n.","alüminyum","The frame is made of light aluminium."],
["ambulance","B2","n.","ambulans","The ambulance arrived within minutes."],
["angel","C1","n.","melek","The child sang like an angel."],
["anger","B2","n.","öfke, kızgınlık","He could not hide his anger."],
["angle","B2","n.","açı","Look at the problem from a different angle."],
["anniversary","B2","n.","yıl dönümü","Today is their tenth wedding anniversary."],
["annual","B2","adj.","yıllık","The annual meeting takes place in May."],
["anxious","B2","adj.","kaygılı, endişeli","She felt anxious before the results came out."],
["apparent","B2","adj.","görünen, açık, belirgin","The reason for the delay soon became apparent."],
["apparently","B2","adv.","görünüşe göre, anlaşılan","Apparently, the meeting has been cancelled."],
["appeal","B2","n., v.","çekicilik; çağrı; temyiz; cazip gelmek","The idea of working abroad appeals to me."],
["approach","B2","n., v.","yaklaşım; yaklaşmak","We need a fresh approach to the problem."],
["appropriate","B2","adj.","uygun, yerinde","Wear clothes appropriate for the weather."],
["approval","B2","n.","onay","The plan needs the committee's approval."],
["approve","B2","v.","onaylamak; uygun bulmak","Her parents approved of her choice."],
["arguably","C1","adv.","tartışmasız denebilecek şekilde, muhtemelen","He is arguably the best player of his generation."],
["arise","B2","v.","ortaya çıkmak, doğmak","Problems arise when people don't communicate."],
["armed","B2","adj.","silahlı","Armed guards stood at the entrance."],
["arms","B2","n.","silahlar","The treaty limits the sale of arms."],
["artificial","B2","adj.","yapay","The drink contains no artificial colours."],
["artistic","B2","adj.","sanatsal; sanatçı ruhlu","The film is an artistic success."],
["ashamed","B2","adj.","utanmış, mahcup","He was ashamed of his rude behaviour."],
["aside","B2","adv.","bir kenara","She set some money aside for the holidays."],
["aspect","B2","n.","yön, boyut, açı","Cost is only one aspect of the problem."],
["assess","B2","v.","değerlendirmek","Teachers assess students' progress each term."],
["assessment","B2","n.","değerlendirme","The doctor made a quick assessment of the injury."],
["associate","B2","v.","ilişkilendirmek, bağdaştırmak","People associate summer with holidays."],
["associated","B2","adj.","ilişkili, bağlantılı","Smoking is associated with many diseases."],
["association","B2","n.","dernek, birlik; çağrışım","She joined the local tennis association."],
["assume","B2","v.","varsaymak; üstlenmek","I assumed you knew about the change."],
["attempt","B2","n., v.","girişim, deneme; kalkışmak","His first attempt at skiing ended in a fall."],
["attorney","C1","n.","avukat (Amerikan İng.)","The attorney advised her client to remain silent."],
["automatic","B2","adj.","otomatik","The doors are automatic."],
["automatically","B2","adv.","otomatik olarak; kendiliğinden","The lights turn off automatically at midnight."],
["bacteria","B2","n.","bakteriler","Some bacteria are good for digestion."],
["balloon","B2","n.","balon","The children let go of their balloons."],
["barrier","B2","n.","bariyer, engel","Language is no longer a barrier for her."],
["basically","B2","adv.","temel olarak, esasen","Basically, we have two choices."],
["beg","B2","v.","yalvarmak; dilenmek","The boy begged his parents for a dog."],
["being","B2","n.","varlık; olma","Human beings need each other."],
["bent","B2","adj.","eğri, bükülmüş","The old fork is bent."],
["bet","B2","n., v.","bahis; bahse girmek","I bet it will rain tomorrow."],
["beyond","B2","adv., prep.","ötesinde, ötede","The village lies just beyond the hills."],
["bitter","B2","adj.","acı (tat); küskün; sert (soğuk)","The coffee has a bitter taste."],
["blame","B2","n., v.","suçlamak; suç, kabahat","Don't blame me for the mistake."],
["blind","B2","adj.","kör, görme engelli","The charity trains dogs for blind people."],
["bond","B2","n.","bağ; tahvil","There is a strong bond between the twins."],
["breast","B2","n.","göğüs, meme","Doctors recommend regular breast checks."],
["brief","B2","adj.","kısa, öz","We had a brief meeting before lunch."],
["broad","B2","adj.","geniş","He has broad shoulders."],
["broadcast","B2","n., v.","yayın(lamak)","The match will be broadcast live."],
["budget","B2","n.","bütçe","We planned the trip on a small budget."],
["bullet","B2","n.","kurşun, mermi","The bullet hit the wall."],
["bunch","B2","n.","demet, salkım; grup","He bought a bunch of flowers."],
["bush","B2","n.","çalı(lık)","A rabbit hid under the bush."],
["cable","B2","n.","kablo","The cable connects the screen to the computer."],
["calculate","B2","v.","hesaplamak","Calculate the total cost of the trip."],
["cancel","B2","v.","iptal etmek","The flight was cancelled because of snow."],
["cancer","B2","n.","kanser","Early treatment of cancer saves lives."],
["capable","B2","adj.","yetenekli, yapabilir","She is capable of solving this alone."],
["capacity","B2","n.","kapasite","The hall has a capacity of five hundred."],
["capture","B2","n., v.","yakalamak, ele geçirmek","The photo captures the beauty of the lake."],
["cast","B2","n., v.","oyuncu kadrosu; atmak; (oy) kullanmak","The film has a brilliant cast."],
["catalogue","C1","n.","katalog","The museum published a catalogue of the exhibition."],
["cell","B2","n.","hücre","The human body has trillions of cells."],
["certificate","B2","n.","sertifika, belge","She received a certificate at the end of the course."],
["chairman","B2","n.","başkan (kurul)","The chairman opened the meeting."],
["characteristic","B2","adj., n.","özellik; karakteristik","Patience is a characteristic of good teachers."],
["chief","B2","adj., n.","baş, ana; şef","The chief reason for moving was the job."],
["circumstance","B2","n.","koşul, durum","Under no circumstances open this door."],
["cite","B2","v.","alıntılamak; örnek göstermek","The author cites several recent studies."],
["citizen","B2","n.","vatandaş, yurttaş","Every citizen has the right to vote."],
["civil","B2","adj.","sivil; medeni; nazik","The country suffered a long civil war."],
["classic","B2","adj., n.","klasik","The film is a classic of cinema."],
["clerk","B2","n.","memur, kâtip","The clerk stamped my documents."],
["closely","B2","adv.","yakından; sıkı sıkıya","The police watched the building closely."],
["collapse","B2","n., v.","çökmek; çöküş","The old bridge collapsed in the flood."],
["colourful","B2","adj.","renkli, rengârenk","The market is full of colourful stalls."],
["combination","B2","n.","kombinasyon, birleşim","The dish is a combination of rice and spices."],
["comfort","B2","n., v.","konfor, rahatlık; teselli etmek","She comforted the crying child."],
["command","B2","n., v.","komut(a etmek), emir","The general gave the command to advance."],
["commission","B2","n., v.","komisyon; sipariş etmek","The artist was commissioned to paint a portrait."],
["commitment","B2","n.","bağlılık, taahhüt","Learning a language requires commitment."],
["committee","B2","n.","komite, kurul","The committee meets every Tuesday."],
["commonly","B2","adv.","yaygın olarak","This plant is commonly found near rivers."],
["complicated","B2","adj.","karmaşık","The instructions are too complicated."],
["component","B2","n.","bileşen, parça","Trust is a key component of friendship."],
["concentration","B2","n.","konsantrasyon, yoğunlaşma","Chess requires deep concentration."],
["concept","B2","n.","kavram","The concept of time is hard to explain."],
["concern","B2","n., v.","endişe; ilgilendirmek","Safety is our main concern."],
["concerned","B2","adj.","endişeli; ilgili","Parents are concerned about screen time."],
["conduct","B2","n., v.","yürütmek; davranış","The scientists conducted a series of tests."],
["confidence","B2","n.","güven, özgüven","Practice gives you confidence."],
["conflict","B2","n., v.","çatışma; çelişmek","The conflict lasted for years."],
["confusing","B2","adj.","kafa karıştırıcı","The map was confusing, so we got lost."],
["conscious","B2","adj.","bilinçli; farkında","He was conscious of being watched."],
["consequently","B2","adv.","sonuç olarak, bu nedenle","He missed the bus and consequently arrived late."],
["conservative","B2","adj., n.","muhafazakâr; temkinli","The town has very conservative tastes."],
["consideration","B2","n.","değerlendirme; düşüncelilik","After careful consideration, we accepted."],
["consistent","B2","adj.","tutarlı, istikrarlı","Her work is always of consistent quality."],
["constant","B2","adj.","sürekli, sabit","The machine needs constant attention."],
["constantly","B2","adv.","sürekli olarak","Technology is constantly changing."],
["constituency","C1","n.","seçim bölgesi","The MP visited her constituency at the weekend."],
["construct","B2","v.","inşa etmek, kurmak","The bridge was constructed in record time."],
["construction","B2","n.","inşaat, yapım","The road is closed for construction."],
["contemporary","B2","adj.","çağdaş, güncel","The gallery shows contemporary art."],
["contest","B2","n., v.","yarışma; itiraz etmek","She entered a national singing contest."],
["contract","B2","n., v.","sözleşme; daralmak","He signed a two-year contract."],
["contribute","B2","v.","katkıda bulunmak","Everyone contributed ideas to the project."],
["contribution","B2","n.","katkı","She made a huge contribution to the team."],
["convert","B2","v.","dönüştürmek","They converted the barn into a house."],
["convinced","B2","adj.","ikna olmuş, emin","I'm convinced that he is telling the truth."],
["core","B2","adj., n.","çekirdek, öz; temel","Maths is a core subject at school."],
["corporate","B2","adj.","kurumsal, şirketle ilgili","He left his corporate job to teach."],
["corporation","B2","n.","büyük şirket","The corporation employs thousands worldwide."],
["council","B2","n.","belediye meclisi; konsey","The council plans to build a new park."],
["councillor","C1","n.","meclis üyesi","The councillor listened to residents' complaints."],
["counselling","C1","n.","psikolojik danışmanlık","The school offers free counselling to students."],
["counsellor","C1","n.","danışman","She spoke to a counsellor about her stress."],
["county","B2","n.","ilçe, kontluk","The county has many small farms."],
["courage","B2","n.","cesaret, yüreklilik","It takes courage to admit a mistake."],
["crash","B2","n., v.","kaza; çarpmak; çökmek","The car crashed into a tree."],
["creation","B2","n.","yaratım, oluşturma","The chef showed us his latest creation."],
["creature","B2","n.","yaratık, canlı","The deep sea is full of strange creatures."],
["crew","B2","n.","mürettebat, ekip","The crew welcomed us aboard."],
["crisis","B2","n.","kriz, buhran","The country faced an energy crisis."],
["criterion","B2","n.","ölçüt, kriter","Price is not the only criterion."],
["critic","B2","n.","eleştirmen","The critics loved her new film."],
["critical","B2","adj.","eleştirel; kritik","The next few days are critical for the patient."],
["criticism","B2","n.","eleştiri","Try to accept fair criticism."],
["criticize","B2","v.","eleştirmek","The plan was criticized for its cost."],
["crop","B2","n.","ekin, mahsul","The rain saved this year's crops."],
["crucial","B2","adj.","çok önemli, hayati","Sleep is crucial for learning."],
["cure","B2","n., v.","tedavi (etmek), çare","There is still no cure for the common cold."],
["curve","B2","n., v.","eğri; kıvrılmak","The road curves around the lake."],
["curved","B2","adj.","kavisli, eğri","The bridge has a curved design."],
["debate","B2","n., v.","tartışma; tartışmak, müzakere etmek","The class debated the use of phones in school."],
["debt","B2","n.","borç","He finally paid off all his debts."],
["decent","B2","adj.","düzgün, makul; saygın","The hotel serves a decent breakfast."],
["declare","B2","v.","ilan etmek, beyan etmek","The mayor declared the festival open."],
["decline","B2","n., v.","düşüş; azalmak; reddetmek","Sales declined sharply in winter."],
["decoration","B2","n.","dekorasyon, süs(leme)","The decorations made the hall look festive."],
["decrease","B2","n., v.","azal(t)ma(k), düşüş","Traffic noise decreased after the new road opened."],
["deeply","B2","adv.","derinden; son derece","She was deeply moved by the letter."],
["defeat","B2","n., v.","yenilgi; yenmek","The team suffered a heavy defeat."],
["defence","B2","n.","savunma","The body's defence against illness is strong."],
["defend","B2","v.","savunmak, korumak","She defended her ideas with confidence."],
["delay","B2","n., v.","gecikme; ertelemek, geciktirmek","Fog delayed all morning flights."],
["deliberate","B2","adj.","kasıtlı, bilinçli","It was a deliberate attempt to mislead us."],
["deliberately","B2","adv.","kasten, bile bile","He deliberately left the door open."],
["delight","B2","n., v.","büyük keyif; sevindirmek","The garden is a delight in spring."],
["delivery","B2","n.","teslimat","Delivery takes three to five days."],
["demand","B2","n., v.","talep (etmek)","There is a high demand for nurses."],
["demonstrate","B2","v.","göstermek, kanıtlamak; gösteri yapmak","The teacher demonstrated the experiment."],
["deny","B2","v.","inkâr etmek; reddetmek","He denied breaking the window."],
["depressed","B2","adj.","depresyonda, çökkün","She felt depressed after losing her job."],
["depressing","B2","adj.","iç karartıcı","The news these days is depressing."],
["depth","B2","n.","derinlik","The lake has a depth of forty metres."],
["deserve","B2","v.","hak etmek","You deserve a holiday after all that work."],
["desire","B2","n., v.","arzu (etmek), istek","She had a strong desire to travel."],
["desperate","B2","adj.","çaresiz; umutsuz; şiddetle isteyen","He was desperate for a job, any job."],
["detailed","B2","adj.","ayrıntılı","The book gives detailed instructions."],
["detect","B2","v.","tespit etmek, saptamak","The device detects smoke very quickly."],
["dig","B2","v.","kazmak","The dog dug a hole in the garden."],
["disc","B2","n.","disk","The data is stored on a disc."],
["discipline","B2","n.","disiplin; bilim dalı","Learning an instrument teaches discipline."],
["dishonest","B2","adj.","sahtekâr, dürüst olmayan","It was dishonest of him to hide the truth."],
["disk","B2","n.","disk (bilgisayar)","Save the files to an external disk."],
["dismiss","B2","v.","işten çıkarmak; (fikri) reddetmek","She dismissed the idea as impossible."],
["display","B2","n., v.","sergi(lemek); ekran","The museum displays old coins."],
["distribute","B2","v.","dağıtmak","Volunteers distributed food to the families."],
["distribution","B2","n.","dağıtım, dağılım","The distribution of water is a big problem."],
["district","B2","n.","semt, bölge","They live in a quiet district of the city."],
["division","B2","n.","bölme, bölünme; bölüm","The division of the money caused an argument."],
["domestic","B2","adj.","yurt içi; evcil; ev ile ilgili","Domestic flights leave from terminal one."],
["dominate","B2","v.","hâkim olmak, egemen olmak","One team dominated the whole match."],
["downtown","B2","adj., adv., n.","şehir merkezi(nde)","We had dinner downtown."],
["downwards","B2","adv.","aşağı doğru","The path slopes downwards to the river."],
["dozen","B2","det., n.","düzine","She bought a dozen eggs."],
["draft","B2","n., v.","taslak (hazırlamak)","Write a first draft of your essay."],
["drag","B2","v.","sürüklemek","He dragged the heavy box across the floor."],
["dramatic","B2","adj.","çarpıcı, köklü; dramatik","There was a dramatic change in the weather."],
["edit","B2","v.","düzenlemek (metin/video)","Edit your essay before sending it."],
["edition","B2","n.","baskı, sürüm","I have the first edition of this novel."],
["efficient","B2","adj.","verimli, etkin","The new heating system is very efficient."],
["elderly","B2","adj.","yaşlı","An elderly couple sat by the window."],
["elect","B2","v.","seçmek (oyla)","The class elected a new president."],
["elsewhere","B2","adv.","başka yer(ler)de","The shop was closed, so we went elsewhere."],
["emerge","B2","v.","ortaya çıkmak, belirmek","The sun emerged from behind the clouds."],
["emotional","B2","adj.","duygusal","It was an emotional farewell at the airport."],
["emphasis","B2","n.","vurgu","The school puts emphasis on languages."],
["emphasize","B2","v.","vurgulamak","The doctor emphasized the need for rest."],
["enable","B2","v.","olanak sağlamak","The app enables you to track your runs."],
["encounter","B2","n., v.","karşılaşma(k)","We encountered several problems early on."],
["endeavour","C1","n.","çaba, girişim","Despite our best endeavours, the plan failed."],
["engage","B2","v.","meşgul etmek; (ilgisini) çekmek; katılmak","Good teachers engage their students."],
["enhance","B2","v.","artırmak, iyileştirmek","Spices enhance the flavour of the dish."],
["enquire","C1","v.","sormak, bilgi istemek","She enquired about the train times."],
["enquiry","B2","n.","soru, bilgi talebi","We received many enquiries about the course."],
["enrol","C1","v.","kaydolmak","He enrolled on a cooking course."],
["ensure","B2","v.","sağlamak, garanti etmek","Please ensure all windows are closed."],
["enthusiasm","B2","n.","coşku, heves","The students showed great enthusiasm."],
["enthusiastic","B2","adj.","hevesli, istekli","She is enthusiastic about the new project."],
["entire","B2","adj.","tüm, bütün","We spent the entire day in the garden."],
["entirely","B2","adv.","tamamen","That is an entirely different question."],
["entrepreneur","B2","n.","girişimci","The young entrepreneur opened two cafés."],
["establish","B2","v.","kurmak; saptamak","The company was established in 1990."],
["estate","B2","n.","arazi, mülk; site","They live on a quiet housing estate."],
["estimate","B2","n., v.","tahmin (etmek)","We estimate the journey will take two hours."],
["ethical","B2","adj.","etik, ahlaki","The shop sells ethical products."],
["evaluate","B2","v.","değerlendirmek","Teachers evaluate students' work each term."],
["evil","B2","adj., n.","kötü(lük)","The story is about good and evil."],
["examination","B2","n.","sınav; inceleme, muayene","The final examination is in June."],
["excuse","B2","n., v.","mazeret; affetmek","He had no excuse for being late."],
["executive","B2","adj., n.","yönetici","She is a senior executive at the bank."],
["exhibit","B2","n., v.","sergilemek; sergi parçası","The gallery exhibits local artists' work."],
["existence","B2","n.","varlık, var oluş","The letters prove the existence of the village."],
["exit","B2","n., v.","çıkış; çıkmak","The emergency exit is at the back."],
["exotic","B2","adj.","egzotik","The garden is full of exotic plants."],
["expectation","B2","n.","beklenti","The trip exceeded all our expectations."],
["expense","B2","n.","masraf, gider","Travel expenses are paid by the company."],
["exploration","B2","n.","keşif, araştırma","Space exploration costs billions."],
["expose","B2","v.","maruz bırakmak; ifşa etmek","Don't expose your skin to the midday sun."],
["extend","B2","v.","uzatmak; genişletmek","They extended their stay by a week."],
["extent","B2","n.","ölçü, derece, boyut","To some extent, I agree with you."],
["external","B2","adj.","dış, harici","The external walls need painting."],
["extraordinary","B2","adj.","olağanüstü","She has an extraordinary memory."],
["facility","B2","n.","tesis, olanak","The hotel has excellent sports facilities."],
["failure","B2","n.","başarısızlık; arıza","The plan ended in failure."],
["faith","B2","n.","inanç; güven","She has great faith in her team."],
["fault","B2","n.","kusur, hata; arıza","The accident was not your fault."],
["favourable","C1","adj.","olumlu, elverişli","The film received favourable reviews."],
["feather","B2","n.","tüy (kuş)","The bird lost a feather."],
["federal","B2","adj.","federal","The decision was made at the federal level."],
["fee","B2","n.","ücret (hizmet)","The entrance fee is five pounds."],
["feedback","B2","n.","geri bildirim","The teacher gave us helpful feedback."],
["fellow","B2","adj.","diğer, hemcins (fellow students)","She gets on well with her fellow workers."],
["fever","B2","n.","ateş (hastalık)","The child has a high fever."],
["fibre","C1","n.","lif; fiber","Vegetables are rich in fibre."],
["film-maker","C1","n.","film yapımcısı, sinemacı","The young film-maker won an award."],
["finance","B2","n., v.","finans(man); finanse etmek","The project is financed by the city."],
["finding","B2","n.","bulgu","The study's findings surprised everyone."],
["fixture","C1","n.","fikstür (maç); sabit demirbaş","The next fixture is against the champions."],
["flame","B2","n.","alev","The candle's flame danced in the wind."],
["flash","B2","n., v.","parlama; flaş; çakmak","A flash of lightning lit the sky."],
["flavour","B2","n.","tat, lezzet, aroma","Which flavour of ice cream do you want?"],
["flexible","B2","adj.","esnek","My working hours are quite flexible."],
["float","B2","v.","yüzmek (suda), batmamak","Wood floats on water."],
["folding","B2","adj.","katlanır","We took folding chairs to the beach."],
["forgive","B2","v.","affetmek, bağışlamak","She forgave him for forgetting her birthday."],
["former","B2","adj.","eski, önceki","The former teacher now writes books."],
["fortune","B2","n.","servet; talih","He made a fortune selling computers."],
["found","B2","v.","kurmak (kuruluş)","The school was founded a century ago."],
["freedom","B2","n.","özgürlük","Freedom of speech is a basic right."],
["frequency","B2","n.","sıklık; frekans","The frequency of storms has increased."],
["fulfil","B2","v.","yerine getirmek; gerçekleştirmek","She fulfilled her dream of becoming a pilot."],
["fully","B2","adv.","tamamen, bütünüyle","I fully understand your concerns."],
["fund","B2","n., v.","fon; finanse etmek","The research is funded by the government."],
["fundamental","B2","adj.","temel, esaslı","There is a fundamental difference between the two plans."],
["funding","B2","n.","finansman, kaynak","The library lost its funding."],
["furthermore","B2","adv.","ayrıca, dahası","The flat is small; furthermore, it is far from the centre."]
];
