// Oxford 3000 A2 vocab. Format: [w, lv, pos, tr, ex]
module.exports = [
["ability","A2","n.","yetenek, beceri","She has the ability to learn fast."],
["able","A2","adj.","yapabilen, muktedir","Are you able to come tomorrow?"],
["abroad","A2","adv.","yurt dışında, yurt dışına","My sister studies abroad."],
["accept","A2","v.","kabul etmek","He accepted the invitation."],
["accident","A2","n.","kaza","There was an accident on the road."],
["according to","A2","prep.","-e göre","According to the news, it will snow."],
["achieve","A2","v.","başarmak, elde etmek","You can achieve your goals with hard work."],
["act","A2","n., v.","davranmak; rol yapmak; eylem","She acts in a TV series."],
["active","A2","adj.","aktif, etkin","My grandfather is still very active."],
["actually","A2","adv.","aslında, gerçekte","Actually, I don't like coffee."],
["advantage","A2","n.","avantaj, üstünlük","Speaking two languages is a big advantage."],
["adventure","A2","n.","macera","The trip was a real adventure."],
["advertise","A2","v.","reklam yapmak","They advertise the phone on TV."],
["advertisement","A2","n.","reklam, ilan","I saw an advertisement for a new café."],
["advertising","A2","n.","reklamcılık","He works in advertising."],
["affect","A2","v.","etkilemek","The weather affects my mood."],
["against","A2","prep.","karşı","We played against a strong team."],
["ah","A2","excl.","ah!","Ah, now I understand!"],
["airline","A2","n.","havayolu (şirketi)","Which airline are you flying with?"],
["alive","A2","adj.","hayatta, canlı","The fish is still alive."],
["all right","A2","adj., adv., excl.","iyi, tamam; peki","Are you all right?"],
["allow","A2","v.","izin vermek","Dogs are not allowed in the shop."],
["almost","A2","adv.","neredeyse, hemen hemen","It's almost time for lunch."],
["alone","A2","adj., adv.","yalnız, tek başına","She lives alone with her cat."],
["along","A2","adv., prep.","boyunca","We walked along the river."],
["already","A2","adv.","zaten, çoktan","I have already seen this film."],
["alternative","A2","adj., n.","alternatif, seçenek","Is there an alternative to the bus?"],
["although","A2","conj.","-e rağmen, her ne kadar","Although it was cold, we went out."],
["among","A2","prep.","arasında (çok şey)","The house is hidden among the trees."],
["amount","A2","n., v.","miktar","Add a small amount of salt."],
["ancient","A2","adj.","antik, çok eski","We visited an ancient city."],
["ankle","A2","n.","ayak bileği","He hurt his ankle playing football."],
["any more","A2","adv.","artık (olumsuz)","She doesn't live here any more."],
["anybody","A2","pron.","herhangi biri, kimse","Is anybody home?"],
["anyway","A2","adv.","her neyse, zaten","It was raining, but we went anyway."],
["anywhere","A2","adv., pron.","herhangi bir yer(de)","I can't find my keys anywhere."],
["app","A2","n.","uygulama","This app helps you learn words."],
["appear","A2","v.","görünmek, ortaya çıkmak","A ship appeared on the horizon."],
["appearance","A2","n.","görünüş, dış görünüm","Don't judge people by their appearance."],
["apply","A2","v.","başvurmak; uygulamak","She applied for a summer job."],
["architect","A2","n.","mimar","The architect designed our school."],
["architecture","A2","n.","mimari, mimarlık","I love the architecture of old towns."],
["argue","A2","v.","tartışmak","They often argue about money."],
["argument","A2","n.","tartışma; argüman","We had an argument about the rules."],
["army","A2","n.","ordu","His brother is in the army."],
["arrange","A2","v.","ayarlamak, düzenlemek","Let's arrange a meeting for Monday."],
["arrangement","A2","n.","düzenleme, ayarlama","We made arrangements for the trip."],
["asleep","A2","adj.","uykuda, uyuyan","The baby is asleep now."],
["assistant","A2","adj., n.","asistan, yardımcı","The shop assistant was very helpful."],
["athlete","A2","n.","atlet, sporcu","The athletes train every day."],
["attack","A2","n., v.","saldırı; saldırmak","The dog attacked the postman."],
["attend","A2","v.","katılmak, devam etmek","All students must attend the meeting."],
["attention","A2","excl., n.","dikkat","Pay attention to the teacher."],
["attractive","A2","adj.","çekici, cazip","The town centre is very attractive."],
["audience","A2","n.","seyirci, dinleyiciler","The audience loved the show."],
["author","A2","n.","yazar","Who is the author of this book?"],
["available","A2","adj.","mevcut, müsait","Tickets are available online."],
["average","A2","adj., n., v.","ortalama","The average age in the class is twelve."],
["avoid","A2","v.","kaçınmak","Avoid sugar before bed."],
["award","A2","n., v.","ödül; ödül vermek","She won an award for her story."],
["awful","A2","adj.","berbat, korkunç","The food at that place was awful."],
["background","A2","n.","arka plan; geçmiş, köken","There are mountains in the background of the photo."],
["badly","A2","adv.","kötü (şekilde)","He played badly in the first half."],
["bar","A2","n., v.","bar; çubuk, kalıp","We met at a coffee bar."],
["baseball","A2","n.","beyzbol","Baseball is popular in America."],
["based","A2","adj.","dayanan, merkezli","The film is based on a true story."],
["basketball","A2","n.","basketbol","We play basketball after school."],
["bean","A2","n.","fasulye","The soup has beans and vegetables."],
["bear","A2","n., v.","ayı; katlanmak","We saw a bear in the forest."],
["beat","A2","n., v.","yenmek; vurmak; ritim","Our team beat them three to one."],
["beef","A2","n.","sığır eti","The beef was soft and tasty."],
["behave","A2","v.","davranmak","The children behaved very well."],
["behaviour","A2","n.","davranış","His behaviour at school is good."],
["belong","A2","v.","ait olmak","This bag belongs to my sister."],
["belt","A2","n.","kemer","He wears a brown leather belt."],
["benefit","A2","n., v.","fayda, yarar; yararlanmak","Exercise has many benefits."],
["billion","A2","num.","milyar","The world has about eight billion people."],
["bin","A2","n.","çöp kutusu","Put the paper in the bin."],
["biology","A2","n.","biyoloji","We study plants in biology."],
["birth","A2","n.","doğum","Write your date of birth here."],
["biscuit","A2","n.","bisküvi","Have a biscuit with your tea."],
["bit","A2","n.","parça, biraz (a bit)","I'm a bit tired today."],
["blank","A2","adj., n.","boş (sayfa/alan)","Fill in the blanks with the right words."],
["blood","A2","n.","kan","The nurse took some blood for the test."],
["board","A2","n., v.","pano, tahta; binmek","Write the answer on the board."],
["boil","A2","v.","kaynamak; haşlamak","Boil the eggs for ten minutes."],
["bone","A2","n.","kemik","The dog buried its bone."],
["borrow","A2","v.","ödünç almak","Can I borrow your bike?"],
["boss","A2","n.","patron, şef","My boss is very fair."],
["bottom","A2","adj., n.","alt, dip","The answer is at the bottom of the page."],
["bowl","A2","n.","kâse, çanak","A bowl of soup, please."],
["brain","A2","n.","beyin","The brain needs rest and sleep."],
["bridge","A2","n.","köprü","We crossed the old stone bridge."],
["bright","A2","adj.","parlak; zeki","The room is bright and sunny."],
["brilliant","A2","adj.","harika; çok parlak/zeki","That's a brilliant idea!"],
["broken","A2","adj.","kırık, bozuk","The window is broken."],
["brush","A2","n., v.","fırça(lamak)","Brush your teeth before bed."],
["burn","A2","n., v.","yanmak; yakmak","Don't burn the toast!"],
["businessman","A2","n.","iş adamı","The businessman travels a lot."],
["button","A2","n.","düğme","Press the red button to start."],
["camp","A2","n., v.","kamp (yapmak)","We camped by the lake."],
["camping","A2","n.","kampçılık","Camping is fun in summer."],
["care","A2","n., v.","bakım; umursamak; ilgilenmek","She cares for her old neighbour."],
["careful","A2","adj.","dikkatli","Be careful on the wet floor."],
["carefully","A2","adv.","dikkatlice","Read the instructions carefully."],
["carpet","A2","n.","halı","The cat sleeps on the carpet."],
["cartoon","A2","n.","çizgi film; karikatür","The kids watch cartoons on Saturday."],
["case","A2","n.","durum; dava; kutu","In that case, let's wait."],
["cash","A2","n.","nakit","Do you pay by card or cash?"],
["castle","A2","n.","kale, şato","The castle is on a hill."],
["catch","A2","n., v.","yakalamak; (otobüs vb.) yetişmek","Catch the ball!"],
["cause","A2","n., v.","neden (olmak)","Heavy rain caused the flood."],
["celebrate","A2","v.","kutlamak","We celebrated her birthday with a cake."],
["celebrity","A2","n.","ünlü kişi","The celebrity signed autographs for fans."],
["certain","A2","adj.","kesin, emin; belirli","I'm certain that he is right."],
["certainly","A2","adv.","kesinlikle, elbette","Certainly, I can help you."],
["chance","A2","n.","şans, fırsat; olasılık","This is your chance to try."],
["character","A2","n.","karakter; kişilik","Who is your favourite character in the book?"],
["charity","A2","n.","hayır kurumu; yardımseverlik","The money goes to charity."],
["chat","A2","n., v.","sohbet (etmek)","We chatted about the holidays."],
["chef","A2","n.","şef, aşçıbaşı","The chef made a special dessert."],
["chemistry","A2","n.","kimya","We did an experiment in chemistry class."],
["chip","A2","n.","patates kızartması; cips; çip","Fish and chips is a famous English dish."],
["choice","A2","n.","seçim, tercih","You have a choice of two desserts."],
["church","A2","n.","kilise","The old church is near the square."],
["cigarette","A2","n.","sigara","Cigarettes are bad for your health."],
["circle","A2","n., v.","daire, çember; yuvarlak içine almak","Draw a circle around the answer."],
["classical","A2","adj.","klasik","She listens to classical music."],
["clear","A2","adj., v.","açık, net; temizlemek","The water is so clear you can see fish."],
["clearly","A2","adv.","açıkça, net biçimde","Please speak clearly."],
["clever","A2","adj.","zeki, akıllı","The clever dog opened the door."],
["climate","A2","n.","iklim","The climate here is warm and dry."],
["closed","A2","adj.","kapalı","The bank is closed on Sundays."],
["clothing","A2","n.","giyim, giysi","Bring warm clothing for the trip."],
["cloud","A2","n.","bulut","Dark clouds mean rain."],
["coach","A2","n., v.","antrenör; yolcu otobüsü","Our coach makes us run every day."],
["coast","A2","n.","sahil, kıyı","The town is on the south coast."],
["code","A2","n.","kod, şifre","Enter the code to open the door."],
["colleague","A2","n.","meslektaş, iş arkadaşı","My colleagues are friendly."],
["collect","A2","v.","toplamak; biriktirmek","He collects old coins."],
["column","A2","n.","sütun; köşe yazısı","Write the numbers in the left column."],
["comedy","A2","n.","komedi","We watched a comedy and laughed a lot."],
["comfortable","A2","adj.","rahat, konforlu","This chair is very comfortable."],
["comment","A2","n., v.","yorum (yapmak)","She left a nice comment on my photo."],
["communicate","A2","v.","iletişim kurmak","We communicate by email."],
["community","A2","n.","topluluk","Our community has a small library."],
["compete","A2","v.","yarışmak, rekabet etmek","Ten teams compete in the cup."],
["competition","A2","n.","yarışma; rekabet","She won the photo competition."],
["complain","A2","v.","şikâyet etmek","He complained about the cold soup."],
["completely","A2","adv.","tamamen","I completely forgot the meeting."],
["condition","A2","n.","durum, koşul","The car is old but in good condition."],
["conference","A2","n.","konferans","She is speaking at a science conference."],
["connect","A2","v.","bağlamak, bağlanmak","Connect the printer to the computer."],
["connected","A2","adj.","bağlı, bağlantılı","The two problems are connected."],
["consider","A2","v.","düşünmek, göz önünde bulundurmak","We are considering a move to the coast."],
["contain","A2","v.","içermek","The box contains old photos."],
["context","A2","n.","bağlam","Guess the meaning from the context."],
["continent","A2","n.","kıta","Africa is a huge continent."],
["continue","A2","v.","devam etmek","The rain continued all night."],
["control","A2","n., v.","kontrol (etmek)","The pilot controls the plane."],
["cooker","A2","n.","ocak, fırın","The kitchen has a new cooker."],
["copy","A2","n., v.","kopya(lamak)","Make a copy of this page."],
["corner","A2","n.","köşe","The café is on the corner."],
["correctly","A2","adv.","doğru biçimde","Did I spell your name correctly?"],
["count","A2","n., v.","saymak","The child can count to a hundred."],
["couple","A2","n.","çift; birkaç (a couple of)","A young couple moved in next door."],
["cover","A2","n., v.","kaplamak, örtmek; kapak","Snow covered the streets."],
["crazy","A2","adj.","çılgın, deli","It was a crazy idea, but it worked."],
["creative","A2","adj.","yaratıcı","She is very creative with colours."],
["credit","A2","n., v.","kredi; itibar","I paid with a credit card."],
["crime","A2","n.","suç","The police fight crime."],
["criminal","A2","adj., n.","suçlu","The criminal was caught at the airport."],
["cross","A2","n., v.","karşıya geçmek; çarpı","Cross the road at the lights."],
["crowd","A2","n.","kalabalık","A crowd waited outside the stadium."],
["crowded","A2","adj.","kalabalık (yer)","The bus is crowded in the morning."],
["cry","A2","n., v.","ağlamak; bağırmak","The baby cried all night."],
["cupboard","A2","n.","dolap","The cups are in the cupboard."],
["curly","A2","adj.","kıvırcık","She has curly brown hair."],
["cycle","A2","n., v.","bisiklete binmek; döngü","I cycle to work every day."],
["daily","A2","adj., adv.","günlük, her gün","Take the medicine twice daily."],
["danger","A2","n.","tehlike","The sign says: Danger! Deep water."],
["data","A2","n.","veri","The computer stores all the data."],
["dead","A2","adj.","ölü","The plant is dead; it needed water."],
["deal","A2","n., v.","anlaşma; ilgilenmek (deal with)","We made a deal to share the work."],
["death","A2","n.","ölüm","The news of his death made us sad."],
["decision","A2","n.","karar","It was a difficult decision."],
["deep","A2","adj., adv.","derin","The lake is very deep."],
["definitely","A2","adv.","kesinlikle","I will definitely come to the party."],
["degree","A2","n.","derece; diploma","It's thirty degrees today."],
["dentist","A2","n.","diş hekimi","I go to the dentist twice a year."],
["department","A2","n.","bölüm, departman","She works in the sales department."],
["depend","A2","v.","bağlı olmak (depend on)","Our picnic depends on the weather."],
["desert","A2","n., v.","çöl","Camels live in the desert."],
["designer","A2","n.","tasarımcı","The designer showed her new dresses."],
["destroy","A2","v.","yok etmek, yıkmak","The fire destroyed the old house."],
["detective","A2","n.","dedektif","The detective found an important clue."],
["develop","A2","v.","geliştirmek, gelişmek","Reading develops your mind."],
["device","A2","n.","cihaz, aygıt","Turn off all devices at night."],
["diary","A2","n.","günlük; ajanda","She writes in her diary every night."],
["differently","A2","adv.","farklı biçimde","Let's try to do it differently."],
["digital","A2","adj.","dijital, sayısal","I have a digital camera."],
["direct","A2","adj., adv., v.","doğrudan, direkt; yönetmek","Is there a direct flight to Rome?"],
["direction","A2","n.","yön","We walked in the wrong direction."],
["director","A2","n.","yönetmen; müdür","The director is making a new film."],
["disagree","A2","v.","aynı fikirde olmamak","I disagree with that idea."],
["disappear","A2","v.","gözden kaybolmak","The sun disappeared behind the clouds."],
["disaster","A2","n.","felaket, afet","The flood was a terrible disaster."],
["discover","A2","v.","keşfetmek","They discovered a cave in the hills."],
["discovery","A2","n.","keşif, buluş","The discovery of fire changed everything."],
["discussion","A2","n.","tartışma, görüşme","We had a class discussion about sport."],
["disease","A2","n.","hastalık","Washing hands prevents disease."],
["distance","A2","n.","mesafe, uzaklık","What is the distance between the two cities?"],
["divorced","A2","adj.","boşanmış","Her parents are divorced."],
["document","A2","n., v.","belge","Sign the document at the bottom."],
["double","A2","adj., adv., det., pron., v.","çift, iki kat","We booked a double room."],
["download","A2","n., v.","indirmek","Download the app for free."],
["drama","A2","n.","drama, tiyatro oyunu","She takes drama classes after school."],
["drawing","A2","n.","çizim, resim","His drawing of the horse is beautiful."],
["dream","A2","n., v.","rüya (görmek); hayal (kurmak)","I had a strange dream last night."],
["drop","A2","n., v.","düşürmek; damla","Don't drop the glass!"],
["drug","A2","n.","ilaç; uyuşturucu","The new drug helps sick children."],
["dry","A2","adj., v.","kuru; kurutmak","The clothes are dry now."],
["earn","A2","v.","kazanmak (para)","She earns money by walking dogs."],
["earth","A2","n.","dünya, yer(yüzü); toprak","The earth goes around the sun."],
["easily","A2","adv.","kolayca","You can easily learn this song."],
["education","A2","n.","eğitim","Education opens many doors."],
["effect","A2","n.","etki, sonuç","Music has a strong effect on me."],
["either","A2","adv., det., pron.","ya ... ya da; ikisinden biri; de (olumsuz)","You can sit on either side."],
["electric","A2","adj.","elektrikli","We have an electric car."],
["electrical","A2","adj.","elektrikle ilgili","My father repairs electrical things."],
["electricity","A2","n.","elektrik","The storm cut the electricity."],
["electronic","A2","adj.","elektronik","Turn off electronic devices at night."],
["employ","A2","v.","istihdam etmek, çalıştırmak","The factory employs two hundred people."],
["employee","A2","n.","çalışan, işçi","The employees get a free lunch."],
["employer","A2","n.","işveren","Her employer gave her a day off."],
["empty","A2","adj., v.","boş; boşaltmak","The bottle is empty."],
["ending","A2","n.","son, bitiş","The film has a happy ending."],
["energy","A2","n.","enerji","Children have so much energy!"],
["engine","A2","n.","motor","The car engine makes a strange noise."],
["engineer","A2","n.","mühendis","The engineer fixed the machine."],
["enormous","A2","adj.","kocaman, devasa","They live in an enormous house."],
["enter","A2","v.","girmek","Knock before you enter."],
["environment","A2","n.","çevre, ortam","We must protect the environment."],
["equipment","A2","n.","ekipman, donanım","The gym has new equipment."],
["error","A2","n.","hata","There is an error in this sentence."],
["especially","A2","adv.","özellikle","I love fruit, especially cherries."],
["essay","A2","n.","deneme, kompozisyon","Write an essay about your town."],
["everyday","A2","adj.","günlük, her günkü","These are my everyday shoes."],
["everywhere","A2","adv.","her yer(de)","I looked everywhere for my keys."],
["evidence","A2","n.","kanıt, delil","The police found new evidence."],
["exact","A2","adj.","tam, kesin","What is the exact time?"],
["exactly","A2","adv.","tam olarak; aynen","That's exactly what I mean."],
["excellent","A2","adj.","mükemmel","Your homework is excellent."],
["except","A2","conj., prep.","hariç, dışında","Everyone came except Tom."],
["exist","A2","v.","var olmak","Do aliens really exist?"],
["expect","A2","v.","beklemek, ummak","I expect he will be late."],
["experience","A2","n., v.","deneyim; yaşamak","She has experience in teaching."],
["experiment","A2","n., v.","deney (yapmak)","We did an experiment with water and salt."],
["expert","A2","adj., n.","uzman","An expert checked the old painting."],
["explanation","A2","n.","açıklama","The teacher gave a clear explanation."],
["express","A2","v.","ifade etmek","It's hard to express my feelings."],
["expression","A2","n.","ifade; deyim","She had a happy expression on her face."],
["extreme","A2","adj., n.","aşırı, uç","Be careful in extreme heat."],
["extremely","A2","adv.","son derece","The test was extremely difficult."],
["factor","A2","n.","etken, faktör","Price is an important factor."],
["factory","A2","n.","fabrika","The factory makes toys."],
["fail","A2","v.","başarısız olmak; kalmak (sınav)","Don't worry if you fail the first time."],
["fair","A2","adj.","adil; açık (ten); fuar","The game wasn't fair."],
["fan","A2","n.","hayran, taraftar; vantilatör","The fans cheered for their team."],
["farming","A2","n.","çiftçilik, tarım","Farming is hard work."],
["fashion","A2","n.","moda","She follows fashion closely."],
["fear","A2","n., v.","korku; korkmak","He has a fear of heights."],
["feature","A2","n., v.","özellik","The phone has many new features."],
["feed","A2","n., v.","beslemek","Don't feed the animals at the zoo."],
["female","A2","adj., n.","dişi, kadın","The female bird builds the nest."],
["fiction","A2","n.","kurgu, roman türü","She reads science fiction."],
["field","A2","n.","tarla; saha; alan","The sheep are in the field."],
["fight","A2","n., v.","kavga (etmek); mücadele etmek","The boys had a fight at school."],
["figure","A2","n., v.","rakam; şekil; figür","Write the figures in the box."],
["finally","A2","adv.","sonunda; son olarak","We finally found the right house."],
["finger","A2","n.","parmak","The baby held my finger."],
["firstly","A2","adv.","ilk olarak, birincisi","Firstly, read the question carefully."],
["fishing","A2","n.","balıkçılık, balık tutma","We go fishing at the lake."],
["fix","A2","n., v.","tamir etmek; sabitlemek","Dad fixed my bike."],
["flu","A2","n.","grip","She is in bed with flu."],
["flying","A2","adj., n.","uçma; uçan","Flying is faster than driving."],
["focus","A2","n., v.","odak(lanmak)","Focus on your homework first."],
["following","A2","adj., n., prep.","takip eden, sonraki","Answer the following questions."],
["foreign","A2","adj.","yabancı (ülke)","She speaks two foreign languages."],
["forest","A2","n.","orman","Many animals live in the forest."],
["fork","A2","n.","çatal","Put the forks next to the plates."],
["formal","A2","adj.","resmî","Wear formal clothes to the interview."],
["fortunately","A2","adv.","neyse ki, çok şükür","Fortunately, nobody was hurt."],
["forward","A2","adj., adv.","ileri(ye)","Take two steps forward."],
["fresh","A2","adj.","taze; temiz (hava)","I bought fresh bread this morning."],
["fridge","A2","n.","buzdolabı","There is milk in the fridge."],
["frog","A2","n.","kurbağa","The frog jumped into the pond."],
["furniture","A2","n.","mobilya","The new flat needs furniture."],
["further","A2","adj., adv.","daha ileri; daha fazla","The shop is a bit further down the road."],
["gallery","A2","n.","galeri","The art gallery is free on Fridays."],
["gap","A2","n.","boşluk, ara","Fill in the gaps in the text."],
["gas","A2","n.","gaz; benzin","We cook with gas."],
["gate","A2","n.","kapı (bahçe); uçuş kapısı","Close the garden gate, please."],
["general","A2","adj.","genel","The book gives general information."],
["gift","A2","n.","hediye; yetenek","Thank you for the lovely gift."],
["goal","A2","n.","hedef; gol","He scored the winning goal."],
["god","A2","n.","tanrı","The old stories talk about many gods."],
["gold","A2","adj., n.","altın","The ring is made of gold."],
["golf","A2","n.","golf","They play golf at the weekend."],
["government","A2","n.","hükümet, devlet","The government opened new hospitals."],
["grass","A2","n.","çimen, ot","Don't walk on the grass."],
["greet","A2","v.","selamlamak, karşılamak","She greeted us with a big smile."],
["ground","A2","n.","yer, zemin; saha","The ground is wet after the rain."],
["guest","A2","n.","misafir, konuk","Our guests arrive at seven."],
["guide","A2","n., v.","rehber(lik etmek)","The guide showed us the castle."],
["gun","A2","n.","silah, tabanca","The police officer carries a gun."],
["guy","A2","n.","adam, herif (gündelik)","He's a really nice guy."],
["habit","A2","n.","alışkanlık","Reading at night is a good habit."],
["hall","A2","n.","salon; koridor","The concert is in the school hall."],
["happily","A2","adv.","mutlulukla; neyse ki","The story ends happily."],
["headache","A2","n.","baş ağrısı","I have a bad headache."],
["heart","A2","n.","kalp, yürek","Running is good for your heart."],
["heat","A2","n., v.","ısı, sıcaklık; ısıtmak","Heat the soup for five minutes."],
["heavy","A2","adj.","ağır; yoğun","This box is too heavy for me."],
["height","A2","n.","yükseklik, boy","What is the height of that wall?"],
["helpful","A2","adj.","yardımcı, faydalı","The map was very helpful."],
["hero","A2","n.","kahraman","The firefighter is a real hero."],
["hers","A2","pron.","onunki (kadın)","This coat is hers."],
["herself","A2","pron.","kendisi (kadın)","She made the dress herself."],
["hide","A2","v.","saklamak, saklanmak","The cat hides under the bed."],
["hill","A2","n.","tepe","Our school is on a hill."],
["himself","A2","pron.","kendisi (erkek)","He fixed the bike himself."],
["hit","A2","n., v.","vurmak; çarpmak; hit (şarkı)","The ball hit the window."],
["hockey","A2","n.","hokey","They play hockey on ice."],
["hole","A2","n.","delik, çukur","There's a hole in my sock."],
["huge","A2","adj.","kocaman, devasa","An elephant is a huge animal."],
["human","A2","adj., n.","insan(a özgü)","Humans need clean water."],
["identify","A2","v.","tanımlamak, kimliğini belirlemek","Can you identify the bird in this photo?"],
["ill","A2","adj.","hasta","She is ill and can't come to school."],
["illness","A2","n.","hastalık","He missed work because of illness."],
["image","A2","n.","görüntü, imaj","The image on the screen is clear."],
["immediately","A2","adv.","hemen, derhal","Call the doctor immediately."],
["impossible","A2","adj.","imkânsız","It's impossible to finish today."],
["included","A2","adj.","dahil","Breakfast is included in the price."],
["including","A2","prep.","dahil olmak üzere","Six people came, including two children."],
["increase","A2","n., v.","artış; art(ır)mak","Prices increased last month."],
["incredible","A2","adj.","inanılmaz","The view from the top is incredible."],
["independent","A2","adj.","bağımsız","She is young but very independent."],
["individual","A2","adj., n.","birey(sel)","Each individual has different needs."],
["industry","A2","n.","sanayi, endüstri","The car industry employs many people."],
["informal","A2","adj.","gayriresmî, samimi","Use informal language with friends."],
["injury","A2","n.","yaralanma, sakatlık","He has a knee injury from football."],
["insect","A2","n.","böcek","Bees are useful insects."],
["inside","A2","adj., adv., n., prep.","iç(inde), içeri","Let's go inside; it's cold."],
["instead","A2","adv.","yerine, onun yerine","There's no tea; have coffee instead."],
["instruction","A2","n.","talimat, yönerge","Follow the instructions on the box."],
["instructor","A2","n.","eğitmen","The swimming instructor is patient."],
["instrument","A2","n.","enstrüman, alet","Do you play an instrument?"],
["intelligent","A2","adj.","zeki, akıllı","Dolphins are intelligent animals."],
["international","A2","adj.","uluslararası","The hotel has international guests."],
["introduction","A2","n.","giriş; tanıtma","Read the introduction of the book first."],
["invent","A2","v.","icat etmek","Who invented the telephone?"],
["invention","A2","n.","icat, buluş","The wheel was a great invention."],
["invitation","A2","n.","davet(iye)","Thanks for the invitation to your party."],
["invite","A2","v.","davet etmek","She invited all her friends."],
["involve","A2","v.","içermek, gerektirmek; dahil etmek","The job involves a lot of travel."],
["itself","A2","pron.","kendisi (cansız/hayvan)","The cat cleaned itself in the sun."],
["item","A2","n.","madde, parça, ürün","Each item has a price tag."],
["jam","A2","n.","reçel; sıkışıklık","I like strawberry jam on toast."],
["jazz","A2","n.","caz","We listened to jazz at the café."],
["jewellery","A2","n.","mücevher, takı","She keeps her jewellery in a small box."],
["joke","A2","n., v.","şaka (yapmak), fıkra","He told a funny joke."],
["journalist","A2","n.","gazeteci","The journalist wrote about the fire."],
["jump","A2","n., v.","atlamak, zıplamak","The cat jumped onto the wall."],
["kid","A2","n.","çocuk (gündelik)","The kids are playing outside."],
["kill","A2","v.","öldürmek","Some plants can kill insects."],
["king","A2","n.","kral","The king lived in a great castle."],
["knee","A2","n.","diz","I hurt my knee when I fell."],
["knife","A2","n.","bıçak","Cut the apple with a knife."],
["knock","A2","n., v.","(kapı) çalmak; vurmak","Someone is knocking at the door."],
["knowledge","A2","n.","bilgi (birikimi)","Her knowledge of history is amazing."],
["lab","A2","n.","laboratuvar","We work in the lab on Fridays."],
["lady","A2","n.","hanım, hanımefendi","An old lady sat next to me."],
["lake","A2","n.","göl","We swam in the lake."],
["lamp","A2","n.","lamba","Turn on the lamp; it's dark."],
["laptop","A2","n.","dizüstü bilgisayar","I write my essays on my laptop."],
["laughter","A2","n.","kahkaha, gülüş","The room was full of laughter."],
["law","A2","n.","yasa, hukuk","The new law starts next year."],
["lawyer","A2","n.","avukat","The lawyer explained the contract."],
["lazy","A2","adj.","tembel","The lazy cat sleeps all day."],
["lead","A2","n., v.","yol göstermek, önderlik etmek","The path leads to the beach."],
["leader","A2","n.","lider, önder","She is the leader of our team."],
["learning","A2","n.","öğrenme","Learning a language takes time."],
["least","A2","adv., det., pron.","en az","At least drink some water."],
["lecture","A2","n., v.","ders, konferans","The lecture was about space."],
["lemon","A2","n.","limon","Add lemon to your tea."],
["lend","A2","v.","ödünç vermek","Can you lend me a pencil?"],
["less","A2","adv., det., pron.","daha az","Eat less sugar."],
["lifestyle","A2","n.","yaşam tarzı","A healthy lifestyle includes exercise."],
["lift","A2","n., v.","asansör; kaldırmak","Take the lift to the fifth floor."],
["likely","A2","adj.","muhtemel, olası","It's likely to rain today."],
["link","A2","n., v.","bağlantı; bağlamak","Click the link to open the page."],
["listener","A2","n.","dinleyici","The radio show has many listeners."],
["lock","A2","n., v.","kilit(lemek)","Lock the door when you leave."],
["lorry","A2","n.","kamyon","A big lorry blocked the road."],
["lost","A2","adj.","kayıp, kaybolmuş","The lost dog found its way home."],
["loud","A2","adj., adv.","yüksek sesli, gürültülü","The music is too loud."],
["loudly","A2","adv.","yüksek sesle","Don't talk loudly in the library."],
["lovely","A2","adj.","hoş, sevimli, güzel","What a lovely garden!"],
["luck","A2","n.","şans, talih","Good luck with your exam!"],
["lucky","A2","adj.","şanslı","You're lucky to live by the sea."],
["mail","A2","n., v.","posta; postalamak","Is there any mail for me today?"],
["major","A2","adj.","büyük, başlıca","Traffic is a major problem here."],
["male","A2","adj., n.","erkek","The male bird has bright colours."],
["manage","A2","v.","yönetmek; başarmak","She manages a small shop."],
["manager","A2","n.","müdür, yönetici","The manager talked to the new workers."],
["manner","A2","n.","tarz, tavır; (manners) görgü","Say thank you; good manners matter."],
["mark","A2","n., v.","not, işaret(lemek)","I got a good mark in maths."],
["marry","A2","v.","evlenmek","They married in June."],
["mathematics","A2","n.","matematik","Mathematics is my favourite subject."],
["maths","A2","n.","matematik (kısa)","We have maths on Monday."],
["matter","A2","n., v.","mesele; önemli olmak","It doesn't matter; we can try again."],
["media","A2","n.","medya","The story was in all the media."],
["medical","A2","adj.","tıbbi","She needs medical help."],
["medicine","A2","n.","ilaç; tıp","Take your medicine after meals."],
["memory","A2","n.","hafıza; anı","I have happy memories of that summer."],
["mention","A2","n., v.","bahsetmek, anmak","He mentioned your name yesterday."],
["metal","A2","n.","metal","The door is made of metal."],
["method","A2","n.","yöntem, metot","This is an easy method to learn words."],
["middle","A2","adj., n.","orta","The table is in the middle of the room."],
["might","A2","modal v.","-ebilir (olasılık)","It might snow tonight."],
["mind","A2","n., v.","zihin, akıl; aldırmak","Do you mind if I open the window?"],
["mine","A2","n., pron.","benimki; maden","That blue bag is mine."],
["mirror","A2","n.","ayna","She looked in the mirror."],
["missing","A2","adj.","kayıp, eksik","Two pages are missing from the book."],
["mobile","A2","adj., n.","cep telefonu; taşınabilir","My mobile is out of battery."],
["monkey","A2","n.","maymun","The monkey ate a banana."],
["moon","A2","n.","ay (gökyüzü)","The moon is bright tonight."],
["mostly","A2","adv.","çoğunlukla","The guests were mostly students."],
["motorcycle","A2","n.","motosiklet","He rides a motorcycle to work."],
["movement","A2","n.","hareket","The dancer's movements were beautiful."],
["musical","A2","adj., n.","müzikal; müzikle ilgili","She comes from a musical family."],
["musician","A2","n.","müzisyen","The musicians played all night."],
["myself","A2","pron.","kendim","I painted the room myself."],
["nature","A2","n.","doğa; doğası","We enjoy walking in nature."],
["nearly","A2","adv.","neredeyse","It's nearly midnight."],
["necessary","A2","adj.","gerekli","Water is necessary for life."],
["neck","A2","n.","boyun","The giraffe has a long neck."],
["neither","A2","adv., det., pron.","hiçbiri (ikisinden); ne ... ne de","Neither answer is correct."],
["nervous","A2","adj.","gergin, heyecanlı","I'm nervous before exams."],
["network","A2","n.","ağ, şebeke","The phone network is down."],
["noise","A2","n.","gürültü, ses","What's that strange noise?"],
["noisy","A2","adj.","gürültülü","The street is noisy at night."],
["none","A2","pron.","hiçbiri","None of the shops were open."],
["normal","A2","adj., n.","normal, olağan","It's normal to feel tired after sport."],
["normally","A2","adv.","normalde, genellikle","I normally walk to school."],
["notice","A2","n., v.","fark etmek; duyuru","Did you notice her new glasses?"],
["nowhere","A2","adv.","hiçbir yer(de)","There was nowhere to sit."],
["nut","A2","n.","kuruyemiş, fındık/ceviz","Nuts are a healthy snack."],
["ocean","A2","n.","okyanus","The ship crossed the ocean."],
["offer","A2","n., v.","teklif (etmek); sunmak","He offered me his seat."],
["officer","A2","n.","memur, subay","The police officer helped the children cross."],
["oil","A2","n.","yağ; petrol","Cook the onions in a little oil."],
["onto","A2","prep.","üzerine, üstüne","The cat jumped onto the table."],
["opportunity","A2","n.","fırsat","This job is a great opportunity."],
["option","A2","n.","seçenek","You have two options: bus or train."],
["ordinary","A2","adj.","sıradan, olağan","It was an ordinary Monday morning."],
["organization","A2","n.","kuruluş, örgüt","She works for a health organization."],
["organize","A2","v.","düzenlemek, organize etmek","We organized a party for the teacher."],
["original","A2","adj., n.","orijinal, özgün; ilk","The original plan was better."],
["ourselves","A2","pron.","kendimiz","We cleaned the classroom ourselves."],
["oven","A2","n.","fırın","The cake is in the oven."],
["owner","A2","n.","sahip","Who is the owner of this car?"],
["pack","A2","n., v.","paketlemek, bavul hazırlamak","Pack your bag for the trip."],
["pain","A2","n.","ağrı, acı","I have a pain in my back."],
["painter","A2","n.","ressam; boyacı","The painter sold his picture."],
["palace","A2","n.","saray","The queen lives in a palace."],
["pants","A2","n.","pantolon; külot","These pants are too short."],
["parking","A2","n.","park etme; otopark","Parking is free after six."],
["particular","A2","adj.","belirli, özel","Are you looking for a particular book?"],
["pass","A2","n., v.","geçmek; uzatmak; pas","Did you pass the test?"],
["passenger","A2","n.","yolcu","The bus carries forty passengers."],
["pattern","A2","n.","desen; kalıp, örüntü","The carpet has a beautiful pattern."],
["peace","A2","n.","barış; huzur","Everyone wants peace in the world."],
["penny","A2","n.","peni","The sweets cost fifty pence."],
["per","A2","prep.","başına, her bir","The room costs forty pounds per night."],
["per cent","A2","adj., adv., n.","yüzde","Ninety per cent of students passed."],
["perform","A2","v.","sahnelemek, icra etmek; performans göstermek","The band performs every Friday."],
["perhaps","A2","adv.","belki","Perhaps we should wait a little."],
["permission","A2","n.","izin","You need permission to leave early."],
["personality","A2","n.","kişilik","She has a warm personality."],
["pet","A2","n.","evcil hayvan","Do you have any pets?"],
["petrol","A2","n.","benzin","We stopped to buy petrol."],
["physical","A2","adj.","fiziksel, bedensel","Physical exercise keeps you healthy."],
["physics","A2","n.","fizik","Physics explains how things move."],
["pilot","A2","n.","pilot","The pilot landed the plane safely."],
["planet","A2","n.","gezegen","Mars is the red planet."],
["plastic","A2","adj., n.","plastik","Use less plastic to help nature."],
["plate","A2","n.","tabak","Put the cake on a plate."],
["platform","A2","n.","peron; platform","The train leaves from platform two."],
["pleased","A2","adj.","memnun, hoşnut","I'm pleased to meet you."],
["pocket","A2","n.","cep","My keys are in my pocket."],
["polite","A2","adj.","kibar, nazik","Be polite to the guests."],
["pollution","A2","n.","kirlilik","Air pollution is bad in big cities."],
["population","A2","n.","nüfus","The population of the town is growing."],
["possession","A2","n.","sahip olunan şey, mal","He lost all his possessions in the fire."],
["possibility","A2","n.","olasılık, ihtimal","There's a possibility of rain."],
["poster","A2","n.","poster, afiş","There's a film poster on my wall."],
["predict","A2","v.","tahmin etmek, öngörmek","Nobody can predict the future."],
["president","A2","n.","cumhurbaşkanı, başkan","The president gave a speech."],
["prevent","A2","v.","önlemek, engellemek","Helmets prevent head injuries."],
["printer","A2","n.","yazıcı","The printer is out of paper."],
["prison","A2","n.","hapishane","The thief went to prison."],
["prize","A2","n.","ödül","She won first prize in the competition."],
["professor","A2","n.","profesör","The professor teaches history."],
["profile","A2","n.","profil","Update your profile on the website."],
["program","A2","n., v.","program(lamak)","He writes computer programs."],
["promise","A2","n., v.","söz (vermek)","I promise to call you tonight."],
["pronounce","A2","v.","telaffuz etmek","How do you pronounce this word?"],
["protect","A2","v.","korumak","Sun cream protects your skin."],
["provide","A2","v.","sağlamak, temin etmek","The school provides free books."],
["pub","A2","n.","birahane, pub","They watched the match at the pub."],
["public","A2","adj., n.","halka açık, kamusal; halk","The park is open to the public."],
["publish","A2","v.","yayımlamak","Her first book was published in May."],
["pull","A2","n., v.","çekmek","Pull the door to open it."],
["purpose","A2","n.","amaç","The purpose of the meeting is to plan."],
["push","A2","n., v.","itmek","Push the button for the lift."],
["quality","A2","n.","kalite; nitelik","The shop sells good quality shoes."],
["quantity","A2","n.","miktar, nicelik","Buy a small quantity of rice."],
["queen","A2","n.","kraliçe","The queen waved to the crowd."],
["quietly","A2","adv.","sessizce","She closed the door quietly."],
["race","A2","n., v.","yarış(mak); ırk","He won the bicycle race."],
["railway","A2","n.","demiryolu","The railway connects the two cities."],
["raise","A2","v.","kaldırmak; yükseltmek; (para) toplamak","Raise your hand to answer."],
["rather","A2","adv.","oldukça; tercihen (would rather)","It's rather cold today."],
["react","A2","v.","tepki vermek","How did she react to the news?"],
["realize","A2","v.","fark etmek, anlamak","I realized I had left my phone at home."],
["receive","A2","v.","almak (posta vb.)","I received your letter yesterday."],
["recent","A2","adj.","yakın zamanda olan, son","Have you seen any recent films?"],
["recently","A2","adv.","son zamanlarda, geçenlerde","We moved here recently."],
["reception","A2","n.","resepsiyon; karşılama","Leave your key at reception."],
["recipe","A2","n.","tarif (yemek)","This is my mother's soup recipe."],
["recognize","A2","v.","tanımak; kabul etmek","I didn't recognize you with short hair!"],
["recommend","A2","v.","tavsiye etmek, önermek","Can you recommend a good film?"],
["record","A2","n., v.","kayıt; kaydetmek; rekor","The teacher recorded our song."],
["recording","A2","n.","kayıt (ses/görüntü)","Listen to the recording twice."],
["recycle","A2","v.","geri dönüştürmek","We recycle paper and glass."],
["reduce","A2","v.","azaltmak","Reduce the heat and cook slowly."],
["refer","A2","v.","atıfta bulunmak, değinmek (refer to)","The teacher referred to page ten."],
["refuse","A2","v.","reddetmek","He refused my offer of help."],
["region","A2","n.","bölge","This region is famous for tea."],
["regular","A2","adj.","düzenli; normal boy","Regular exercise is important."],
["relationship","A2","n.","ilişki","They have a good relationship."],
["remove","A2","v.","çıkarmak, kaldırmak","Remove your shoes at the door."],
["repair","A2","n., v.","tamir (etmek)","He repaired the broken chair."],
["replace","A2","v.","değiştirmek, yerine koymak","Replace the old batteries."],
["reply","A2","n., v.","yanıt(lamak)","She replied to my email quickly."],
["reporter","A2","n.","muhabir","The reporter asked many questions."],
["request","A2","n., v.","talep, rica (etmek)","We made a request for more time."],
["research","A2","n., v.","araştırma (yapmak)","She does research on dolphins."],
["researcher","A2","n.","araştırmacı","The researchers work at the university."],
["respond","A2","v.","yanıt vermek, karşılık vermek","He didn't respond to my message."],
["response","A2","n.","yanıt, tepki","Her response was very polite."],
["rest","A2","n., v.","dinlenmek; geri kalan","Rest for an hour after lunch."],
["review","A2","n., v.","inceleme, eleştiri; gözden geçirmek","The film got great reviews."],
["ring","A2","n., v.","yüzük; çalmak (zil)","The phone is ringing."],
["rise","A2","n., v.","yükselmek, artmak","Prices rise every year."],
["role","A2","n.","rol","She plays the role of the queen."],
["roof","A2","n.","çatı","The cat is on the roof."],
["route","A2","n.","rota, güzergâh","This is the shortest route to the beach."],
["rubbish","A2","n.","çöp; saçmalık","Put the rubbish in the bin."],
["rude","A2","adj.","kaba","It's rude to shout at people."],
["runner","A2","n.","koşucu","The runners started at nine."],
["running","A2","n.","koşu","Running keeps me fit."],
["sadly","A2","adv.","ne yazık ki; üzgün biçimde","Sadly, the old cinema closed."],
["safe","A2","adj.","güvenli, emniyetli","Keep your money in a safe place."],
["sail","A2","n., v.","yelken; denize açılmak","The boat sails at noon."],
["sailing","A2","n.","yelkencilik","We went sailing on the lake."],
["salary","A2","n.","maaş","She gets a good salary."],
["sale","A2","n.","satış; indirim","The shop has a big sale this week."],
["sauce","A2","n.","sos","Pasta with tomato sauce, please."],
["save","A2","v.","kurtarmak; biriktirmek; tasarruf etmek","I'm saving money for a bike."],
["scared","A2","adj.","korkmuş","The little boy is scared of the dark."],
["scary","A2","adj.","korkutucu","That was a scary film!"],
["scene","A2","n.","sahne; olay yeri","The first scene is in a garden."],
["score","A2","n., v.","skor; gol/sayı atmak","What's the score in the match?"],
["search","A2","n., v.","arama(k)","I searched the internet for the answer."],
["season","A2","n.","mevsim; sezon","Spring is my favourite season."],
["secondly","A2","adv.","ikinci olarak","Secondly, check your spelling."],
["secret","A2","adj., n.","gizli; sır","Can you keep a secret?"],
["secretary","A2","n.","sekreter","The secretary answered the phone."],
["seem","A2","v.","görünmek, gibi gelmek","You seem tired today."],
["separate","A2","adj., v.","ayrı; ayırmak","The children sleep in separate rooms."],
["series","A2","n.","dizi, seri","We watched a new TV series."],
["serious","A2","adj.","ciddi","It's a serious problem."],
["serve","A2","v.","servis etmek, hizmet vermek","Dinner is served at seven."],
["service","A2","n.","hizmet, servis","The service at the hotel was excellent."],
["several","A2","det., pron.","birkaç, birçok","I called him several times."],
["shake","A2","n., v.","sallamak; titremek; el sıkışmak","Shake the bottle before opening."],
["shall","A2","modal v.","-elim mi?; -ecek","Shall we go for a walk?"],
["sheet","A2","n.","çarşaf; yaprak (kâğıt)","Take a clean sheet of paper."],
["shoulder","A2","n.","omuz","He carried the bag on his shoulder."],
["shout","A2","n., v.","bağırmak","Don't shout; I can hear you."],
["shut","A2","adj., v.","kapatmak; kapalı","Shut the window, please."],
["side","A2","n.","taraf, yan, kenar","Our house is on the other side of the road."],
["sign","A2","n., v.","tabela, işaret; imzalamak","Sign your name at the bottom."],
["silver","A2","adj., n.","gümüş","She wore silver earrings."],
["simple","A2","adj.","basit, sade","The rules of the game are simple."],
["since","A2","adv., conj., prep.","-den beri; çünkü","We have lived here since 2015."],
["singing","A2","n.","şarkı söyleme","Her singing filled the hall."],
["single","A2","adj., n.","tek; bekâr","There wasn't a single cloud in the sky."],
["sir","A2","n.","beyefendi, efendim","Excuse me, sir, is this your bag?"],
["site","A2","n.","alan, yer; site","This is the site of the new school."],
["size","A2","n.","boyut, beden","What size shoes do you wear?"],
["ski","A2","adj., n., v.","kayak (yapmak)","We ski in the mountains every winter."],
["skiing","A2","n.","kayak (sporu)","Skiing is exciting but tiring."],
["skin","A2","n.","cilt, deri","The sun can burn your skin."],
["sky","A2","n.","gökyüzü","The sky is full of stars."],
["slowly","A2","adv.","yavaşça","Speak slowly, please."],
["smartphone","A2","n.","akıllı telefon","She reads news on her smartphone."],
["smell","A2","n., v.","koku; koklamak; kokmak","The flowers smell wonderful."],
["smile","A2","n., v.","gülümseme(k)","She smiled at the baby."],
["smoke","A2","n., v.","duman; sigara içmek","Smoke rose from the chimney."],
["smoking","A2","n.","sigara içme","Smoking is not allowed here."],
["soap","A2","n.","sabun","Wash your hands with soap."],
["soccer","A2","n.","futbol","Soccer is the world's favourite game."],
["social","A2","adj.","sosyal, toplumsal","School has a social side too."],
["society","A2","n.","toplum; dernek","We live in a busy modern society."],
["sock","A2","n.","çorap","I bought three pairs of socks."],
["soft","A2","adj.","yumuşak","The pillow is nice and soft."],
["soldier","A2","n.","asker","The soldiers marched through the town."],
["solution","A2","n.","çözüm","There is a simple solution to this problem."],
["solve","A2","v.","çözmek","Can you solve this puzzle?"],
["somewhere","A2","adv., pron.","bir yer(de)","I left my umbrella somewhere."],
["sort","A2","n., v.","tür; sıralamak, ayırmak","What sort of music do you like?"],
["source","A2","n.","kaynak","Fruit is a good source of vitamins."],
["speaker","A2","n.","konuşmacı; hoparlör","The speaker talked about healthy food."],
["specific","A2","adj.","belirli, özgül","Give a specific example."],
["speech","A2","n.","konuşma, nutuk","The head teacher gave a short speech."],
["spider","A2","n.","örümcek","A spider made a web in the corner."],
["spoon","A2","n.","kaşık","Eat the soup with a spoon."],
["square","A2","adj., n.","kare; meydan","The hotel is near the main square."],
["stair","A2","n.","basamak, merdiven","The stairs go up to the bedrooms."],
["stamp","A2","n.","pul; damga","Put a stamp on the envelope."],
["state","A2","adj., n., v.","devlet; durum; belirtmek","The letter states the time of the meeting."],
["steal","A2","v.","çalmak (hırsızlık)","Someone stole my bike!"],
["stomach","A2","n.","mide, karın","My stomach hurts after lunch."],
["stone","A2","n.","taş","The wall is made of stone."],
["store","A2","n., v.","mağaza; depolamak","The store opens at nine."],
["storm","A2","n.","fırtına","The storm broke many trees."],
["straight","A2","adj., adv.","düz; doğruca","Go straight and turn left."],
["strange","A2","adj.","garip, tuhaf","I heard a strange sound outside."],
["strategy","A2","n.","strateji","We need a new strategy to win."],
["stress","A2","n., v.","stres; vurgulamak","Exams cause a lot of stress."],
["stupid","A2","adj.","aptalca, salak","It was a stupid mistake."],
["succeed","A2","v.","başarmak, başarılı olmak","Work hard and you will succeed."],
["successful","A2","adj.","başarılı","She is a successful writer."],
["such","A2","det., pron.","böyle, öyle; o kadar","It was such a nice day."],
["suddenly","A2","adv.","aniden, birdenbire","Suddenly, the lights went out."],
["suggest","A2","v.","önermek","I suggest we leave early."],
["suggestion","A2","n.","öneri","That's a very good suggestion."],
["suit","A2","n., v.","takım elbise; yakışmak; uymak","Blue really suits you."],
["support","A2","n., v.","destek(lemek)","My family supports my plans."],
["suppose","A2","v.","sanmak, varsaymak","I suppose you're right."],
["surprise","A2","n., v.","sürpriz; şaşırtmak","We planned a surprise for her birthday."],
["surprised","A2","adj.","şaşırmış","I was surprised by the question."],
["surprising","A2","adj.","şaşırtıcı","The end of the story was surprising."],
["sweet","A2","adj., n.","tatlı; şeker","This tea is too sweet."],
["symbol","A2","n.","sembol, simge","The dove is a symbol of peace."],
["system","A2","n.","sistem","The school has a new computer system."],
["tablet","A2","n.","tablet","The kids play games on the tablet."],
["task","A2","n.","görev, iş","Finish this task before lunch."],
["taste","A2","n., v.","tat; tatmak; tadı olmak","The cake tastes delicious."],
["teaching","A2","n.","öğretmenlik, öğretim","Teaching is a rewarding job."],
["technology","A2","n.","teknoloji","Technology changes very fast."],
["teenage","A2","adj.","ergenlik çağındaki","She has two teenage sons."],
["temperature","A2","n.","sıcaklık; ateş (vücut)","The temperature dropped at night."],
["themselves","A2","pron.","kendileri","The kids made the cake themselves."],
["thick","A2","adj.","kalın; yoğun","Wear a thick coat; it's freezing."],
["thief","A2","n.","hırsız","The thief took her bag."],
["thin","A2","adj.","ince; zayıf","The walls are very thin."],
["thinking","A2","n.","düşünme, düşünce","What's your thinking on this plan?"],
["thought","A2","n.","düşünce","She shared her thoughts about the book."],
["throw","A2","v.","atmak, fırlatmak","Throw the ball to me!"],
["tidy","A2","adj., v.","derli toplu; toplamak","Tidy your room before dinner."],
["tie","A2","n., v.","kravat; bağlamak","Tie your shoes before running."],
["tip","A2","n., v.","ipucu; bahşiş; uç","Here's a tip: read the questions first."],
["tool","A2","n.","alet, araç","A hammer is a useful tool."],
["touch","A2","n., v.","dokunmak; temas","Don't touch the hot pan!"],
["tour","A2","n., v.","tur, gezi","We took a tour of the castle."],
["tourism","A2","n.","turizm","Tourism brings money to the town."],
["towards","A2","prep.","-e doğru","She walked towards the door."],
["towel","A2","n.","havlu","Dry your hands with this towel."],
["tower","A2","n.","kule","The clock tower is very old."],
["toy","A2","adj., n.","oyuncak","The baby plays with soft toys."],
["tradition","A2","n.","gelenek","Family dinners are a tradition for us."],
["traditional","A2","adj.","geleneksel","We ate traditional Turkish food."],
["trainer","A2","n.","spor ayakkabı; antrenör","My new trainers are very comfortable."],
["training","A2","n.","eğitim, antrenman","The team has training on Tuesdays."],
["transport","A2","n., v.","ulaşım; taşımak","Public transport is cheap here."],
["traveller","A2","n.","gezgin, yolcu","The traveller visited many countries."],
["truck","A2","n.","kamyon","The truck delivered the furniture."],
["twin","A2","adj., n.","ikiz","The twins wear the same clothes."],
["typical","A2","adj.","tipik","This is a typical Turkish breakfast."],
["underground","A2","adj., adv.","yeraltı(nda); metro","We took the underground to the centre."],
["understanding","A2","n.","anlayış; anlama","She has a good understanding of maths."],
["unfortunately","A2","adv.","ne yazık ki, maalesef","Unfortunately, the tickets are sold out."],
["unhappy","A2","adj.","mutsuz","He was unhappy about the result."],
["uniform","A2","n.","üniforma, forma","Students wear a blue uniform."],
["unit","A2","n.","ünite, birim","We finished unit five in the book."],
["united","A2","adj.","birleşmiş","The fans stood united behind the team."],
["unusual","A2","adj.","alışılmadık, sıra dışı","It's unusual to see snow in May."],
["used to","A2","modal v.","eskiden ... yapardı","I used to live in a village."],
["user","A2","n.","kullanıcı","The app has a million users."],
["usual","A2","adj.","her zamanki, olağan","I'll meet you at the usual place."],
["valley","A2","n.","vadi","The river runs through a green valley."],
["van","A2","n.","minibüs, kamyonet","The van delivers bread every morning."],
["variety","A2","n.","çeşit(lilik)","The market has a variety of fruits."],
["vehicle","A2","n.","taşıt, araç","Park your vehicle behind the building."],
["view","A2","n., v.","manzara; görüş","The room has a sea view."],
["virus","A2","n.","virüs","The virus spread very quickly."],
["voice","A2","n.","ses (insan)","She has a soft voice."],
["war","A2","n.","savaş","The war ended in 1945."],
["washing","A2","n.","çamaşır (yıkama)","Hang the washing in the garden."],
["wave","A2","n., v.","dalga; el sallamak","The waves are big today."],
["weak","A2","adj.","zayıf, güçsüz","I feel weak after the flu."],
["web","A2","n.","ağ; internet","The spider made a beautiful web."],
["wedding","A2","n.","düğün","The wedding is in June."],
["weight","A2","n.","ağırlık, kilo","The box has a weight of ten kilos."],
["wet","A2","adj.","ıslak; yağışlı","My shoes are wet from the rain."],
["wheel","A2","n.","tekerlek; direksiyon","The bike's front wheel is flat."],
["while","A2","conj., n.","iken, sırasında; süre","I read while I wait for the bus."],
["whole","A2","adj., n.","bütün, tüm","We spent the whole day at the beach."],
["whose","A2","det., pron.","kimin","Whose bag is this?"],
["wide","A2","adj.","geniş","The river is very wide here."],
["wild","A2","adj.","vahşi, yabani","Wild flowers grow by the road."],
["winner","A2","n.","kazanan","The winner gets a gold medal."],
["wish","A2","n., v.","dilek; dilemek","Make a wish and blow out the candles!"],
["wood","A2","n.","odun, ahşap; koru","The table is made of wood."],
["wooden","A2","adj.","ahşap, tahta","We sat on a wooden bench."],
["working","A2","adj.","çalışan; iş ile ilgili","Working parents are often busy."],
["worried","A2","adj.","endişeli","I'm worried about the exam."],
["worry","A2","n., v.","endişe(lenmek)","Don't worry; everything will be fine."],
["wow","A2","excl.","vay canına!","Wow! What a goal!"],
["yours","A2","pron.","seninki, sizinki","Is this pen yours?"],
["zero","A2","num.","sıfır","The temperature fell below zero."]
];
