// Oxford 5000 B2-C1 vocab: N-O-P. Format: [w, lv, pos, tr, ex]
module.exports = [
["naked","B2","adj.","çıplak","The hill was naked of any trees."],
["namely","C1","adv.","yani, şöyle ki","One student passed, namely the one who practised daily."],
["narrow","B2","v.","daralmak; daraltmak","The road narrows sharply after the bridge."],
["nasty","B2","adj.","kötü, pis, çirkin","He had a nasty fall on the ice."],
["national","B2","n.","vatandaş, yurttaş","Foreign nationals must register with the police."],
["nationwide","C1","adj.","ülke çapında","The chain has more than two hundred stores nationwide."],
["naval","C1","adj.","deniz kuvvetlerine ait","The naval base guards the entrance to the bay."],
["navigation","B2","n.","seyrüsefer, yön bulma","Thick fog made navigation almost impossible."],
["nearby","B2","adj., adv.","yakındaki; yakında","The injured man was taken to a nearby clinic."],
["neat","B2","adj.","derli toplu, düzenli","Her desk is always neat and tidy."],
["necessity","B2","n.","gereklilik, zorunluluk; ihtiyaç","A car is a necessity in this remote area."],
["negative","B2","n.","olumsuz yön/yanıt; negatif","The plan has one big negative: its cost."],
["neglect","C1","n., v.","ihmal; ihmal etmek","The garden had suffered years of neglect."],
["negotiate","B2","v.","müzakere etmek, pazarlık etmek","The union negotiated a better deal for drivers."],
["negotiation","B2","n.","müzakere, görüşme","Negotiations between the two sides resumed today."],
["neighbouring","C1","adj.","komşu (yer)","Refugees crossed into neighbouring countries."],
["nerve","B2","n.","sinir; cesaret","The dentist removed the damaged nerve."],
["nest","C1","n.","yuva","A pair of storks built a nest on the chimney."],
["net","C1","adj.","net (kesintiler sonrası)","Her net salary is lower than the advertised figure."],
["neutral","B2","adj.","tarafsız; nötr","The referee must remain strictly neutral."],
["nevertheless","B2","adv.","yine de, buna rağmen","The task was hard; nevertheless, they finished on time."],
["newly","B2","adv.","yeni, henüz","The newly opened café is already popular."],
["newsletter","C1","n.","bülten","The club sends a monthly newsletter to members."],
["niche","C1","n.","niş; özel alan/pazar","She found a niche selling handmade lamps online."],
["nightmare","B2","n.","kâbus","Moving house turned into a complete nightmare."],
["noble","C1","adj.","soylu; asil, yüce","Forgiving him was a noble gesture."],
["nod","C1","v.","başını sallamak (onay)","She nodded in agreement and smiled."],
["nominate","C1","v.","aday göstermek; atamak","The film was nominated for three awards."],
["nomination","C1","n.","adaylık, aday gösterme","Her nomination surprised the party leadership."],
["nominee","C1","n.","aday (gösterilen)","The nominees will be announced next week."],
["non-profit","C1","adj.","kâr amacı gütmeyen","She runs a non-profit organization for refugees."],
["nonetheless","C1","adv.","yine de","The evidence was thin; nonetheless, the jury convicted."],
["nonsense","C1","n.","saçmalık","Don't believe that nonsense about haunted houses."],
["noon","C1","n.","öğle vakti","The market closes at noon on Sundays."],
["norm","B2","n.","norm, ölçüt; olağan durum","Remote working has become the norm in many firms."],
["notable","C1","adj.","dikkate değer, önemli","The visit was notable for one surprising announcement."],
["notably","C1","adv.","özellikle; dikkat çekici biçimde","Several countries, notably Japan, opposed the plan."],
["notebook","B2","n.","defter; dizüstü bilgisayar","He writes every idea in a small notebook."],
["notify","C1","v.","bildirmek, haber vermek","Please notify the school of any absence."],
["notion","B2","n.","kavram, fikir","The notion that money buys happiness is questionable."],
["notorious","C1","adj.","adı çıkmış (kötü)","The junction is notorious for accidents."],
["novel","C1","adj.","yeni, özgün","The team tried a novel approach to the problem."],
["novelist","B2","n.","romancı","The novelist based the story on her own village."],
["nowadays","B2","adv.","bugünlerde, günümüzde","Nowadays most people pay by phone."],
["numerous","B2","adj.","çok sayıda","We've discussed this on numerous occasions."],
["nursery","C1","n.","kreş; fidanlık","The twins started nursery this autumn."],
["nursing","B2","n.","hemşirelik","She chose nursing as a career after the accident."],
["nutrition","B2","n.","beslenme","Good nutrition is essential for growing children."],
["obesity","B2","n.","obezite","Obesity rates have doubled in twenty years."],
["obey","B2","v.","itaat etmek, uymak","Soldiers are trained to obey orders."],
["object","B2","v.","itiraz etmek","Several residents objected to the new car park."],
["objection","C1","n.","itiraz","The lawyer raised an objection to the question."],
["objective","B2","adj., n.","nesnel; hedef","Our main objective is to cut waste by half."],
["obligation","B2","n.","yükümlülük","Parents have a legal obligation to educate their children."],
["oblige","C1","v.","zorunda bırakmak; ricayı yerine getirmek","Bad weather obliged us to cancel the picnic."],
["observation","B2","n.","gözlem","The patient was kept in hospital for observation."],
["observe","B2","v.","gözlemlemek; (kurala) uymak","Astronomers observed the comet for weeks."],
["observer","B2","n.","gözlemci","International observers monitored the election."],
["obsess","C1","v.","kafayı takmak, takıntı yapmak","He's obsessed with keeping his car spotless."],
["obsession","C1","n.","takıntı, saplantı","Tidiness has become an obsession with her."],
["obstacle","B2","n.","engel","Lack of money was the biggest obstacle to the plan."],
["obtain","B2","v.","elde etmek, edinmek","Visitors must obtain a permit before entering."],
["occasional","C1","adj.","ara sıra olan","She enjoys an occasional game of tennis."],
["occasionally","B2","adv.","ara sıra, bazen","We occasionally meet for coffee in town."],
["occupation","B2","n.","meslek; işgal","Please state your name and occupation."],
["occupy","B2","v.","işgal etmek; (yer) kaplamak; meşgul etmek","Toys occupied the children for the whole journey."],
["occurrence","C1","n.","olay; meydana gelme","Flooding is a common occurrence here in spring."],
["odds","C1","n.","olasılık, ihtimal; şans","The odds of winning the prize are tiny."],
["offence","B2","n.","suç; gücenme","Parking here is a minor offence."],
["offend","B2","v.","gücendirmek; suç işlemek","I didn't mean to offend you with my joke."],
["offender","B2","n.","suçlu, suç işleyen","Young offenders attend a separate court."],
["offensive","B2","adj.","saldırgan; hakaret içeren","The post was removed for offensive language."],
["offering","C1","n.","sunulan şey, ürün; adak","The bakery's latest offering is a honey cake."],
["official","B2","n.","yetkili, görevli","Customs officials searched the lorry."],
["offspring","C1","n.","yavru; çocuk(lar)","The lioness guards her offspring fiercely."],
["ongoing","B2","adj.","devam eden, süregelen","The road is closed due to ongoing repairs."],
["opening","B2","n.","açılış; açıklık; boş kadro","The gallery's opening attracted a large crowd."],
["openly","B2","adv.","açıkça, alenen","They spoke openly about their disagreements."],
["opera","B2","n.","opera","We saw a famous opera at the summer festival."],
["operate","B2","v.","çalışmak, işletmek; ameliyat etmek","The machine operates around the clock."],
["operational","C1","adj.","işler durumda; operasyonel","The new airport is fully operational."],
["operator","B2","n.","operatör; işletmeci","The crane operator works from a high cabin."],
["opponent","B2","n.","rakip; karşıt","She defeated her opponent in straight sets."],
["oppose","B2","v.","karşı çıkmak","Local farmers oppose the new motorway."],
["opposed","B2","adj.","karşı, muhalif","He is firmly opposed to any rise in fees."],
["opposition","B2","n.","muhalefet, karşıtlık","The plan met strong opposition from parents."],
["opt","C1","v.","tercih etmek, seçmek","Most guests opted for the vegetarian menu."],
["optical","C1","adj.","optik, görmeyle ilgili","The drawing creates a clever optical illusion."],
["optimism","C1","n.","iyimserlik","There are grounds for cautious optimism."],
["optimistic","B2","adj.","iyimser","She remains optimistic about finding a job."],
["oral","C1","adj.","sözlü; ağızdan","The course ends with an oral examination."],
["orchestra","B2","n.","orkestra","The orchestra tuned their instruments before the concert."],
["organ","B2","n.","organ; org","The heart is the body's hardest-working organ."],
["organic","B2","adj.","organik","They sell organic vegetables at the market."],
["organizational","C1","adj.","örgütsel, organizasyonla ilgili","Good organizational skills are essential for this job."],
["orientation","C1","n.","yönelim; uyum programı","New staff attend a two-day orientation."],
["origin","B2","n.","köken, kaynak","The word's origin is Latin."],
["originate","C1","v.","kaynaklanmak, doğmak","The custom originated in rural villages."],
["otherwise","B2","adv.","aksi takdirde; bunun dışında","Leave now; otherwise you'll miss the train."],
["outbreak","C1","n.","(salgın/savaş) patlak verme","An outbreak of measles closed the school."],
["outcome","B2","n.","sonuç","The outcome of the trial surprised everyone."],
["outer","B2","adj.","dış, dıştaki","The outer walls are nearly a metre thick."],
["outfit","B2","n.","kıyafet (takım)","She bought a new outfit for the interview."],
["outing","C1","n.","gezi, gezinti","The class enjoyed an outing to the science museum."],
["outlet","C1","n.","satış noktası; çıkış (yolu); priz","Running gives him an outlet for his stress."],
["outline","B2","n., v.","taslak, ana hat; ana hatlarıyla anlatmak","The manager outlined the plan in five minutes."],
["outlook","C1","n.","görünüm, beklenti; bakış açısı","The economic outlook has improved slightly."],
["output","B2","n.","çıktı, üretim (miktarı)","Factory output rose three per cent last month."],
["outrage","C1","n., v.","öfke, infial; çileden çıkarmak","The decision sparked outrage among fans."],
["outsider","C1","n.","yabancı, dışarıdan biri","As an outsider, she saw the town's problems clearly."],
["outstanding","B2","adj.","seçkin, olağanüstü; ödenmemiş","She received an award for outstanding service."],
["overall","B2","adj., adv.","genel; genel olarak","Overall, the project was a success."],
["overcome","B2","v.","üstesinden gelmek, yenmek","He overcame his fear of flying."],
["overlook","C1","v.","gözden kaçırmak; göz yummak; (manzaraya) bakmak","The room overlooks a quiet courtyard."],
["overly","C1","adv.","aşırı derecede, fazla","Don't be overly critical of your own work."],
["overnight","B2","adv.","bir gecede; gece boyunca","The town's fortunes changed overnight."],
["overseas","B2","adj., adv.","denizaşırı, yurt dışında","The firm hopes to expand into overseas markets."],
["oversee","C1","v.","denetlemek, gözetmek","A committee oversees spending on public projects."],
["overturn","C1","v.","devirmek; (kararı) bozmak","The appeal court overturned the original verdict."],
["overwhelm","C1","v.","boğmak, altında ezmek; gark etmek","The tiny clinic was overwhelmed by patients."],
["overwhelming","C1","adj.","ezici, karşı konulmaz","An overwhelming majority voted yes."],
["owe","B2","v.","borçlu olmak","I owe my brother fifty pounds."],
["ownership","B2","n.","sahiplik, mülkiyet","Home ownership is falling among the young."],
["oxygen","B2","n.","oksijen","Climbers carry oxygen at extreme altitudes."],
["pace","B2","n., v.","tempo, hız; volta atmak","She set a steady pace from the start of the race."],
["package","B2","v.","paketlemek, ambalajlamak","The nuts are packaged in small paper bags."],
["packet","B2","n.","paket (küçük)","He opened a packet of biscuits."],
["pad","C1","n.","ped, yastıkçık; not defteri","Write the number on the pad by the phone."],
["palm","B2","n.","avuç içi; palmiye","She held the coin in the palm of her hand."],
["panel","B2","n.","panel, kurul; pano","A panel of judges will choose the winner."],
["panic","B2","n.","panik","The fire alarm caused a brief panic."],
["parade","B2","n.","geçit töreni","Children lined the streets to watch the parade."],
["parallel","B2","adj., n.","paralel; benzerlik","The film draws a parallel between past and present."],
["parameter","C1","n.","parametre, sınır","The study stayed within strict ethical parameters."],
["parental","C1","adj.","ebeveynle ilgili","The trip requires parental permission."],
["parish","C1","n.","mahalle kilisesi bölgesi; cemaat","The priest has served this parish for decades."],
["parliament","B2","n.","parlamento, meclis","Parliament will debate the bill tomorrow."],
["parliamentary","C1","adj.","parlamenter, meclisle ilgili","A parliamentary committee examined the evidence."],
["part-time","B2","adj.","yarı zamanlı","She took a part-time job at the library."],
["partial","C1","adj.","kısmi; taraflı","The strike caused a partial shutdown of the port."],
["partially","C1","adv.","kısmen","The road is partially blocked by a fallen tree."],
["participant","B2","n.","katılımcı","Each participant received a certificate."],
["participation","B2","n.","katılım","The course encourages active participation."],
["partly","B2","adv.","kısmen","The delay was partly my fault."],
["partnership","B2","n.","ortaklık","The museum works in partnership with local schools."],
["passage","B2","n.","pasaj, bölüm; geçit; geçiş","Read the passage and answer the questions."],
["passing","C1","n.","geçiş; vefat","The bell marked the passing of the old year."],
["passionate","B2","adj.","tutkulu","He is passionate about protecting wildlife."],
["passive","C1","adj.","pasif, edilgen","Watching television is a largely passive activity."],
["password","B2","n.","şifre, parola","Choose a password that is hard to guess."],
["pastor","C1","n.","papaz (Protestan)","The pastor greeted the congregation at the door."],
["patch","C1","n.","yama; küçük alan/dönem","The team is going through a difficult patch."],
["patent","C1","n.","patent","The inventor filed a patent for her design."],
["pathway","C1","n.","patika; yol (kariyer/süreç)","The course offers a pathway into engineering."],
["patience","B2","n.","sabır","Teaching young children takes great patience."],
["patient","B2","adj.","sabırlı","Be patient; the results take a week."],
["patrol","C1","n., v.","devriye; devriye gezmek","Police patrol the park after dark."],
["patron","C1","n.","hami, destekçi; müdavim","She is a generous patron of young artists."],
["pause","B2","n., v.","duraklama; duraklamak","He paused before answering the question."],
["peak","C1","n.","zirve, doruk","Traffic reaches its peak at eight in the morning."],
["peasant","C1","n.","köylü (tarihsel)","The peasants worked the lord's fields."],
["peculiar","C1","adj.","tuhaf, acayip; özgü","There was a peculiar smell in the cellar."],
["peer","B2","n.","akran, emsal","Teenagers care deeply about the opinions of their peers."],
["penalty","B2","n.","ceza; penaltı","The penalty for late payment is ten per cent."],
["pension","B2","n.","emekli maaşı","She retired early on a reduced pension."],
["perceive","B2","v.","algılamak","The change was too slow to be perceived."],
["perception","B2","n.","algı","Public perception of the police has improved."],
["permanent","B2","adj.","kalıcı, daimi","The accident left no permanent damage."],
["permanently","B2","adv.","kalıcı olarak","The factory closed permanently last year."],
["permit","B2","n., v.","izin (belgesi); izin vermek","Smoking is not permitted anywhere in the building."],
["persist","C1","v.","sürmek; ısrar etmek","If the pain persists, see a doctor."],
["persistent","C1","adj.","inatçı, sürekli","A persistent cough kept him awake."],
["personnel","C1","n.","personel","Only authorised personnel may enter this area."],
["perspective","B2","n.","bakış açısı; perspektif","Travel gives you a fresh perspective on home."],
["petition","C1","n.","dilekçe, imza kampanyası","Thousands signed a petition to save the library."],
["phase","B2","n.","evre, aşama","The project is still in its early phase."],
["phenomenon","B2","n.","olgu, fenomen","Migration is a global phenomenon."],
["philosopher","C1","n.","filozof","The philosopher questioned what justice really means."],
["philosophical","C1","adj.","felsefi; metanetli","He was philosophical about losing the match."],
["philosophy","B2","n.","felsefe","Her philosophy is simple: work hard, be kind."],
["physician","C1","n.","hekim, doktor","Consult a physician before starting the diet."],
["pick","B2","n.","seçim; en iyisi","Take your pick of the remaining seats."],
["picture","B2","v.","hayal etmek, gözünde canlandırmak","Picture a beach at sunset, totally empty."],
["pile","B2","n., v.","yığın; yığmak","A pile of letters waited on the desk."],
["pill","B2","n.","hap","Take one pill with each meal."],
["pioneer","C1","n., v.","öncü; öncülük etmek","She pioneered a new method of teaching reading."],
["pipeline","C1","n.","boru hattı; (in the pipeline) yolda","A new gas pipeline crosses the region."],
["pirate","C1","n.","korsan","Pirates attacked merchant ships along this coast."],
["pit","C1","n.","çukur; maden ocağı","The miners went down the pit at dawn."],
["pitch","B2","n.","saha; perde (ses); sunum","The pitch was too wet to play on."],
["pity","B2","n.","acıma; yazık","What a pity you can't come to the party."],
["placement","B2","n.","yerleştirme; staj","The course includes a work placement in a hospital."],
["plain","B2","adj.","sade, düz; açık, net","She prefers plain food without rich sauces."],
["plea","C1","n.","rica, yakarış; savunma (mahkeme)","The mother made an emotional plea for help."],
["plead","C1","v.","yalvarmak; (suçlamayı) kabul/ret beyan etmek","The defendant pleaded not guilty."],
["pledge","C1","n., v.","söz, taahhüt; söz vermek","The mayor pledged to plant ten thousand trees."],
["plot","B2","v.","komplo kurmak; (grafik) çizmek","The generals plotted to seize power."],
["plug","C1","n., v.","fiş, tapa; tıkamak","Pull out the plug before cleaning the machine."],
["plunge","C1","v.","dalmak; aniden düşmek","Temperatures plunged below zero overnight."],
["plus","B2","adj., conj., n.","artı; avantaj","Speaking two languages is a definite plus."],
["pointed","B2","adj.","sivri; iğneleyici","She gave him a pointed look when he arrived late."],
["pole","C1","n.","direk; kutup","Flags flew from every pole along the route."],
["poll","C1","n.","anket; oylama","The poll shows support for the mayor falling."],
["pond","C1","n.","gölcük, havuz","Ducks swam across the village pond."],
["pop","C1","v.","patlamak; aniden çıkmak/uğramak","A warning suddenly popped up on the screen."],
["popularity","B2","n.","popülerlik","The sport's popularity is growing among girls."],
["portfolio","C1","n.","portföy; dosya (çalışma örnekleri)","Bring a portfolio of your designs to the interview."],
["portion","B2","n.","porsiyon; pay, kısım","A large portion of the budget goes on rent."],
["portray","C1","v.","betimlemek, canlandırmak","The film portrays the artist as a lonely genius."],
["pose","B2","v.","oluşturmak (tehdit/soru); poz vermek","Melting ice poses a threat to coastal cities."],
["position","B2","v.","yerleştirmek, konumlandırmak","Position the lamp so the light falls on the page."],
["positive","B2","n.","olumlu yön; pozitif","Let's focus on the positives of the situation."],
["possess","B2","v.","sahip olmak","He possesses a rare talent for languages."],
["post-war","C1","adj.","savaş sonrası","The post-war years brought rapid rebuilding."],
["postpone","C1","v.","ertelemek","The match was postponed because of fog."],
["potential","B2","adj., n.","potansiyel, olası; gizilgüç","The site has great potential for development."],
["potentially","B2","adv.","potansiyel olarak","The chemical is potentially dangerous if heated."],
["power","B2","v.","güç sağlamak, çalıştırmak","Solar cells power the small weather station."],
["practitioner","C1","n.","uygulayıcı (doktor/avukat vb.)","She is a respected legal practitioner."],
["praise","B2","n., v.","övgü; övmek","Critics praised the novel's honesty."],
["preach","C1","v.","vaaz vermek; öğütlemek","He preaches patience but rarely shows it."],
["precede","B2","v.","önce gelmek","A short film preceded the main feature."],
["precedent","C1","n.","emsal, içtihat","The ruling set an important precedent."],
["precious","B2","adj.","değerli, kıymetli","Clean water is a precious resource."],
["precise","B2","adj.","kesin, tam","The map gives the precise location of the well."],
["precisely","B2","adv.","tam olarak; kesinlikle","The train left at precisely nine o'clock."],
["precision","C1","n.","kesinlik, hassasiyet","The parts are cut with laser precision."],
["predator","C1","n.","yırtıcı (hayvan), avcı","Owls are night-time predators of mice."],
["predecessor","C1","n.","öncel, selef","The new director reversed her predecessor's policies."],
["predictable","B2","adj.","tahmin edilebilir","The plot was enjoyable but predictable."],
["predominantly","C1","adv.","ağırlıklı olarak, çoğunlukla","The audience was predominantly young."],
["preference","B2","n.","tercih","We try to respect each guest's preferences."],
["pregnancy","C1","n.","hamilelik, gebelik","Smoking during pregnancy harms the baby."],
["pregnant","B2","adj.","hamile, gebe","She was pregnant with her second child."],
["prejudice","C1","n.","ön yargı","The law aims to protect workers from prejudice."],
["preliminary","C1","adj.","ön, hazırlık niteliğinde","Preliminary results suggest the vaccine works."],
["premier","C1","adj.","başlıca, en önde gelen","The hall is the city's premier concert venue."],
["premise","C1","n.","öncül, varsayım","The argument rests on a false premise."],
["premium","C1","n.","sigorta primi; ek ücret; üstün kalite","Fresh fish sells at a premium in winter."],
["preparation","B2","n.","hazırlık","Months of preparation went into the festival."],
["prescribe","C1","v.","reçete yazmak; öngörmek","The doctor prescribed a course of antibiotics."],
["prescription","C1","n.","reçete","These tablets are only available on prescription."],
["presence","B2","n.","varlık, mevcudiyet","The army kept a strong presence in the city."],
["presently","C1","adv.","şu anda; birazdan","The manager is presently in a meeting."],
["preservation","C1","n.","koruma, muhafaza","The society works for the preservation of old buildings."],
["preserve","B2","v.","korumak, muhafaza etmek","Salt was used to preserve meat for winter."],
["preside","C1","v.","başkanlık etmek","A senior judge presided over the trial."],
["presidency","C1","n.","başkanlık (makamı/dönemi)","The economy grew during her presidency."],
["presidential","C1","adj.","başkanlık ile ilgili","The presidential election takes place in May."],
["prestigious","C1","adj.","prestijli, saygın","She won a place at a prestigious university."],
["presumably","C1","adv.","muhtemelen, tahminen","Presumably the flight was delayed by the storm."],
["presume","C1","v.","varsaymak, farz etmek","I presume the meeting is still on for Friday."],
["prevail","C1","v.","galip gelmek; hüküm sürmek","Common sense prevailed and the fight was avoided."],
["prevalence","C1","n.","yaygınlık","The survey measures the prevalence of allergies."],
["prevention","C1","n.","önleme","Prevention is better than cure."],
["prey","C1","n.","av (hayvan)","The eagle circled, watching for prey."],
["price","B2","v.","fiyatlandırmak","The tickets are priced for families, not collectors."],
["pride","B2","n.","gurur, onur","She showed us her garden with great pride."],
["primarily","B2","adv.","öncelikle, esasen","The course is aimed primarily at beginners."],
["prime","B2","adj.","başlıca, birincil; en kaliteli","Safety is our prime concern."],
["principal","B2","adj., n.","başlıca; okul müdürü","Tourism is the island's principal source of income."],
["principle","B2","n.","ilke, prensip","She refused on a matter of principle."],
["print","B2","n.","baskı; basılı yazı","The print is too small for me to read."],
["prior","B2","adj.","önceki, önceden olan","The course requires no prior knowledge."],
["priority","B2","n.","öncelik","Fixing the roof is the top priority."],
["privacy","B2","n.","mahremiyet, özel hayat","The fence gives the garden more privacy."],
["privatization","C1","n.","özelleştirme","The privatization of the railways remains controversial."],
["privilege","C1","n.","ayrıcalık, imtiyaz","Education should be a right, not a privilege."],
["probability","B2","n.","olasılık","There is a high probability of showers tonight."],
["probable","B2","adj.","muhtemel, olası","The most probable cause was an electrical fault."],
["probe","C1","n., v.","sonda; soruşturma; irdelemek","Reporters probed the company's accounts."],
["problematic","C1","adj.","sorunlu","The bridge's design proved problematic."],
["procedure","B2","n.","prosedür, işlem, yöntem","Follow the safety procedure during the drill."],
["proceed","B2","v.","devam etmek, ilerlemek","The building work can now proceed as planned."],
["proceeding","C1","n.","(hukuki) işlem, dava süreci","Legal proceedings began against the supplier."],
["proceeds","C1","n.","hasılat, gelir","The proceeds of the concert go to charity."],
["process","B2","v.","işlemek, işleme almak","The factory processes tonnes of fruit daily."],
["processing","C1","n.","işleme","Visa processing takes around three weeks."],
["processor","C1","n.","işlemci","The new phone has a much faster processor."],
["proclaim","C1","v.","ilan etmek, duyurmak","The republic was proclaimed on this square."],
["produce","B2","n.","tarım ürünü, mahsul","The shop sells fresh local produce."],
["productive","C1","adj.","verimli, üretken","We had a very productive meeting this morning."],
["productivity","C1","n.","verimlilik, üretkenlik","Better tools raised the workshop's productivity."],
["professional","B2","n.","profesyonel, meslek sahibi","The course is designed for busy professionals."],
["profitable","C1","adj.","kârlı","The bakery became profitable in its second year."],
["profound","C1","adj.","derin, köklü","The war had a profound effect on his writing."],
["programming","B2","n.","programlama; yayın akışı","She is learning programming in the evenings."],
["progress","B2","v.","ilerlemek","The talks progressed more quickly than expected."],
["progressive","B2","adj.","ilerici; aşamalı","The school is known for its progressive methods."],
["prohibit","B2","v.","yasaklamak","The law prohibits the sale of fireworks to children."],
["project","B2","v.","öngörmek; yansıtmak","Sales are projected to double within five years."],
["projection","C1","n.","projeksiyon, öngörü; yansıtma","Current projections show the population falling."],
["prominent","C1","adj.","önde gelen; göze çarpan","A prominent scientist chaired the committee."],
["promising","B2","adj.","umut vadeden","She is one of the most promising young players."],
["promotion","B2","n.","terfi; tanıtım, promosyon","He got a promotion after two years."],
["prompt","B2","v.","yol açmak; harekete geçirmek; hatırlatmak","The scandal prompted calls for his resignation."],
["pronounced","C1","adj.","belirgin","He walks with a pronounced limp."],
["proof","B2","n.","kanıt, delil","There is no proof that the letter ever existed."],
["propaganda","C1","n.","propaganda","The posters were pure political propaganda."],
["proportion","B2","n.","oran; kısım","A large proportion of students work part-time."],
["proposal","B2","n.","öneri, teklif","The committee rejected the proposal."],
["propose","B2","v.","önermek; evlenme teklif etmek","She proposed a change to the agenda."],
["proposition","C1","n.","önerme; teklif (iş)","Running a farm is an expensive proposition."],
["prosecute","C1","v.","kovuşturmak, dava açmak","Shoplifters will be prosecuted."],
["prosecution","C1","n.","kovuşturma; iddia makamı","The prosecution called its first witness."],
["prosecutor","C1","n.","savcı","The prosecutor demanded a long sentence."],
["prospect","B2","n.","olasılık, beklenti; aday","The prospect of moving abroad excites her."],
["prospective","C1","adj.","müstakbel, olası","Prospective buyers toured the house all weekend."],
["prosperity","C1","n.","refah, gönenç","Trade brought prosperity to the port towns."],
["protection","B2","n.","koruma","The cream gives protection against the sun."],
["protective","C1","adj.","koruyucu","Wear protective gloves when handling glass."],
["protein","B2","n.","protein","Eggs are an excellent source of protein."],
["protester","B2","n.","protestocu, eylemci","Protesters gathered outside the embassy."],
["protocol","C1","n.","protokol; kurallar dizisi","Visitors must follow strict safety protocols."],
["province","C1","n.","il, eyalet; taşra","The province is famous for its tea gardens."],
["provincial","C1","adj.","taşraya özgü; il ile ilgili","He never lost his provincial accent."],
["provision","C1","n.","sağlama, tedarik; hüküm (sözleşme)","The contract includes a provision for early exit."],
["provoke","C1","v.","kışkırtmak; yol açmak","The article provoked a storm of complaints."],
["psychiatric","C1","adj.","psikiyatrik","The hospital has a small psychiatric unit."],
["psychological","B2","adj.","psikolojik","The injury was physical, but the scars were psychological."],
["psychologist","B2","n.","psikolog","A psychologist spoke to the children after the fire."],
["psychology","B2","n.","psikoloji","She studied psychology at university."],
["publication","B2","n.","yayın, yayımlama","The report's publication was delayed a month."],
["publicity","B2","n.","tanıtım; kamuoyu ilgisi","The case attracted enormous publicity."],
["publishing","B2","n.","yayıncılık","She works in children's publishing."],
["pulse","C1","n.","nabız","The nurse checked his pulse and temperature."],
["pump","C1","n., v.","pompa; pompalamak","The heart pumps blood around the body."],
["punch","C1","n., v.","yumruk; yumruklamak; delgeçle delmek","The boxer threw a quick punch."],
["punk","B2","n.","punk (müzik/akım)","Punk changed British music in the late seventies."],
["pupil","B2","n.","öğrenci; göz bebeği","The school has nine hundred pupils."],
["purchase","B2","n., v.","satın alma; satın almak","Keep the receipt as proof of purchase."],
["pure","B2","adj.","saf, katıksız","The ring is made of pure gold."],
["purely","B2","adv.","sadece, tamamen","Their meeting was purely accidental."],
["pursue","B2","v.","peşinden gitmek; sürdürmek","She left her job to pursue a singing career."],
["pursuit","B2","n.","kovalama; uğraş","The police car sped past in pursuit of a van."],
["puzzle","B2","n.","bulmaca; bilmece, muamma","The cause of the illness remains a puzzle."]
];
