// Oxford 5000 B2-C1 vocab: L-M. Format: [w, lv, pos, tr, ex]
module.exports = [
["labour","B2","n.","emek, iş gücü; doğum sancısı","The bridge took years of hard labour to build."],
["lad","C1","n.","delikanlı, oğlan","He's a friendly lad who helps his neighbours."],
["ladder","B2","n.","merdiven (taşınır); kariyer basamakları","He climbed the ladder to clean the gutters."],
["landing","B2","n.","iniş; merdiven sahanlığı","The pilot made a smooth landing despite the wind."],
["landlord","C1","n.","ev sahibi, mülk sahibi","The landlord agreed to repair the heating."],
["landmark","C1","n.","simge yapı; dönüm noktası","The tower is the city's most famous landmark."],
["landscape","B2","n.","manzara, peyzaj; genel görünüm","The train passed through a dramatic mountain landscape."],
["lane","B2","n.","şerit; dar yol","Stay in the left lane until the exit."],
["lap","C1","n.","kucak; tur (yarış)","The cat fell asleep on her lap."],
["large-scale","C1","adj.","büyük ölçekli","The company began large-scale production of the device."],
["largely","B2","adv.","büyük ölçüde","The accident was largely the driver's fault."],
["laser","C1","n.","lazer","The scar was removed with a laser."],
["lately","B2","adv.","son zamanlarda","Have you spoken to your cousin lately?"],
["latest","B2","n.","en yenisi, son çıkan","Her latest is even better than the first novel."],
["latter","C1","adj., n.","ikincisi, sonuncusu (bahsedilenlerden)","Of tea and coffee, I prefer the latter."],
["launch","B2","n., v.","fırlatma, lansman; başlatmak, piyasaya sürmek","The charity launched a campaign against food waste."],
["lawn","C1","n.","çim, çimenlik","He mows the lawn every other weekend."],
["lawsuit","C1","n.","dava","The actor filed a lawsuit against the magazine."],
["layout","C1","n.","yerleşim, düzen, sayfa düzeni","The layout of the office encourages conversation."],
["leadership","B2","n.","liderlik, önderlik","The team improved under her leadership."],
["leaflet","B2","n.","broşür, el ilanı","A volunteer handed out leaflets about recycling."],
["league","B2","n.","lig; birlik","The club was promoted to the top league."],
["leak","C1","n., v.","sızıntı; sızdırmak","A gas leak forced the building to be evacuated."],
["lean","B2","v.","yaslanmak, eğilmek","She leaned against the wall to rest."],
["leap","C1","n., v.","sıçrama; sıçramak","The dancer made a graceful leap across the stage."],
["leave","B2","n.","izin (işten)","He took two weeks' leave to visit his family."],
["legacy","C1","n.","miras, kalıt","The festival is the legacy of one determined teacher."],
["legend","B2","n.","efsane","According to legend, a dragon guarded the lake."],
["legendary","C1","adj.","efsanevi","Her parties were legendary in the neighbourhood."],
["legislation","C1","n.","mevzuat, yasama","New legislation will tighten rules on advertising."],
["legislative","C1","adj.","yasama ile ilgili","The assembly has full legislative powers."],
["legislature","C1","n.","yasama organı","The legislature voted to raise the minimum wage."],
["legitimate","C1","adj.","meşru, yasal; haklı","Voters raised legitimate concerns about the plan."],
["lengthy","C1","adj.","uzun (süren)","The contract followed lengthy negotiations."],
["lens","B2","n.","mercek, lens; objektif","The photographer changed to a wider lens."],
["lesbian","C1","adj.","lezbiyen","The festival screened several lesbian films."],
["lesser","C1","adj.","daha az(önemli), küçük","He was convicted of a lesser charge."],
["lethal","C1","adj.","öldürücü","The snake's venom can be lethal to humans."],
["level","B2","v.","düzlemek; eşitlemek; (suçlama) yöneltmek","Workers levelled the ground before laying the path."],
["liable","C1","adj.","yükümlü, sorumlu; eğilimli","Drivers are liable for damage they cause."],
["liberal","C1","adj., n.","özgürlükçü, liberal; hoşgörülü","Her parents took a liberal approach to bedtime."],
["liberation","C1","n.","kurtuluş, özgürleşme","The city celebrated its liberation every spring."],
["liberty","C1","n.","özgürlük, hürriyet","The constitution protects individual liberty."],
["licence","B2","n.","ehliyet, ruhsat, lisans","You need a licence to fish in this river."],
["license","C1","v.","ruhsat vermek, yetkilendirmek","The café is licensed to serve alcohol."],
["lifelong","C1","adj.","ömür boyu süren","Reading became a lifelong passion."],
["lifetime","B2","n.","ömür, yaşam süresi","Such storms happen once in a lifetime."],
["lighting","B2","n.","aydınlatma","Soft lighting made the room feel warm."],
["likelihood","C1","n.","olasılık, ihtimal","There is little likelihood of rain this week."],
["likewise","B2","adv.","aynı şekilde, keza","The first test failed; the second, likewise."],
["limb","C1","n.","uzuv, kol/bacak; dal","The accident cost him the use of one limb."],
["limitation","B2","n.","sınırlama, kısıt","Every method has its limitations."],
["limited","B2","adj.","sınırlı, kısıtlı","Seats are limited, so book early."],
["line","B2","v.","kaplamak, astarlamak; sıralanmak","Trees lined the avenue on both sides."],
["line-up","C1","n.","kadro, program (etkinlik)","The festival announced a strong line-up of bands."],
["linear","C1","adj.","doğrusal, çizgisel","The story does not follow a linear order."],
["linger","C1","v.","oyalanmak, geçmek bilmemek","The smell of paint lingered for days."],
["listing","C1","n.","liste kaydı, ilan","The flat's listing attracted dozens of calls."],
["literacy","C1","n.","okuryazarlık","The campaign aims to improve adult literacy."],
["literally","B2","adv.","kelimenin tam anlamıyla","The town was literally buried in snow."],
["literary","B2","adj.","edebî, yazınsal","She won a major literary prize."],
["litre","B2","n.","litre","The recipe needs a litre of milk."],
["litter","B2","n.","çöp (yere atılan)","Volunteers collected litter along the beach."],
["lively","B2","adj.","canlı, hareketli","The market is liveliest on Saturday mornings."],
["liver","C1","n.","karaciğer","The liver removes toxins from the blood."],
["load","B2","n., v.","yük; yüklemek","They loaded the van with furniture."],
["loan","B2","n.","kredi, borç; ödünç verme","She took out a loan to start the bakery."],
["lobby","C1","n., v.","lobi; kulis yapmak, baskı grubu oluşturmak","Farmers lobbied the government for better prices."],
["log","C1","n., v.","kütük; kayıt; kaydetmek","The captain logged the ship's position every hour."],
["logic","C1","n.","mantık","I can't follow the logic of his argument."],
["logical","B2","adj.","mantıklı, mantıksal","Moving closer to work was the logical choice."],
["logo","B2","n.","logo","The new logo appears on all their products."],
["long-standing","C1","adj.","uzun süredir devam eden","They finally settled a long-standing dispute."],
["long-term","B2","adj., adv.","uzun vadeli","Smoking causes long-term damage to the lungs."],
["long-time","C1","adj.","eski, uzun süreli (ilişki)","A long-time friend gave the wedding speech."],
["loom","C1","v.","belirmek (tehditkâr); yaklaşmak","Dark mountains loomed ahead of the climbers."],
["loop","C1","n.","döngü, ilmek","The path makes a loop around the lake."],
["loose","B2","adj.","gevşek; bol; serbest","One of the screws has come loose."],
["lord","B2","n.","lort; efendi","The castle once belonged to a powerful lord."],
["lottery","B2","n.","piyango","Winning the lottery did not make him happier."],
["low","B2","n.","en düşük nokta/değer; dip","The currency fell to a new low."],
["lower","B2","v.","alçaltmak, indirmek, düşürmek","Please lower your voice in the library."],
["loyal","B2","adj.","sadık, vefalı","The shop has a small but loyal group of customers."],
["loyalty","C1","n.","sadakat, bağlılık","His loyalty to his friends never wavered."],
["lung","B2","n.","akciğer","Polluted air damages the lungs over time."],
["lyric","B2","n.","şarkı sözü","She writes the lyrics and her brother composes."],
["machinery","C1","n.","makineler; mekanizma","The farm invested in modern machinery."],
["magical","C1","adj.","büyülü, sihirli","The lanterns gave the garden a magical feel."],
["magistrate","C1","n.","sulh hâkimi","The magistrate fined the driver and warned him."],
["magnetic","C1","adj.","manyetik; çekici (kişilik)","The earth has a magnetic field."],
["magnificent","B2","adj.","muhteşem, görkemli","The palace has a magnificent marble staircase."],
["magnitude","C1","n.","büyüklük; önem derecesi","They underestimated the magnitude of the task."],
["mainland","C1","n.","ana kara","A ferry links the island to the mainland."],
["mainstream","C1","adj., n.","ana akım","The idea moved from the margins into the mainstream."],
["maintain","B2","v.","sürdürmek; bakımını yapmak; iddia etmek","It is hard to maintain focus for hours."],
["maintenance","C1","n.","bakım; sürdürme","The lift is closed for routine maintenance."],
["majority","B2","n.","çoğunluk","The majority of members voted for the change."],
["make","B2","n.","marka, yapım","What make is your washing machine?"],
["make-up","B2","n.","makyaj; yapı, bileşim","She wears very little make-up to work."],
["making","B2","n.","yapım, oluşturma","The documentary shows the making of the film."],
["mandate","C1","n.","yetki (seçimle verilen); görev emri","The new government claimed a clear mandate for reform."],
["mandatory","C1","adj.","zorunlu","Seat belts are mandatory for all passengers."],
["manifest","C1","v.","açıkça göstermek, belirti vermek","Her anxiety manifested itself as sleeplessness."],
["manipulate","C1","v.","yönlendirmek, manipüle etmek; ustaca kullanmak","The film accuses the press of manipulating public opinion."],
["manipulation","C1","n.","manipülasyon, yönlendirme","The trial exposed years of financial manipulation."],
["manufacture","B2","v.","imal etmek, üretmek","The plant manufactures parts for aircraft."],
["manufacturing","B2","n.","imalat (sanayisi)","Manufacturing still employs millions of workers."],
["manuscript","C1","n.","el yazması; müsvedde","The library preserves a twelfth-century manuscript."],
["map","B2","v.","haritalamak; ayrıntısıyla ortaya koymak","Scientists have mapped the entire genome."],
["marathon","B2","n.","maraton","She ran her first marathon at fifty."],
["march","C1","n., v.","yürüyüş (protesto/asker); yürümek","Thousands marched through the capital for peace."],
["margin","B2","n.","kenar boşluğu; marj, fark","He won the election by a narrow margin."],
["marginal","C1","adj.","önemsiz, marjinal; kenarda kalan","The change had only a marginal effect on sales."],
["marine","C1","adj.","denizle ilgili, deniz-","Plastic waste threatens marine life."],
["marker","B2","n.","işaret(leyici); keçeli kalem","A stone marker shows where the old gate stood."],
["marketplace","C1","n.","pazar yeri; piyasa","Small firms struggle in a crowded marketplace."],
["martial","B2","adj.","savaşla ilgili, askeri","He has practised martial arts since childhood."],
["mask","C1","n.","maske","The nurse wore a mask and gloves."],
["mass","B2","adj., n.","kitle(sel); yığın; kütle","Mass tourism has changed the small town completely."],
["massacre","C1","n.","katliam","The museum commemorates the victims of the massacre."],
["massive","B2","adj.","devasa, çok büyük","A massive crowd filled the square."],
["master","B2","n., v.","usta; efendi; ustalaşmak","It takes years to master a musical instrument."],
["matching","B2","adj.","uyumlu, takım (renk/desen)","She wore a hat with matching gloves."],
["mate","B2","n., v.","arkadaş; eş (hayvan); çiftleşmek","He went fishing with a couple of mates."],
["material","B2","adj.","maddi; önemli (hukuk)","The witness withheld material facts from the court."],
["mathematical","C1","adj.","matematiksel","The model rests on a few mathematical assumptions."],
["mature","C1","adj., v.","olgun; olgunlaşmak","She is very mature for her age."],
["maximize","C1","v.","en üst düzeye çıkarmak","Arrange the shelves to maximize storage space."],
["maximum","B2","adj., n.","azami, en çok; üst sınır","The hall holds a maximum of two hundred people."],
["mayor","B2","n.","belediye başkanı","The mayor opened the new sports centre."],
["meaningful","C1","adj.","anlamlı","Volunteering gave her work a meaningful purpose."],
["means","B2","n.","araç, yol; olanaklar","The bicycle is his only means of transport."],
["meantime","C1","n.","bu arada (in the meantime)","The bus comes at six; in the meantime, let's walk."],
["measurement","B2","n.","ölçüm, ölçü","Take careful measurements before cutting the wood."],
["mechanic","B2","n.","tamirci, makinist","The mechanic found the fault in minutes."],
["mechanical","B2","adj.","mekanik","The delay was caused by a mechanical failure."],
["mechanism","B2","n.","mekanizma, düzenek","The clock's mechanism needs cleaning."],
["medal","B2","n.","madalya","She won a gold medal in swimming."],
["medication","B2","n.","ilaç (tedavisi)","Remember to take your medication with food."],
["medieval","C1","adj.","orta çağa ait","The town kept its medieval walls."],
["meditation","C1","n.","meditasyon; derin düşünme","Ten minutes of meditation calms her mind."],
["medium","B2","n.","araç, ortam; iletişim aracı","Radio remains a powerful medium in rural areas."],
["melody","C1","n.","melodi, ezgi","The song's melody stayed with me all day."],
["melt","B2","v.","erimek; eritmek","The snow melted quickly in the morning sun."],
["membership","B2","n.","üyelik","Gym membership costs less in summer."],
["memo","C1","n.","kısa not, bildiri (kurum içi)","A memo announced the new working hours."],
["memoir","C1","n.","anı kitabı","Her memoir describes her childhood at sea."],
["memorable","B2","adj.","unutulmaz, akılda kalıcı","The trip ended with a memorable sunset."],
["memorial","C1","n.","anıt, anma","A memorial honours the miners who died."],
["mentor","C1","n.","akıl hocası, rehber","A good mentor can shape a young career."],
["merchant","C1","n.","tüccar","The port grew rich on the trade of merchants."],
["mercy","C1","n.","merhamet","The prisoner begged the king for mercy."],
["mere","C1","adj.","sadece, yalnızca (küçümseme)","He was a mere child when the war began."],
["merely","C1","adv.","sadece, yalnızca","I was merely asking a question."],
["merge","C1","v.","birleşmek; kaynaşmak","The two banks merged last year."],
["merger","C1","n.","(şirket) birleşme(si)","The merger created the country's largest insurer."],
["merit","C1","n.","değer, meziyet; haklılık payı","Each application is judged on its merits."],
["metaphor","B2","n.","metafor, eğretileme","The poet uses winter as a metaphor for loss."],
["methodology","C1","n.","yöntem bilimi, metodoloji","The study's methodology is described in detail."],
["midst","C1","n.","orta(sı) (in the midst of)","He stayed calm in the midst of the chaos."],
["migration","C1","n.","göç","The birds begin their migration in October."],
["militant","C1","adj., n.","militan; mücadeleci","Militant protesters blocked the main road."],
["military","B2","adj., n.","askeri; ordu","He spent six years in the military."],
["militia","C1","n.","milis (kuvveti)","Armed militias controlled the border region."],
["mill","C1","n.","değirmen; fabrika","The old mill has been turned into flats."],
["miner","B2","n.","madenci","The miners worked deep below the surface."],
["mineral","B2","n.","mineral, maden","The region is rich in valuable minerals."],
["minimal","C1","adj.","asgari, çok az","The storm caused only minimal damage."],
["minimize","C1","v.","en aza indirmek","Wear a helmet to minimize the risk of injury."],
["minimum","B2","adj., n.","asgari, en az; alt sınır","Keep noise to a minimum after ten."],
["mining","C1","n.","madencilik","Coal mining shaped this valley for a century."],
["minister","B2","n.","bakan","The minister announced new funding for schools."],
["ministry","C1","n.","bakanlık","She works at the Ministry of Health."],
["minor","B2","adj.","küçük, önemsiz; ikincil","The car needs a few minor repairs."],
["minority","B2","n.","azınlık","Only a small minority opposed the plan."],
["minute","C1","adj.","çok küçük, minicik","The water contains minute traces of iron."],
["miracle","C1","n.","mucize","It's a miracle no one was hurt in the crash."],
["miserable","B2","adj.","perişan, çok mutsuz; berbat","He felt miserable after failing the test."],
["misery","C1","n.","sefalet, büyük mutsuzluk","The drought brought misery to thousands."],
["misleading","C1","adj.","yanıltıcı","The advert was banned for being misleading."],
["missile","C1","n.","füze","The ship carries defensive missiles."],
["mission","B2","n.","görev, misyon","Their mission is to bring clean water to villages."],
["mistake","B2","v.","yanlış anlamak; (for ile) karıştırmak","I mistook the salt for sugar."],
["mixed","B2","adj.","karışık, karma","The film received mixed reviews."],
["mob","C1","n.","öfkeli kalabalık; güruh","An angry mob gathered outside the courthouse."],
["mobility","C1","n.","hareketlilik; devinim","The exercises improve mobility in the joints."],
["mobilize","C1","v.","seferber etmek, harekete geçirmek","The charity mobilized hundreds of volunteers overnight."],
["mode","B2","n.","mod, kip; biçim","Switch your phone to silent mode."],
["model","B2","v.","modellemek; örnek almak","The simulation models the flow of traffic."],
["moderate","C1","adj.","ılımlı; orta düzeyde","Moderate exercise is good for the heart."],
["modest","B2","adj.","alçakgönüllü; mütevazı (miktar)","They live in a modest house near the park."],
["modification","C1","n.","değişiklik, tadilat","The engine needs only minor modifications."],
["modify","B2","v.","değiştirmek, uyarlamak","The recipe can be modified for vegetarians."],
["momentum","C1","n.","ivme, momentum","The campaign gained momentum after the debate."],
["monitor","B2","n., v.","ekran; izlemek, takip etmek","Nurses monitored the patient's heart rate."],
["monk","C1","n.","keşiş","The monks rise before dawn to pray."],
["monopoly","C1","n.","tekel","For years the company held a monopoly on rail travel."],
["monster","B2","n.","canavar","The story is about a kind-hearted monster."],
["monthly","B2","adj.","aylık","The magazine is published on a monthly basis."],
["monument","B2","n.","anıt","A monument marks the site of the battle."],
["moral","B2","adj., n.","ahlaki; ders (öykü)","The story's moral is simple: be honest."],
["morality","C1","n.","ahlak (anlayışı)","The play questions the morality of war."],
["moreover","B2","adv.","dahası, üstelik","The flat is small; moreover, it is expensive."],
["mortgage","B2","n.","konut kredisi, ipotek","They finally paid off their mortgage."],
["mosque","B2","n.","cami","The mosque's minaret rises above the rooftops."],
["motion","B2","n.","hareket; önerge","The gentle motion of the boat sent her to sleep."],
["motivate","B2","v.","motive etmek, isteklendirmek","Praise motivates students more than punishment."],
["motivation","B2","n.","motivasyon, güdü","His motivation faded halfway through the course."],
["motive","C1","n.","sebep, saik","The police could find no motive for the attack."],
["motor","B2","adj., n.","motor(lu)","The boat is powered by a small electric motor."],
["motorist","C1","n.","sürücü, otomobil kullanan","Motorists were warned of black ice on the roads."],
["mount","B2","v.","artmak; (kampanya) düzenlemek; binmek","Pressure mounted on the minister to resign."],
["moving","B2","adj.","dokunaklı, duygulandırıcı","She gave a moving speech about her grandmother."],
["multiple","B2","adj.","çok sayıda, birden çok","The driver suffered multiple injuries."],
["multiply","B2","v.","çarpmak; çoğalmak","Bacteria multiply rapidly in warm conditions."],
["municipal","C1","adj.","belediyeye ait","Municipal workers cleared the fallen branches."],
["mutual","C1","adj.","karşılıklı; ortak","They parted by mutual agreement."],
["mysterious","B2","adj.","gizemli, esrarengiz","A mysterious light appeared over the field."],
["myth","B2","n.","mit, efsane; yaygın yanlış inanç","It's a myth that we use only ten per cent of our brains."]
];
