// Oxford 5000 B2-C1 vocab: G-H. Format: [w, lv, pos, tr, ex]
module.exports = [
["gain","B2","n., v.","kazanç; kazanmak, elde etmek","She gained confidence with every speech she gave."],
["gallon","C1","n.","galon (yaklaşık 4,5 litre)","The tank holds about twelve gallons of fuel."],
["gambling","C1","n.","kumar","He lost his savings through online gambling."],
["gaming","B2","n.","(bilgisayar) oyun oynama; oyun sektörü","The gaming industry now earns more than cinema."],
["gang","B2","n.","çete; (arkadaş) grup","A gang of teenagers gathered on the corner."],
["gathering","C1","n.","toplantı, bir araya gelme","It was a small family gathering, nothing formal."],
["gay","B2","adj.","eşcinsel","The festival celebrates the city's gay community."],
["gaze","C1","n., v.","sabit bakış; gözünü dikip bakmak","She gazed out of the window at the falling snow."],
["gear","C1","n.","vites; donanım, takım","Bring your climbing gear; the route is steep."],
["gender","B2","n.","cinsiyet, toplumsal cinsiyet","The study found no difference between the genders."],
["gene","B2","n.","gen","A single gene can influence many traits."],
["generate","B2","v.","üretmek, yaratmak","Wind farms generate clean electricity for thousands of homes."],
["generic","C1","adj.","genel, jenerik; markasız","The doctor prescribed a cheaper generic version of the drug."],
["genetic","B2","adj.","genetik, kalıtsal","Some diseases have a strong genetic component."],
["genius","B2","n.","dahi; üstün yetenek","Einstein is often described as a genius."],
["genocide","C1","n.","soykırım","The tribunal investigated accusations of genocide."],
["genre","B2","n.","tür (edebiyat/film/müzik)","Science fiction is her favourite genre."],
["genuine","B2","adj.","gerçek, hakiki; samimi","The signature turned out to be genuine."],
["genuinely","B2","adv.","gerçekten, içtenlikle","He seemed genuinely surprised by the news."],
["gesture","B2","n.","jest, el hareketi; davranış","She raised her hand in a gesture of greeting."],
["gig","B2","n.","konser; kısa süreli iş","The band played a small gig in a local café."],
["glance","C1","n., v.","kısa bakış; göz atmak","He glanced at his watch and hurried out."],
["glimpse","C1","n.","kısa görüş, bir anlık görme","We caught a glimpse of the sea between the hills."],
["globalization","B2","n.","küreselleşme","Globalization has connected markets across continents."],
["globe","B2","n.","yerküre, dünya","Tourists from across the globe visit the ancient site."],
["glorious","C1","adj.","muhteşem, şanlı","We woke to a glorious sunny morning."],
["glory","C1","n.","şan, zafer; ihtişam","The team returned home covered in glory."],
["golden","B2","adj.","altın (rengi); altın değerinde","This is a golden opportunity you should not miss."],
["goodness","B2","n.","iyilik; (şaşkınlık ünlemi)","She believes in the basic goodness of people."],
["gorgeous","B2","adj.","çok güzel, göz alıcı","The bride wore a gorgeous silk dress."],
["govern","B2","v.","yönetmek; belirlemek","Strict rules govern the use of laboratory animals."],
["governance","C1","n.","yönetişim, yönetim biçimi","Good governance requires transparency and accountability."],
["governor","B2","n.","vali; yönetici","The governor announced a new education budget."],
["grab","B2","v.","kapmak, yakalamak","He grabbed his coat and ran for the bus."],
["grace","C1","n.","zarafet; lütuf","The dancer moved with effortless grace."],
["grade","B2","v.","notlandırmak; derecelendirmek","The teacher spent the evening grading essays."],
["gradually","B2","adv.","yavaş yavaş, giderek","The weather gradually improved during the week."],
["grand","B2","adj.","görkemli, büyük","They held the reception in a grand old hotel."],
["grant","B2","n., v.","hibe, burs; vermek, kabul etmek","The university granted her a scholarship for research."],
["graphic","B2","adj.","grafiksel; çok canlı/açık (tasvir)","The report contained graphic descriptions of the accident."],
["graphics","B2","n.","grafikler, görseller","The game's graphics are remarkably realistic."],
["grasp","C1","n., v.","kavrayış; kavramak, sıkıca tutmak","She quickly grasped the main idea of the lecture."],
["grave","C1","adj., n.","ciddi, vahim; mezar","The patient's condition remains grave."],
["gravity","C1","n.","yer çekimi; ciddiyet","Objects fall to the ground because of gravity."],
["greatly","B2","adv.","büyük ölçüde, çok","Your support is greatly appreciated."],
["greenhouse","B2","n.","sera","Tomatoes grow well in a heated greenhouse."],
["grid","C1","n.","ızgara (düzeni); elektrik şebekesi","Solar panels feed power back into the grid."],
["grief","C1","n.","derin üzüntü, yas","Grief takes a different form in every person."],
["grin","C1","n., v.","sırıtış; sırıtmak","He grinned when he saw the surprise cake."],
["grind","C1","v.","öğütmek; bilemek","Grind the coffee beans just before brewing."],
["grip","C1","n., v.","sıkı tutuş; kavramak","She tightened her grip on the railing."],
["grocery","B2","n.","bakkaliye; market alışverişi","I do my grocery shopping on Saturday mornings."],
["gross","C1","adj.","brüt; kaba, iğrenç","Her gross income is higher, but taxes take a third."],
["guarantee","B2","n., v.","garanti; garanti etmek","The machine comes with a two-year guarantee."],
["guerrilla","C1","n.","gerilla","The guerrillas operated from bases in the mountains."],
["guidance","C1","n.","rehberlik, yol gösterme","Students receive career guidance in their final year."],
["guideline","B2","n.","yönerge, kılavuz ilke","The ministry published new guidelines for food safety."],
["guilt","C1","n.","suçluluk (duygusu)","He was haunted by guilt over the broken promise."],
["gut","C1","n.","bağırsak; (guts) cesaret","Trust your gut when something feels wrong."],
["habitat","B2","n.","doğal yaşam alanı","Wetlands are an important habitat for migrating birds."],
["hail","C1","v.","selamlamak, övmek; (taksi) çevirmek","Critics hailed the film as a masterpiece."],
["halfway","C1","adv.","yarı yolda, ortasında","We stopped for coffee halfway through the journey."],
["halt","C1","n., v.","duruş; durdurmak","The strike brought production to a halt."],
["handful","C1","n.","bir avuç; az sayıda","Only a handful of people attended the meeting."],
["handle","B2","n., v.","kulp, sap; ele almak, başa çıkmak","She handled the complaint calmly and politely."],
["handling","C1","n.","ele alma, yönetme; taşıma","The minister was criticised for his handling of the crisis."],
["handy","C1","adj.","kullanışlı; el altında","Keep a torch handy in case of power cuts."],
["harassment","C1","n.","taciz, rahatsız etme","The company has a strict policy against harassment."],
["harbour","B2","n.","liman","Fishing boats returned to the harbour at sunset."],
["hardware","C1","n.","donanım; hırdavat","The problem lies in the hardware, not the software."],
["harm","B2","n., v.","zarar; zarar vermek","A little rain won't do any harm to the garden."],
["harmful","B2","adj.","zararlı","Smoking is harmful to everyone in the room."],
["harmony","C1","n.","uyum, ahenk","The two communities live together in harmony."],
["harsh","C1","adj.","sert, acımasız; haşin","The desert has a harsh climate of extremes."],
["harvest","C1","n., v.","hasat; hasat etmek","Farmers harvest the wheat in late summer."],
["hatred","C1","n.","nefret","The speech was full of hatred and fear."],
["haunt","C1","v.","(hayalet) musallat olmak; aklından çıkmamak","Memories of the war still haunt him."],
["hazard","C1","n.","tehlike, risk","Icy roads are a serious hazard for drivers."],
["headquarters","B2","n.","genel merkez, karargâh","The company moved its headquarters to Berlin."],
["heal","B2","v.","iyileşmek; iyileştirmek","The wound healed slowly over several weeks."],
["healthcare","B2","n.","sağlık hizmetleri","The country provides free healthcare for children."],
["hearing","B2","n.","işitme; duruşma","Her hearing has worsened with age."],
["heaven","B2","n.","cennet; gökyüzü","The garden felt like a little piece of heaven."],
["heel","B2","n.","topuk","These shoes have a very high heel."],
["heighten","C1","v.","artırmak, yoğunlaştırmak","The music heightened the tension in the final scene."],
["hell","B2","n.","cehennem","The traffic this morning was absolute hell."],
["helmet","B2","n.","kask, miğfer","Always wear a helmet when you cycle."],
["hence","B2","adv.","bu nedenle, dolayısıyla","The road was closed; hence the long delay."],
["herb","B2","n.","şifalı/aromatik bitki, ot","She grows fresh herbs on the kitchen windowsill."],
["heritage","C1","n.","miras, kültürel miras","The old town is part of our national heritage."],
["hesitate","B2","v.","tereddüt etmek, duraksamak","Don't hesitate to call me if you need help."],
["hidden","B2","adj.","gizli, saklı","The camera was hidden behind a mirror."],
["hierarchy","C1","n.","hiyerarşi, aşama düzeni","Decisions travel slowly up the company hierarchy."],
["high","B2","n.","en yüksek nokta/değer; doruk","Prices reached a record high in June."],
["high-profile","C1","adj.","göz önünde olan, çok tanınan","A high-profile lawyer agreed to take the case."],
["highway","B2","n.","otoyol, karayolu","The new highway cuts the journey time in half."],
["hilarious","B2","adj.","çok komik","Her impression of the manager was hilarious."],
["hint","C1","n., v.","ipucu, ima; ima etmek","He hinted that an announcement was coming soon."],
["hip","B2","n.","kalça","She stood with her hands on her hips."],
["hire","B2","n.","kiralama; işe alma","Bike hire is available next to the station."],
["historian","B2","n.","tarihçi","Historians still argue about the causes of the war."],
["hold","B2","n.","tutma, tutuş; (gemi) ambar","He kept a firm hold on the rope."],
["hollow","B2","adj.","içi boş; anlamsız, sahte","The old tree trunk was completely hollow."],
["holy","B2","adj.","kutsal","The city is holy to three religions."],
["homeland","C1","n.","anavatan, yurt","After thirty years abroad, she returned to her homeland."],
["homeless","B2","adj.","evsiz","The charity provides meals for homeless people."],
["honesty","B2","n.","dürüstlük","I value honesty above all other qualities."],
["honour","B2","n., v.","onur, şeref; onurlandırmak","The ceremony was held to honour the retiring teacher."],
["hook","B2","n., v.","kanca, çengel; takmak","Hang your coat on the hook behind the door."],
["hopeful","C1","adj.","umutlu, umut verici","We remain hopeful that an agreement can be reached."],
["hopefully","B2","adv.","umarım, inşallah; umutla","Hopefully the rain will stop before the match."],
["horizon","C1","n.","ufuk","A ship appeared slowly on the horizon."],
["horn","C1","n.","korna; boynuz","The driver behind us kept sounding his horn."],
["host","B2","v.","ev sahipliği yapmak","The city will host the games next summer."],
["hostage","C1","n.","rehine","The gunman released the hostages after six hours."],
["hostile","C1","adj.","düşmanca; karşıt","The proposal met a hostile reaction from residents."],
["hostility","C1","n.","düşmanlık, husumet","There was open hostility between the two groups."],
["house","B2","v.","barındırmak, yerleştirmek","The museum houses a famous collection of paintings."],
["household","B2","n.","hane, ev halkı","The average household now owns several screens."],
["housing","B2","n.","konut; barınma","The city faces a serious shortage of affordable housing."],
["humanitarian","C1","adj.","insani (yardım)","Humanitarian aid reached the flooded villages by boat."],
["humanity","C1","n.","insanlık; insancıllık","The discovery could benefit all of humanity."],
["humble","C1","adj.","alçakgönüllü; mütevazı","Despite her fame, she remained remarkably humble."],
["humorous","B2","adj.","esprili, mizahi","He gave a humorous account of his first day at work."],
["humour","B2","n.","mizah; espri anlayışı","She has a wonderful sense of humour."],
["hunger","B2","n.","açlık; şiddetli istek","Millions of people still suffer from hunger."],
["hunt","B2","n.","av; arama","The hunt for the missing climbers continued at dawn."],
["hunting","B2","n.","avcılık","Hunting is strictly controlled in the national park."],
["hurt","B2","n.","incinme, kırgınlık","The hurt in her voice was impossible to miss."],
["hydrogen","C1","n.","hidrojen","Hydrogen may one day fuel our cars."],
["hypothesis","B2","n.","hipotez, varsayım","The experiment was designed to test a simple hypothesis."]
];
